/**
 * Sprachdatei für den XP Level Bot – 10 Sprachen, alle Texte humorvoll & emoji-lastig
 * wie beim Birthday Bot. Struktur 1:1 ähnlich, damit Design & Handling konsistent sind.
 */

const LANGS = {
  de: {
    name: 'Deutsch',
    names: { de: 'Deutsch', en: 'German', fr: 'Allemand', es: 'Alemán', pt: 'Alemão', ru: 'Немецкий', ja: 'ドイツ語', ko: '독일어', zh: '德语', it: 'Tedesco' },
    flag: '🇩🇪',
    locale: 'de-DE',
    tz: 'Europe/Berlin',
    months: ['Januar', 'Februar', 'März', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember'],
    short: ['jan', 'feb', 'mär', 'apr', 'mai', 'jun', 'jul', 'aug', 'sep', 'okt', 'nov', 'dez'],
    extra: [['jänner'], [], ['maerz'], [], [], [], [], [], [], [], [], []],
  },
  en: {
    name: 'English',
    names: { de: 'Englisch', en: 'English', fr: 'Anglais', es: 'Inglés', pt: 'Inglês', ru: 'Английский', ja: '英語', ko: '영어', zh: '英语', it: 'Inglese' },
    flag: '🇬🇧',
    locale: 'en-US',
    tz: 'America/New_York',
    months: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
    short: ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec'],
    extra: [],
  },
  fr: {
    name: 'Français',
    names: { de: 'Französisch', en: 'French', fr: 'Français', es: 'Francés', pt: 'Francês', ru: 'Французский', ja: 'フランス語', ko: '프랑스어', zh: '法语', it: 'Francese' },
    flag: '🇫🇷',
    locale: 'fr-FR',
    tz: 'Europe/Paris',
    months: ['janvier', 'février', 'mars', 'avril', 'mai', 'juin', 'juillet', 'août', 'septembre', 'octobre', 'novembre', 'décembre'],
    short: ['janv', 'févr', 'mars', 'avr', 'mai', 'juin', 'juil', 'août', 'sept', 'oct', 'nov', 'déc'],
    extra: [['janvier'], ['fevrier', 'février'], [], ['avril'], [], [], ['juillet'], ['aout', 'août'], ['septembre'], [], [], ['decembre', 'décembre']],
  },
  es: {
    name: 'Español',
    names: { de: 'Spanisch', en: 'Spanish', fr: 'Espagnol', es: 'Español', pt: 'Espanhol', ru: 'Испанский', ja: 'スペイン語', ko: '스페인어', zh: '西班牙语', it: 'Spagnolo' },
    flag: '🇪🇸',
    locale: 'es-ES',
    tz: 'Europe/Madrid',
    months: ['enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio', 'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre'],
    short: ['ene', 'feb', 'mar', 'abr', 'may', 'jun', 'jul', 'ago', 'sep', 'oct', 'nov', 'dic'],
    extra: [['enero'], [], ['marzo'], [], [], [], [], [], ['setiembre', 'septiembre'], [], [], []],
  },
  pt: {
    name: 'Português',
    names: { de: 'Portugiesisch', en: 'Portuguese', fr: 'Portugais', es: 'Portugués', pt: 'Português', ru: 'Португальский', ja: 'ポルトガル語', ko: '포르투갈어', zh: '葡萄牙语', it: 'Portoghese' },
    flag: '🇧🇷',
    locale: 'pt-BR',
    tz: 'America/Sao_Paulo',
    months: ['janeiro', 'fevereiro', 'março', 'abril', 'maio', 'junho', 'julho', 'agosto', 'setembro', 'outubro', 'novembro', 'dezembro'],
    short: ['jan', 'fev', 'mar', 'abr', 'mai', 'jun', 'jul', 'ago', 'set', 'out', 'nov', 'dez'],
    extra: [['janeiro'], [], ['marco', 'março'], [], [], [], [], [], ['setembro'], [], [], []],
  },
  ru: {
    name: 'Русский',
    names: { de: 'Russisch', en: 'Russian', fr: 'Russe', es: 'Ruso', pt: 'Russo', ru: 'Русский', ja: 'ロシア語', ko: '러시아어', zh: '俄语', it: 'Russo' },
    flag: '🇷🇺',
    locale: 'ru-RU',
    tz: 'Europe/Moscow',
    months: ['январь', 'февраль', 'март', 'апрель', 'май', 'июнь', 'июль', 'август', 'сентябрь', 'октябрь', 'ноябрь', 'декабрь'],
    short: ['янв', 'фев', 'мар', 'апр', 'май', 'июн', 'июл', 'авг', 'сен', 'окт', 'ноя', 'дек'],
    extra: [['января'], ['февраля'], ['марта'], ['апреля'], ['мая'], ['июня'], ['июля'], ['августа'], ['сентября'], ['октября'], ['ноября'], ['декабря']],
  },
  ja: {
    name: '日本語',
    names: { de: 'Japanisch', en: 'Japanese', fr: 'Japonais', es: 'Japonés', pt: 'Japonês', ru: 'Японский', ja: '日本語', ko: '일본어', zh: '日语', it: 'Giapponese' },
    flag: '🇯🇵',
    locale: 'ja-JP',
    tz: 'Asia/Tokyo',
    months: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
    short: [],
    kanji: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'],
    numeralSuffix: '月',
    extra: [],
  },
  ko: {
    name: '한국어',
    names: { de: 'Koreanisch', en: 'Korean', fr: 'Coréen', es: 'Coreano', pt: 'Coreano', ru: 'Корейский', ja: '韓国語', ko: '한국어', zh: '韩语', it: 'Coreano' },
    flag: '🇰🇷',
    locale: 'ko-KR',
    tz: 'Asia/Seoul',
    months: ['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월'],
    short: [],
    hangul: ['일월', '이월', '삼월', '사월', '오월', '유월', '칠월', '팔월', '구월', '시월', '십일월', '십이월'],
    numeralSuffix: '월',
    extra: [],
  },
  zh: {
    name: '中文',
    names: { de: 'Chinesisch', en: 'Chinese', fr: 'Chinois', es: 'Chino', pt: 'Chinês', ru: 'Китайский', ja: '中国語', ko: '중국어', zh: '中文', it: 'Cinese' },
    flag: '🇨🇳',
    locale: 'zh-CN',
    tz: 'Asia/Shanghai',
    months: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
    short: [],
    kanji: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'],
    numeralSuffix: '月',
    extra: [],
  },
  it: {
    name: 'Italiano',
    names: { de: 'Italienisch', en: 'Italian', fr: 'Italien', es: 'Italiano', pt: 'Italiano', ru: 'Итальянский', ja: 'イタリア語', ko: '이탈리아어', zh: '意大利语', it: 'Italiano' },
    flag: '🇮🇹',
    locale: 'it-IT',
    tz: 'Europe/Rome',
    months: ['gennaio', 'febbraio', 'marzo', 'aprile', 'maggio', 'giugno', 'luglio', 'agosto', 'settembre', 'ottobre', 'novembre', 'dicembre'],
    short: ['gen', 'feb', 'mar', 'apr', 'mag', 'giu', 'lug', 'ago', 'set', 'ott', 'nov', 'dic'],
    extra: [['gennaio'], [], ['marzo'], [], [], [], [], [], ['settembre'], [], [], []],
  },
};

const T = {
  // ------------------------------------------------------------
  // Leaderboard
  // ------------------------------------------------------------
  lbTitle: {
    de: '🏆 Level Leaderboard',
    en: '🏆 Level Leaderboard',
    fr: '🏆 Classement par niveau',
    es: '🏆 Tabla de niveles',
    pt: '🏆 Ranking de níveis',
    ru: '🏆 Таблица уровней',
    ja: '🏆 レベルランキング',
    ko: '🏆 레벨 리더보드',
    zh: '🏆 等级排行榜',
    it: '🏆 Classifica livelli',
  },
  lbTagline: {
    de: 'Die fleißigsten Chatter – streng dich an und kletter hoch! 🚀',
    en: 'The most active chatters – grind hard and climb up! 🚀',
    fr: 'Les plus actifs – bosse dur et grimpe ! 🚀',
    es: '¡Los más activos – esfuerzate y sube! 🚀',
    pt: 'Os mais ativos – rale muito e suba! 🚀',
    ru: 'Самые активные болтуны – старайся и поднимайся! 🚀',
    ja: '最もアクティブなメンバー – 頑張って上を目指そう！🚀',
    ko: '가장 활발한 멤버 – 열심히 해서 올라가세요! 🚀',
    zh: '最活跃的成员——努力聊天，冲上榜首！🚀',
    it: 'I più attivi – datti da fare e scala la classifica! 🚀',
  },
  lbEmpty: {
    de: 'Noch niemand hat XP gesammelt. Schreib die erste Nachricht und hol dir Level 1! ✨',
    en: 'No one has earned XP yet. Send the first message and claim Level 1! ✨',
    fr: 'Personne n’a encore gagné d’XP. Envoie le premier message et prends le niveau 1 ! ✨',
    es: 'Aún nadie ha ganado XP. ¡Envía el primer mensaje y consigue el nivel 1! ✨',
    pt: 'Ninguém ganhou XP ainda. Envie a primeira mensagem e pegue o nível 1! ✨',
    ru: 'Пока никто не заработал XP. Напиши первым и забери 1 уровень! ✨',
    ja: 'まだ誰もXPを獲得していません。最初のメッセージを送ってレベル1をゲットしよう！✨',
    ko: '아직 아무도 XP를 얻지 못했어요. 첫 메시지를 보내고 레벨 1을 차지하세요! ✨',
    zh: '还没有人获得 XP。发送第一条消息，拿下 1 级！✨',
    it: 'Nessuno ha ancora guadagnato XP. Invia il primo messaggio e prenditi il livello 1! ✨',
  },
  lbUpdated: {
    de: '🕒 Zuletzt aktualisiert: **{time}** ({tz})',
    en: '🕒 Last updated: **{time}** ({tz})',
    fr: '🕒 Dernière mise à jour : **{time}** ({tz})',
    es: '🕒 Última actualización: **{time}** ({tz})',
    pt: '🕒 Última atualização: **{time}** ({tz})',
    ru: '🕒 Последнее обновление: **{time}** ({tz})',
    ja: '🕒 最終更新: **{time}** ({tz})',
    ko: '🕒 마지막 업데이트: **{time}** ({tz})',
    zh: '🕒 最后更新：**{time}** ({tz})',
    it: '🕒 Ultimo aggiornamento: **{time}** ({tz})',
  },
  lbNextUpdate: {
    de: '⏰ Aktualisiert stündlich & nach Level-Ups – bleib dran!',
    en: '⏰ Refreshes hourly & after level-ups – stay tuned!',
    fr: '⏰ Mise à jour chaque heure & après un niveau – reste branché !',
    es: '⏰ ¡Se actualiza cada hora y tras subir de nivel – mantente al día!',
    pt: '⏰ Atualiza a cada hora e após subir de nível – fique ligado!',
    ru: '⏰ Обновляется каждый час и после повышения уровня – следи за обновлениями!',
    ja: '⏰ 毎時＆レベルアップ後に更新 – お見逃しなく！',
    ko: '⏰ 매시간 및 레벨업 후 업데이트 – 계속 확인하세요!',
    zh: '⏰ 每小时及升级后更新——敬请关注！',
    it: '⏰ Aggiornato ogni ora e dopo un level-up – resta sintonizzato!',
  },
  lbDecayNotice: {
    de: '⚠️ **XP-Schwund:** Um 0 Uhr verlierst du etwas XP. Bei 0 verlierst du ein Level – chatten hält dich oben! 💬🔥',
    en: '⚠️ **XP decay:** You lose a bit of XP at midnight. Hit 0 and you drop a level – keep chatting! 💬🔥',
    fr: '⚠️ **Perte XP :** Chaque minuit tu perds un peu d’XP. À 0, tu perds un niveau – continue à chatter ! 💬🔥',
    es: '⚠️ **Pérdida XP:** Cada medianoche pierdes algo de XP. En 0 pierdes un nivel – ¡sigue chateando! 💬🔥',
    pt: '⚠️ **Decaimento XP:** Todo dia à meia-noite você perde um pouco de XP. No 0, perde um nível – continue conversando! 💬🔥',
    ru: '⚠️ **Потеря XP:** Каждую полночь ты теряешь немного XP. На нуле теряешь уровень – болтай больше! 💬🔥',
    ja: '⚠️ **XP減少:** 毎日0時にXPを少し失います。0になるとレベルダウン – チャットで維持しよう！💬🔥',
    ko: '⚠️ **XP 감소:** 매일 자정에 XP를 조금 잃어요. 0이 되면 레벨 다운 – 계속 채팅하세요! 💬🔥',
    zh: '⚠️ **XP 衰减：** 每天零点会损失少量 XP。归零则掉级——继续聊天！💬🔥',
    it: '⚠️ **Decadimento XP:** Ogni mezzanotte perdi un po’ di XP. A 0 perdi un livello – continua a chattare! 💬🔥',
  },
  lbEntryLine: {
    de: '`#{rank}` <@{userId}> — **Lvl {level}** · {xp}/{needed} XP {medal}',
    en: '`#{rank}` <@{userId}> — **Lvl {level}** · {xp}/{needed} XP {medal}',
    fr: '`#{rank}` <@{userId}> — **Niv {level}** · {xp}/{needed} XP {medal}',
    es: '`#{rank}` <@{userId}> — **Nvl {level}** · {xp}/{needed} XP {medal}',
    pt: '`#{rank}` <@{userId}> — **Nvl {level}** · {xp}/{needed} XP {medal}',
    ru: '`#{rank}` <@{userId}> — **Ур {level}** · {xp}/{needed} XP {medal}',
    ja: '`#{rank}` <@{userId}> — **Lv {level}** · {xp}/{needed} XP {medal}',
    ko: '`#{rank}` <@{userId}> — **Lv {level}** · {xp}/{needed} XP {medal}',
    zh: '`#{rank}` <@{userId}> — **等级 {level}** · {xp}/{needed} XP {medal}',
    it: '`#{rank}` <@{userId}> — **Liv {level}** · {xp}/{needed} XP {medal}',
  },

  // ------------------------------------------------------------
  // Rank Command
  // ------------------------------------------------------------
  rankTitle: {
    de: '📊 Dein Rank',
    en: '📊 Your Rank',
    fr: '📊 Ton rang',
    es: '📊 Tu puesto',
    pt: '📊 Seu rank',
    ru: '📊 Твой ранг',
    ja: '📊 あなたのランク',
    ko: '📊 당신의 랭크',
    zh: '📊 你的排名',
    it: '📊 Il tuo rank',
  },
  rankBody: {
    de: 'Hey {user}!\n\n🏅 **Platz:** #{rank} von {total}\n⭐ **Level:** {level}\n✨ **XP:** {xp} / {needed} XP bis Level {nextLevel}\n📈 **Fortschritt:** {bar} {percent}%\n📉 **Verlust um 0 Uhr:** {decayXp} XP',
    en: 'Hey {user}!\n\n🏅 **Rank:** #{rank} of {total}\n⭐ **Level:** {level}\n✨ **XP:** {xp} / {needed} XP to Level {nextLevel}\n📈 **Progress:** {bar} {percent}%\n📉 **Loss at 0:00:** {decayXp} XP',
    fr: 'Salut {user} !\n\n🏅 **Rang :** #{rank} sur {total}\n⭐ **Niveau :** {level}\n✨ **XP :** {xp} / {needed} XP jusqu’au niveau {nextLevel}\n📈 **Progression :** {bar} {percent}%\n📉 **Perte à minuit :** {decayXp} XP',
    es: '¡Hey {user}!\n\n🏅 **Puesto:** #{rank} de {total}\n⭐ **Nivel:** {level}\n✨ **XP:** {xp} / {needed} XP hasta el nivel {nextLevel}\n📈 **Progreso:** {bar} {percent}%\n📉 **Pérdida a medianoche:** {decayXp} XP',
    pt: 'Hey {user}!\n\n🏅 **Posição:** #{rank} de {total}\n⭐ **Nível:** {level}\n✨ **XP:** {xp} / {needed} XP até o nível {nextLevel}\n📈 **Progresso:** {bar} {percent}%\n📉 **Perda à meia-noite:** {decayXp} XP',
    ru: 'Привет {user}!\n\n🏅 **Место:** #{rank} из {total}\n⭐ **Уровень:** {level}\n✨ **XP:** {xp} / {needed} XP до {nextLevel} уровня\n📈 **Прогресс:** {bar} {percent}%\n📉 **Потеря в полночь:** {decayXp} XP',
    ja: 'やあ {user}！\n\n🏅 **順位:** {total}人中 {rank}位\n⭐ **レベル:** {level}\n✨ **XP:** {xp} / {needed} XP で Lv{nextLevel} へ\n📈 **進捗:** {bar} {percent}%\n📉 **0時の減少:** {decayXp} XP',
    ko: '안녕 {user}!\n\n🏅 **순위:** {total}명 중 {rank}위\n⭐ **레벨:** {level}\n✨ **XP:** {xp} / {needed} XP → Lv{nextLevel}\n📈 **진행도:** {bar} {percent}%\n📉 **자정 손실:** {decayXp} XP',
    zh: '嗨 {user}！\n\n🏅 **排名：** 第 {rank} 名 / 共 {total} 人\n⭐ **等级：** {level}\n✨ **XP：** {xp} / {needed} XP 到 {nextLevel} 级\n📈 **进度：** {bar} {percent}%\n📉 **零点损失：** {decayXp} XP',
    it: 'Ehi {user}!\n\n🏅 **Posizione:** #{rank} su {total}\n⭐ **Livello:** {level}\n✨ **XP:** {xp} / {needed} XP per il livello {nextLevel}\n📈 **Progresso:** {bar} {percent}%\n📉 **Perdita a mezzanotte:** {decayXp} XP',
  },
  rankNoSetup: {
    de: '⛔ Auf diesem Server wurde noch kein XP-System eingerichtet. Bitte **/setup** vom Admin ausführen lassen! 🛠️',
    en: '⛔ XP system not set up on this server yet. Ask an admin to run **/setup**! 🛠️',
    fr: '⛔ Le système XP n’est pas encore configuré. Demande à un admin de faire **/setup** ! 🛠️',
    es: '⛔ El sistema de XP aún no está configurado. ¡Pide a un admin que ejecute **/setup**! 🛠️',
    pt: '⛔ Sistema de XP ainda não configurado. Peça a um admin para usar **/setup**! 🛠️',
    ru: '⛔ Система XP ещё не настроена. Попроси админа выполнить **/setup**! 🛠️',
    ja: '⛔ このサーバーではXPシステムがまだ設定されていません。管理者に **/setup** を実行してもらってね！🛠️',
    ko: '⛔ 이 서버에는 아직 XP 시스템이 설정되지 않았어요. 관리자에게 **/setup**을 요청하세요! 🛠️',
    zh: '⛔ 此服务器尚未设置 XP 系统，请让管理员执行 **/setup**！🛠️',
    it: '⛔ Sistema XP non ancora configurato. Chiedi a un admin di eseguire **/setup**! 🛠️',
  },
  rankNotFound: {
    de: '🤔 Hmm, ich finde dich nicht. Schreib erst eine Nachricht, um XP zu sammeln!',
    en: '🤔 Hmm, I can’t find you. Send a message first to earn XP!',
    fr: '🤔 Hmm, je ne te trouve pas. Envoie d’abord un message pour gagner de l’XP !',
    es: '🤔 Hmm, no te encuentro. ¡Envía un mensaje para ganar XP!',
    pt: '🤔 Hmm, não te encontrei. Envie uma mensagem para ganhar XP!',
    ru: '🤔 Хм, не могу тебя найти. Сначала напиши сообщение, чтобы получить XP!',
    ja: '🤔 あれ、見つからないよ。まずメッセージを送ってXPをゲットしよう！',
    ko: '🤔 음, 찾을 수 없어요. 먼저 메시지를 보내 XP를 얻으세요!',
    zh: '🤔 嗯，找不到你。先发一条消息来获得 XP 吧！',
    it: '🤔 Hmm, non ti trovo. Invia prima un messaggio per guadagnare XP!',
  },

  // ------------------------------------------------------------
  // Bonus-Belohnungen (Zufalls-XP-Drops im Haupt-Chat)
  // ------------------------------------------------------------
  bonusTitle: {
    de: '🎁 Bonus-Belohnung!',
    en: '🎁 Bonus reward!',
    fr: '🎁 Récompense bonus !',
    es: '🎁 ¡Recompensa extra!',
    pt: '🎁 Recompensa bônus!',
    ru: '🎁 Бонусная награда!',
    ja: '🎁 ボーナス報酬！',
    ko: '🎁 럭키 보상!',
    zh: '🎁 额外奖励！',
    it: '🎁 Ricompensa bonus!',
  },
  bonusBody: {
    de: 'Im Chat geht es gerade richtig rund – und schnell sein lohnt sich! ⚡ Klicke als Erster auf **Einsammeln** und schnapp dir die Belohnung: **{xp} XP** geschenkt!',
    en: 'The chat is buzzing right now – and being fast pays off! ⚡ Be the first to hit **Claim** and grab the reward: **{xp} XP** for free!',
    fr: 'Le chat est en feu en ce moment – et la rapidité paie ! ⚡ Sois le premier à cliquer sur **Récupérer** et empoche la récompense : **{xp} XP** offerts !',
    es: '¡El chat está que arde ahora mismo – y ser rápido merece la pena! ⚡ Sé el primero en pulsar **Recoger** y llévate la recompensa: ¡**{xp} XP** gratis!',
    pt: 'O chat está pegando fogo agora – e ser rápido vale a pena! ⚡ Seja o primeiro a clicar em **Coletar** e pegue a recompensa: **{xp} XP** de graça!',
    ru: 'Чат сейчас кипит – и скорость вознаграждается! ⚡ Нажми **Забрать** первым и получи награду: **{xp} XP** даром!',
    ja: 'チャットが今すごく盛り上がってる – 素早さが報われるよ！⚡ 最初に **受け取る** を押した人だけがもらえる報酬: **{xp} XP** プレゼント！',
    ko: '지금 채팅이 아주 활발해요 – 빠른 사람이 이득! ⚡ 가장 먼저 **받기**를 눌러 보상을 가져가세요: **{xp} XP** 공짜!',
    zh: '聊天现在非常火热——手快有奖励！⚡ 第一个点击 **领取** 的人将获得奖励：免费 **{xp} XP**！',
    it: 'La chat è in fermento adesso – e la velocità paga! ⚡ Clicca per primo su **Riscuoti** e prendi la ricompensa: **{xp} XP** gratis!',
  },
  bonusBtn: {
    de: '⚡ Einsammeln!',
    en: '⚡ Claim!',
    fr: '⚡ Récupérer !',
    es: '⚡ ¡Recoger!',
    pt: '⚡ Coletar!',
    ru: '⚡ Забрать!',
    ja: '⚡ 受け取る！',
    ko: '⚡ 받기!',
    zh: '⚡ 领取！',
    it: '⚡ Riscuoti!',
  },
  bonusClaimedTitle: {
    de: '🎁 Bonus-Belohnung – vergriffen!',
    en: '🎁 Bonus reward – claimed!',
    fr: '🎁 Récompense bonus – déjà prise !',
    es: '🎁 Recompensa extra – ¡reclamada!',
    pt: '🎁 Recompensa bônus – já foi!',
    ru: '🎁 Бонусная награда – разобрано!',
    ja: '🎁 ボーナス報酬 – 終了！',
    ko: '🎁 럭키 보상 – 수령 완료!',
    zh: '🎁 额外奖励——已被领取！',
    it: '🎁 Ricompensa bonus – già presa!',
  },
  bonusClaimedBody: {
    de: '⚡ {user} war am schnellsten und hat die **{xp} XP** eingesammelt! Glückwunsch! 🎉 Wer zuerst klickt, gewinnt – nächstes Mal bist du vielleicht dran!',
    en: '⚡ {user} was the fastest and claimed the **{xp} XP**! Congrats! 🎉 First click wins – maybe next time it’s you!',
    fr: '⚡ {user} a été le plus rapide et a récupéré les **{xp} XP** ! Bravo ! 🎉 Le premier clic gagne – la prochaine fois, ce sera peut-être toi !',
    es: '⚡ ¡{user} fue el más rápido y recogió los **{xp} XP**! ¡Felicidades! 🎉 El primero en hacer clic gana – ¡quizá la próxima seas tú!',
    pt: '⚡ {user} foi o mais rápido e coletou os **{xp} XP**! Parabéns! 🎉 Quem clica primeiro ganha – talvez na próxima seja você!',
    ru: '⚡ {user} был быстрее всех и забрал **{xp} XP**! Поздравляем! 🎉 Кто первый нажал, тот и выиграл – в следующий раз, может, ты!',
    ja: '⚡ {user} が一番速くて **{xp} XP** をゲット！おめでとう！🎉 早押し勝負 – 次は君の番かも！',
    ko: '⚡ {user}님이 가장 빨라서 **{xp} XP**를 가져갔어요! 축하해요! 🎉 먼저 누르는 사람이 승자 – 다음엔 당신 차례일지도!',
    zh: '⚡ {user} 手最快，领取了 **{xp} XP**！恭喜！🎉 先到先得——下次可能就轮到你！',
    it: '⚡ {user} è stato il più veloce e ha riscosso i **{xp} XP**! Complimenti! 🎉 Chi clicca prima vince – la prossima volta forse tocca a te!',
  },
  bonusExpiredTitle: {
    de: '🎁 Bonus-Belohnung – verfallen!',
    en: '🎁 Bonus reward – expired!',
    fr: '🎁 Récompense bonus – expirée !',
    es: '🎁 Recompensa extra – ¡caducada!',
    pt: '🎁 Recompensa bônus – expirada!',
    ru: '🎁 Бонусная награда – истекла!',
    ja: '🎁 ボーナス報酬 – 期限切れ！',
    ko: '🎁 럭키 보상 – 기간 만료!',
    zh: '🎁 额外奖励——已过期！',
    it: '🎁 Ricompensa bonus – scaduta!',
  },
  bonusExpiredBody: {
    de: '⌛ Zu langsam … niemand war schnell genug. Die **{xp} XP** sind verfallen!',
    en: '⌛ Too slow … nobody was fast enough. The **{xp} XP** have expired!',
    fr: '⌛ Trop lent … personne n’a été assez rapide. Les **{xp} XP** ont expiré !',
    es: '⌛ Demasiado lento … nadie fue lo bastante rápido. ¡Los **{xp} XP** caducaron!',
    pt: '⌛ Muito devagar … ninguém foi rápido o suficiente. Os **{xp} XP** expiraram!',
    ru: '⌛ Слишком медленно … никто не успел. **{xp} XP** сгорели!',
    ja: '⌛ 残念 … 誰も間に合わなかった。**{xp} XP** は消えちゃった！',
    ko: '⌛ 너무 느렸어요 … 아무것도 가져가지 못해서 **{xp} XP**가 사라졌어요!',
    zh: '⌛ 太慢了……没人来得及领取。**{xp} XP** 已过期！',
    it: '⌛ Troppo lenti … nessuno è stato abbastanza veloce. I **{xp} XP** sono scaduti!',
  },
  bonusGone: {
    de: '😴 Zu spät! Diese Belohnung wurde schon eingesammelt oder ist abgelaufen.',
    en: '😴 Too late! This reward was already claimed or has expired.',
    fr: '😴 Trop tard ! Cette récompense a déjà été récupérée ou a expiré.',
    es: '😴 ¡Demasiado tarde! Esta recompensa ya fue recogida o caducó.',
    pt: '😴 Tarde demais! Esta recompensa já foi coletada ou expirou.',
    ru: '😴 Поздно! Эту награду уже забрали или она истекла.',
    ja: '😴 遅かった！この報酬はもう受け取られたか期限切れだよ。',
    ko: '😴 늦었어요! 이 보상은 이미 수령됐거나 만료됐어요.',
    zh: '😴 太迟了！该奖励已被领取或已过期。',
    it: '😴 Troppo tardi! Questa ricompensa è già stata riscossa o è scaduta.',
  },
  bonusClaimedYou: {
    de: '🎉 Stark! Du hast die **{xp} XP** eingesammelt!',
    en: '🎉 Nice! You claimed the **{xp} XP**!',
    fr: '🎉 Bravo ! Tu as récupéré les **{xp} XP** !',
    es: '🎉 ¡Genial! ¡Has recogido los **{xp} XP**!',
    pt: '🎉 Boa! Você coletou os **{xp} XP**!',
    ru: '🎉 Круто! Ты забрал **{xp} XP**!',
    ja: '🎉 やったね！**{xp} XP** をゲット！',
    ko: '🎉 대박! **{xp} XP**를 받았어요!',
    zh: '🎉 太棒了！你领取了 **{xp} XP**！',
    it: '🎉 Grande! Hai riscosso i **{xp} XP**!',
  },

  // ------------------------------------------------------------
  // Level Up / Down
  // ------------------------------------------------------------
  levelUp: {
    de: '🎉 {user} ist auf Level {level} aufgestiegen! Weiter so!',
    en: '🎉 {user} reached Level {level}! Keep it up!',
    fr: '🎉 {user} est passé au niveau {level} ! Continue comme ça !',
    es: '🎉 ¡{user} alcanzó el nivel {level}! ¡Sigue así!',
    pt: '🎉 {user} chegou ao nível {level}! Continua assim!',
    ru: '🎉 {user} достиг уровня {level}! Так держать!',
    ja: '🎉 {user} がレベル {level} に到達！その調子！',
    ko: '🎉 {user}님이 레벨 {level} 달성! 계속 가즈아!',
    zh: '🎉 {user} 达到了 {level} 级！继续冲！',
    it: '🎉 {user} ha raggiunto il livello {level}! Continua così!',
  },
  levelDown: {
    de: '😢 Oh nein! {user} ist auf **Level {level}** abgestiegen… {xp}/{needed} XP – mehr chatten, sonst rutschst du weiter! 💬😬',
    en: '😢 Oh no! {user} dropped to **Level {level}**… {xp}/{needed} XP – chat more or you’ll slide further! 💬😬',
    fr: '😢 Oh non ! {user} est retombé au **niveau {level}**… {xp}/{needed} XP – discute plus ! 💬😬',
    es: '😢 ¡Oh no! {user} bajó al **nivel {level}**… {xp}/{needed} XP – ¡chatea más! 💬😬',
    pt: '😢 Oh não! {user} caiu para o **nível {level}**… {xp}/{needed} XP – converse mais! 💬😬',
    ru: '😢 О нет! {user} упал до **уровня {level}**… {xp}/{needed} XP – болтай больше! 💬😬',
    ja: '😢 あらら！{user} が **レベル {level}** にダウン… {xp}/{needed} XP – もっとチャットしよう！💬😬',
    ko: '😢 앗! {user}님이 **레벨 {level}**(으)로 떨어졌어요… {xp}/{needed} XP – 더 채팅하세요! 💬😬',
    zh: '😢 哎呀！{user} 掉到了 **{level} 级**… {xp}/{needed} XP——多聊聊吧！💬😬',
    it: '😢 Oh no! {user} è sceso al **livello {level}**… {xp}/{needed} XP – chatta di più! 💬😬',
  },

  // ------------------------------------------------------------
  // Nickname
  // ------------------------------------------------------------
  nickFail: {
    de: '😅 Hey {user}! Ich konnte dein Level nicht in deinen Nicknamen einbauen da mir die nötigen Rechte fehlen. 🙈 Ich brauche eine Rolle, die **über allen anderen Rollen liegt**. Bitte den Server-Owner darum, meine Rolle ganz nach oben zu schieben, damit ich wirklich die Nicknames aller Nutzer ändern kann! 🛠️✨',
    en: '😅 Hey {user}! I couldn\'t add your level to your nickname – I\'m missing permissions. 🙈 I need a role that **sits above all other roles**. Please ask the server owner to move my role to the very top so I can update everyone\'s nicknames! 🛠️✨',
    fr: '😅 Hey {user} ! Je n’ai pas pu ajouter ton niveau à ton pseudo – il me manque des permissions. 🙈 J’ai besoin d’un rôle **au-dessus de tous les autres**. Demande au propriétaire de mettre mon rôle tout en haut ! 🛠️✨',
    es: '😅 ¡Hey {user}! No pude añadir tu nivel a tu apodo – me faltan permisos. 🙈 Necesito un rol **por encima de todos los demás**. ¡Pide al dueño que ponga mi rol arriba del todo! 🛠️✨',
    pt: '😅 Hey {user}! Não consegui adicionar seu nível ao seu apelido – faltam permissões. 🙈 Preciso de um cargo **acima de todos os outros**. Peça ao dono para colocar meu cargo no topo! 🛠️✨',
    ru: '😅 Привет {user}! Не смог добавить уровень в твой ник – не хватает прав. 🙈 Мне нужна роль **выше всех остальных**. Попроси владельца поднять мою роль наверх! 🛠️✨',
    ja: '😅 やあ {user}！権限不足でニックネームにレベルを入れられなかったよ🙈 **一番上のロール**が必要なんだ。サーバーオーナーに私のロールを一番上にしてもらってね！🛠️✨',
    ko: '😅 안녕 {user}! 권한이 없어서 닉네임에 레벨을 넣지 못했어요🙈 **모든 역할보다 위에 있는 역할**이 필요해요. 서버 소유자에게 내 역할을 맨 위로 올려 달라고 해주세요! 🛠️✨',
    zh: '😅 嗨 {user}！我无法把你的等级加入昵称——权限不足🙈 我需要一个**高于所有其他角色**的身份组。请让服主把我的身份组移到最顶端！🛠️✨',
    it: '😅 Ehi {user}! Non sono riuscito ad aggiungere il tuo livello al nickname – mi mancano i permessi. 🙈 Ho bisogno di un ruolo **sopra tutti gli altri**. Chiedi al proprietario di spostare il mio ruolo in cima! 🛠️✨',
  },
  nickUpdated: {
    de: '🏷️ Dein Nickname wurde auf **{nick}** aktualisiert!',
    en: '🏷️ Your nickname was updated to **{nick}**!',
    fr: '🏷️ Ton pseudo a été mis à jour : **{nick}** !',
    es: '🏷️ ¡Tu apodo se actualizó a **{nick}**!',
    pt: '🏷️ Seu apelido foi atualizado para **{nick}**!',
    ru: '🏷️ Твой ник обновлён на **{nick}**!',
    ja: '🏷️ ニックネームを **{nick}** に更新したよ！',
    ko: '🏷️ 닉네임이 **{nick}**(으)로 업데이트됐어요!',
    zh: '🏷️ 你的昵称已更新为 **{nick}**！',
    it: '🏷️ Il tuo nickname è stato aggiornato a **{nick}**!',
  },

  // ------------------------------------------------------------
  // Level-Rollen (Belohnungsrollen)
  // ------------------------------------------------------------
  levelRolesHelp: {
    de: 'Passt die Level-Belohnungsrollen an (Formular)',
    en: 'Adjust the level reward roles (form)',
    fr: 'Ajuste les rôles de récompense de niveau (formulaire)',
    es: 'Ajusta los roles de recompensa por nivel (formulario)',
    pt: 'Ajusta os cargos de recompensa por nível (formulário)',
    ru: 'Настройка ролей-наград за уровни (форма)',
    ja: 'レベル報酬ロールを調整（フォーム）',
    ko: '레벨 보상 역할 조정 (양식)',
    zh: '调整等级奖励身份组（表单）',
    it: 'Regola i ruoli premio di livello (modulo)',
  },
  levelRolesModalTitle: {
    de: '🎖️ Level-Rollen einstellen',
    en: '🎖️ Set level roles',
    fr: '🎖️ Configurer les rôles de niveau',
    es: '🎖️ Configurar roles de nivel',
    pt: '🎖️ Configurar cargos de nível',
    ru: '🎖️ Настройка ролей уровней',
    ja: '🎖️ レベルロール設定',
    ko: '🎖️ 레벨 역할 설정',
    zh: '🎖️ 设置等级身份组',
    it: '🎖️ Imposta ruoli di livello',
  },
  levelRolesFormatLabel: {
    de: 'Format: {LEVEL} wird durch die Zahl ersetzt',
    en: 'Format: {LEVEL} is replaced by the number',
    fr: 'Format : {LEVEL} remplacé par le nombre',
    es: 'Formato: {LEVEL} se sustituye por el número',
    pt: 'Formato: {LEVEL} é substituído pelo número',
    ru: 'Формат: {LEVEL} заменяется на число',
    ja: '形式: {LEVEL} は数字に置き換わります',
    ko: '형식: {LEVEL}은 숫자로 바뀝니다',
    zh: '格式：{LEVEL} 会替换成数字',
    it: 'Formato: {LEVEL} sostituito dal numero',
  },
  levelRolesLevelsLabel: {
    de: 'Level-Zahlen, Komma getrennt (z.B. 3,6,10,20)',
    en: 'Levels, comma separated (e.g. 3,6,10,20)',
    fr: 'Niveaux séparés par virgule (ex. 3,6,10,20)',
    es: 'Niveles separados por coma (ej. 3,6,10,20)',
    pt: 'Níveis separados por vírgula (ex. 3,6,10,20)',
    ru: 'Уровни через запятую (напр. 3,6,10,20)',
    ja: 'レベル番号をカンマ区切り (例 3,6,10,20)',
    ko: '레벨 숫자를 쉼표로 구분 (예: 3,6,10,20)',
    zh: '等级数字，用逗号分隔（如 3,6,10,20）',
    it: 'Livelli separati da virgola (es. 3,6,10,20)',
  },
  levelRolesNoLevels: {
    de: '⚠️ Ich konnte keine gültigen Level-Zahlen finden. Bitte gib Zahlen ein, die mit Komma getrennt sind – z.B. `3,6,10,20`.',
    en: '⚠️ I couldn’t find any valid level numbers. Please enter numbers separated by commas – e.g. `3,6,10,20`.',
    fr: '⚠️ Je n’ai trouvé aucun numéro de niveau valide. Sépare les nombres par des virgules – ex. `3,6,10,20`.',
    es: '⚠️ No encontré números de nivel válidos. Introduce números separados por comas – ej. `3,6,10,20`.',
    pt: '⚠️ Não encontrei números de nível válidos. Digite números separados por vírgulas – ex. `3,6,10,20`.',
    ru: '⚠️ Не нашёл допустимых номеров уровней. Введи числа через запятую – напр. `3,6,10,20`.',
    ja: '⚠️ 有効なレベル番号が見つかりませんでした。カンマ区切りで入力してね – 例 `3,6,10,20`。',
    ko: '⚠️ 유효한 레벨 숫자를 찾지 못했어요. 쉼표로 구분해 입력하세요 – 예: `3,6,10,20`.',
    zh: '⚠️ 没有找到有效的等级数字。请用逗号分隔输入数字，例如 `3,6,10,20`。',
    it: '⚠️ Non ho trovato numeri di livello validi. Inserisci numeri separati da virgole – es. `3,6,10,20`.',
  },
  levelRolesNoPlaceholder: {
    de: '⚠️ Das Rollen-Format muss den Platzhalter **{LEVEL}** enthalten – z.B. `Level {LEVEL}`.',
    en: '⚠️ The role format must contain the placeholder **{LEVEL}** – e.g. `Level {LEVEL}`.',
    fr: '⚠️ Le format du rôle doit contenir le marqueur **{LEVEL}** – ex. `Niveau {LEVEL}`.',
    es: '⚠️ El formato del rol debe contener el marcador **{LEVEL}** – ej. `Nivel {LEVEL}`.',
    pt: '⚠️ O formato do cargo deve conter o marcador **{LEVEL}** – ex. `Nível {LEVEL}`.',
    ru: '⚠️ Формат роли должен содержать заполнитель **{LEVEL}** – напр. `Уровень {LEVEL}`.',
    ja: '⚠️ ロール名の形式には **{LEVEL}** を含めてね – 例 `レベル {LEVEL}`。',
    ko: '⚠️ 역할 형식에는 **{LEVEL}** 자리표시자가 필요해요 – 예: `레벨 {LEVEL}`.',
    zh: '⚠️ 身份组名称格式必须包含占位符 **{LEVEL}**，例如 `等级 {LEVEL}`。',
    it: '⚠️ Il formato del ruolo deve contenere il segnaposto **{LEVEL}** – es. `Livello {LEVEL}`.',
  },
  levelRolesBotPerms: {
    de: '⛔ Die Level-Rollen konnten nicht erstellt werden – ich brauche die Berechtigung **Rollen verwalten**. ({error})',
    en: '⛔ Could not create the level roles – I need the **Manage Roles** permission. ({error})',
    fr: '⛔ Impossible de créer les rôles de niveau – il me faut la permission **Gérer les rôles**. ({error})',
    es: '⛔ No se pudieron crear los roles de nivel – necesito el permiso **Gestionar roles**. ({error})',
    pt: '⛔ Não foi possível criar os cargos de nível – preciso da permissão **Gerenciar cargos**. ({error})',
    ru: '⛔ Не удалось создать роли уровней – мне нужно право **Управление ролями**. ({error})',
    ja: '⛔ レベルロールを作成できませんでした – **ロールの管理**権限が必要です。（{error}）',
    ko: '⛔ 레벨 역할을 만들 수 없어요 – **역할 관리** 권한이 필요합니다. ({error})',
    zh: '⛔ 无法创建等级身份组——我需要**管理身份组**权限。（{error}）',
    it: '⛔ Impossibile creare i ruoli di livello – mi serve il permesso **Gestisci ruoli**. ({error})',
  },
  levelRolesDoneTitle: {
    de: '🎖️ Level-Rollen erledigt',
    en: '🎖️ Level roles done',
    fr: '🎖️ Rôles de niveau prêts',
    es: '🎖️ Roles de nivel listos',
    pt: '🎖️ Cargos de nível prontos',
    ru: '🎖️ Роли уровней готовы',
    ja: '🎖️ レベルロール完了',
    ko: '🎖️ 레벨 역할 완료',
    zh: '🎖️ 等级身份组已完成',
    it: '🎖️ Ruoli di livello pronti',
  },
  levelRolesDone: {
    de: '✅ **Erledigt!** {count} Level-Rollen wurden neu erstellt, nach Level sortiert und ganz unten einsortiert ({deleted} alte entfernt).\n\nDu kannst die Rollenfarben und Namen jetzt nochmal manuell anpassen. 🎨',
    en: '✅ **Done!** {count} level roles were created, sorted by level and placed at the very bottom ({deleted} old ones removed).\n\nYou can now adjust the role colors and names manually. 🎨',
    fr: '✅ **Terminé !** {count} rôles de niveau créés, triés par niveau et placés tout en bas ({deleted} anciens supprimés).\n\nTu peux maintenant ajuster couleurs et noms manuellement. 🎨',
    es: '✅ **¡Listo!** {count} roles de nivel creados, ordenados por nivel y colocados abajo del todo ({deleted} antiguos eliminados).\n\nYa puedes ajustar colores y nombres manualmente. 🎨',
    pt: '✅ **Pronto!** {count} cargos de nível criados, ordenados por nível e colocados lá embaixo ({deleted} antigos removidos).\n\nAgora você pode ajustar cores e nomes manualmente. 🎨',
    ru: '✅ **Готово!** Создано ролей уровней: {count} – отсортированы по уровню и размещены в самом низу (удалено старых: {deleted}).\n\nТеперь ты можешь вручную настроить цвета и названия. 🎨',
    ja: '✅ **完了！** {count} 個のレベルロールを作成・レベル順に並べて最下部に配置しました（{deleted} 個の旧ロールを削除）。\n\n色や名前はあとで手動で調整できますよ。🎨',
    ko: '✅ **완료!** 레벨 역할 {count}개를 만들고 레벨순으로 정렬해 맨 아래에 배치했어요 (이전 {deleted}개 제거).\n\n이제 역할 색상과 이름을 직접 조정할 수 있어요. 🎨',
    zh: '✅ **完成！** 已创建 {count} 个等级身份组，按等级排序并放在最底部（删除 {deleted} 个旧的）。\n\n你现在可以手动调整身份组的颜色和名称。🎨',
    it: '✅ **Fatto!** {count} ruoli di livello creati, ordinati per livello e posizionati in fondo ({deleted} vecchi rimossi).\n\nOra puoi regolare colori e nomi manualmente. 🎨',
  },
  levelRolesListTitle: {
    de: '📜 **Rollen (ganz unten in der Liste, mehr Level = weiter oben):**',
    en: '📜 **Roles (at the very bottom of the list, higher level = higher):**',
    fr: '📜 **Rôles (tout en bas de la liste, niveau plus haut = au-dessus) :**',
    es: '📜 **Roles (abajo del todo, más nivel = más arriba):**',
    pt: '📜 **Cargos (lá embaixo, mais nível = mais acima):**',
    ru: '📜 **Роли (в самом низу списка, выше уровень = выше роль):**',
    ja: '📜 **ロール（リスト最下部、レベルが高いほど上）:**',
    ko: '📜 **역할 (목록 맨 아래, 레벨이 높을수록 위):**',
    zh: '📜 **身份组（列表最底部，等级越高越靠上）：**',
    it: '📜 **Ruoli (in fondo alla lista, più livello = più in alto):**',
  },

  // ------------------------------------------------------------
  // Setup
  // ------------------------------------------------------------
  setupLeaderDesc: {
    de: 'Kanal für das stündliche Leaderboard',
    en: 'Channel for the hourly leaderboard',
    fr: 'Salon pour le classement horaire',
    es: 'Canal para la tabla horaria',
    pt: 'Canal para o ranking horário',
    ru: 'Канал для ежечасной таблицы лидеров',
    ja: 'ランキング用のチャンネル（1時間ごと）',
    ko: '시간별 리더보드 채널',
    zh: '用于每小时排行榜的频道',
    it: 'Canale per la classifica oraria',
  },
  setupMainDesc: {
    de: 'Haupt-Chat-Kanal für Level-Up-Nachrichten',
    en: 'Main chat channel for level-up messages',
    fr: 'Salon principal pour les messages de niveau',
    es: 'Canal principal para mensajes de nivel',
    pt: 'Canal principal para mensagens de nível',
    ru: 'Основной канал для сообщений о повышении уровня',
    ja: 'レベルアップ通知用のメインチャンネル',
    ko: '레벨업 메시지용 메인 채널',
    zh: '用于等级提升消息的主聊天频道',
    it: 'Canale principale per i messaggi di level-up',
  },
  setupLangDesc: {
    de: 'Sprache des Bots auf diesem Server',
    en: 'Language of the bot on this server',
    fr: 'Langue du bot sur ce serveur',
    es: 'Idioma del bot en este servidor',
    pt: 'Idioma do bot neste servidor',
    ru: 'Язык бота на этом сервере',
    ja: 'このサーバーでのボットの言語',
    ko: '이 서버에서의 봇 언어',
    zh: '机器人在此服务器上的语言',
    it: 'Lingua del bot su questo server',
  },
  setupSuccess: {
    de: '🎉 Alles eingerichtet! **Leaderboard:** {leader}  **Haupt-Chat:** {main}  **Sprache:** {lang} 🚀 Leaderboard erscheint stündlich neu & wird sofort erstellt! ✨',
    en: '🎉 All set! **Leaderboard:** {leader}  **Main Chat:** {main}  **Language:** {lang} 🚀 Leaderboard refreshes hourly & was created instantly! ✨',
    fr: '🎉 Tout est prêt ! **Classement :** {leader}  **Chat principal :** {main}  **Langue :** {lang} 🚀',
    es: '🎉 ¡Todo listo! **Tabla:** {leader}  **Chat principal:** {main}  **Idioma:** {lang} 🚀',
    pt: '🎉 Tudo pronto! **Ranking:** {leader}  **Chat principal:** {main}  **Idioma:** {lang} 🚀',
    ru: '🎉 Всё готово! **Таблица:** {leader}  **Главный чат:** {main}  **Язык:** {lang} 🚀',
    ja: '🎉 設定完了！**ランキング:** {leader}  **メイン:** {main}  **言語:** {lang} 🚀',
    ko: '🎉 설정 완료! **리더보드:** {leader}  **메인 채팅:** {main}  **언어:** {lang} 🚀',
    zh: '🎉 设置完成！**排行榜：** {leader}  **主频道：** {main}  **语言：** {lang} 🚀',
    it: '🎉 Tutto pronto! **Classifica:** {leader}  **Chat principale:** {main}  **Lingua:** {lang} 🚀',
  },
  setupLangBad: {
    de: '⛔ Bitte wähle eine gültige Sprache aus den Vorschlägen.',
    en: '⛔ Please pick a valid language from the suggestions.',
    fr: '⛔ Choisis une langue valide dans les suggestions.',
    es: '⛔ Elige un idioma válido de las sugerencias.',
    pt: '⛔ Escolha um idioma válido nas sugestões.',
    ru: '⛔ Выбери допустимый язык из предложенных.',
    ja: '⛔ 提案の中から有効な言語を選んでください。',
    ko: '⛔ 제안 중에서 유효한 언어를 선택하세요.',
    zh: '⛔ 请从建议中选择有效的语言。',
    it: '⛔ Scegli una lingua valida dai suggerimenti.',
  },
  setupFoundOld: {
    de: '🔎 Bestehendes Setup gefunden – übernehme Einstellungen & XP!',
    en: '🔎 Found existing setup – carrying over settings & XP!',
    fr: '🔎 Configuration existante trouvée – reprise des paramètres & XP !',
    es: '🔎 Configuración existente encontrada – ¡manteniendo ajustes y XP!',
    pt: '🔎 Configuração existente encontrada – mantendo ajustes e XP!',
    ru: '🔎 Найдена существующая настройка – переношу настройки и XP!',
    ja: '🔎 既存の設定を見つけたよ – 設定とXPを引き継ぐね！',
    ko: '🔎 기존 설정을 찾았어요 – 설정과 XP를 유지할게요!',
    zh: '🔎 找到现有设置——正在迁移设置和 XP！',
    it: '🔎 Configurazione esistente trovata – mantengo impostazioni e XP!',
  },

  // ------------------------------------------------------------
  // Errors generic
  // ------------------------------------------------------------
  errGuildOnly: {
    de: '⛔ Dieser Befehl funktioniert nur auf einem Server.',
    en: '⛔ This command only works on a server.',
    fr: '⛔ Cette commande ne fonctionne que sur un serveur.',
    es: '⛔ Este comando solo funciona en un servidor.',
    pt: '⛔ Este comando só funciona em um servidor.',
    ru: '⛔ Эта команда работает только на сервере.',
    ja: '⛔ このコマンドはサーバーでのみ使用できます。',
    ko: '⛔ 이 명령어는 서버에서만 사용할 수 있어요.',
    zh: '⛔ 此命令只能在服务器上使用。',
    it: '⛔ Questo comando funziona solo su un server.',
  },
  errNoPermission: {
    de: '⛔ Dazu brauchst du die **Administrator**-Berechtigung!',
    en: '⛔ You need the **Administrator** permission for this!',
    fr: '⛔ Tu as besoin de la permission **Administrateur** pour ça !',
    es: '⛔ ¡Necesitas el permiso de **Administrador** para esto!',
    pt: '⛔ Você precisa da permissão de **Administrador** para isso!',
    ru: '⛔ Для этого нужны права **Администратора**!',
    ja: '⛔ これには**管理者**権限が必要です！',
    ko: '⛔ 이 작업에는 **관리자** 권한이 필요해요!',
    zh: '⛔ 执行此操作需要**管理员**权限！',
    it: '⛔ Per questo serve il permesso **Amministratore**!',
  },
  errOwnerOnly: {
    de: '⛔ Nur der Bot-Owner kann das nutzen!',
    en: '⛔ Only the bot owner can use this!',
    fr: '⛔ Seul le propriétaire du bot peut utiliser ça !',
    es: '⛔ ¡Solo el propietario del bot puede usar esto!',
    pt: '⛔ Somente o dono do bot pode usar isso!',
    ru: '⛔ Это может использовать только владелец бота!',
    ja: '⛔ これはボットの所有者だけが使えます！',
    ko: '⛔ 봇 소유자만 사용할 수 있어요!',
    zh: '⛔ 只有机器人所有者才能使用此功能！',
    it: '⛔ Solo il proprietario del bot può usarlo!',
  },
  errDmOnly: {
    de: '⛔ Bitte nutze diesen Befehl im Privatchat mit dem Bot-Owner!',
    en: '⛔ Please use this command in the DM with the bot owner!',
    fr: '⛔ Utilise cette commande en MP avec le propriétaire du bot !',
    es: '⛔ ¡Usa este comando en el DM con el propietario del bot!',
    pt: '⛔ Use este comando no DM com o dono do bot!',
    ru: '⛔ Используй эту команду в ЛС с владельцем бота!',
    ja: '⛔ ボット所有者とのDMでこのコマンドを使用してください！',
    ko: '⛔ 봇 소유자와의 DM에서 이 명령어를 사용하세요!',
    zh: '⛔ 请在机器人所有者的私聊中使用此命令！',
    it: '⛔ Usa questo comando nel DM con il proprietario del bot!',
  },
  errChannelBad: {
    de: '⛔ Bitte wähle einen Textchannel aus!',
    en: '⛔ Please choose a text channel!',
    fr: '⛔ Choisis un salon textuel !',
    es: '⛔ ¡Elige un canal de texto!',
    pt: '⛔ Escolha um canal de texto!',
    ru: '⛔ Выбери текстовый канал!',
    ja: '⛔ テキストチャンネルを選択してください！',
    ko: '⛔ 텍스트 채널을 선택하세요!',
    zh: '⛔ 请选择一个文字频道！',
    it: '⛔ Scegli un canale testuale!',
  },
  errBotPerms: {
    de: '⛔ Ich brauche die Berechtigungen **Nachrichten senden** und **Kanal ansehen** in {channel}!',
    en: '⛔ I need **Send Messages** and **View Channel** permissions in {channel}!',
    fr: '⛔ J’ai besoin des permissions **Envoyer des messages** et **Voir le salon** dans {channel} !',
    es: '⛔ ¡Necesito los permisos **Enviar mensajes** y **Ver canal** en {channel}!',
    pt: '⛔ Preciso das permissões **Enviar mensagens** e **Ver canal** em {channel}!',
    ru: '⛔ Мне нужны права **Отправлять сообщения** и **Просматривать канал** в {channel}!',
    ja: '⛔ {channel} で**メッセージを送信**と**チャンネルを見る**権限が必要です！',
    ko: '⛔ {channel}에서 **메시지 보내기** 및 **채널 보기** 권한이 필요해요!',
    zh: '⛔ 我需要在{channel}中拥有**发送消息**和**查看频道**的权限！',
    it: '⛔ Mi servono i permessi **Invia messaggi** e **Vedi canale** in {channel}!',
  },
  errGeneric: {
    de: '😵 Ups, da ist etwas schiefgelaufen. Bitte versuch es nochmal! 🤖',
    en: '😵 Oops, something went wrong. Please try again! 🤖',
    fr: '😵 Oups, quelque chose s’est mal passé. Réessaie ! 🤖',
    es: '😵 Vaya, algo salió mal. ¡Inténtalo de nuevo! 🤖',
    pt: '😵 Opa, algo deu errado. Tente novamente! 🤖',
    ru: '😵 Ой, что-то пошло не так. Попробуй ещё раз! 🤖',
    ja: '😵 あれ、何かがうまくいきませんでした。もう一度お試しください！🤖',
    ko: '😵 앗, 뭔가 잘못됐어요. 다시 시도해 주세요! 🤖',
    zh: '😵 哎呀，出了点问题，请重试！🤖',
    it: '😵 Ops, qualcosa è andato storto. Riprova! 🤖',
  },
  errNoSetup: {
    de: '⛔ Es gibt noch kein XP-System auf diesem Server. Bitte nutze zuerst **/setup**! 🛠️',
    en: '⛔ XP system not set up yet. Please use **/setup** first! 🛠️',
    fr: '⛔ Le système XP n’est pas encore configuré. Utilise d’abord **/setup** ! 🛠️',
    es: '⛔ El sistema de XP aún no está configurado. ¡Usa primero **/setup**! 🛠️',
    pt: '⛔ Sistema de XP ainda não configurado. Use **/setup** primeiro! 🛠️',
    ru: '⛔ Система XP ещё не настроена. Сначала используй **/setup**! 🛠️',
    ja: '⛔ まだXPシステムが設定されていません。先に **/setup** を使ってね！🛠️',
    ko: '⛔ 아직 XP 시스템이 설정되지 않았어요. 먼저 **/setup**을 사용하세요! 🛠️',
    zh: '⛔ 尚未设置 XP 系统，请先使用 **/setup**！🛠️',
    it: '⛔ Sistema XP non ancora configurato. Usa prima **/setup**! 🛠️',
  },

  // ------------------------------------------------------------
  // Help
  // ------------------------------------------------------------
  helpTitle: {
    de: '📖 Hilfe & Befehle – XP Level Bot',
    en: '📖 Help & Commands – XP Level Bot',
    fr: '📖 Aide et commandes – XP Level Bot',
    es: '📖 Ayuda y comandos – XP Level Bot',
    pt: '📖 Ajuda e comandos – XP Level Bot',
    ru: '📖 Помощь и команды – XP Level Bot',
    ja: '📖 ヘルプ＆コマンド – XPレベルBot',
    ko: '📖 도움말 및 명령어 – XP 레벨 봇',
    zh: '📖 帮助与命令 – XP 等级机器人',
    it: '📖 Aiuto e comandi – XP Level Bot',
  },
  helpDesc: {
    de: 'Hier findest du alle Befehle des XP-Bots – werde zum Chat-Champion! 👇✨',
    en: 'Here are all the XP bot’s commands – become the chat champion! 👇✨',
    fr: 'Voici toutes les commandes du bot XP – deviens champion du chat ! 👇✨',
    es: '¡Aquí tienes todos los comandos del bot de XP – conviértete en campeón del chat! 👇✨',
    pt: 'Aqui estão todos os comandos do bot de XP – torne-se o campeão do chat! 👇✨',
    ru: 'Вот все команды XP-бота – стань чемпионом чата! 👇✨',
    ja: 'XPボットの全コマンドはこちら – チャットチャンピオンになろう！👇✨',
    ko: 'XP 봇의 모든 명령어예요 – 채팅 챔피언이 되어 보세요! 👇✨',
    zh: '以下是 XP 机器人的所有命令——成为聊天冠军吧！👇✨',
    it: 'Ecco tutti i comandi del bot XP – diventa campione della chat! 👇✨',
  },
  helpSetup: {
    de: 'Richtet das XP-System ein (Leaderboard-Kanal + Haupt-Chat + Sprache). Nur für Admins.',
    en: 'Sets up the XP system (leaderboard channel + main chat + language). Admins only.',
    fr: 'Configure le système XP (salon classement + chat principal + langue). Réservé aux admins.',
    es: 'Configura el sistema de XP (canal de tabla + chat principal + idioma). Solo admins.',
    pt: 'Configura o sistema de XP (canal de ranking + chat principal + idioma). Só admins.',
    ru: 'Настраивает систему XP (канал таблицы + главный чат + язык). Только для админов.',
    ja: 'XPシステムを設定します（ランキングチャンネル＋メインチャット＋言語）。管理者のみ。',
    ko: 'XP 시스템을 설정해요(리더보드 채널 + 메인 채팅 + 언어). 관리자 전용.',
    zh: '设置 XP 系统（排行榜频道+主聊天+语言）。仅限管理员。',
    it: 'Configura il sistema XP (canale classifica + chat principale + lingua). Solo admin.',
  },
  helpRank: {
    de: 'Zeigt deinen aktuellen Level, XP und Platz auf dem Server. Für alle!',
    en: 'Shows your current level, XP and rank on the server. For everyone!',
    fr: 'Affiche ton niveau, ton XP et ton rang sur le serveur. Pour tous !',
    es: 'Muestra tu nivel, XP y puesto en el servidor. ¡Para todos!',
    pt: 'Mostra seu nível, XP e posição no servidor. Para todos!',
    ru: 'Показывает твой уровень, XP и место на сервере. Для всех!',
    ja: 'あなたの現在のレベル、XP、順位を表示します。誰でも使えるよ！',
    ko: '현재 레벨, XP, 서버 순위를 보여줘요. 모두 사용 가능!',
    zh: '显示你当前的等级、XP 和服务器排名，人人可用！',
    it: 'Mostra il tuo livello, XP e posizione sul server. Per tutti!',
  },
  helpHelp: {
    de: 'Zeigt diese Übersicht an.',
    en: 'Shows this overview.',
    fr: 'Affiche cet aperçu.',
    es: 'Muestra esta vista general.',
    pt: 'Mostra esta visão geral.',
    ru: 'Показывает этот обзор.',
    ja: 'この概要を表示します。',
    ko: '이 개요를 보여줘요.',
    zh: '显示此概览。',
    it: 'Mostra questa panoramica.',
  },
  helpSetProfile: {
    de: 'Ändert das Profilbild des Bots auf diesem Server.',
    en: 'Changes the bot’s profile picture on this server.',
    fr: 'Modifie l’image de profil du bot sur ce serveur.',
    es: 'Cambia la foto de perfil del bot en este servidor.',
    pt: 'Altera a foto de perfil do bot neste servidor.',
    ru: 'Меняет аватар бота на этом сервере.',
    ja: 'このサーバーでのボットのプロフィール画像を変更します。',
    ko: '이 서버에서 봇의 프로필 사진을 변경해요.',
    zh: '更改机器人在此服务器上的头像。',
    it: 'Cambia l’immagine del profilo del bot su questo server.',
  },
  helpAdminPanel: {
    de: 'Owner-Panel (nur im DM mit dem Bot-Owner).',
    en: 'Owner panel (DM with the bot owner only).',
    fr: 'Panneau propriétaire (MP avec le propriétaire uniquement).',
    es: 'Panel del propietario (solo en DM con el propietario del bot).',
    pt: 'Painel do dono (somente no DM com o dono do bot).',
    ru: 'Панель владельца (только в ЛС с владельцем бота).',
    ja: 'オーナーパネル（ボット所有者とのDMのみ）。',
    ko: '소유자 패널(봇 소유자와의 DM에서만).',
    zh: '所有者面板（仅限与机器人所有者的私聊）。',
    it: 'Pannello proprietario (solo in DM con il proprietario del bot).',
  },

  // ------------------------------------------------------------
  // Admin Panel XP variant details
  // ------------------------------------------------------------
  apTitle: { de: '🛠️ Admin Panel – XP Bot' },
  apServerListDesc: {
    de: 'Hier ist die Übersicht aller **{count}** Server, auf denen der XP-Bot ist:\n\n{list}\n\n🔴 = Bot-Owner ist nicht auf dem Server\n\nWähle unten einen Server aus, um Details zu sehen.',
  },
  apNoServers: { de: '😢 Der XP-Bot ist noch auf keinem Server. Zeit, Freunde einzuladen!' },
  apPage: { de: 'Seite {page} von {total}' },
  apSelectPlaceholder: { de: 'Server auswählen …' },
  apSelectLabel: { de: 'Server wählen' },
  apDetailTitle: { de: '🗂️ Server-Übersicht – XP' },
  apDetailOwner: { de: '👑 **Owner:** {mention}' },
  apDetailName: { de: '🏷️ **Name:** {name}' },
  apDetailMembers: { de: '👥 **Mitglieder:** {count}' },
  apDetailSetup: { de: '🏆 **XP-System:** {status}' },
  apDetailXpUsers: { de: '⭐ **Nutzer mit XP:** {count}' },
  apSetupYes: { de: '✅ Eingerichtet' },
  apSetupNo: { de: '❌ Nicht eingerichtet' },
  apBtnBack: { de: '◀ Zurück' },
  apBtnInvite: { de: '🔗 Einladung' },
  apBtnLeave: { de: '🚪 Verlassen' },
  apBtnRefresh: { de: '🔄 Aktualisieren' },
  apBtnPrev: { de: '◀' },
  apBtnNext: { de: '▶' },
  apLeaveAsk: { de: 'Sicher, dass der XP-Bot **{name}** verlassen soll? Klicke erneut auf **Wirklich verlassen**.' },
  apBtnLeaveConfirm: { de: '🚪 Wirklich verlassen' },
  apBtnLeaveCancel: { de: '↩️ Abbrechen' },
  apInviteSent: { de: '🔗 Einladung erstellt – gültig **1 Stunde**, **1× nutzbar**!' },
  apInviteLink: { de: '**Einladungslink:** {url}' },
  apInviteFailed: { de: '⛔ Konnte keine Einladung erstellen: {error}' },
  apLeft: { de: '✅ Der XP-Bot hat **{name}** verlassen.' },
  apJoinNotice: {
    de: '👋 **Neuer XP-Server!**\n\n🏷️ **{name}**\n👥 **{members}** Mitglieder\n👑 **Owner:** {owner}\n\nSchau mal ins **/adminpanel** – da kannst du alles verwalten! 🛠️',
  },
  apInvalidGuild: { de: '⛔ Diesen Server konnte ich nicht finden.' },
  apNeedDm: { de: '⛔ Das XP Admin-Panel funktioniert nur im Privatchat mit dem Bot-Owner!' },

  // ------------------------------------------------------------
  // Profile choices same as birthday
  // ------------------------------------------------------------
  profileImageDesc: {
    de: 'Welches Bild soll verwendet werden?',
    en: 'Which image should be used?',
    fr: 'Quelle image doit être utilisée ?',
    es: '¿Qué imagen se debe usar?',
    pt: 'Qual imagem deve ser usada?',
    ru: 'Какое изображение использовать?',
    ja: 'どの画像を使いますか？',
    ko: '어떤 이미지를 사용할까요?',
    zh: '使用哪张图片？',
    it: 'Quale immagine deve essere usata?',
  },
  profileSet: {
    de: '🖼️ Profilbild geändert: {choice}',
    en: '🖼️ Profile picture changed: {choice}',
    fr: '🖼️ Image de profil modifiée : {choice}',
    es: '🖼️ Foto de perfil cambiada: {choice}',
    pt: '🖼️ Foto de perfil alterada: {choice}',
    ru: '🖼️ Аватар изменён: {choice}',
    ja: '🖼️ プロフィール画像を変更しました: {choice}',
    ko: '🖼️ 프로필 사진을 변경했어요: {choice}',
    zh: '🖼️ 头像已更改：{choice}',
    it: '🖼️ Immagine del profilo cambiata: {choice}',
  },
  profileChoiceStandard: {
    de: 'Standard-Profilbild',
    en: 'Standard profile picture',
    fr: 'Image de profil standard',
    es: 'Foto de perfil estándar',
    pt: 'Foto de perfil padrão',
    ru: 'Стандартный аватар',
    ja: '標準プロフィール画像',
    ko: '기본 프로필 사진',
    zh: '标准头像',
    it: 'Immagine del profilo standard',
  },
  profileChoiceServer: {
    de: 'Server-Profilbild',
    en: 'Server profile picture',
    fr: 'Image du serveur',
    es: 'Foto del servidor',
    pt: 'Foto do servidor',
    ru: 'Аватар сервера',
    ja: 'サーバーの画像',
    ko: '서버 사진',
    zh: '服务器头像',
    it: 'Immagine del server',
  },
  profileChoiceOwner: {
    de: 'Profilbild des Server-Owners',
    en: 'Server owner’s profile picture',
    fr: 'Image du propriétaire du serveur',
    es: 'Foto del propietario del servidor',
    pt: 'Foto do dono do servidor',
    ru: 'Аватар владельца сервера',
    ja: 'サーバー所有者の画像',
    ko: '서버 소유자 사진',
    zh: '服务器所有者头像',
    it: 'Immagine del proprietario del server',
  },
  errAvatar: {
    de: '⛔ Das Profilbild konnte nicht geändert werden: {error}',
    en: '⛔ Couldn’t change the profile picture: {error}',
    fr: '⛔ Impossible de modifier l’image de profil : {error}',
    es: '⛔ No se pudo cambiar la foto de perfil: {error}',
    pt: '⛔ Não foi possível alterar a foto de perfil: {error}',
    ru: '⛔ Не удалось изменить аватар: {error}',
    ja: '⛔ プロフィール画像を変更できませんでした: {error}',
    ko: '⛔ 프로필 사진을 변경하지 못했어요: {error}',
    zh: '⛔ 无法更改头像：{error}',
    it: '⛔ Impossibile cambiare l’immagine del profilo: {error}',
  },
  errAvatarPerms: {
    de: '⛔ Dem Bot fehlt die Berechtigung „Nickname ändern“. Gib dem Bot diese Berechtigung (oder Administrator-Rechte) und versuche es dann erneut.',
    en: '⛔ The bot is missing the “Change Nickname” permission. Grant that permission (or Administrator) to the bot, then try again.',
    fr: '⛔ Il manque au bot la permission « Changer le pseudo ». Accordez-lui cette permission (ou Administrateur), puis réessayez.',
    es: '⛔ Al bot le falta el permiso «Cambiar apodo». Concédele ese permiso (o Administrador) e inténtalo de nuevo.',
    pt: '⛔ O bot não tem a permissão «Alterar apelido». Conceda-lhe essa permissão (ou Administrador) e tente novamente.',
    ru: '⛔ У бота нет права «Изменить никнейм». Дайте боту это право (или «Администратор») и повторите попытку.',
    ja: '⛔ ボットに「ニックネームの変更」権限がありません。この権限（または管理者）を付与してから、もう一度お試しください。',
    ko: '⛔ 봇에게 "닉네임 변경하기" 권한이 없어요. 해당 권한(또는 관리자)을 부여한 뒤 다시 시도해 주세요.',
    zh: '⛔ 机器人缺少“更改昵称”权限。请为机器人授予该权限（或管理员权限）后重试。',
    it: '⛔ Al bot manca l’autorizzazione «Cambia nickname». Concedigliela (o Amministratore) e riprova.',
  },
  errServerNoIcon: {
    de: '⛔ Dieser Server hat kein eigenes Profilbild.',
    en: '⛔ This server has no profile picture of its own.',
    fr: '⛔ Ce serveur n’a pas d’image de profil.',
    es: '⛔ Este servidor no tiene foto de perfil propia.',
    pt: '⛔ Este servidor não tem foto de perfil própria.',
    ru: '⛔ У этого сервера нет собственного аватара.',
    ja: '⛔ このサーバーにはプロフィール画像がありません。',
    ko: '⛔ 이 서버에는 프로필 사진이 없어요.',
    zh: '⛔ 此服务器没有自己的头像。',
    it: '⛔ Questo server non ha un’immagine del profilo.',
  },
};

function t(key, lang, vars = {}) {
  const entry = T[key];
  if (!entry) return `??${key}??`;
  let text = entry[lang] || entry.de || '';
  for (const [k, v] of Object.entries(vars)) {
    text = text.split(`{${k}}`).join(String(v));
  }
  return text;
}

function tzOf(code) {
  const override = process.env[`XP_BOT_TZ_${String(code).toUpperCase()}`] || process.env[`BIRTHDAY_BOT_TZ_${String(code).toUpperCase()}`];
  return override || (LANGS[code] && LANGS[code].tz) || 'Europe/Berlin';
}

function formatToday(lang, date = new Date()) {
  const locale = (LANGS[lang] && LANGS[lang].locale) || 'en-US';
  return new Intl.DateTimeFormat(locale, { dateStyle: 'full', timeZone: tzOf(lang) }).format(date);
}

const DISCORD_LOCALE = {
  de: 'de',
  en: 'en-US',
  fr: 'fr',
  es: 'es-ES',
  pt: 'pt-BR',
  ru: 'ru',
  ja: 'ja',
  ko: 'ko',
  zh: 'zh-CN',
  it: 'it',
};

const DISCORD_LOCALE_MAP = {
  de: 'de',
  'en-US': 'en',
  'en-GB': 'en',
  fr: 'fr',
  'es-ES': 'es',
  'pt-BR': 'pt',
  'pt-PT': 'pt',
  ru: 'ru',
  ja: 'ja',
  ko: 'ko',
  'zh-CN': 'zh',
  'zh-TW': 'zh',
  it: 'it',
};

function langFromDiscord(locale) {
  return DISCORD_LOCALE_MAP[locale] || 'en';
}

module.exports = { LANGS, T, t, tzOf, formatToday, langFromDiscord, DISCORD_LOCALE };
