/**
 * Sprachdatei für den XP Level Bot – 10 Sprachen, alle Texte humorvoll & emoji-lastig
 * wie beim Birthday Bot. Struktur 1:1 ähnlich, damit Design & Handling konsistent sind.
 */

const LANGS = {
  de: {
    name: 'Deutsch',
    names: { de: 'Deutsch', en: 'German', fr: 'Allemand', es: 'Alemán', pt: 'Alemão', ru: 'Немецкий', ja: 'ドイツ語', ko: '독일어', zh: '德语', it: 'Tedesco' },
    flag: '🇩🇪',
    locale: 'de-DE',
    tz: 'Europe/Berlin',
    months: ['Januar', 'Februar', 'März', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember'],
    short: ['jan', 'feb', 'mär', 'apr', 'mai', 'jun', 'jul', 'aug', 'sep', 'okt', 'nov', 'dez'],
    extra: [['jänner'], [], ['maerz'], [], [], [], [], [], [], [], [], []],
  },
  en: {
    name: 'English',
    names: { de: 'Englisch', en: 'English', fr: 'Anglais', es: 'Inglés', pt: 'Inglês', ru: 'Английский', ja: '英語', ko: '영어', zh: '英语', it: 'Inglese' },
    flag: '🇬🇧',
    locale: 'en-US',
    tz: 'America/New_York',
    months: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
    short: ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec'],
    extra: [],
  },
  fr: {
    name: 'Français',
    names: { de: 'Französisch', en: 'French', fr: 'Français', es: 'Francés', pt: 'Francês', ru: 'Французский', ja: 'フランス語', ko: '프랑스어', zh: '法语', it: 'Francese' },
    flag: '🇫🇷',
    locale: 'fr-FR',
    tz: 'Europe/Paris',
    months: ['janvier', 'février', 'mars', 'avril', 'mai', 'juin', 'juillet', 'août', 'septembre', 'octobre', 'novembre', 'décembre'],
    short: ['janv', 'févr', 'mars', 'avr', 'mai', 'juin', 'juil', 'août', 'sept', 'oct', 'nov', 'déc'],
    extra: [['janvier'], ['fevrier', 'février'], [], ['avril'], [], [], ['juillet'], ['aout', 'août'], ['septembre'], [], [], ['decembre', 'décembre']],
  },
  es: {
    name: 'Español',
    names: { de: 'Spanisch', en: 'Spanish', fr: 'Espagnol', es: 'Español', pt: 'Espanhol', ru: 'Испанский', ja: 'スペイン語', ko: '스페인어', zh: '西班牙语', it: 'Spagnolo' },
    flag: '🇪🇸',
    locale: 'es-ES',
    tz: 'Europe/Madrid',
    months: ['enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio', 'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre'],
    short: ['ene', 'feb', 'mar', 'abr', 'may', 'jun', 'jul', 'ago', 'sep', 'oct', 'nov', 'dic'],
    extra: [['enero'], [], ['marzo'], [], [], [], [], [], ['setiembre', 'septiembre'], [], [], []],
  },
  pt: {
    name: 'Português',
    names: { de: 'Portugiesisch', en: 'Portuguese', fr: 'Portugais', es: 'Portugués', pt: 'Português', ru: 'Португальский', ja: 'ポルトガル語', ko: '포르투갈어', zh: '葡萄牙语', it: 'Portoghese' },
    flag: '🇧🇷',
    locale: 'pt-BR',
    tz: 'America/Sao_Paulo',
    months: ['janeiro', 'fevereiro', 'março', 'abril', 'maio', 'junho', 'julho', 'agosto', 'setembro', 'outubro', 'novembro', 'dezembro'],
    short: ['jan', 'fev', 'mar', 'abr', 'mai', 'jun', 'jul', 'ago', 'set', 'out', 'nov', 'dez'],
    extra: [['janeiro'], [], ['marco', 'março'], [], [], [], [], [], ['setembro'], [], [], []],
  },
  ru: {
    name: 'Русский',
    names: { de: 'Russisch', en: 'Russian', fr: 'Russe', es: 'Ruso', pt: 'Russo', ru: 'Русский', ja: 'ロシア語', ko: '러시아어', zh: '俄语', it: 'Russo' },
    flag: '🇷🇺',
    locale: 'ru-RU',
    tz: 'Europe/Moscow',
    months: ['январь', 'февраль', 'март', 'апрель', 'май', 'июнь', 'июль', 'август', 'сентябрь', 'октябрь', 'ноябрь', 'декабрь'],
    short: ['янв', 'фев', 'мар', 'апр', 'май', 'июн', 'июл', 'авг', 'сен', 'окт', 'ноя', 'дек'],
    extra: [['января'], ['февраля'], ['марта'], ['апреля'], ['мая'], ['июня'], ['июля'], ['августа'], ['сентября'], ['октября'], ['ноября'], ['декабря']],
  },
  ja: {
    name: '日本語',
    names: { de: 'Japanisch', en: 'Japanese', fr: 'Japonais', es: 'Japonés', pt: 'Japonês', ru: 'Японский', ja: '日本語', ko: '일본어', zh: '日语', it: 'Giapponese' },
    flag: '🇯🇵',
    locale: 'ja-JP',
    tz: 'Asia/Tokyo',
    months: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
    short: [],
    kanji: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'],
    numeralSuffix: '月',
    extra: [],
  },
  ko: {
    name: '한국어',
    names: { de: 'Koreanisch', en: 'Korean', fr: 'Coréen', es: 'Coreano', pt: 'Coreano', ru: 'Корейский', ja: '韓国語', ko: '한국어', zh: '韩语', it: 'Coreano' },
    flag: '🇰🇷',
    locale: 'ko-KR',
    tz: 'Asia/Seoul',
    months: ['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월'],
    short: [],
    hangul: ['일월', '이월', '삼월', '사월', '오월', '유월', '칠월', '팔월', '구월', '시월', '십일월', '십이월'],
    numeralSuffix: '월',
    extra: [],
  },
  zh: {
    name: '中文',
    names: { de: 'Chinesisch', en: 'Chinese', fr: 'Chinois', es: 'Chino', pt: 'Chinês', ru: 'Китайский', ja: '中国語', ko: '중국어', zh: '中文', it: 'Cinese' },
    flag: '🇨🇳',
    locale: 'zh-CN',
    tz: 'Asia/Shanghai',
    months: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
    short: [],
    kanji: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'],
    numeralSuffix: '月',
    extra: [],
  },
  it: {
    name: 'Italiano',
    names: { de: 'Italienisch', en: 'Italian', fr: 'Italien', es: 'Italiano', pt: 'Italiano', ru: 'Итальянский', ja: 'イタリア語', ko: '이탈리아어', zh: '意大利语', it: 'Italiano' },
    flag: '🇮🇹',
    locale: 'it-IT',
    tz: 'Europe/Rome',
    months: ['gennaio', 'febbraio', 'marzo', 'aprile', 'maggio', 'giugno', 'luglio', 'agosto', 'settembre', 'ottobre', 'novembre', 'dicembre'],
    short: ['gen', 'feb', 'mar', 'apr', 'mag', 'giu', 'lug', 'ago', 'set', 'ott', 'nov', 'dic'],
    extra: [['gennaio'], [], ['marzo'], [], [], [], [], [], ['settembre'], [], [], []],
  },
};

const T = {
  // ------------------------------------------------------------
  // Leaderboard
  // ------------------------------------------------------------
  lbTitle: {
    de: '🏆 XP Leaderboard',
    en: '🏆 XP Leaderboard',
    fr: '🏆 Classement XP',
    es: '🏆 Tabla de XP',
    pt: '🏆 Ranking de XP',
    ru: '🏆 Таблица XP',
    ja: '🏆 XPランキング',
    ko: '🏆 XP 리더보드',
    zh: '🏆 XP 排行榜',
    it: '🏆 Classifica XP',
  },
  lbTagline: {
    de: 'Die fleißigsten Chatter – streng dich an und kletter hoch! 🚀',
    en: 'The most active chatters – grind hard and climb up! 🚀',
    fr: 'Les plus actifs – bosse dur et grimpe ! 🚀',
    es: '¡Los más activos – esfuerzate y sube! 🚀',
    pt: 'Os mais ativos – rale muito e suba! 🚀',
    ru: 'Самые активные болтуны – старайся и поднимайся! 🚀',
    ja: '最もアクティブなメンバー – 頑張って上を目指そう！🚀',
    ko: '가장 활발한 멤버 – 열심히 해서 올라가세요! 🚀',
    zh: '最活跃的成员——努力聊天，冲上榜首！🚀',
    it: 'I più attivi – datti da fare e scala la classifica! 🚀',
  },
  lbEmpty: {
    de: 'Noch niemand hat XP gesammelt. Schreib die erste Nachricht und hol dir Level 1! ✨',
    en: 'No one has earned XP yet. Send the first message and claim Level 1! ✨',
    fr: 'Personne n’a encore gagné d’XP. Envoie le premier message et prends le niveau 1 ! ✨',
    es: 'Aún nadie ha ganado XP. ¡Envía el primer mensaje y consigue el nivel 1! ✨',
    pt: 'Ninguém ganhou XP ainda. Envie a primeira mensagem e pegue o nível 1! ✨',
    ru: 'Пока никто не заработал XP. Напиши первым и забери 1 уровень! ✨',
    ja: 'まだ誰もXPを獲得していません。最初のメッセージを送ってレベル1をゲットしよう！✨',
    ko: '아직 아무도 XP를 얻지 못했어요. 첫 메시지를 보내고 레벨 1을 차지하세요! ✨',
    zh: '还没有人获得 XP。发送第一条消息，拿下 1 级！✨',
    it: 'Nessuno ha ancora guadagnato XP. Invia il primo messaggio e prenditi il livello 1! ✨',
  },
  lbUpdated: {
    de: '🕒 Zuletzt aktualisiert: **{time}** ({tz})',
    en: '🕒 Last updated: **{time}** ({tz})',
    fr: '🕒 Dernière mise à jour : **{time}** ({tz})',
    es: '🕒 Última actualización: **{time}** ({tz})',
    pt: '🕒 Última atualização: **{time}** ({tz})',
    ru: '🕒 Последнее обновление: **{time}** ({tz})',
    ja: '🕒 最終更新: **{time}** ({tz})',
    ko: '🕒 마지막 업데이트: **{time}** ({tz})',
    zh: '🕒 最后更新：**{time}** ({tz})',
    it: '🕒 Ultimo aggiornamento: **{time}** ({tz})',
  },
  lbNextUpdate: {
    de: '⏰ Nächstes Update stündlich – bleib dran!',
    en: '⏰ Next update hourly – stay tuned!',
    fr: '⏰ Prochaine mise à jour chaque heure !',
    es: '⏰ ¡Próxima actualización cada hora!',
    pt: '⏰ Próxima atualização a cada hora!',
    ru: '⏰ Следующее обновление каждый час!',
    ja: '⏰ 次の更新は1時間ごと！',
    ko: '⏰ 다음 업데이트는 매 시간!',
    zh: '⏰ 每小时更新一次——敬请关注！',
    it: '⏰ Prossimo aggiornamento ogni ora!',
  },
  lbDecayNotice: {
    de: '⚠️ **Täglicher XP-Schwund:** Jeden Tag um 0 Uhr verlierst du **7%** der XP, die du für dein nächstes Level brauchst. Wenn du auf 0 fällst, verlierst du ein Level und landest bei 93% des neuen Levels. Viel chatten verhindert den Abstieg! 💬🔥',
    en: '⚠️ **Daily XP Decay:** Every day at midnight you lose **7%** of the XP needed for your next level. If you drop to 0, you lose a level and land at 93% of the new level. Keep chatting to stay on top! 💬🔥',
    fr: '⚠️ **Perte d’XP quotidienne :** Chaque jour à minuit tu perds **7%** de l’XP nécessaire pour ton prochain niveau. Si tu tombes à 0, tu perds un niveau et repars à 93% du nouveau niveau. Reste actif ! 💬🔥',
    es: '⚠️ **Pérdida diaria de XP:** Cada día a medianoche pierdes el **7%** del XP necesario para tu próximo nivel. Si caes a 0, pierdes un nivel y caes al 93% del nuevo nivel. ¡Sigue chateando! 💬🔥',
    pt: '⚠️ **Decaimento diário de XP:** Todo dia à meia-noite você perde **7%** do XP necessário para o próximo nível. Se cair a 0, perde um nível e vai para 93% do novo nível. Continue conversando! 💬🔥',
    ru: '⚠️ **Ежедневная потеря XP:** Каждый день в полночь ты теряешь **7%** от XP, нужного для следующего уровня. Если упадёшь до 0, потеряешь уровень и окажешься на 93% нового уровня. Болтай больше! 💬🔥',
    ja: '⚠️ **毎日のXP減少:** 毎日0時に次のレベルに必要なXPの**7%**を失います。0になるとレベルが1つ下がり、新しいレベルの93%から再スタート。たくさんチャットしてキープしよう！💬🔥',
    ko: '⚠️ **매일 XP 감소:** 매일 자정에 다음 레벨에 필요한 XP의 **7%**를 잃어요. 0이 되면 레벨이 하나 내려가고 새 레벨의 93%에서 시작해요. 계속 채팅하세요! 💬🔥',
    zh: '⚠️ **每日 XP 衰减：** 每天 0 点你会失去下一级所需 XP 的 **7%**。如果掉到 0，会掉一级并回到新等级的 93%。多多聊天防止掉级！💬🔥',
    it: '⚠️ **Decadimento giornaliero XP:** Ogni giorno a mezzanotte perdi il **7%** dell’XP necessario per il prossimo livello. Se scendi a 0, perdi un livello e riparti al 93% del nuovo livello. Continua a chattare! 💬🔥',
  },
  lbEntryLine: {
    de: '`#{rank}` <@{userId}> — **Lvl {level}** · {xp}/{needed} XP {medal}',
    en: '`#{rank}` <@{userId}> — **Lvl {level}** · {xp}/{needed} XP {medal}',
    fr: '`#{rank}` <@{userId}> — **Niv {level}** · {xp}/{needed} XP {medal}',
    es: '`#{rank}` <@{userId}> — **Nvl {level}** · {xp}/{needed} XP {medal}',
    pt: '`#{rank}` <@{userId}> — **Nvl {level}** · {xp}/{needed} XP {medal}',
    ru: '`#{rank}` <@{userId}> — **Ур {level}** · {xp}/{needed} XP {medal}',
    ja: '`#{rank}` <@{userId}> — **Lv {level}** · {xp}/{needed} XP {medal}',
    ko: '`#{rank}` <@{userId}> — **Lv {level}** · {xp}/{needed} XP {medal}',
    zh: '`#{rank}` <@{userId}> — **等级 {level}** · {xp}/{needed} XP {medal}',
    it: '`#{rank}` <@{userId}> — **Liv {level}** · {xp}/{needed} XP {medal}',
  },

  // ------------------------------------------------------------
  // Rank Command
  // ------------------------------------------------------------
  rankTitle: {
    de: '📊 Dein Rank',
    en: '📊 Your Rank',
    fr: '📊 Ton rang',
    es: '📊 Tu puesto',
    pt: '📊 Seu rank',
    ru: '📊 Твой ранг',
    ja: '📊 あなたのランク',
    ko: '📊 당신의 랭크',
    zh: '📊 你的排名',
    it: '📊 Il tuo rank',
  },
  rankBody: {
    de: 'Hey {user}! Du bist **Platz #{rank}** von {total} auf diesem Server! 🏅\n\n⭐ **Level:** {level}\n✨ **XP:** {xp} / {needed} XP bis Level {nextLevel}\n📈 **Fortschritt:** {bar} {percent}% \n\nHalte durch – noch {remaining} XP bis zum Aufstieg! 🚀\n\n> 💡 *Tipp: Chatten gibt 3 XP pro Wort (max 30 XP), Voice 25 XP/Minute – aber nur mit 30s Cooldown und täglichem 7% Schwund um Mitternacht!*',
    en: 'Hey {user}! You are **rank #{rank}** of {total} on this server! 🏅\n\n⭐ **Level:** {level}\n✨ **XP:** {xp} / {needed} XP to Level {nextLevel}\n📈 **Progress:** {bar} {percent}%\n\nKeep it up – just {remaining} XP to level up! 🚀\n\n> 💡 *Tip: Chatting gives 3 XP per word (max 30 XP), voice 25 XP/min – but with 30s cooldown and daily 7% decay at midnight!*',
    fr: 'Hey {user} ! Tu es **#{rank}** sur {total} sur ce serveur ! 🏅\n\n⭐ **Niveau :** {level}\n✨ **XP :** {xp} / {needed} XP jusqu’au niveau {nextLevel}\n📈 **Progression :** {bar} {percent}%\n\nEncore {remaining} XP pour monter ! 🚀',
    es: '¡Hey {user}! ¡Eres el **puesto #{rank}** de {total} en este servidor! 🏅\n\n⭐ **Nivel:** {level}\n✨ **XP:** {xp} / {needed} XP hasta el nivel {nextLevel}\n📈 **Progreso:** {bar} {percent}%\n\n¡Solo {remaining} XP para subir! 🚀',
    pt: 'Hey {user}! Você está em **#{rank}** de {total} neste servidor! 🏅\n\n⭐ **Nível:** {level}\n✨ **XP:** {xp} / {needed} XP até o nível {nextLevel}\n📈 **Progresso:** {bar} {percent}%\n\nFaltam só {remaining} XP para subir! 🚀',
    ru: 'Привет {user}! Ты **#{rank}** из {total} на этом сервере! 🏅\n\n⭐ **Уровень:** {level}\n✨ **XP:** {xp} / {needed} XP до {nextLevel} уровня\n📈 **Прогресс:** {bar} {percent}%\n\nЕщё {remaining} XP до повышения! 🚀',
    ja: 'やあ {user}！このサーバーで **{rank}位 / {total}人中** だよ！🏅\n\n⭐ **レベル:** {level}\n✨ **XP:** {xp} / {needed} XP で Lv{nextLevel} へ\n📈 **進捗:** {bar} {percent}%\n\nあと {remaining} XPでレベルアップ！🚀',
    ko: '안녕 {user}! 이 서버에서 **{total}명 중 {rank}위** 예요! 🏅\n\n⭐ **레벨:** {level}\n✨ **XP:** {xp} / {needed} XP → Lv{nextLevel}\n📈 **진행도:** {bar} {percent}%\n\n레벨업까지 {remaining} XP 남았어요! 🚀',
    zh: '嗨 {user}！你在这服务器排名 **第 {rank} 名 / 共 {total} 人**！🏅\n\n⭐ **等级：** {level}\n✨ **XP：** {xp} / {needed} XP 到 {nextLevel} 级\n📈 **进度：** {bar} {percent}%\n\n再有 {remaining} XP 就升级！🚀',
    it: 'Ehi {user}! Sei **#{rank}** su {total} in questo server! 🏅\n\n⭐ **Livello:** {level}\n✨ **XP:** {xp} / {needed} XP per il livello {nextLevel}\n📈 **Progresso:** {bar} {percent}%\n\nAncora {remaining} XP per salire! 🚀',
  },
  rankNoSetup: {
    de: '⛔ Auf diesem Server wurde noch kein XP-System eingerichtet. Bitte **/setup** vom Admin ausführen lassen! 🛠️',
    en: '⛔ XP system not set up on this server yet. Ask an admin to run **/setup**! 🛠️',
    fr: '⛔ Le système XP n’est pas encore configuré. Demande à un admin de faire **/setup** ! 🛠️',
    es: '⛔ El sistema de XP aún no está configurado. ¡Pide a un admin que ejecute **/setup**! 🛠️',
    pt: '⛔ Sistema de XP ainda não configurado. Peça a um admin para usar **/setup**! 🛠️',
    ru: '⛔ Система XP ещё не настроена. Попроси админа выполнить **/setup**! 🛠️',
    ja: '⛔ このサーバーではXPシステムがまだ設定されていません。管理者に **/setup** を実行してもらってね！🛠️',
    ko: '⛔ 이 서버에는 아직 XP 시스템이 설정되지 않았어요. 관리자에게 **/setup**을 요청하세요! 🛠️',
    zh: '⛔ 此服务器尚未设置 XP 系统，请让管理员执行 **/setup**！🛠️',
    it: '⛔ Sistema XP non ancora configurato. Chiedi a un admin di eseguire **/setup**! 🛠️',
  },
  rankNotFound: {
    de: '🤔 Hmm, ich finde dich nicht. Schreib erst eine Nachricht, um XP zu sammeln!',
    en: '🤔 Hmm, I can’t find you. Send a message first to earn XP!',
    fr: '🤔 Hmm, je ne te trouve pas. Envoie d’abord un message pour gagner de l’XP !',
    es: '🤔 Hmm, no te encuentro. ¡Envía un mensaje para ganar XP!',
    pt: '🤔 Hmm, não te encontrei. Envie uma mensagem para ganhar XP!',
    ru: '🤔 Хм, не могу тебя найти. Сначала напиши сообщение, чтобы получить XP!',
    ja: '🤔 あれ、見つからないよ。まずメッセージを送ってXPをゲットしよう！',
    ko: '🤔 음, 찾을 수 없어요. 먼저 메시지를 보내 XP를 얻으세요!',
    zh: '🤔 嗯，找不到你。先发一条消息来获得 XP 吧！',
    it: '🤔 Hmm, non ti trovo. Invia prima un messaggio per guadagnare XP!',
  },

  // ------------------------------------------------------------
  // Level Up / Down
  // ------------------------------------------------------------
  levelUp: {
    de: '🎉 LEVEL UP! {user} ist auf **Level {level}** aufgestiegen! ✨ {xp}/{needed} XP – weiter so, du Maschine! 🚀🔥',
    en: '🎉 LEVEL UP! {user} reached **Level {level}**! ✨ {xp}/{needed} XP – keep grinding, legend! 🚀🔥',
    fr: '🎉 NIVEAU SUPÉRIEUR ! {user} est passé au **niveau {level}** ! ✨ {xp}/{needed} XP – continue comme ça ! 🚀🔥',
    es: '🎉 ¡SUBIDA DE NIVEL! ¡{user} alcanzó el **nivel {level}**! ✨ {xp}/{needed} XP – ¡sigue así, crack! 🚀🔥',
    pt: '🎉 SUBIU DE NÍVEL! {user} chegou ao **nível {level}**! ✨ {xp}/{needed} XP – continua assim, lenda! 🚀🔥',
    ru: '🎉 НОВЫЙ УРОВЕНЬ! {user} достиг **уровня {level}**! ✨ {xp}/{needed} XP – так держать, легенда! 🚀🔥',
    ja: '🎉 レベルアップ！{user} が **レベル {level}** に到達！✨ {xp}/{needed} XP – その調子！🚀🔥',
    ko: '🎉 레벨 업! {user}님이 **레벨 {level}** 달성! ✨ {xp}/{needed} XP – 계속 가즈아! 🚀🔥',
    zh: '🎉 升级啦！{user} 达到了 **{level} 级**！✨ {xp}/{needed} XP——继续冲！🚀🔥',
    it: '🎉 LEVEL UP! {user} ha raggiunto il **livello {level}**! ✨ {xp}/{needed} XP – continua così, leggenda! 🚀🔥',
  },
  levelDown: {
    de: '😢 Oh nein! {user} ist auf **Level {level}** abgestiegen… {xp}/{needed} XP – mehr chatten, sonst rutschst du weiter! 💬😬',
    en: '😢 Oh no! {user} dropped to **Level {level}**… {xp}/{needed} XP – chat more or you’ll slide further! 💬😬',
    fr: '😢 Oh non ! {user} est retombé au **niveau {level}**… {xp}/{needed} XP – discute plus ! 💬😬',
    es: '😢 ¡Oh no! {user} bajó al **nivel {level}**… {xp}/{needed} XP – ¡chatea más! 💬😬',
    pt: '😢 Oh não! {user} caiu para o **nível {level}**… {xp}/{needed} XP – converse mais! 💬😬',
    ru: '😢 О нет! {user} упал до **уровня {level}**… {xp}/{needed} XP – болтай больше! 💬😬',
    ja: '😢 あらら！{user} が **レベル {level}** にダウン… {xp}/{needed} XP – もっとチャットしよう！💬😬',
    ko: '😢 앗! {user}님이 **레벨 {level}**(으)로 떨어졌어요… {xp}/{needed} XP – 더 채팅하세요! 💬😬',
    zh: '😢 哎呀！{user} 掉到了 **{level} 级**… {xp}/{needed} XP——多聊聊吧！💬😬',
    it: '😢 Oh no! {user} è sceso al **livello {level}**… {xp}/{needed} XP – chatta di più! 💬😬',
  },

  // ------------------------------------------------------------
  // Nickname
  // ------------------------------------------------------------
  nickFail: {
    de: '😅 Hey {user}! Ich konnte dein Level nicht in deinen Nicknamen einbauen da mir die nötigen Rechte fehlen. 🙈 Ich brauche eine Rolle, die **über allen anderen Rollen liegt**. Bitte den Server-Owner darum, meine Rolle ganz nach oben zu schieben, damit ich wirklich die Nicknames aller Nutzer ändern kann! 🛠️✨',
    en: '😅 Hey {user}! I couldn\'t add your level to your nickname – I\'m missing permissions. 🙈 I need a role that **sits above all other roles**. Please ask the server owner to move my role to the very top so I can update everyone\'s nicknames! 🛠️✨',
    fr: '😅 Hey {user} ! Je n’ai pas pu ajouter ton niveau à ton pseudo – il me manque des permissions. 🙈 J’ai besoin d’un rôle **au-dessus de tous les autres**. Demande au propriétaire de mettre mon rôle tout en haut ! 🛠️✨',
    es: '😅 ¡Hey {user}! No pude añadir tu nivel a tu apodo – me faltan permisos. 🙈 Necesito un rol **por encima de todos los demás**. ¡Pide al dueño que ponga mi rol arriba del todo! 🛠️✨',
    pt: '😅 Hey {user}! Não consegui adicionar seu nível ao seu apelido – faltam permissões. 🙈 Preciso de um cargo **acima de todos os outros**. Peça ao dono para colocar meu cargo no topo! 🛠️✨',
    ru: '😅 Привет {user}! Не смог добавить уровень в твой ник – не хватает прав. 🙈 Мне нужна роль **выше всех остальных**. Попроси владельца поднять мою роль наверх! 🛠️✨',
    ja: '😅 やあ {user}！権限不足でニックネームにレベルを入れられなかったよ🙈 **一番上のロール**が必要なんだ。サーバーオーナーに私のロールを一番上にしてもらってね！🛠️✨',
    ko: '😅 안녕 {user}! 권한이 없어서 닉네임에 레벨을 넣지 못했어요🙈 **모든 역할보다 위에 있는 역할**이 필요해요. 서버 소유자에게 내 역할을 맨 위로 올려 달라고 해주세요! 🛠️✨',
    zh: '😅 嗨 {user}！我无法把你的等级加入昵称——权限不足🙈 我需要一个**高于所有其他角色**的身份组。请让服主把我的身份组移到最顶端！🛠️✨',
    it: '😅 Ehi {user}! Non sono riuscito ad aggiungere il tuo livello al nickname – mi mancano i permessi. 🙈 Ho bisogno di un ruolo **sopra tutti gli altri**. Chiedi al proprietario di spostare il mio ruolo in cima! 🛠️✨',
  },
  nickUpdated: {
    de: '🏷️ Dein Nickname wurde auf **{nick}** aktualisiert!',
    en: '🏷️ Your nickname was updated to **{nick}**!',
    fr: '🏷️ Ton pseudo a été mis à jour : **{nick}** !',
    es: '🏷️ ¡Tu apodo se actualizó a **{nick}**!',
    pt: '🏷️ Seu apelido foi atualizado para **{nick}**!',
    ru: '🏷️ Твой ник обновлён на **{nick}**!',
    ja: '🏷️ ニックネームを **{nick}** に更新したよ！',
    ko: '🏷️ 닉네임이 **{nick}**(으)로 업데이트됐어요!',
    zh: '🏷️ 你的昵称已更新为 **{nick}**！',
    it: '🏷️ Il tuo nickname è stato aggiornato a **{nick}**!',
  },

  // ------------------------------------------------------------
  // Setup
  // ------------------------------------------------------------
  setupLeaderDesc: {
    de: 'Kanal für das stündliche Leaderboard',
    en: 'Channel for the hourly leaderboard',
    fr: 'Salon pour le classement horaire',
    es: 'Canal para la tabla horaria',
    pt: 'Canal para o ranking horário',
    ru: 'Канал для ежечасной таблицы лидеров',
    ja: 'ランキング用のチャンネル（1時間ごと）',
    ko: '시간별 리더보드 채널',
    zh: '用于每小时排行榜的频道',
    it: 'Canale per la classifica oraria',
  },
  setupMainDesc: {
    de: 'Haupt-Chat-Kanal für Level-Up-Nachrichten',
    en: 'Main chat channel for level-up messages',
    fr: 'Salon principal pour les messages de niveau',
    es: 'Canal principal para mensajes de nivel',
    pt: 'Canal principal para mensagens de nível',
    ru: 'Основной канал для сообщений о повышении уровня',
    ja: 'レベルアップ通知用のメインチャンネル',
    ko: '레벨업 메시지용 메인 채널',
    zh: '用于等级提升消息的主聊天频道',
    it: 'Canale principale per i messaggi di level-up',
  },
  setupLangDesc: {
    de: 'Sprache des Bots auf diesem Server',
    en: 'Language of the bot on this server',
    fr: 'Langue du bot sur ce serveur',
    es: 'Idioma del bot en este servidor',
    pt: 'Idioma do bot neste servidor',
    ru: 'Язык бота на этом сервере',
    ja: 'このサーバーでのボットの言語',
    ko: '이 서버에서의 봇 언어',
    zh: '机器人在此服务器上的语言',
    it: 'Lingua del bot su questo server',
  },
  setupSuccess: {
    de: '🎉 Alles eingerichtet! **Leaderboard:** {leader}  **Haupt-Chat:** {main}  **Sprache:** {lang} 🚀 Leaderboard erscheint stündlich neu & wird sofort erstellt! ✨',
    en: '🎉 All set! **Leaderboard:** {leader}  **Main Chat:** {main}  **Language:** {lang} 🚀 Leaderboard refreshes hourly & was created instantly! ✨',
    fr: '🎉 Tout est prêt ! **Classement :** {leader}  **Chat principal :** {main}  **Langue :** {lang} 🚀',
    es: '🎉 ¡Todo listo! **Tabla:** {leader}  **Chat principal:** {main}  **Idioma:** {lang} 🚀',
    pt: '🎉 Tudo pronto! **Ranking:** {leader}  **Chat principal:** {main}  **Idioma:** {lang} 🚀',
    ru: '🎉 Всё готово! **Таблица:** {leader}  **Главный чат:** {main}  **Язык:** {lang} 🚀',
    ja: '🎉 設定完了！**ランキング:** {leader}  **メイン:** {main}  **言語:** {lang} 🚀',
    ko: '🎉 설정 완료! **리더보드:** {leader}  **메인 채팅:** {main}  **언어:** {lang} 🚀',
    zh: '🎉 设置完成！**排行榜：** {leader}  **主频道：** {main}  **语言：** {lang} 🚀',
    it: '🎉 Tutto pronto! **Classifica:** {leader}  **Chat principale:** {main}  **Lingua:** {lang} 🚀',
  },
  setupLangBad: {
    de: '⛔ Bitte wähle eine gültige Sprache aus den Vorschlägen.',
    en: '⛔ Please pick a valid language from the suggestions.',
    fr: '⛔ Choisis une langue valide dans les suggestions.',
    es: '⛔ Elige un idioma válido de las sugerencias.',
    pt: '⛔ Escolha um idioma válido nas sugestões.',
    ru: '⛔ Выбери допустимый язык из предложенных.',
    ja: '⛔ 提案の中から有効な言語を選んでください。',
    ko: '⛔ 제안 중에서 유효한 언어를 선택하세요.',
    zh: '⛔ 请从建议中选择有效的语言。',
    it: '⛔ Scegli una lingua valida dai suggerimenti.',
  },
  setupFoundOld: {
    de: '🔎 Bestehendes Setup gefunden – übernehme Einstellungen & XP!',
    en: '🔎 Found existing setup – carrying over settings & XP!',
    fr: '🔎 Configuration existante trouvée – reprise des paramètres & XP !',
    es: '🔎 Configuración existente encontrada – ¡manteniendo ajustes y XP!',
    pt: '🔎 Configuração existente encontrada – mantendo ajustes e XP!',
    ru: '🔎 Найдена существующая настройка – переношу настройки и XP!',
    ja: '🔎 既存の設定を見つけたよ – 設定とXPを引き継ぐね！',
    ko: '🔎 기존 설정을 찾았어요 – 설정과 XP를 유지할게요!',
    zh: '🔎 找到现有设置——正在迁移设置和 XP！',
    it: '🔎 Configurazione esistente trovata – mantengo impostazioni e XP!',
  },

  // ------------------------------------------------------------
  // Errors generic
  // ------------------------------------------------------------
  errGuildOnly: {
    de: '⛔ Dieser Befehl funktioniert nur auf einem Server.',
    en: '⛔ This command only works on a server.',
    fr: '⛔ Cette commande ne fonctionne que sur un serveur.',
    es: '⛔ Este comando solo funciona en un servidor.',
    pt: '⛔ Este comando só funciona em um servidor.',
    ru: '⛔ Эта команда работает только на сервере.',
    ja: '⛔ このコマンドはサーバーでのみ使用できます。',
    ko: '⛔ 이 명령어는 서버에서만 사용할 수 있어요.',
    zh: '⛔ 此命令只能在服务器上使用。',
    it: '⛔ Questo comando funziona solo su un server.',
  },
  errNoPermission: {
    de: '⛔ Dazu brauchst du die **Administrator**-Berechtigung!',
    en: '⛔ You need the **Administrator** permission for this!',
    fr: '⛔ Tu as besoin de la permission **Administrateur** pour ça !',
    es: '⛔ ¡Necesitas el permiso de **Administrador** para esto!',
    pt: '⛔ Você precisa da permissão de **Administrador** para isso!',
    ru: '⛔ Для этого нужны права **Администратора**!',
    ja: '⛔ これには**管理者**権限が必要です！',
    ko: '⛔ 이 작업에는 **관리자** 권한이 필요해요!',
    zh: '⛔ 执行此操作需要**管理员**权限！',
    it: '⛔ Per questo serve il permesso **Amministratore**!',
  },
  errOwnerOnly: {
    de: '⛔ Nur der Bot-Owner kann das nutzen!',
    en: '⛔ Only the bot owner can use this!',
    fr: '⛔ Seul le propriétaire du bot peut utiliser ça !',
    es: '⛔ ¡Solo el propietario del bot puede usar esto!',
    pt: '⛔ Somente o dono do bot pode usar isso!',
    ru: '⛔ Это может использовать только владелец бота!',
    ja: '⛔ これはボットの所有者だけが使えます！',
    ko: '⛔ 봇 소유자만 사용할 수 있어요!',
    zh: '⛔ 只有机器人所有者才能使用此功能！',
    it: '⛔ Solo il proprietario del bot può usarlo!',
  },
  errDmOnly: {
    de: '⛔ Bitte nutze diesen Befehl im Privatchat mit dem Bot-Owner!',
    en: '⛔ Please use this command in the DM with the bot owner!',
    fr: '⛔ Utilise cette commande en MP avec le propriétaire du bot !',
    es: '⛔ ¡Usa este comando en el DM con el propietario del bot!',
    pt: '⛔ Use este comando no DM com o dono do bot!',
    ru: '⛔ Используй эту команду в ЛС с владельцем бота!',
    ja: '⛔ ボット所有者とのDMでこのコマンドを使用してください！',
    ko: '⛔ 봇 소유자와의 DM에서 이 명령어를 사용하세요!',
    zh: '⛔ 请在机器人所有者的私聊中使用此命令！',
    it: '⛔ Usa questo comando nel DM con il proprietario del bot!',
  },
  errChannelBad: {
    de: '⛔ Bitte wähle einen Textchannel aus!',
    en: '⛔ Please choose a text channel!',
    fr: '⛔ Choisis un salon textuel !',
    es: '⛔ ¡Elige un canal de texto!',
    pt: '⛔ Escolha um canal de texto!',
    ru: '⛔ Выбери текстовый канал!',
    ja: '⛔ テキストチャンネルを選択してください！',
    ko: '⛔ 텍스트 채널을 선택하세요!',
    zh: '⛔ 请选择一个文字频道！',
    it: '⛔ Scegli un canale testuale!',
  },
  errBotPerms: {
    de: '⛔ Ich brauche die Berechtigungen **Nachrichten senden** und **Kanal ansehen** in {channel}!',
    en: '⛔ I need **Send Messages** and **View Channel** permissions in {channel}!',
    fr: '⛔ J’ai besoin des permissions **Envoyer des messages** et **Voir le salon** dans {channel} !',
    es: '⛔ ¡Necesito los permisos **Enviar mensajes** y **Ver canal** en {channel}!',
    pt: '⛔ Preciso das permissões **Enviar mensagens** e **Ver canal** em {channel}!',
    ru: '⛔ Мне нужны права **Отправлять сообщения** и **Просматривать канал** в {channel}!',
    ja: '⛔ {channel} で**メッセージを送信**と**チャンネルを見る**権限が必要です！',
    ko: '⛔ {channel}에서 **메시지 보내기** 및 **채널 보기** 권한이 필요해요!',
    zh: '⛔ 我需要在{channel}中拥有**发送消息**和**查看频道**的权限！',
    it: '⛔ Mi servono i permessi **Invia messaggi** e **Vedi canale** in {channel}!',
  },
  errGeneric: {
    de: '😵 Ups, da ist etwas schiefgelaufen. Bitte versuch es nochmal! 🤖',
    en: '😵 Oops, something went wrong. Please try again! 🤖',
    fr: '😵 Oups, quelque chose s’est mal passé. Réessaie ! 🤖',
    es: '😵 Vaya, algo salió mal. ¡Inténtalo de nuevo! 🤖',
    pt: '😵 Opa, algo deu errado. Tente novamente! 🤖',
    ru: '😵 Ой, что-то пошло не так. Попробуй ещё раз! 🤖',
    ja: '😵 あれ、何かがうまくいきませんでした。もう一度お試しください！🤖',
    ko: '😵 앗, 뭔가 잘못됐어요. 다시 시도해 주세요! 🤖',
    zh: '😵 哎呀，出了点问题，请重试！🤖',
    it: '😵 Ops, qualcosa è andato storto. Riprova! 🤖',
  },
  errNoSetup: {
    de: '⛔ Es gibt noch kein XP-System auf diesem Server. Bitte nutze zuerst **/setup**! 🛠️',
    en: '⛔ XP system not set up yet. Please use **/setup** first! 🛠️',
    fr: '⛔ Le système XP n’est pas encore configuré. Utilise d’abord **/setup** ! 🛠️',
    es: '⛔ El sistema de XP aún no está configurado. ¡Usa primero **/setup**! 🛠️',
    pt: '⛔ Sistema de XP ainda não configurado. Use **/setup** primeiro! 🛠️',
    ru: '⛔ Система XP ещё не настроена. Сначала используй **/setup**! 🛠️',
    ja: '⛔ まだXPシステムが設定されていません。先に **/setup** を使ってね！🛠️',
    ko: '⛔ 아직 XP 시스템이 설정되지 않았어요. 먼저 **/setup**을 사용하세요! 🛠️',
    zh: '⛔ 尚未设置 XP 系统，请先使用 **/setup**！🛠️',
    it: '⛔ Sistema XP non ancora configurato. Usa prima **/setup**! 🛠️',
  },

  // ------------------------------------------------------------
  // Help
  // ------------------------------------------------------------
  helpTitle: {
    de: '📖 Hilfe & Befehle – XP Level Bot',
    en: '📖 Help & Commands – XP Level Bot',
    fr: '📖 Aide et commandes – XP Level Bot',
    es: '📖 Ayuda y comandos – XP Level Bot',
    pt: '📖 Ajuda e comandos – XP Level Bot',
    ru: '📖 Помощь и команды – XP Level Bot',
    ja: '📖 ヘルプ＆コマンド – XPレベルBot',
    ko: '📖 도움말 및 명령어 – XP 레벨 봇',
    zh: '📖 帮助与命令 – XP 等级机器人',
    it: '📖 Aiuto e comandi – XP Level Bot',
  },
  helpDesc: {
    de: 'Hier findest du alle Befehle des XP-Bots – werde zum Chat-Champion! 👇✨',
    en: 'Here are all the XP bot’s commands – become the chat champion! 👇✨',
    fr: 'Voici toutes les commandes du bot XP – deviens champion du chat ! 👇✨',
    es: '¡Aquí tienes todos los comandos del bot de XP – conviértete en campeón del chat! 👇✨',
    pt: 'Aqui estão todos os comandos do bot de XP – torne-se o campeão do chat! 👇✨',
    ru: 'Вот все команды XP-бота – стань чемпионом чата! 👇✨',
    ja: 'XPボットの全コマンドはこちら – チャットチャンピオンになろう！👇✨',
    ko: 'XP 봇의 모든 명령어예요 – 채팅 챔피언이 되어 보세요! 👇✨',
    zh: '以下是 XP 机器人的所有命令——成为聊天冠军吧！👇✨',
    it: 'Ecco tutti i comandi del bot XP – diventa campione della chat! 👇✨',
  },
  helpSetup: {
    de: 'Richtet das XP-System ein (Leaderboard-Kanal + Haupt-Chat + Sprache). Nur für Admins.',
    en: 'Sets up the XP system (leaderboard channel + main chat + language). Admins only.',
    fr: 'Configure le système XP (salon classement + chat principal + langue). Réservé aux admins.',
    es: 'Configura el sistema de XP (canal de tabla + chat principal + idioma). Solo admins.',
    pt: 'Configura o sistema de XP (canal de ranking + chat principal + idioma). Só admins.',
    ru: 'Настраивает систему XP (канал таблицы + главный чат + язык). Только для админов.',
    ja: 'XPシステムを設定します（ランキングチャンネル＋メインチャット＋言語）。管理者のみ。',
    ko: 'XP 시스템을 설정해요(리더보드 채널 + 메인 채팅 + 언어). 관리자 전용.',
    zh: '设置 XP 系统（排行榜频道+主聊天+语言）。仅限管理员。',
    it: 'Configura il sistema XP (canale classifica + chat principale + lingua). Solo admin.',
  },
  helpRank: {
    de: 'Zeigt deinen aktuellen Level, XP und Platz auf dem Server. Für alle!',
    en: 'Shows your current level, XP and rank on the server. For everyone!',
    fr: 'Affiche ton niveau, ton XP et ton rang sur le serveur. Pour tous !',
    es: 'Muestra tu nivel, XP y puesto en el servidor. ¡Para todos!',
    pt: 'Mostra seu nível, XP e posição no servidor. Para todos!',
    ru: 'Показывает твой уровень, XP и место на сервере. Для всех!',
    ja: 'あなたの現在のレベル、XP、順位を表示します。誰でも使えるよ！',
    ko: '현재 레벨, XP, 서버 순위를 보여줘요. 모두 사용 가능!',
    zh: '显示你当前的等级、XP 和服务器排名，人人可用！',
    it: 'Mostra il tuo livello, XP e posizione sul server. Per tutti!',
  },
  helpHelp: {
    de: 'Zeigt diese Übersicht an.',
    en: 'Shows this overview.',
    fr: 'Affiche cet aperçu.',
    es: 'Muestra esta vista general.',
    pt: 'Mostra esta visão geral.',
    ru: 'Показывает этот обзор.',
    ja: 'この概要を表示します。',
    ko: '이 개요를 보여줘요.',
    zh: '显示此概览。',
    it: 'Mostra questa panoramica.',
  },
  helpSetProfile: {
    de: 'Ändert das Profilbild des Bots auf diesem Server.',
    en: 'Changes the bot’s profile picture on this server.',
    fr: 'Modifie l’image de profil du bot sur ce serveur.',
    es: 'Cambia la foto de perfil del bot en este servidor.',
    pt: 'Altera a foto de perfil do bot neste servidor.',
    ru: 'Меняет аватар бота на этом сервере.',
    ja: 'このサーバーでのボットのプロフィール画像を変更します。',
    ko: '이 서버에서 봇의 프로필 사진을 변경해요.',
    zh: '更改机器人在此服务器上的头像。',
    it: 'Cambia l’immagine del profilo del bot su questo server.',
  },
  helpAdminPanel: {
    de: 'Owner-Panel (nur im DM mit dem Bot-Owner).',
    en: 'Owner panel (DM with the bot owner only).',
    fr: 'Panneau propriétaire (MP avec le propriétaire uniquement).',
    es: 'Panel del propietario (solo en DM con el propietario del bot).',
    pt: 'Painel do dono (somente no DM com o dono do bot).',
    ru: 'Панель владельца (только в ЛС с владельцем бота).',
    ja: 'オーナーパネル（ボット所有者とのDMのみ）。',
    ko: '소유자 패널(봇 소유자와의 DM에서만).',
    zh: '所有者面板（仅限与机器人所有者的私聊）。',
    it: 'Pannello proprietario (solo in DM con il proprietario del bot).',
  },

  // ------------------------------------------------------------
  // Admin Panel XP variant details
  // ------------------------------------------------------------
  apTitle: { de: '🛠️ Admin Panel – XP Bot' },
  apServerListDesc: {
    de: 'Hier ist die Übersicht aller **{count}** Server, auf denen der XP-Bot ist:\\n\\n{list}\\n\\n🔴 = Bot-Owner ist nicht auf dem Server\\n\\nWähle unten einen Server aus, um Details zu sehen.',
  },
  apNoServers: { de: '😢 Der XP-Bot ist noch auf keinem Server. Zeit, Freunde einzuladen!' },
  apPage: { de: 'Seite {page} von {total}' },
  apSelectPlaceholder: { de: 'Server auswählen …' },
  apSelectLabel: { de: 'Server wählen' },
  apDetailTitle: { de: '🗂️ Server-Übersicht – XP' },
  apDetailOwner: { de: '👑 **Owner:** {mention}' },
  apDetailName: { de: '🏷️ **Name:** {name}' },
  apDetailMembers: { de: '👥 **Mitglieder:** {count}' },
  apDetailSetup: { de: '🏆 **XP-System:** {status}' },
  apDetailXpUsers: { de: '⭐ **Nutzer mit XP:** {count}' },
  apSetupYes: { de: '✅ Eingerichtet' },
  apSetupNo: { de: '❌ Nicht eingerichtet' },
  apBtnBack: { de: '◀ Zurück' },
  apBtnInvite: { de: '🔗 Einladung' },
  apBtnLeave: { de: '🚪 Verlassen' },
  apBtnRefresh: { de: '🔄 Aktualisieren' },
  apBtnPrev: { de: '◀' },
  apBtnNext: { de: '▶' },
  apLeaveAsk: { de: 'Sicher, dass der XP-Bot **{name}** verlassen soll? Klicke erneut auf **Wirklich verlassen**.' },
  apBtnLeaveConfirm: { de: '🚪 Wirklich verlassen' },
  apBtnLeaveCancel: { de: '↩️ Abbrechen' },
  apInviteSent: { de: '🔗 Einladung erstellt – gültig **1 Stunde**, **1× nutzbar**!' },
  apInviteLink: { de: '**Einladungslink:** {url}' },
  apInviteFailed: { de: '⛔ Konnte keine Einladung erstellen: {error}' },
  apLeft: { de: '✅ Der XP-Bot hat **{name}** verlassen.' },
  apJoinNotice: {
    de: '👋 **Neuer XP-Server!**\\n\\n🏷️ **{name}**\\n👥 **{members}** Mitglieder\\n👑 **Owner:** {owner}\\n\\nSchau mal ins **/adminpanel** – da kannst du alles verwalten! 🛠️',
  },
  apInvalidGuild: { de: '⛔ Diesen Server konnte ich nicht finden.' },
  apNeedDm: { de: '⛔ Das XP Admin-Panel funktioniert nur im Privatchat mit dem Bot-Owner!' },

  // ------------------------------------------------------------
  // Profile choices same as birthday
  // ------------------------------------------------------------
  profileImageDesc: {
    de: 'Welches Bild soll verwendet werden?',
    en: 'Which image should be used?',
    fr: 'Quelle image doit être utilisée ?',
    es: '¿Qué imagen se debe usar?',
    pt: 'Qual imagem deve ser usada?',
    ru: 'Какое изображение использовать?',
    ja: 'どの画像を使いますか？',
    ko: '어떤 이미지를 사용할까요?',
    zh: '使用哪张图片？',
    it: 'Quale immagine deve essere usata?',
  },
  profileSet: {
    de: '🖼️ Profilbild geändert: {choice}',
    en: '🖼️ Profile picture changed: {choice}',
    fr: '🖼️ Image de profil modifiée : {choice}',
    es: '🖼️ Foto de perfil cambiada: {choice}',
    pt: '🖼️ Foto de perfil alterada: {choice}',
    ru: '🖼️ Аватар изменён: {choice}',
    ja: '🖼️ プロフィール画像を変更しました: {choice}',
    ko: '🖼️ 프로필 사진을 변경했어요: {choice}',
    zh: '🖼️ 头像已更改：{choice}',
    it: '🖼️ Immagine del profilo cambiata: {choice}',
  },
  profileChoiceStandard: {
    de: 'Standard-Profilbild',
    en: 'Standard profile picture',
    fr: 'Image de profil standard',
    es: 'Foto de perfil estándar',
    pt: 'Foto de perfil padrão',
    ru: 'Стандартный аватар',
    ja: '標準プロフィール画像',
    ko: '기본 프로필 사진',
    zh: '标准头像',
    it: 'Immagine del profilo standard',
  },
  profileChoiceServer: {
    de: 'Server-Profilbild',
    en: 'Server profile picture',
    fr: 'Image du serveur',
    es: 'Foto del servidor',
    pt: 'Foto do servidor',
    ru: 'Аватар сервера',
    ja: 'サーバーの画像',
    ko: '서버 사진',
    zh: '服务器头像',
    it: 'Immagine del server',
  },
  profileChoiceOwner: {
    de: 'Profilbild des Server-Owners',
    en: 'Server owner’s profile picture',
    fr: 'Image du propriétaire du serveur',
    es: 'Foto del propietario del servidor',
    pt: 'Foto do dono do servidor',
    ru: 'Аватар владельца сервера',
    ja: 'サーバー所有者の画像',
    ko: '서버 소유자 사진',
    zh: '服务器所有者头像',
    it: 'Immagine del proprietario del server',
  },
  errAvatar: {
    de: '⛔ Das Profilbild konnte nicht geändert werden: {error}',
    en: '⛔ Couldn’t change the profile picture: {error}',
    fr: '⛔ Impossible de modifier l’image de profil : {error}',
    es: '⛔ No se pudo cambiar la foto de perfil: {error}',
    pt: '⛔ Não foi possível alterar a foto de perfil: {error}',
    ru: '⛔ Не удалось изменить аватар: {error}',
    ja: '⛔ プロフィール画像を変更できませんでした: {error}',
    ko: '⛔ 프로필 사진을 변경하지 못했어요: {error}',
    zh: '⛔ 无法更改头像：{error}',
    it: '⛔ Impossibile cambiare l’immagine del profilo: {error}',
  },
  errAvatarPerms: {
    de: '⛔ Dem Bot fehlt die Berechtigung „Nickname ändern“. Gib dem Bot diese Berechtigung (oder Administrator-Rechte) und versuche es dann erneut.',
    en: '⛔ The bot is missing the “Change Nickname” permission. Grant that permission (or Administrator) to the bot, then try again.',
    fr: '⛔ Il manque au bot la permission « Changer le pseudo ». Accordez-lui cette permission (ou Administrateur), puis réessayez.',
    es: '⛔ Al bot le falta el permiso «Cambiar apodo». Concédele ese permiso (o Administrador) e inténtalo de nuevo.',
    pt: '⛔ O bot não tem a permissão «Alterar apelido». Conceda-lhe essa permissão (ou Administrador) e tente novamente.',
    ru: '⛔ У бота нет права «Изменить никнейм». Дайте боту это право (или «Администратор») и повторите попытку.',
    ja: '⛔ ボットに「ニックネームの変更」権限がありません。この権限（または管理者）を付与してから、もう一度お試しください。',
    ko: '⛔ 봇에게 "닉네임 변경하기" 권한이 없어요. 해당 권한(또는 관리자)을 부여한 뒤 다시 시도해 주세요.',
    zh: '⛔ 机器人缺少“更改昵称”权限。请为机器人授予该权限（或管理员权限）后重试。',
    it: '⛔ Al bot manca l’autorizzazione «Cambia nickname». Concedigliela (o Amministratore) e riprova.',
  },
  errServerNoIcon: {
    de: '⛔ Dieser Server hat kein eigenes Profilbild.',
    en: '⛔ This server has no profile picture of its own.',
    fr: '⛔ Ce serveur n’a pas d’image de profil.',
    es: '⛔ Este servidor no tiene foto de perfil propia.',
    pt: '⛔ Este servidor não tem foto de perfil própria.',
    ru: '⛔ У этого сервера нет собственного аватара.',
    ja: '⛔ このサーバーにはプロフィール画像がありません。',
    ko: '⛔ 이 서버에는 프로필 사진이 없어요.',
    zh: '⛔ 此服务器没有自己的头像。',
    it: '⛔ Questo server non ha un’immagine del profilo.',
  },
};

function t(key, lang, vars = {}) {
  const entry = T[key];
  if (!entry) return `??${key}??`;
  let text = entry[lang] || entry.de || '';
  for (const [k, v] of Object.entries(vars)) {
    text = text.split(`{${k}}`).join(String(v));
  }
  return text;
}

function tzOf(code) {
  const override = process.env[`XP_BOT_TZ_${String(code).toUpperCase()}`] || process.env[`BIRTHDAY_BOT_TZ_${String(code).toUpperCase()}`];
  return override || (LANGS[code] && LANGS[code].tz) || 'Europe/Berlin';
}

function formatToday(lang, date = new Date()) {
  const locale = (LANGS[lang] && LANGS[lang].locale) || 'en-US';
  return new Intl.DateTimeFormat(locale, { dateStyle: 'full', timeZone: tzOf(lang) }).format(date);
}

const DISCORD_LOCALE = {
  de: 'de',
  en: 'en-US',
  fr: 'fr',
  es: 'es-ES',
  pt: 'pt-BR',
  ru: 'ru',
  ja: 'ja',
  ko: 'ko',
  zh: 'zh-CN',
  it: 'it',
};

const DISCORD_LOCALE_MAP = {
  de: 'de',
  'en-US': 'en',
  'en-GB': 'en',
  fr: 'fr',
  'es-ES': 'es',
  'pt-BR': 'pt',
  'pt-PT': 'pt',
  ru: 'ru',
  ja: 'ja',
  ko: 'ko',
  'zh-CN': 'zh',
  'zh-TW': 'zh',
  it: 'it',
};

function langFromDiscord(locale) {
  return DISCORD_LOCALE_MAP[locale] || 'en';
}

module.exports = { LANGS, T, t, tzOf, formatToday, langFromDiscord, DISCORD_LOCALE };
