/**
 * Sprachdatei für den Love Tester Bot – 10 Sprachen, alle Texte humorvoll
 * & emoji-lastig, exakt im gleichen Stil wie Birthday- und XP-Bot.
 *
 * Struktur: Jeder Text-Key enthält alle 10 Sprachen direkt untereinander.
 * Die Owner-Panel-Texte (ap…) sind bewusst nur auf Deutsch (wie bei den
 * anderen Bots).
 */

const LANGS = {
  de: {
    name: 'Deutsch',
    names: { de: 'Deutsch', en: 'German', fr: 'Allemand', es: 'Alemán', pt: 'Alemão', ru: 'Немецкий', ja: 'ドイツ語', ko: '독일어', zh: '德语', it: 'Tedesco' },
    flag: '🇩🇪',
    locale: 'de-DE',
    tz: 'Europe/Berlin',
  },
  en: {
    name: 'English',
    names: { de: 'Englisch', en: 'English', fr: 'Anglais', es: 'Inglés', pt: 'Inglês', ru: 'Английский', ja: '英語', ko: '영어', zh: '英语', it: 'Inglese' },
    flag: '🇬🇧',
    locale: 'en-US',
    tz: 'America/New_York',
  },
  fr: {
    name: 'Français',
    names: { de: 'Französisch', en: 'French', fr: 'Français', es: 'Francés', pt: 'Francês', ru: 'Французский', ja: 'フランス語', ko: '프랑스어', zh: '法语', it: 'Francese' },
    flag: '🇫🇷',
    locale: 'fr-FR',
    tz: 'Europe/Paris',
  },
  es: {
    name: 'Español',
    names: { de: 'Spanisch', en: 'Spanish', fr: 'Espagnol', es: 'Español', pt: 'Espanhol', ru: 'Испанский', ja: 'スペイン語', ko: '스페인어', zh: '西班牙语', it: 'Spagnolo' },
    flag: '🇪🇸',
    locale: 'es-ES',
    tz: 'Europe/Madrid',
  },
  pt: {
    name: 'Português',
    names: { de: 'Portugiesisch', en: 'Portuguese', fr: 'Portugais', es: 'Portugués', pt: 'Português', ru: 'Португальский', ja: 'ポルトガル語', ko: '포르투갈어', zh: '葡萄牙语', it: 'Portoghese' },
    flag: '🇧🇷',
    locale: 'pt-BR',
    tz: 'America/Sao_Paulo',
  },
  ru: {
    name: 'Русский',
    names: { de: 'Russisch', en: 'Russian', fr: 'Russe', es: 'Ruso', pt: 'Russo', ru: 'Русский', ja: 'ロシア語', ko: '러시아어', zh: '俄语', it: 'Russo' },
    flag: '🇷🇺',
    locale: 'ru-RU',
    tz: 'Europe/Moscow',
  },
  ja: {
    name: '日本語',
    names: { de: 'Japanisch', en: 'Japanese', fr: 'Japonais', es: 'Japonés', pt: 'Japonês', ru: 'Японский', ja: '日本語', ko: '일본어', zh: '日语', it: 'Giapponese' },
    flag: '🇯🇵',
    locale: 'ja-JP',
    tz: 'Asia/Tokyo',
  },
  ko: {
    name: '한국어',
    names: { de: 'Koreanisch', en: 'Korean', fr: 'Coréen', es: 'Coreano', pt: 'Coreano', ru: 'Корейский', ja: '韓国語', ko: '한국어', zh: '韩语', it: 'Coreano' },
    flag: '🇰🇷',
    locale: 'ko-KR',
    tz: 'Asia/Seoul',
  },
  zh: {
    name: '中文',
    names: { de: 'Chinesisch', en: 'Chinese', fr: 'Chinois', es: 'Chino', pt: 'Chinês', ru: 'Китайский', ja: '中国語', ko: '중국어', zh: '中文', it: 'Cinese' },
    flag: '🇨🇳',
    locale: 'zh-CN',
    tz: 'Asia/Shanghai',
  },
  it: {
    name: 'Italiano',
    names: { de: 'Italienisch', en: 'Italian', fr: 'Italien', es: 'Italiano', pt: 'Italiano', ru: 'Итальянский', ja: 'イタリア語', ko: '이탈리아어', zh: '意大利语', it: 'Italiano' },
    flag: '🇮🇹',
    locale: 'it-IT',
    tz: 'Europe/Rome',
  },
};

const T = {
  // ------------------------------------------------------------
  // Setup-Wizard (3 Schritte)
  // ------------------------------------------------------------
  setupStepTitle: {
    de: '🛠️ Love-Tester Setup – Schritt {n} von 3',
    en: '🛠️ Love Tester Setup – Step {n} of 3',
    fr: '🛠️ Configuration du Love Tester – Étape {n} sur 3',
    es: '🛠️ Configuración del Love Tester – Paso {n} de 3',
    pt: '🛠️ Configuração do Love Tester – Etapa {n} de 3',
    ru: '🛠️ Настройка Love Tester – шаг {n} из 3',
    ja: '🛠️ ラブテスター設定 – ステップ {n} / 3',
    ko: '🛠️ 러브 테스터 설정 – 3단계 중 {n}단계',
    zh: '🛠️ 恋爱测试仪设置 – 第 {n} 步，共 3 步',
    it: '🛠️ Configurazione Love Tester – Passo {n} di 3',
  },
  setupStep1Desc: {
    de: 'Willkommen beim Love Tester! 💘 Ich schätze Liebe zwischen zwei Menschen – wissenschaftlich fundiert (durch Chat-Logs) und herrlich unseriös (durch Humor).\n\n**Schritt 1:** Wähle zuerst die Sprache, in der der Bot mit deinem Server spricht.',
    en: 'Welcome to the Love Tester! 💘 I estimate love between two people – scientifically grounded (via chat logs) and gloriously unserious (via humor).\n\n**Step 1:** First pick the language the bot speaks on your server.',
    fr: 'Bienvenue chez le Love Tester ! 💘 J’estime l’amour entre deux personnes – fondé sur la science (grâce aux logs de chat) et superbement déjanté (grâce à l’humour).\n\n**Étape 1 :** Choisis d’abord la langue du bot sur ton serveur.',
    es: '¡Bienvenido al Love Tester! 💘 Estimo el amor entre dos personas – con base científica (gracias a los chats) y gloriosamente poco serio (gracias al humor).\n\n**Paso 1:** Elige primero el idioma del bot en tu servidor.',
    pt: 'Bem-vindo ao Love Tester! 💘 Eu estimo o amor entre duas pessoas – com base científica (via logs de chat) e gloriosamente sem seriedade (via humor).\n\n**Etapa 1:** Escolha primeiro o idioma do bot no seu servidor.',
    ru: 'Добро пожаловать в Love Tester! 💘 Я оцениваю любовь между двумя людьми – научно обоснованно (по логам чата) и восхитительно несерьёзно (с юмором).\n\n**Шаг 1:** Сначала выбери язык, на котором бот будет говорить на сервере.',
    ja: 'ラブテスターへようこそ！💘 私は二人の愛を推定します – 科学的根拠（チャットログ）と、見事に不真面目なユーモアで。\n\n**ステップ1:** まず、サーバーでボットが話す言語を選んでください。',
    ko: '러브 테스터에 오신 걸 환영해요! 💘 저는 두 사람 사이의 사랑을 추정해요 – 과학적 근거(채팅 로그)와 근사하게 진지하지 않은 유머로요.\n\n**1단계:** 먼저 서버에서 봇이 사용할 언어를 선택하세요.',
    zh: '欢迎使用恋爱测试仪！💘 我会估算两个人之间的爱意——既有科学依据（聊天记录），又不失幽默（非常不正经）。\n\n**第1步：** 请先选择机器人在服务器上使用的语言。',
    it: 'Benvenuto nel Love Tester! 💘 Estimo l’amore tra due persone – con basi scientifiche (tramite i log di chat) e gloriosamente poco serio (tramite l’umorismo).\n\n**Passo 1:** Scegli prima la lingua che il bot userà sul tuo server.',
  },
  setupStep2Desc: {
    de: '**Schritt 2:** Wähle die Kanäle aus, die der Bot durchsuchen darf, um Liebes-Spuren zu finden. 🕵️\n\nDu kannst **mehrere Kanäle** auswählen – je mehr, desto besser kann ich die Chemie analysieren. Der Bot liest dort nur Nachrichten, wenn jemand den Befehl `/test_love` benutzt.',
    en: '**Step 2:** Choose the channels the bot may search for traces of love. 🕵️\n\nYou can select **multiple channels** – the more, the better I can analyze the chemistry. The bot only reads messages there when someone uses `/test_love`.',
    fr: '**Étape 2 :** Choisis les salons que le bot peut fouiller pour trouver des traces d’amour. 🕵️\n\nTu peux sélectionner **plusieurs salons** – plus il y en a, mieux je peux analyser la chimie. Le bot ne lit les messages que lorsque quelqu’un utilise `/test_love`.',
    es: '**Paso 2:** Elige los canales que el bot puede rastrear en busca de rastros de amor. 🕵️\n\nPuedes seleccionar **varios canales**: cuantos más, mejor analizaré la química. El bot solo lee mensajes cuando alguien usa `/test_love`.',
    pt: '**Etapa 2:** Escolha os canais que o bot pode vasculhar em busca de vestígios de amor. 🕵️\n\nVocê pode selecionar **vários canais** – quanto mais, melhor analiso a química. O bot só lê mensagens quando alguém usa `/test_love`.',
    ru: '**Шаг 2:** Выбери каналы, которые бот может обыскивать в поисках следов любви. 🕵️\n\nМожно выбрать **несколько каналов** – чем больше, тем лучше я проанализирую химию. Бот читает сообщения только когда кто-то использует `/test_love`.',
    ja: '**ステップ2:** ボットが愛の痕跡を探してもよいチャンネルを選んでください。🕵️\n\n**複数のチャンネル**を選べます – 多いほど化学反応をよく分析できます。ボットは誰かが `/test_love` を使ったときだけメッセージを読みます。',
    ko: '**2단계:** 봇이 사랑의 흔적을 찾아볼 채널을 선택하세요. 🕵️\n\n**여러 채널**을 선택할 수 있어요 – 많을수록 케미를 더 잘 분석해요. 봇은 누군가 `/test_love`를 사용할 때만 메시지를 읽어요.',
    zh: '**第2步：** 请选择机器人可以搜索爱情线索的频道。🕵️\n\n您可以选择**多个频道**——越多越好，我就能更好地分析化学反应。机器人只会在有人使用 `/test_love` 时读取那里的消息。',
    it: '**Passo 2:** Scegli i canali che il bot può setacciare alla ricerca di tracce d’amore. 🕵️\n\nPuoi selezionare **più canali** – più sono, meglio analizzo la chimica. Il bot legge i messaggi solo quando qualcuno usa `/test_love`.',
  },
  setupStep3Desc: {
    de: '**Schritt 3:** Fast geschafft! Gib den **Groq-API-Key** ein. 🔑\n\nDamit kann der Bot die Chat-Ausschnitte an die KI schicken, die eure Liebe in Prozent schätzt. Hol dir einen kostenlosen Key auf **console.groq.com** (Format: `gsk_…`).',
    en: '**Step 3:** Almost done! Enter the **Groq API key**. 🔑\n\nIt lets the bot send the chat excerpts to the AI that estimates your love in percent. Grab a free key at **console.groq.com** (format: `gsk_…`).',
    fr: '**Étape 3 :** Presque fini ! Saisis la **clé API Groq**. 🔑\n\nElle permet au bot d’envoyer les extraits de chat à l’IA qui estime votre amour en pourcentage. Récupère une clé gratuite sur **console.groq.com** (format : `gsk_…`).',
    es: '**Paso 3:** ¡Casi listo! Introduce la **clave API de Groq**. 🔑\n\nAsí el bot puede enviar los extractos de chat a la IA que estima vuestro amor en porcentaje. Consigue una clave gratis en **console.groq.com** (formato: `gsk_…`).',
    pt: '**Etapa 3:** Quase pronto! Digite a **chave da API Groq**. 🔑\n\nAssim o bot pode enviar os trechos do chat para a IA que estima o amor em porcentagem. Pegue uma chave grátis em **console.groq.com** (formato: `gsk_…`).',
    ru: '**Шаг 3:** Почти готово! Введи **API-ключ Groq**. 🔑\n\nОн позволяет боту отправлять фрагменты чата ИИ, который оценивает любовь в процентах. Получи бесплатный ключ на **console.groq.com** (формат: `gsk_…`).',
    ja: '**ステップ3:** もう少しで完成！**Groq APIキー**を入力してください。🔑\n\nこれでボットがチャットの抜粋をAIに送り、愛をパーセントで推定します。**console.groq.com** で無料キーを取得（形式: `gsk_…`）。',
    ko: '**3단계:** 거의 다 됐어요! **Groq API 키**를 입력하세요. 🔑\n\n그러면 봇이 채팅 발췌문을 AI에 보내서 사랑을 퍼센트로 추정해요. **console.groq.com**에서 무료 키를 받으세요 (형식: `gsk_…`).',
    zh: '**第3步：** 快完成了！请输入 **Groq API 密钥**。🔑\n\n这样机器人才能把聊天片段发送给 AI，让它估算你们的爱情百分比。在 **console.groq.com** 获取免费密钥（格式：`gsk_…`）。',
    it: '**Passo 3:** Quasi fatto! Inserisci la **chiave API Groq**. 🔑\n\nPermette al bot di inviare gli estratti della chat all’IA che stima il vostro amore in percentuale. Ottieni una chiave gratuita su **console.groq.com** (formato: `gsk_…`).',
  },
  setupLangSelectPlaceholder: {
    de: '🌐 Sprache auswählen …',
    en: '🌐 Select language …',
    fr: '🌐 Choisir la langue …',
    es: '🌐 Seleccionar idioma …',
    pt: '🌐 Selecionar idioma …',
    ru: '🌐 Выберите язык …',
    ja: '🌐 言語を選択 …',
    ko: '🌐 언어 선택 …',
    zh: '🌐 选择语言 …',
    it: '🌐 Seleziona la lingua …',
  },
  setupChannelSelectPlaceholder: {
    de: '📂 Kanäle auswählen (mehrere möglich) …',
    en: '📂 Select channels (multiple allowed) …',
    fr: '📂 Choisir les salons (plusieurs possibles) …',
    es: '📂 Seleccionar canales (varios posibles) …',
    pt: '📂 Selecionar canais (vários possíveis) …',
    ru: '📂 Выберите каналы (можно несколько) …',
    ja: '📂 チャンネルを選択（複数可）…',
    ko: '📂 채널 선택 (여러 개 가능) …',
    zh: '📂 选择频道（可多选）…',
    it: '📂 Seleziona i canali (più di uno possibile) …',
  },
  setupChannelsSelected: {
    de: '✅ {count} Kanal/Kanäle ausgewählt: {list}',
    en: '✅ {count} channel(s) selected: {list}',
    fr: '✅ {count} salon(s) sélectionné(s) : {list}',
    es: '✅ {count} canal(es) seleccionado(s): {list}',
    pt: '✅ {count} canal(is) selecionado(s): {list}',
    ru: '✅ Выбрано каналов: {count} – {list}',
    ja: '✅ {count} チャンネル選択済み: {list}',
    ko: '✅ 채널 {count}개 선택됨: {list}',
    zh: '✅ 已选择 {count} 个频道：{list}',
    it: '✅ {count} canale/i selezionato/i: {list}',
  },
  setupCurrentLang: {
    de: '🌐 **Sprache:** {lang}',
    en: '🌐 **Language:** {lang}',
    fr: '🌐 **Langue :** {lang}',
    es: '🌐 **Idioma:** {lang}',
    pt: '🌐 **Idioma:** {lang}',
    ru: '🌐 **Язык:** {lang}',
    ja: '🌐 **言語:** {lang}',
    ko: '🌐 **언어:** {lang}',
    zh: '🌐 **语言：**{lang}',
    it: '🌐 **Lingua:** {lang}',
  },
  setupCurrentKey: {
    de: '🔑 **Groq API-Key:** {key}',
    en: '🔑 **Groq API key:** {key}',
    fr: '🔑 **Clé API Groq :** {key}',
    es: '🔑 **Clave API de Groq:** {key}',
    pt: '🔑 **Chave da API Groq:** {key}',
    ru: '🔑 **API-ключ Groq:** {key}',
    ja: '🔑 **Groq APIキー:** {key}',
    ko: '🔑 **Groq API 키:** {key}',
    zh: '🔑 **Groq API 密钥：**{key}',
    it: '🔑 **Chiave API Groq:** {key}',
  },
  setupKeyModalTitle: {
    de: '🔑 Groq API Key eingeben',
    en: '🔑 Enter Groq API key',
    fr: '🔑 Saisir la clé API Groq',
    es: '🔑 Introducir clave API de Groq',
    pt: '🔑 Digite a chave da API Groq',
    ru: '🔑 Введите API-ключ Groq',
    ja: '🔑 Groq APIキーを入力',
    ko: '🔑 Groq API 키 입력',
    zh: '🔑 输入 Groq API 密钥',
    it: '🔑 Inserisci la chiave API Groq',
  },
  setupKeyLabel: {
    de: 'Groq API Key (gsk_…)',
    en: 'Groq API key (gsk_…)',
    fr: 'Clé API Groq (gsk_…)',
    es: 'Clave API de Groq (gsk_…)',
    pt: 'Chave da API Groq (gsk_…)',
    ru: 'API-ключ Groq (gsk_…)',
    ja: 'Groq APIキー (gsk_…)',
    ko: 'Groq API 키 (gsk_…)',
    zh: 'Groq API 密钥（gsk_…）',
    it: 'Chiave API Groq (gsk_…)',
  },
  setupKeyPlaceholder: {
    de: 'gsk_xxxxxxxxxxxxxxxxxxxxxxxx',
    en: 'gsk_xxxxxxxxxxxxxxxxxxxxxxxx',
    fr: 'gsk_xxxxxxxxxxxxxxxxxxxxxxxx',
    es: 'gsk_xxxxxxxxxxxxxxxxxxxxxxxx',
    pt: 'gsk_xxxxxxxxxxxxxxxxxxxxxxxx',
    ru: 'gsk_xxxxxxxxxxxxxxxxxxxxxxxx',
    ja: 'gsk_xxxxxxxxxxxxxxxxxxxxxxxx',
    ko: 'gsk_xxxxxxxxxxxxxxxxxxxxxxxx',
    zh: 'gsk_xxxxxxxxxxxxxxxxxxxxxxxx',
    it: 'gsk_xxxxxxxxxxxxxxxxxxxxxxxx',
  },
  setupKeyHint: {
    de: '💡 Der Key wird serverseitig gespeichert und nur für die Analyse an die Groq-API gesendet. Nie weitergeben!',
    en: '💡 The key is stored per server and only sent to the Groq API for analysis. Never share it!',
    fr: '💡 La clé est stockée par serveur et envoyée uniquement à l’API Groq pour l’analyse. Ne la partage jamais !',
    es: '💡 La clave se guarda por servidor y solo se envía a la API de Groq para el análisis. ¡Nunca la compartas!',
    pt: '💡 A chave é salva por servidor e só é enviada à API Groq para análise. Nunca compartilhe!',
    ru: '💡 Ключ хранится на сервере и отправляется только в API Groq для анализа. Никому не передавай!',
    ja: '💡 キーはサーバーごとに保存され、分析のときだけGroq APIに送信されます。絶対に共有しないでください！',
    ko: '💡 키는 서버별로 저장되고 분석할 때만 Groq API로 보내져요. 절대 공유하지 마세요!',
    zh: '💡 密钥按服务器保存，仅在分析时发送给 Groq API。切勿分享！',
    it: '💡 La chiave è salvata per server e inviata solo all’API Groq per l’analisi. Non condividerla mai!',
  },
  setupKeyEntered: {
    de: '✅ Key gespeichert: {key}\n\nDrücke **Bestätigen**, wenn alles passt – oder **Zurück**, um etwas zu ändern.',
    en: '✅ Key saved: {key}\n\nPress **Confirm** if everything looks right – or **Back** to change something.',
    fr: '✅ Clé enregistrée : {key}\n\nAppuie sur **Confirmer** si tout va bien – ou **Retour** pour modifier quelque chose.',
    es: '✅ Clave guardada: {key}\n\nPulsa **Confirmar** si todo está bien – o **Atrás** para cambiar algo.',
    pt: '✅ Chave salva: {key}\n\nPressione **Confirmar** se estiver tudo certo – ou **Voltar** para mudar algo.',
    ru: '✅ Ключ сохранён: {key}\n\nНажми **Подтвердить**, если всё в порядке – или **Назад**, чтобы что-то изменить.',
    ja: '✅ キーを保存しました: {key}\n\nよければ**確認**を押してください – 変更する場合は**戻る**。',
    ko: '✅ 키 저장됨: {key}\n\n괜찮으면 **확인**을 누르세요 – 바꾸려면 **뒤로**.',
    zh: '✅ 密钥已保存：{key}\n\n一切正常请按**确认**——如需修改请按**返回**。',
    it: '✅ Chiave salvata: {key}\n\nPremi **Conferma** se va tutto bene – oppure **Indietro** per modificare.',
  },
  setupSuccess: {
    de: '✅ **Love Tester ist startklar!** 💘\n\n🌐 Sprache: {lang}\n📂 Kanäle: {channels}\n🔑 Groq API-Key: {key}\n\nJetzt kann jeder mit `/test_love @User1 @User2` die große Liebe (oder das große Drama) analysieren lassen!',
    en: '✅ **Love Tester is ready!** 💘\n\n🌐 Language: {lang}\n📂 Channels: {channels}\n🔑 Groq API key: {key}\n\nNow everyone can use `/test_love @User1 @User2` to analyze the great love (or the great drama)!',
    fr: '✅ **Le Love Tester est prêt !** 💘\n\n🌐 Langue : {lang}\n📂 Salons : {channels}\n🔑 Clé API Groq : {key}\n\nMaintenant, tout le monde peut utiliser `/test_love @User1 @User2` pour analyser le grand amour (ou le grand drame) !',
    es: '✅ **¡El Love Tester está listo!** 💘\n\n🌐 Idioma: {lang}\n📂 Canales: {channels}\n🔑 Clave API de Groq: {key}\n\n¡Ahora cualquiera puede usar `/test_love @User1 @User2` para analizar el gran amor (o el gran drama)!',
    pt: '✅ **Love Tester pronto!** 💘\n\n🌐 Idioma: {lang}\n📂 Canais: {channels}\n🔑 Chave da API Groq: {key}\n\nAgora todo mundo pode usar `/test_love @User1 @User2` para analisar o grande amor (ou o grande drama)!',
    ru: '✅ **Love Tester готов!** 💘\n\n🌐 Язык: {lang}\n📂 Каналы: {channels}\n🔑 API-ключ Groq: {key}\n\nТеперь каждый может использовать `/test_love @User1 @User2`, чтобы проанализировать большую любовь (или большую драму)!',
    ja: '✅ **ラブテスター準備完了！** 💘\n\n🌐 言語: {lang}\n📂 チャンネル: {channels}\n🔑 Groq APIキー: {key}\n\n`/test_love @User1 @User2` で、大いなる愛（または大いなるドラマ）を分析してもらおう！',
    ko: '✅ **러브 테스터 준비 완료!** 💘\n\n🌐 언어: {lang}\n📂 채널: {channels}\n🔑 Groq API 키: {key}\n\n이제 누구나 `/test_love @User1 @User2`로 위대한 사랑(또는 위대한 드라마)을 분석할 수 있어요!',
    zh: '✅ **恋爱测试仪已就绪！** 💘\n\n🌐 语言：{lang}\n📂 频道：{channels}\n🔑 Groq API 密钥：{key}\n\n现在每个人都可以使用 `/test_love @User1 @User2` 来分析伟大的爱情（或伟大的闹剧）！',
    it: '✅ **Love Tester è pronto!** 💘\n\n🌐 Lingua: {lang}\n📂 Canali: {channels}\n🔑 Chiave API Groq: {key}\n\nOra chiunque può usare `/test_love @User1 @User2` per analizzare il grande amore (o il grande dramma)!',
  },
  setupNoPermission: {
    de: '⛔ Nur **Administratoren** dürfen den Love Tester einrichten.',
    en: '⛔ Only **administrators** can set up the Love Tester.',
    fr: '⛔ Seuls les **administrateurs** peuvent configurer le Love Tester.',
    es: '⛔ Solo los **administradores** pueden configurar el Love Tester.',
    pt: '⛔ Apenas **administradores** podem configurar o Love Tester.',
    ru: '⛔ Настраивать Love Tester могут только **администраторы**.',
    ja: '⛔ ラブテスターを設定できるのは**管理者**だけです。',
    ko: '⛔ **관리자만** 러브 테스터를 설정할 수 있어요.',
    zh: '⛔ 只有**管理员**可以设置恋爱测试仪。',
    it: '⛔ Solo gli **amministratori** possono configurare il Love Tester.',
  },
  setupNeedLang: {
    de: '⚠️ Wähle zuerst eine Sprache im Menü aus!',
    en: '⚠️ Please select a language from the menu first!',
    fr: '⚠️ Choisis d’abord une langue dans le menu !',
    es: '⚠️ ¡Primero selecciona un idioma en el menú!',
    pt: '⚠️ Selecione primeiro um idioma no menu!',
    ru: '⚠️ Сначала выбери язык в меню!',
    ja: '⚠️ 先にメニューで言語を選んでください！',
    ko: '⚠️ 먼저 메뉴에서 언어를 선택하세요!',
    zh: '⚠️ 请先从菜单中选择一种语言！',
    it: '⚠️ Scegli prima una lingua dal menu!',
  },
  setupNeedChannels: {
    de: '⚠️ Wähle mindestens **einen Kanal** aus!',
    en: '⚠️ Please select at least **one channel**!',
    fr: '⚠️ Sélectionne au moins **un salon** !',
    es: '⚠️ ¡Selecciona al menos **un canal**!',
    pt: '⚠️ Selecione pelo menos **um canal**!',
    ru: '⚠️ Выбери хотя бы **один канал**!',
    ja: '⚠️ 少なくとも**1つのチャンネル**を選んでください！',
    ko: '⚠️ **채널을 하나 이상** 선택하세요!',
    zh: '⚠️ 请至少选择**一个频道**！',
    it: '⚠️ Seleziona almeno **un canale**!',
  },
  setupNeedKey: {
    de: '⚠️ Gib zuerst den Groq-API-Key ein (Button „API-Key eingeben“)!',
    en: '⚠️ Please enter the Groq API key first (“Enter API key” button)!',
    fr: '⚠️ Saisis d’abord la clé API Groq (bouton « Saisir la clé API ») !',
    es: '⚠️ ¡Introduce primero la clave API de Groq (botón «Introducir clave API»)!',
    pt: '⚠️ Digite primeiro a chave da API Groq (botão «Digite a chave da API»)!',
    ru: '⚠️ Сначала введи API-ключ Groq (кнопка «Ввести API-ключ»)!',
    ja: '⚠️ 先にGroq APIキーを入力してください（「APIキーを入力」ボタン）！',
    ko: '⚠️ 먼저 Groq API 키를 입력하세요 (「API 키 입력」버튼)!',
    zh: '⚠️ 请先输入 Groq API 密钥（“输入 API 密钥”按钮）！',
    it: '⚠️ Inserisci prima la chiave API Groq (pulsante «Inserisci chiave API»)!',
  },
  setupInvalidKey: {
    de: '⛔ Das sieht nicht nach einem gültigen Groq-API-Key aus (erwartet: `gsk_…`). Bitte prüfe die Eingabe.',
    en: '⛔ That doesn’t look like a valid Groq API key (expected: `gsk_…`). Please check your input.',
    fr: '⛔ Ça ne ressemble pas à une clé API Groq valide (attendu : `gsk_…`). Vérifie ta saisie.',
    es: '⛔ Eso no parece una clave API de Groq válida (se espera: `gsk_…`). Revisa la entrada.',
    pt: '⛔ Isso não parece uma chave da API Groq válida (esperado: `gsk_…`). Verifique a entrada.',
    ru: '⛔ Это не похоже на действующий API-ключ Groq (ожидается: `gsk_…`). Проверь ввод.',
    ja: '⛔ 有効なGroq APIキーのように見えません（形式: `gsk_…`）。入力を確認してください。',
    ko: '⛔ 유효한 Groq API 키 같지 않아요 (형식: `gsk_…`). 입력을 확인해 주세요.',
    zh: '⛔ 这看起来不像有效的 Groq API 密钥（应为：`gsk_…`）。请检查输入。',
    it: '⛔ Non sembra una chiave API Groq valida (previsto: `gsk_…`). Controlla l’input.',
  },
  setupCancelNote: {
    de: '❌ Setup abgebrochen – nichts wurde gespeichert.',
    en: '❌ Setup cancelled – nothing was saved.',
    fr: '❌ Configuration annulée – rien n’a été enregistré.',
    es: '❌ Configuración cancelada – no se guardó nada.',
    pt: '❌ Configuração cancelada – nada foi salvo.',
    ru: '❌ Настройка отменена – ничего не сохранено.',
    ja: '❌ 設定をキャンセルしました – 何も保存されていません。',
    ko: '❌ 설정이 취소됐어요 – 아무것도 저장되지 않았어요.',
    zh: '❌ 设置已取消——未保存任何内容。',
    it: '❌ Configurazione annullata – non è stato salvato nulla.',
  },
  setupReconfigureHint: {
    de: 'ℹ️ Es gibt bereits ein Setup auf diesem Server – du kannst es hier einfach überschreiben.',
    en: 'ℹ️ This server already has a setup – you can simply overwrite it here.',
    fr: 'ℹ️ Ce serveur a déjà une configuration – tu peux simplement la remplacer ici.',
    es: 'ℹ️ Este servidor ya tiene configuración – puedes sobrescribirla aquí.',
    pt: 'ℹ️ Este servidor já tem configuração – você pode simplesmente substituí-la aqui.',
    ru: 'ℹ️ На этом сервере уже есть настройка – здесь её можно просто перезаписать.',
    ja: 'ℹ️ このサーバーには設定が既にあります – ここで上書きできます。',
    ko: 'ℹ️ 이 서버에는 설정이 이미 있어요 – 여기서 덮어쓸 수 있어요.',
    zh: 'ℹ️ 该服务器已有设置——您可以在这里直接覆盖。',
    it: 'ℹ️ Questo server ha già una configurazione – puoi semplicemente sovrascriverla qui.',
  },

  // ------------------------------------------------------------
  // Buttons (Setup)
  // ------------------------------------------------------------
  btnBack: {
    de: '◀ Zurück',
    en: '◀ Back',
    fr: '◀ Retour',
    es: '◀ Atrás',
    pt: '◀ Voltar',
    ru: '◀ Назад',
    ja: '◀ 戻る',
    ko: '◀ 뒤로',
    zh: '◀ 返回',
    it: '◀ Indietro',
  },
  btnNext: {
    de: 'Weiter ▶',
    en: 'Next ▶',
    fr: 'Suivant ▶',
    es: 'Siguiente ▶',
    pt: 'Avançar ▶',
    ru: 'Далее ▶',
    ja: '次へ ▶',
    ko: '다음 ▶',
    zh: '下一步 ▶',
    it: 'Avanti ▶',
  },
  btnConfirm: {
    de: '✅ Bestätigen',
    en: '✅ Confirm',
    fr: '✅ Confirmer',
    es: '✅ Confirmar',
    pt: '✅ Confirmar',
    ru: '✅ Подтвердить',
    ja: '✅ 確認',
    ko: '✅ 확인',
    zh: '✅ 确认',
    it: '✅ Conferma',
  },
  btnCancel: {
    de: '❌ Abbrechen',
    en: '❌ Cancel',
    fr: '❌ Annuler',
    es: '❌ Cancelar',
    pt: '❌ Cancelar',
    ru: '❌ Отмена',
    ja: '❌ キャンセル',
    ko: '❌ 취소',
    zh: '❌ 取消',
    it: '❌ Annulla',
  },
  btnEnterKey: {
    de: '🔑 API-Key eingeben',
    en: '🔑 Enter API key',
    fr: '🔑 Saisir la clé API',
    es: '🔑 Introducir clave API',
    pt: '🔑 Digite a chave da API',
    ru: '🔑 Ввести API-ключ',
    ja: '🔑 APIキーを入力',
    ko: '🔑 API 키 입력',
    zh: '🔑 输入 API 密钥',
    it: '🔑 Inserisci chiave API',
  },

  // ------------------------------------------------------------
  // /test_love
  // ------------------------------------------------------------
  loveNoSetup: {
    de: '⛔ Der Love Tester ist hier noch nicht eingerichtet. Bitte bitte einen **Administrator**, `/setup` auszuführen!',
    en: '⛔ The Love Tester isn’t set up here yet. Please ask an **administrator** to run `/setup`!',
    fr: '⛔ Le Love Tester n’est pas encore configuré ici. Demande à un **administrateur** d’exécuter `/setup` !',
    es: '⛔ El Love Tester aún no está configurado aquí. ¡Pide a un **administrador** que ejecute `/setup`!',
    pt: '⛔ O Love Tester ainda não está configurado aqui. Peça a um **administrador** para executar `/setup`!',
    ru: '⛔ Love Tester ещё не настроен на этом сервере. Попроси **администратора** выполнить `/setup`!',
    ja: '⛔ このサーバーではラブテスターが未設定です。**管理者**に `/setup` を実行してもらってください！',
    ko: '⛔ 여기에는 러브 테스터가 아직 설정되지 않았어요. **관리자**에게 `/setup`을 실행해 달라고 하세요!',
    zh: '⛔ 恋爱测试仪尚未在此服务器设置。请让**管理员**运行 `/setup`！',
    it: '⛔ Il Love Tester non è ancora configurato qui. Chiedi a un **amministratore** di eseguire `/setup`!',
  },
  loveSameUser: {
    de: '🙃 Du kannst nicht die Liebe einer Person mit sich selbst testen … oder doch? (Nein.) Wähle **zwei verschiedene Personen**.',
    en: '🙃 You can’t test a person’s love for themselves … or can you? (No.) Pick **two different people**.',
    fr: '🙃 Tu ne peux pas tester l’amour d’une personne envers elle-même… ou si ? (Non.) Choisis **deux personnes différentes**.',
    es: '🙃 No puedes probar el amor de una persona consigo misma… ¿o sí? (No.) Elige **dos personas distintas**.',
    pt: '🙃 Você não pode testar o amor de uma pessoa por si mesma… ou pode? (Não.) Escolha **duas pessoas diferentes**.',
    ru: '🙃 Нельзя проверить любовь человека к самому себе… или можно? (Нет.) Выбери **двух разных людей**.',
    ja: '🙃 自分自身との愛はテストできません… いや、もしかして？（できません）**別々の2人**を選んでください。',
    ko: '🙃 혼자서 자신과의 사랑을 테스트할 순 없어요… 설마요? (아니요.) **서로 다른 두 사람**을 고르세요.',
    zh: '🙃 你不能测试一个人对自己的爱……也许可以？（不行。）请选择**两个不同的人**。',
    it: '🙃 Non puoi testare l’amore di una persona con sé stessa… o forse sì? (No.) Scegli **due persone diverse**.',
  },
  loveUserGone: {
    de: '🤔 Einen der beiden konnte ich auf dem Server nicht finden. Sind die noch Mitglied?',
    en: '🤔 I couldn’t find one of them on this server. Are they still a member?',
    fr: '🤔 Je n’ai pas trouvé l’une des deux personnes sur le serveur. Est-elle encore membre ?',
    es: '🤔 No pude encontrar a una de las dos personas en el servidor. ¿Sigue siendo miembro?',
    pt: '🤔 Não consegui encontrar uma das duas pessoas no servidor. Ainda é membro?',
    ru: '🤔 Я не нашёл одного из них на сервере. Он/она ещё участник?',
    ja: '🤔 サーバーでどちらか一方が見つかりませんでした。まだメンバーですか？',
    ko: '🤔 서버에서 둘 중 한 명을 찾지 못했어요. 아직 멤버인가요?',
    zh: '🤔 我在服务器上找不到其中一人。他们还是成员吗？',
    it: '🤔 Non ho trovato uno dei due sul server. È ancora membro?',
  },
  loveTestTitle: {
    de: '💘 Love Test – {u1} × {u2}',
    en: '💘 Love Test – {u1} × {u2}',
    fr: '💘 Love Test – {u1} × {u2}',
    es: '💘 Love Test – {u1} × {u2}',
    pt: '💘 Love Test – {u1} × {u2}',
    ru: '💘 Тест любви – {u1} × {u2}',
    ja: '💘 ラブテスト – {u1} × {u2}',
    ko: '💘 러브 테스트 – {u1} × {u2}',
    zh: '💘 爱情测试 – {u1} × {u2}',
    it: '💘 Love Test – {u1} × {u2}',
  },
  loveConfirmBody: {
    de: '⚠️ **Hinweis zum Datenschutz:**\n\nFür die Analyse werden **Chatverläufe aus den eingerichteten Kanälen** an **Groq** (einen Drittanbieter-KI-Dienst) weitergeleitet, um die Liebe zwischen **{u1}** und **{u2}** in Prozent zu schätzen.\n\nEs werden **maximal 500 Nachrichten** durchsucht, nur Ausschnitte werden gesendet – aber triff diese Entscheidung bewusst! 😉',
    en: '⚠️ **Privacy notice:**\n\nFor the analysis, **chat logs from the configured channels** will be forwarded to **Groq** (a third-party AI service) to estimate the love between **{u1}** and **{u2}** in percent.\n\nA maximum of **500 messages** will be searched and only excerpts will be sent – but make this decision consciously! 😉',
    fr: '⚠️ **Avis de confidentialité :**\n\nPour l’analyse, des **extraits de chat des salons configurés** seront transmis à **Groq** (un service IA tiers) afin d’estimer l’amour entre **{u1}** et **{u2}** en pourcentage.\n\nAu maximum **500 messages** seront parcourus, seuls des extraits seront envoyés – mais prends cette décision en connaissance de cause ! 😉',
    es: '⚠️ **Aviso de privacidad:**\n\nPara el análisis, se enviarán **extractos de chat de los canales configurados** a **Groq** (un servicio de IA de terceros) para estimar el amor entre **{u1}** y **{u2}** en porcentaje.\n\nSe buscarán **máximo 500 mensajes** y solo se enviarán extractos. ¡Pero toma esta decisión con conciencia! 😉',
    pt: '⚠️ **Aviso de privacidade:**\n\nPara a análise, **trechos de chat dos canais configurados** serão enviados à **Groq** (um serviço de IA de terceiros) para estimar o amor entre **{u1}** e **{u2}** em porcentagem.\n\nNo máximo **500 mensagens** serão pesquisadas e apenas trechos serão enviados – mas tome essa decisão conscientemente! 😉',
    ru: '⚠️ **Уведомление о конфиденциальности:**\n\nДля анализа **фрагменты чатов из настроенных каналов** будут отправлены в **Groq** (сторонний ИИ-сервис), чтобы оценить любовь между **{u1}** и **{u2}** в процентах.\n\nБудет просмотрено **максимум 500 сообщений**, отправляются только фрагменты – но принимай это решение осознанно! 😉',
    ja: '⚠️ **プライバシーに関する注意事項：**\n\n分析のため、**設定されたチャンネルのチャットログ**が**Groq**（第三者AIサービス）に送信され、**{u1}** と **{u2}** の間の愛がパーセントで推定されます。\n\n検索されるのは**最大500件のメッセージ**で、送信されるのは抜粋のみです – でも、この決断はよく考えて！ 😉',
    ko: '⚠️ **개인정보 고지:**\n\n분석을 위해 **설정된 채널의 채팅 로그**가 **Groq**(제3자 AI 서비스)로 전송되어 **{u1}**과 **{u2}** 사이의 사랑을 퍼센트로 추정합니다.\n\n**최대 500개 메시지**만 검색되고 발췌문만 전송돼요 – 하지만 신중하게 결정하세요! 😉',
    zh: '⚠️ **隐私提示：**\n\n为了进行分析，**已设置频道中的聊天记录**将被转发给 **Groq**（第三方 AI 服务），以估算 **{u1}** 和 **{u2}** 之间的爱情百分比。\n\n最多搜索 **500 条消息**，且仅发送片段——但请慎重做出这个决定！😉',
    it: '⚠️ **Avviso sulla privacy:**\n\nPer l’analisi, **estratti di chat dai canali configurati** verranno inoltrati a **Groq** (un servizio AI di terze parti) per stimare l’amore tra **{u1}** e **{u2}** in percentuale.\n\nVerranno cercati al massimo **500 messaggi** e inviati solo estratti – ma prendi questa decisione con consapevolezza! 😉',
  },
  btnAccept: {
    de: '✅ Annehmen & Analysieren',
    en: '✅ Accept & Analyze',
    fr: '✅ Accepter & analyser',
    es: '✅ Aceptar y analizar',
    pt: '✅ Aceitar e analisar',
    ru: '✅ Принять и анализировать',
    ja: '✅ 同意して分析',
    ko: '✅ 동의하고 분석',
    zh: '✅ 同意并分析',
    it: '✅ Accetta e analizza',
  },
  btnDecline: {
    de: '❌ Ablehnen',
    en: '❌ Decline',
    fr: '❌ Refuser',
    es: '❌ Rechazar',
    pt: '❌ Recusar',
    ru: '❌ Отклонить',
    ja: '❌ 拒否',
    ko: '❌ 거절',
    zh: '❌ 拒绝',
    it: '❌ Rifiuta',
  },
  loveButtonsOwnerOnly: {
    de: '🔒 Diese Buttons kann nur {user} benutzen – die Person, die den Test gestartet hat!',
    en: '🔒 Only {user} – the person who started the test – can use these buttons!',
    fr: '🔒 Seul {user} – la personne qui a lancé le test – peut utiliser ces boutons !',
    es: '🔒 ¡Solo {user} – la persona que inició el test – puede usar estos botones!',
    pt: '🔒 Só {user} – a pessoa que iniciou o teste – pode usar estes botões!',
    ru: '🔒 Эти кнопки может использовать только {user} – тот, кто запустил тест!',
    ja: '🔒 これらのボタンはテストを開始した {user} だけが使えます！',
    ko: '🔒 이 버튼은 테스트를 시작한 {user}만 사용할 수 있어요!',
    zh: '🔒 只有发起测试的 {user} 才能使用这些按钮！',
    it: '🔒 Solo {user} – la persona che ha avviato il test – può usare questi pulsanti!',
  },
  loveDeclined: {
    de: '🙈 Analyse abgelehnt – die Liebe bleibt vorerst ein Geheimnis. Schade!',
    en: '🙈 Analysis declined – for now, love remains a mystery. Too bad!',
    fr: '🙈 Analyse refusée – pour l’instant, l’amour reste un mystère. Dommage !',
    es: '🙈 Análisis rechazado: el amor sigue siendo un misterio por ahora. ¡Qué pena!',
    pt: '🙈 Análise recusada – por enquanto, o amor continua um mistério. Que pena!',
    ru: '🙈 Анализ отклонён – пока любовь остаётся загадкой. Жаль!',
    ja: '🙈 分析を拒否しました – 愛は当分謎のまま。残念！',
    ko: '🙈 분석이 거절됐어요 – 사랑은 당분간 미스터리로 남아요. 아쉽네요!',
    zh: '🙈 已拒绝分析——爱情暂时仍是个谜。真可惜！',
    it: '🙈 Analisi rifiutata – per ora l’amore resta un mistero. Peccato!',
  },
  loveAccepted: {
    de: '🧪 **Analyse gestartet!** Gleich wird die große Liebe (oder das große Drama) seziert …',
    en: '🧪 **Analysis started!** The great love (or the great drama) is about to be dissected …',
    fr: '🧪 **Analyse lancée !** Le grand amour (ou le grand drame) va être disséqué …',
    es: '🧪 **¡Análisis iniciado!** El gran amor (o el gran drama) va a ser diseccionado …',
    pt: '🧪 **Análise iniciada!** O grande amor (ou o grande drama) vai ser dissecado …',
    ru: '🧪 **Анализ запущен!** Великая любовь (или великая драма) сейчас будет препарирована …',
    ja: '🧪 **分析開始！** 大いなる愛（または大いなるドラマ）を解剖します …',
    ko: '🧪 **분석 시작!** 위대한 사랑(또는 위대한 드라마)을 해부할 거예요 …',
    zh: '🧪 **分析已开始！** 即将剖析伟大的爱情（或伟大的闹剧）……',
    it: '🧪 **Analisi avviata!** Il grande amore (o il grande dramma) sta per essere dissezionato …',
  },
  analysingProgress: {
    de: '**{pct} %** · {phase}',
    en: '**{pct} %** · {phase}',
    fr: '**{pct} %** · {phase}',
    es: '**{pct} %** · {phase}',
    pt: '**{pct} %** · {phase}',
    ru: '**{pct} %** · {phase}',
    ja: '**{pct} %** · {phase}',
    ko: '**{pct} %** · {phase}',
    zh: '**{pct} %** · {phase}',
    it: '**{pct} %** · {phase}',
  },
  analysingScan: {
    de: 'Nachrichten werden gelesen …',
    en: 'Reading messages …',
    fr: 'Lecture des messages …',
    es: 'Leyendo mensajes …',
    pt: 'Lendo mensagens …',
    ru: 'Читаю сообщения …',
    ja: 'メッセージを読み込んでいます …',
    ko: '메시지를 읽는 중 …',
    zh: '正在读取消息……',
    it: 'Lettura dei messaggi …',
  },
  analysingPrepare: {
    de: 'Gesprächsausschnitte werden vorbereitet …',
    en: 'Preparing conversation excerpts …',
    fr: 'Préparation des extraits de conversation …',
    es: 'Preparando extractos de conversación …',
    pt: 'Preparando trechos da conversa …',
    ru: 'Готовлю фрагменты разговора …',
    ja: '会話の抜粋を準備しています …',
    ko: '대화 발췌문을 준비하는 중 …',
    zh: '正在准备对话片段……',
    it: 'Preparazione degli estratti della conversazione …',
  },
  analysingStats: {
    de: '{scanned} Nachrichten gelesen · {channels} Kanäle · {excerpts} Ausschnitte',
    en: '{scanned} messages read · {channels} channels · {excerpts} excerpts',
    fr: '{scanned} messages lus · {channels} salons · {excerpts} extraits',
    es: '{scanned} mensajes leídos · {channels} canales · {excerpts} extractos',
    pt: '{scanned} mensagens lidas · {channels} canais · {excerpts} trechos',
    ru: '{scanned} сообщений прочитано · {channels} каналов · {excerpts} фрагментов',
    ja: '{scanned} 件のメッセージを読み込み · {channels} チャンネル · {excerpts} 抜粋',
    ko: '메시지 {scanned}개 읽음 · 채널 {channels}개 · 발췌 {excerpts}개',
    zh: '已读取 {scanned} 条消息 · {channels} 个频道 · {excerpts} 个片段',
    it: '{scanned} messaggi letti · {channels} canali · {excerpts} estratti',
  },
  analysingPhases: {
    de: [
      'Nachrichten werden gelesen …',
      'Chatverläufe werden durchsucht …',
      'Relevante Nachrichten werden gesammelt …',
      'Kontext wird vorbereitet …',
    ],
    en: [
      'Reading messages …',
      'Searching chat histories …',
      'Collecting relevant messages …',
      'Preparing context …',
    ],
    fr: [
      'Lecture des messages …',
      'Recherche dans les historiques …',
      'Collecte des messages pertinents …',
      'Préparation du contexte …',
    ],
    es: [
      'Leyendo mensajes …',
      'Buscando en los chats …',
      'Reuniendo mensajes relevantes …',
      'Preparando el contexto …',
    ],
    pt: [
      'Lendo mensagens …',
      'Vasculhando os chats …',
      'Coletando mensagens relevantes …',
      'Preparando o contexto …',
    ],
    ru: [
      'Читаю сообщения …',
      'Просматриваю историю чатов …',
      'Собираю нужные сообщения …',
      'Готовлю контекст …',
    ],
    ja: [
      'メッセージを読み込んでいます …',
      'チャット履歴を検索しています …',
      '関連メッセージを集めています …',
      'コンテキストを準備しています …',
    ],
    ko: [
      '메시지를 읽는 중 …',
      '채팅 기록을 검색하는 중 …',
      '관련 메시지를 모으는 중 …',
      '컨텍스트를 준비하는 중 …',
    ],
    zh: [
      '正在读取消息……',
      '正在搜索聊天记录……',
      '正在收集相关消息……',
      '正在准备上下文……',
    ],
    it: [
      'Lettura dei messaggi …',
      'Ricerca nelle chat …',
      'Raccolta dei messaggi rilevanti …',
      'Preparazione del contesto …',
    ],
  },
  analysingFinal: {
    de: 'KI wertet die Daten aus …',
    en: 'AI is evaluating the data …',
    fr: 'L’IA évalue les données …',
    es: 'La IA está evaluando los datos …',
    pt: 'A IA está avaliando os dados …',
    ru: 'ИИ оценивает данные …',
    ja: 'AIがデータを評価しています …',
    ko: 'AI가 데이터를 평가하는 중 …',
    zh: 'AI 正在评估数据……',
    it: 'L’IA sta valutando i dati …',
  },
  loveResultTitle: {
    de: 'Ergebnis',
    en: 'Result',
    fr: 'Résultat',
    es: 'Resultado',
    pt: 'Resultado',
    ru: 'Результат',
    ja: '結果',
    ko: '결과',
    zh: '结果',
    it: 'Risultato',
  },
  loveResultFooter: {
    de: '\n-# 🤖 Nur zum Spaß. Liebe ist keine Prozentzahl – aber shippen tun wir trotzdem.',
    en: '\n-# 🤖 Just for fun. Love isn’t a percent – but we’re shipping them anyway.',
    fr: '\n-# 🤖 Juste pour le fun. L’amour n’est pas un pourcentage – mais on ship quand même.',
    es: '\n-# 🤖 Solo por diversión. El amor no es un porcentaje – pero los shippeamos igual.',
    pt: '\n-# 🤖 Só por diversão. Amor não é porcentagem – mas a gente shippa mesmo assim.',
    ru: '\n-# 🤖 Просто ради фана. Любовь не в процентах – но шиппить мы всё равно будем.',
    ja: '\n-# 🤖 ネタです。愛はパーセントじゃない – でもシップはする。',
    ko: '\n-# 🤖 그냥 재미로. 사랑은 퍼센트가 아니에요 – 그래도 쉽은 합니다.',
    zh: '\n-# 🤖 纯属娱乐。爱不是百分比——但我们还是要组 CP。',
    it: '\n-# 🤖 Solo per divertimento. L’amore non è una percentuale – ma li shippiamo lo stesso.',
  },

  // ------------------------------------------------------------
  // Ausschnitt-Aufbereitung (für die KI)
  // ------------------------------------------------------------
  excerptIntro: {
    de: 'USER 1: {u1}\nUSER 2: {u2}',
    en: 'USER 1: {u1}\nUSER 2: {u2}',
    fr: 'USER 1 : {u1}\nUSER 2 : {u2}',
    es: 'USER 1: {u1}\nUSER 2: {u2}',
    pt: 'USER 1: {u1}\nUSER 2: {u2}',
    ru: 'USER 1: {u1}\nUSER 2: {u2}',
    ja: 'USER 1: {u1}\nUSER 2: {u2}',
    ko: 'USER 1: {u1}\nUSER 2: {u2}',
    zh: 'USER 1：{u1}\nUSER 2：{u2}',
    it: 'USER 1: {u1}\nUSER 2: {u2}',
  },
  excerptHeader: {
    de: '---- AUSSCHNITT {n} ----',
    en: '---- EXCERPT {n} ----',
    fr: '---- EXTRAIT {n} ----',
    es: '---- EXTRACTO {n} ----',
    pt: '---- TRECHO {n} ----',
    ru: '---- ФРАГМЕНТ {n} ----',
    ja: '---- 抜粋 {n} ----',
    ko: '---- 발췌 {n} ----',
    zh: '---- 片段 {n} ----',
    it: '---- ESTRATTO {n} ----',
  },
  msgRepliedTo: {
    de: '*hat auf eine Nachricht von {user} mit dem Inhalt „{content}“ geantwortet mit:*',
    en: '*replied to a message by {user} with the content “{content}”:*',
    fr: '*a répondu à un message de {user} avec le contenu « {content} » :*',
    es: '*respondió a un mensaje de {user} con el contenido «{content}»:*',
    pt: '*respondeu a uma mensagem de {user} com o conteúdo «{content}»:*',
    ru: '*ответил(а) на сообщение {user} с содержанием «{content}»:*',
    ja: '*{user} のメッセージ「{content}」に返信しました:*',
    ko: '*{user}님의 메시지 "{content}"에 답장했어요:*',
    zh: '*回复了 {user} 的内容为“{content}”的消息：*',
    it: '*ha risposto a un messaggio di {user} con il contenuto «{content}»:*',
  },
  msgRepliedGeneric: {
    de: '*hat auf eine Nachricht geantwortet mit:*',
    en: '*replied to a message with:*',
    fr: '*a répondu à un message avec :*',
    es: '*respondió a un mensaje con:*',
    pt: '*respondeu a uma mensagem com:*',
    ru: '*ответил(а) на сообщение:*',
    ja: '*メッセージに返信しました:*',
    ko: '*메시지에 답장했어요:*',
    zh: '*回复了一条消息：*',
    it: '*ha risposto a un messaggio con:*',
  },
  msgImage: {
    de: '*hat ein Bild gesendet*',
    en: '*sent an image*',
    fr: '*a envoyé une image*',
    es: '*envió una imagen*',
    pt: '*enviou uma imagem*',
    ru: '*отправил(а) изображение*',
    ja: '*画像を送信しました*',
    ko: '*이미지를 보냈어요*',
    zh: '*发送了一张图片*',
    it: '*ha inviato un’immagine*',
  },
  msgVideo: {
    de: '*hat ein Video gesendet*',
    en: '*sent a video*',
    fr: '*a envoyé une vidéo*',
    es: '*envió un vídeo*',
    pt: '*enviou um vídeo*',
    ru: '*отправил(а) видео*',
    ja: '*動画を送信しました*',
    ko: '*영상을 보냈어요*',
    zh: '*发送了一个视频*',
    it: '*ha inviato un video*',
  },
  msgVoice: {
    de: '*hat eine Sprachnachricht gesendet*',
    en: '*sent a voice message*',
    fr: '*a envoyé un message vocal*',
    es: '*envió una nota de voz*',
    pt: '*enviou um áudio*',
    ru: '*отправил(а) голосовое сообщение*',
    ja: '*ボイスメッセージを送信しました*',
    ko: '*음성 메시지를 보냈어요*',
    zh: '*发送了一条语音消息*',
    it: '*ha inviato un messaggio vocale*',
  },
  msgAudio: {
    de: '*hat eine Audiodatei gesendet*',
    en: '*sent an audio file*',
    fr: '*a envoyé un fichier audio*',
    es: '*envió un archivo de audio*',
    pt: '*enviou um arquivo de áudio*',
    ru: '*отправил(а) аудиофайл*',
    ja: '*音声ファイルを送信しました*',
    ko: '*오디오 파일을 보냈어요*',
    zh: '*发送了一个音频文件*',
    it: '*ha inviato un file audio*',
  },
  msgFile: {
    de: '*hat eine Datei „{name}“ gesendet*',
    en: '*sent a file “{name}”*',
    fr: '*a envoyé un fichier « {name} »*',
    es: '*envió un archivo «{name}»*',
    pt: '*enviou um arquivo «{name}»*',
    ru: '*отправил(а) файл «{name}»*',
    ja: '*ファイル「{name}」を送信しました*',
    ko: '*파일 "{name}"을(를) 보냈어요*',
    zh: '*发送了一个文件“{name}”*',
    it: '*ha inviato un file «{name}»*',
  },
  msgSticker: {
    de: '*hat einen Sticker „{name}“ gesendet*',
    en: '*sent a sticker “{name}”*',
    fr: '*a envoyé un sticker « {name} »*',
    es: '*envió una pegatina «{name}»*',
    pt: '*enviou um sticker «{name}»*',
    ru: '*отправил(а) стикер «{name}»*',
    ja: '*ステッカー「{name}」を送信しました*',
    ko: '*스티커 "{name}"을(를) 보냈어요*',
    zh: '*发送了一个贴纸“{name}”*',
    it: '*ha inviato uno sticker «{name}»*',
  },
  msgEmbed: {
    de: '*hat einen Embed geteilt*',
    en: '*shared an embed*',
    fr: '*a partagé un embed*',
    es: '*compartió un embed*',
    pt: '*compartilhou um embed*',
    ru: '*поделился(ась) embed-сообщением*',
    ja: '*埋め込みを共有しました*',
    ko: '*임베드를 공유했어요*',
    zh: '*分享了一个嵌入内容*',
    it: '*ha condiviso un embed*',
  },
  genericUser: {
    de: 'jemand',
    en: 'someone',
    fr: 'quelqu’un',
    es: 'alguien',
    pt: 'alguém',
    ru: 'кто-то',
    ja: '誰か',
    ko: '누군가',
    zh: '某人',
    it: 'qualcuno',
  },
  genericRole: {
    de: 'Rolle',
    en: 'role',
    fr: 'rôle',
    es: 'rol',
    pt: 'cargo',
    ru: 'роль',
    ja: 'ロール',
    ko: '역할',
    zh: '身份组',
    it: 'ruolo',
  },
  genericChannel: {
    de: 'Kanal',
    en: 'channel',
    fr: 'salon',
    es: 'canal',
    pt: 'canal',
    ru: 'канал',
    ja: 'チャンネル',
    ko: '채널',
    zh: '频道',
    it: 'canale',
  },
  msgEmoji: {
    de: 'Emoji „{name}“',
    en: 'emoji “{name}”',
    fr: 'emoji « {name} »',
    es: 'emoji «{name}»',
    pt: 'emoji «{name}»',
    ru: 'эмодзи «{name}»',
    ja: '絵文字「{name}」',
    ko: '이모지 "{name}"',
    zh: '表情“{name}”',
    it: 'emoji «{name}»',
  },

  // ------------------------------------------------------------
  // Fehler & Retry
  // ------------------------------------------------------------
  errTitle: {
    de: '😱 Upps – da ist etwas schiefgelaufen!',
    en: '😱 Oops – something went wrong!',
    fr: '😱 Oups – quelque chose a mal tourné !',
    es: '😱 ¡Ups, algo salió mal!',
    pt: '😱 Opa – algo deu errado!',
    ru: '😱 Упс – что-то пошло не так!',
    ja: '😱 おっと – 何かがうまくいきませんでした！',
    ko: '😱 이런 – 뭔가 잘못됐어요!',
    zh: '😱 哎呀——出问题了！',
    it: '😱 Ops – qualcosa è andato storto!',
  },
  errGroqRateLimit: {
    de: '⏳ **Groq-Nutzungslimit erreicht.** Die KI ist gerade überrannt worden (vermutlich von zu vielen Liebestests). Warte einen Moment und versuche es erneut – die bisher gescannten Nachrichten bleiben erhalten!',
    en: '⏳ **Groq usage limit reached.** The AI just got overwhelmed (probably by too many love tests). Wait a moment and try again – the messages scanned so far are kept!',
    fr: '⏳ **Limite d’utilisation Groq atteinte.** L’IA vient d’être submergée (probablement par trop de love tests). Attends un instant et réessaie – les messages déjà scannés sont conservés !',
    es: '⏳ **Límite de uso de Groq alcanzado.** La IA acaba de verse desbordada (seguramente por demasiados love tests). Espera un momento e inténtalo de nuevo: ¡los mensajes escaneados se conservan!',
    pt: '⏳ **Limite de uso da Groq atingido.** A IA acabou de ser sobrecarregada (provavelmente por testes de amor demais). Espere um momento e tente de novo – as mensagens já escaneadas ficam salvas!',
    ru: '⏳ **Достигнут лимит Groq.** ИИ только что перегрузили (наверное, слишком много любовных тестов). Подожди немного и попробуй снова – уже просканированные сообщения сохраняются!',
    ja: '⏳ **Groqの利用制限に達しました。** AIが押し寄せるラブテストで過負荷です。少し待って再試行してください – スキャン済みのメッセージは保持されます！',
    ko: '⏳ **Groq 사용 한도에 도달했어요.** AI가 러브 테스트 폭주로 과부하가 걸렸어요. 잠시 후 다시 시도하세요 – 스캔한 메시지는 유지돼요!',
    zh: '⏳ **已到达 Groq 使用限额。** AI 刚刚被过多的爱情测试淹没。请稍等片刻再试——已扫描的消息都会保留！',
    it: '⏳ **Limite di utilizzo Groq raggiunto.** L’IA è appena stata sommersa (probabilmente da troppi love test). Aspetta un attimo e riprova – i messaggi già scansionati vengono conservati!',
  },
  errGroqAuth: {
    de: '⛔ **Groq hat den API-Key abgelehnt** (401/403). Prüfe den Key im Setup (`/setup` → Schritt 3) oder ob das Groq-Konto genug Guthaben hat.',
    en: '⛔ **Groq rejected the API key** (401/403). Check the key in setup (`/setup` → Step 3) or whether the Groq account has enough credits.',
    fr: '⛔ **Groq a refusé la clé API** (401/403). Vérifie la clé dans la configuration (`/setup` → Étape 3) ou si le compte Groq a assez de crédits.',
    es: '⛔ **Groq rechazó la clave API** (401/403). Revisa la clave en la configuración (`/setup` → Paso 3) o si la cuenta de Groq tiene crédito suficiente.',
    pt: '⛔ **A Groq rejeitou a chave da API** (401/403). Verifique a chave na configuração (`/setup` → Etapa 3) ou se a conta Groq tem créditos suficientes.',
    ru: '⛔ **Groq отклонил API-ключ** (401/403). Проверь ключ в настройках (`/setup` → шаг 3) или баланс аккаунта Groq.',
    ja: '⛔ **GroqがAPIキーを拒否しました**（401/403）。設定（`/setup` → ステップ3）でキーを確認するか、Groqアカウントの残高を確認してください。',
    ko: '⛔ **Groq가 API 키를 거부했어요** (401/403). 설정(`/setup` → 3단계)에서 키를 확인하거나 Groq 계정 크레딧을 확인해 주세요.',
    zh: '⛔ **Groq 拒绝了 API 密钥**（401/403）。请在设置中检查密钥（`/setup` → 第3步），或检查 Groq 账户额度是否充足。',
    it: '⛔ **Groq ha rifiutato la chiave API** (401/403). Controlla la chiave nella configurazione (`/setup` → Passo 3) o se l’account Groq ha abbastanza crediti.',
  },
  errGroqServer: {
    de: '⚠️ **Groq-Serverfehler** ({status}). Die KI-Herde hat gerade Schluckauf. Versuch es gleich noch einmal – die gescannten Nachrichten bleiben erhalten!',
    en: '⚠️ **Groq server error** ({status}). The AI herd is having a hiccup right now. Try again in a moment – the scanned messages are kept!',
    fr: '⚠️ **Erreur serveur Groq** ({status}). Le troupeau d’IA a le hoquet en ce moment. Réessaie dans un instant – les messages scannés sont conservés !',
    es: '⚠️ **Error de servidor de Groq** ({status}). El rebaño de IA está teniendo hipo ahora mismo. Inténtalo de nuevo en un momento: ¡los mensajes escaneados se conservan!',
    pt: '⚠️ **Erro de servidor da Groq** ({status}). O rebanho de IAs está com soluço agora. Tente de novo daqui a pouco – as mensagens escaneadas ficam salvas!',
    ru: '⚠️ **Ошибка сервера Groq** ({status}). У стада ИИ сейчас икота. Попробуй ещё раз чуть позже – просканированные сообщения сохраняются!',
    ja: '⚠️ **Groqサーバーエラー**（{status}）。AIの群れがしゃっくり中です。少ししてから再試行してください – スキャン済みメッセージは保持されます！',
    ko: '⚠️ **Groq 서버 오류** ({status}). AI 무리가 지금 딸꾹질 중이에요. 잠시 후 다시 시도하세요 – 스캔한 메시지는 유지돼요!',
    zh: '⚠️ **Groq 服务器错误**（{status}）。AI 群目前正在打嗝。请稍后重试——已扫描的消息都会保留！',
    it: '⚠️ **Errore del server Groq** ({status}). Il gregge di IA ha il singhiozzo in questo momento. Riprova tra un attimo – i messaggi scansionati vengono conservati!',
  },
  errGroqNetwork: {
    de: '📡 **Netzwerkfehler zu Groq.** Die Leitung zwischen Discord und der KI ist wohl geknickt. Versuch es noch einmal!',
    en: '📡 **Network error with Groq.** The line between Discord and the AI seems to be bent. Try again!',
    fr: '📡 **Erreur réseau avec Groq.** La liaison entre Discord et l’IA semble être coupée. Réessaie !',
    es: '📡 **Error de red con Groq.** La conexión entre Discord y la IA parece estar doblada. ¡Inténtalo de nuevo!',
    pt: '📡 **Erro de rede com a Groq.** A conexão entre o Discord e a IA parece estar rompida. Tente de novo!',
    ru: '📡 **Сетевая ошибка Groq.** Линия между Discord и ИИ, похоже, перегнулась. Попробуй ещё раз!',
    ja: '📡 **Groqとのネットワークエラー。** DiscordとAIの回線が切れているようです。もう一度お試しください！',
    ko: '📡 **Groq 네트워크 오류.** Discord와 AI 사이의 회선이 꺾인 것 같아요. 다시 시도해 보세요!',
    zh: '📡 **与 Groq 的网络错误。** Discord 与 AI 之间的线路似乎断了。请再试一次！',
    it: '📡 **Errore di rete con Groq.** La linea tra Discord e l’IA sembra piegata. Riprova!',
  },
  errGroqContext: {
    de: '📦 Der Kontext war zu groß – ich habe die Ausschnitte gestutzt und versuche es noch einmal mit weniger (aber den wichtigsten) Nachrichten.',
    en: '📦 The context was too large – I trimmed the excerpts and will try again with fewer (but the most important) messages.',
    fr: '📦 Le contexte était trop grand – j’ai réduit les extraits et je réessaie avec moins de messages (mais les plus importants).',
    es: '📦 El contexto era demasiado grande: recorté los extractos e intentaré de nuevo con menos mensajes (pero los más importantes).',
    pt: '📦 O contexto era grande demais – cortei os trechos e vou tentar de novo com menos mensagens (mas as mais importantes).',
    ru: '📦 Контекст был слишком большим – я сократил фрагменты и попробую ещё раз с меньшим числом (но самых важных) сообщений.',
    ja: '📦 コンテキストが大きすぎました – 抜粋を削って、少ない（でも最重要な）メッセージで再試行します。',
    ko: '📦 컨텍스트가 너무 컸어요 – 발췌문을 줄이고 더 적은(하지만 가장 중요한) 메시지로 다시 시도할게요.',
    zh: '📦 上下文太大——我已精简片段，将用更少（但最重要）的消息重试。',
    it: '📦 Il contesto era troppo grande – ho ridotto gli estratti e riproverò con meno messaggi (ma i più importanti).',
  },
  errNoMessages: {
    de: '🕳️ **Keine brauchbaren Nachrichten gefunden.** Die beiden haben in den eingestellten Kanälen offenbar nie miteinander (oder überhaupt) geschrieben. Entweder andere Kanäle im `/setup` wählen oder warten, bis geflirtet wird! 😄',
    en: '🕳️ **No usable messages found.** Apparently the two have never written to each other (or at all) in the configured channels. Either choose other channels in `/setup` or wait until someone flirts! 😄',
    fr: '🕳️ **Aucun message exploitable trouvé.** Visiblement, les deux ne se sont jamais écrit (ou pas du tout) dans les salons configurés. Choisis d’autres salons dans `/setup` ou attends que le flirt commence ! 😄',
    es: '🕳️ **No se encontraron mensajes útiles.** Al parecer, los dos nunca se han escrito (ni escrito nada) en los canales configurados. ¡Elige otros canales en `/setup` o espera a que empiece el coqueteo! 😄',
    pt: '🕳️ **Nenhuma mensagem útil encontrada.** Aparentemente os dois nunca se escreveram (nem escreveram nada) nos canais configurados. Escolha outros canais no `/setup` ou espere até alguém flertar! 😄',
    ru: '🕳️ **Полезных сообщений не найдено.** Похоже, эти двое никогда не переписывались (или вообще не писали) в настроенных каналах. Выбери другие каналы в `/setup` или подожди, пока начнётся флирт! 😄',
    ja: '🕳️ **使えるメッセージが見つかりません。** 設定されたチャンネルでは、二人はどうやら一度も書き合っていない（または書いていない）ようです。`/setup` で別のチャンネルを選ぶか、恋の駆け引きが始まるのを待ちましょう！ 😄',
    ko: '🕳️ **쓸 만한 메시지를 찾지 못했어요.** 설정된 채널에서 두 분은 서로에게(또는 아예) 쓴 적이 없는 것 같아요. `/setup`에서 다른 채널을 선택하거나 누군가 플러팅할 때까지 기다리세요! 😄',
    zh: '🕳️ **未找到可用的消息。** 看来这两人在已设置的频道中从未互相（或从未）发过消息。请在 `/setup` 中选择其他频道，或者等待调情开始！😄',
    it: '🕳️ **Nessun messaggio utile trovato.** A quanto pare i due non si sono mai scritti (né hanno scritto altro) nei canali configurati. Scegli altri canali in `/setup` o aspetta che inizi il flirt! 😄',
  },
  errDiscordRateLimit: {
    de: '🚦 **Discord-Rate-Limit.** Discord hat gesagt: „Langsamer, Liebesforscher!“ Die bereits gescannten Nachrichten bleiben erhalten – versuch es gleich noch einmal.',
    en: '🚦 **Discord rate limit.** Discord said: “Slower, love detective!” The messages scanned so far are kept – try again in a moment.',
    fr: '🚦 **Limite de débit Discord.** Discord a dit : « Plus doucement, détective de l’amour ! » Les messages déjà scannés sont conservés – réessaie dans un instant.',
    es: '🚦 **Límite de velocidad de Discord.** Discord dijo: «¡Más despacio, detective del amor!» Los mensajes escaneados se conservan: inténtalo de nuevo en un momento.',
    pt: '🚦 **Limite de taxa do Discord.** O Discord disse: “Mais devagar, detetive do amor!” As mensagens já escaneadas ficam salvas – tente de novo daqui a pouco.',
    ru: '🚦 **Лимит запросов Discord.** Discord сказал: «Помедленнее, любовный детектив!» Просканированные сообщения сохраняются – попробуй ещё раз чуть позже.',
    ja: '🚦 **Discordのレート制限。** Discordが「ゆっくり、ラブ探偵！」と言っています。スキャン済みメッセージは保持されます – 少ししてから再試行してください。',
    ko: '🚦 **Discord 속도 제한.** Discord가 "천천히, 러브 탐정님!"이라고 했어요. 스캔한 메시지는 유지되니 잠시 후 다시 시도해 주세요.',
    zh: '🚦 **Discord 频率限制。** Discord 说：“慢一点，爱情侦探！”已扫描的消息都会保留——请稍后重试。',
    it: '🚦 **Limite di richieste Discord.** Discord ha detto: «Più piano, detective dell’amore!» I messaggi già scansionati vengono conservati – riprova tra un attimo.',
  },
  errGeneric: {
    de: '⛔ **Fehler:** {error}',
    en: '⛔ **Error:** {error}',
    fr: '⛔ **Erreur :** {error}',
    es: '⛔ **Error:** {error}',
    pt: '⛔ **Erro:** {error}',
    ru: '⛔ **Ошибка:** {error}',
    ja: '⛔ **エラー:** {error}',
    ko: '⛔ **오류:** {error}',
    zh: '⛔ **错误：**{error}',
    it: '⛔ **Errore:** {error}',
  },
  btnRetry: {
    de: '🔄 Erneut versuchen',
    en: '🔄 Try again',
    fr: '🔄 Réessayer',
    es: '🔄 Reintentar',
    pt: '🔄 Tentar de novo',
    ru: '🔄 Попробовать снова',
    ja: '🔄 もう一度試す',
    ko: '🔄 다시 시도',
    zh: '🔄 重试',
    it: '🔄 Riprova',
  },
  btnContinue: {
    de: '📚 Weiter analysieren',
    en: '📚 Keep analyzing',
    fr: '📚 Continuer l’analyse',
    es: '📚 Seguir analizando',
    pt: '📚 Continuar analisando',
    ru: '📚 Продолжить анализ',
    ja: '📚 分析を続ける',
    ko: '📚 계속 분석하기',
    zh: '📚 继续分析',
    it: '📚 Continua l’analisi',
  },
  btnStop: {
    de: '🛑 Abbrechen',
    en: '🛑 Stop',
    fr: '🛑 Arrêter',
    es: '🛑 Detener',
    pt: '🛑 Parar',
    ru: '🛑 Остановить',
    ja: '🛑 停止',
    ko: '🛑 중지',
    zh: '🛑 停止',
    it: '🛑 Ferma',
  },
  loveStopped: {
    de: '🛑 Analyse abgebrochen. Die Liebe muss warten … bis zum nächsten Test!',
    en: '🛑 Analysis stopped. Love will have to wait … until the next test!',
    fr: '🛑 Analyse interrompue. L’amour devra attendre … jusqu’au prochain test !',
    es: '🛑 Análisis detenido. El amor tendrá que esperar… ¡hasta el próximo test!',
    pt: '🛑 Análise interrompida. O amor vai ter que esperar… até o próximo teste!',
    ru: '🛑 Анализ остановлен. Любви придётся подождать… до следующего теста!',
    ja: '🛑 分析を停止しました。愛は次のテストまで待つようです…',
    ko: '🛑 분석을 중지했어요. 사랑은 다음 테스트까지 기다려야 해요…',
    zh: '🛑 已停止分析。爱情只能等到下次测试了……',
    it: '🛑 Analisi interrotta. L’amore dovrà aspettare … fino al prossimo test!',
  },
  loveNoMore: {
    de: '📭 Es gibt keine weiteren Nachrichten zu durchsuchen – das war wirklich alles!',
    en: '📭 There are no more messages to search – that really was everything!',
    fr: '📭 Il n’y a plus de messages à parcourir – c’était vraiment tout !',
    es: '📭 No hay más mensajes que buscar: ¡eso era todo de verdad!',
    pt: '📭 Não há mais mensagens para pesquisar – era isso mesmo!',
    ru: '📭 Больше нечего искать – это действительно всё!',
    ja: '📭 検索するメッセージはもうありません – 本当に全部です！',
    ko: '📭 더 검색할 메시지가 없어요 – 정말 그게 전부예요!',
    zh: '📭 没有更多消息可搜索了——真的就这些了！',
    it: '📭 Non ci sono più messaggi da cercare – era davvero tutto!',
  },
  loveBusy: {
    de: '⏳ Die Analyse läuft bereits – bitte etwas Geduld, die Liebe braucht ihre Zeit!',
    en: '⏳ The analysis is already running – please be patient, love takes time!',
    fr: '⏳ L’analyse est déjà en cours – un peu de patience, l’amour prend du temps !',
    es: '⏳ El análisis ya está en curso: ¡ten paciencia, el amor necesita su tiempo!',
    pt: '⏳ A análise já está em andamento – paciência, o amor leva tempo!',
    ru: '⏳ Анализ уже идёт – наберись терпения, любовь требует времени!',
    ja: '⏳ 分析はすでに実行中です – 愛には時間がかかるので、お待ちください！',
    ko: '⏳ 분석이 이미 진행 중이에요 – 사랑에는 시간이 필요하니까 조금만 기다려 주세요!',
    zh: '⏳ 分析已在运行中——请耐心等待，爱情需要时间！',
    it: '⏳ L’analisi è già in corso – abbi pazienza, l’amore richiede tempo!',
  },

  // ------------------------------------------------------------
  // Hilfe & Profile (wie Birthday-/XP-Bot)
  // ------------------------------------------------------------
  helpTitle: {
    de: '💘 Love Tester – Hilfe',
    en: '💘 Love Tester – Help',
    fr: '💘 Love Tester – Aide',
    es: '💘 Love Tester – Ayuda',
    pt: '💘 Love Tester – Ajuda',
    ru: '💘 Love Tester – справка',
    ja: '💘 ラブテスター – ヘルプ',
    ko: '💘 러브 테스터 – 도움말',
    zh: '💘 恋爱测试仪 – 帮助',
    it: '💘 Love Tester – Aiuto',
  },
  helpDesc: {
    de: 'Der Love Tester schätzt die Liebe zwischen zwei Personen anhand eurer Chatverläufe – humorvoll, ungefährlich und mit 100 % mehr KI. 🤖💘',
    en: 'The Love Tester estimates the love between two people based on your chat logs – humorous, harmless and with 100% more AI. 🤖💘',
    fr: 'Le Love Tester estime l’amour entre deux personnes à partir de vos logs de chat – humoristique, inoffensif et avec 100 % d’IA en plus. 🤖💘',
    es: 'El Love Tester estima el amor entre dos personas a partir de vuestros chats: con humor, sin peligro y con un 100 % más de IA. 🤖💘',
    pt: 'O Love Tester estima o amor entre duas pessoas com base nos seus chats – com humor, sem perigo e com 100% mais IA. 🤖💘',
    ru: 'Love Tester оценивает любовь между двумя людьми по вашим логам чата – с юмором, безопасно и на 100 % больше ИИ. 🤖💘',
    ja: 'ラブテスターはチャットログから二人の愛を推定します – ユーモアたっぷり、安全、そしてAI 100%増し。🤖💘',
    ko: '러브 테스터는 채팅 로그를 바탕으로 두 사람 사이의 사랑을 추정해요 – 유머러스하고, 안전하고, AI가 100% 더 들어갔어요. 🤖💘',
    zh: '恋爱测试仪会根据你们的聊天记录估算两个人之间的爱情——幽默、无害，且 AI 含量增加 100%。🤖💘',
    it: 'Il Love Tester stima l’amore tra due persone basandosi sui vostri log di chat – umoristico, innocuo e con il 100% di IA in più. 🤖💘',
  },
  helpSetup: {
    de: 'Richtet den Bot ein: Sprache, Kanäle & Groq-API-Key (nur Admins, 3-Schritte-Assistent)',
    en: 'Sets up the bot: language, channels & Groq API key (admins only, 3-step wizard)',
    fr: 'Configure le bot : langue, salons et clé API Groq (admins uniquement, assistant en 3 étapes)',
    es: 'Configura el bot: idioma, canales y clave API de Groq (solo admins, asistente de 3 pasos)',
    pt: 'Configura o bot: idioma, canais e chave da API Groq (só admins, assistente de 3 etapas)',
    ru: 'Настраивает бота: язык, каналы и API-ключ Groq (только админы, мастер из 3 шагов)',
    ja: 'ボットを設定: 言語・チャンネル・Groq APIキー（管理者のみ、3ステップのウィザード）',
    ko: '봇을 설정해요: 언어, 채널, Groq API 키 (관리자 전용, 3단계 마법사)',
    zh: '设置机器人：语言、频道和 Groq API 密钥（仅限管理员，3 步向导）',
    it: 'Configura il bot: lingua, canali e chiave API Groq (solo admin, procedura in 3 passi)',
  },
  helpTestLove: {
    de: 'Startet einen Love-Test zwischen zwei Personen (mit Datenschutz-Bestätigung)',
    en: 'Starts a love test between two people (with privacy confirmation)',
    fr: 'Lance un love test entre deux personnes (avec confirmation de confidentialité)',
    es: 'Inicia un love test entre dos personas (con confirmación de privacidad)',
    pt: 'Inicia um teste de amor entre duas pessoas (com confirmação de privacidade)',
    ru: 'Запускает тест любви между двумя людьми (с подтверждением конфиденциальности)',
    ja: '二人の間のラブテストを開始（プライバシー確認付き）',
    ko: '두 사람 사이의 러브 테스트를 시작해요 (개인정보 확인 포함)',
    zh: '开始两个人之间的爱情测试（需隐私确认）',
    it: 'Avvia un love test tra due persone (con conferma sulla privacy)',
  },
  helpHelp: {
    de: 'Zeigt diese Übersicht',
    en: 'Shows this overview',
    fr: 'Affiche cet aperçu',
    es: 'Muestra esta vista general',
    pt: 'Mostra esta visão geral',
    ru: 'Показывает этот обзор',
    ja: 'この概要を表示',
    ko: '이 개요를 보여줘요',
    zh: '显示此概览',
    it: 'Mostra questa panoramica',
  },
  helpSetProfile: {
    de: 'Ändert das Profilbild des Bots auf diesem Server',
    en: 'Changes the bot’s profile picture on this server',
    fr: 'Change l’image de profil du bot sur ce serveur',
    es: 'Cambia la foto de perfil del bot en este servidor',
    pt: 'Altera a foto de perfil do bot neste servidor',
    ru: 'Меняет аватар бота на этом сервере',
    ja: 'このサーバーでのボットのプロフィール画像を変更',
    ko: '이 서버에서 봇의 프로필 사진을 변경해요',
    zh: '更改机器人在此服务器上的头像',
    it: 'Cambia l’immagine del profilo del bot su questo server',
  },
  helpAdminPanel: {
    de: 'Owner-Admin-Panel (nur im DM)',
    en: 'Owner admin panel (DM only)',
    fr: 'Panneau d’admin du propriétaire (MP uniquement)',
    es: 'Panel de administración del propietario (solo DM)',
    pt: 'Painel do administrador (somente DM)',
    ru: 'Панель администратора (только в ЛС)',
    ja: 'オーナー管理パネル（DM限定）',
    ko: '소유자 관리 패널 (DM 전용)',
    zh: '所有者管理面板（仅私信）',
    it: 'Pannello admin del proprietario (solo DM)',
  },
  testLoveUser1Desc: {
    de: 'Person 1 (der/die Erste)',
    en: 'Person 1 (the first one)',
    fr: 'Personne 1 (la première)',
    es: 'Persona 1 (la primera)',
    pt: 'Pessoa 1 (a primeira)',
    ru: 'Человек 1 (первый)',
    ja: '人物1（一人目）',
    ko: '사람 1 (첫 번째)',
    zh: '人物 1（第一位）',
    it: 'Persona 1 (la prima)',
  },
  testLoveUser2Desc: {
    de: 'Person 2 (die/der andere)',
    en: 'Person 2 (the other one)',
    fr: 'Personne 2 (l’autre)',
    es: 'Persona 2 (la otra)',
    pt: 'Pessoa 2 (a outra)',
    ru: 'Человек 2 (второй)',
    ja: '人物2（もう一人）',
    ko: '사람 2 (다른 한 명)',
    zh: '人物 2（另一位）',
    it: 'Persona 2 (l’altra)',
  },

  // ------------------------------------------------------------
  // Profile (identisch zu den anderen Bots)
  // ------------------------------------------------------------
  profileImageDesc: {
    de: 'Welches Bild soll verwendet werden?',
    en: 'Which image should be used?',
    fr: 'Quelle image doit être utilisée ?',
    es: '¿Qué imagen se debe usar?',
    pt: 'Qual imagem deve ser usada?',
    ru: 'Какое изображение использовать?',
    ja: 'どの画像を使いますか？',
    ko: '어떤 이미지를 사용할까요?',
    zh: '使用哪张图片？',
    it: 'Quale immagine deve essere usata?',
  },
  profileSet: {
    de: '🖼️ Profilbild geändert: {choice}',
    en: '🖼️ Profile picture changed: {choice}',
    fr: '🖼️ Image de profil modifiée : {choice}',
    es: '🖼️ Foto de perfil cambiada: {choice}',
    pt: '🖼️ Foto de perfil alterada: {choice}',
    ru: '🖼️ Аватар изменён: {choice}',
    ja: '🖼️ プロフィール画像を変更しました: {choice}',
    ko: '🖼️ 프로필 사진을 변경했어요: {choice}',
    zh: '🖼️ 头像已更改：{choice}',
    it: '🖼️ Immagine del profilo cambiata: {choice}',
  },
  profileChoiceStandard: {
    de: 'Standard-Profilbild',
    en: 'Standard profile picture',
    fr: 'Image de profil standard',
    es: 'Foto de perfil estándar',
    pt: 'Foto de perfil padrão',
    ru: 'Стандартный аватар',
    ja: '標準プロフィール画像',
    ko: '기본 프로필 사진',
    zh: '标准头像',
    it: 'Immagine del profilo standard',
  },
  profileChoiceServer: {
    de: 'Server-Profilbild',
    en: 'Server profile picture',
    fr: 'Image du serveur',
    es: 'Foto del servidor',
    pt: 'Foto do servidor',
    ru: 'Аватар сервера',
    ja: 'サーバーの画像',
    ko: '서버 사진',
    zh: '服务器头像',
    it: 'Immagine del server',
  },
  profileChoiceOwner: {
    de: 'Profilbild des Server-Owners',
    en: 'Server owner’s profile picture',
    fr: 'Image du propriétaire du serveur',
    es: 'Foto del propietario del servidor',
    pt: 'Foto do dono do servidor',
    ru: 'Аватар владельца сервера',
    ja: 'サーバー所有者の画像',
    ko: '서버 소유자 사진',
    zh: '服务器所有者头像',
    it: 'Immagine del proprietario del server',
  },
  errAvatar: {
    de: '⛔ Das Profilbild konnte nicht geändert werden: {error}',
    en: '⛔ Couldn’t change the profile picture: {error}',
    fr: '⛔ Impossible de modifier l’image de profil : {error}',
    es: '⛔ No se pudo cambiar la foto de perfil: {error}',
    pt: '⛔ Não foi possível alterar a foto de perfil: {error}',
    ru: '⛔ Не удалось изменить аватар: {error}',
    ja: '⛔ プロフィール画像を変更できませんでした: {error}',
    ko: '⛔ 프로필 사진을 변경하지 못했어요: {error}',
    zh: '⛔ 无法更改头像：{error}',
    it: '⛔ Impossibile cambiare l’immagine del profilo: {error}',
  },
  errAvatarPerms: {
    de: '⛔ Dem Bot fehlt die Berechtigung „Nickname ändern“. Gib dem Bot diese Berechtigung (oder Administrator-Rechte) und versuche es dann erneut.',
    en: '⛔ The bot is missing the “Change Nickname” permission. Grant that permission (or Administrator) to the bot, then try again.',
    fr: '⛔ Il manque au bot la permission « Changer le pseudo ». Accordez-lui cette permission (ou Administrateur), puis réessayez.',
    es: '⛔ Al bot le falta el permiso «Cambiar apodo». Concédele ese permiso (o Administrador) e inténtalo de nuevo.',
    pt: '⛔ O bot não tem a permissão «Alterar apelido». Conceda-lhe essa permissão (ou Administrador) e tente novamente.',
    ru: '⛔ У бота нет права «Изменить никнейм». Дайте боту это право (или «Администратор») и повторите попытку.',
    ja: '⛔ ボットに「ニックネームの変更」権限がありません。この権限（または管理者）を付与してから、もう一度お試しください。',
    ko: '⛔ 봇에게 \"닉네임 변경하기\" 권한이 없어요. 해당 권한(또는 관리자)을 부여한 뒤 다시 시도해 주세요.',
    zh: '⛔ 机器人缺少“更改昵称”权限。请为机器人授予该权限（或管理员权限）后重试。',
    it: '⛔ Al bot manca l’autorizzazione «Cambia nickname». Concedigliela (o Amministratore) e riprova.',
  },
  errServerNoIcon: {
    de: '⛔ Dieser Server hat kein eigenes Profilbild.',
    en: '⛔ This server has no profile picture of its own.',
    fr: '⛔ Ce serveur n’a pas d’image de profil.',
    es: '⛔ Este servidor no tiene foto de perfil propia.',
    pt: '⛔ Este servidor não tem foto de perfil própria.',
    ru: '⛔ У этого сервера нет собственного аватара.',
    ja: '⛔ このサーバーにはプロフィール画像がありません。',
    ko: '⛔ 이 서버에는 프로필 사진이 없어요.',
    zh: '⛔ 此服务器没有自己的头像。',
    it: '⛔ Questo server non ha un’immagine del profilo.',
  },

  // ------------------------------------------------------------
  // Allgemeine Fehler
  // ------------------------------------------------------------
  errGuildOnly: {
    de: '⛔ Dieser Befehl funktioniert nur auf einem Server.',
    en: '⛔ This command only works on a server.',
    fr: '⛔ Cette commande ne fonctionne que sur un serveur.',
    es: '⛔ Este comando solo funciona en un servidor.',
    pt: '⛔ Este comando só funciona em um servidor.',
    ru: '⛔ Эта команда работает только на сервере.',
    ja: '⛔ このコマンドはサーバーでのみ使用できます。',
    ko: '⛔ 이 명령어는 서버에서만 사용할 수 있어요.',
    zh: '⛔ 此命令只能在服务器上使用。',
    it: '⛔ Questo comando funziona solo su un server.',
  },
  errNoPermission: {
    de: '⛔ Dafür brauchst du **Administrator**-Rechte!',
    en: '⛔ You need **Administrator** permissions for that!',
    fr: '⛔ Tu as besoin des droits **Administrateur** pour ça !',
    es: '⛔ ¡Necesitas permisos de **Administrador** para eso!',
    pt: '⛔ Você precisa de permissão de **Administrador** para isso!',
    ru: '⛔ Для этого нужны права **администратора**!',
    ja: '⛔ それには**管理者**権限が必要です！',
    ko: '⛔ 그러려면 **관리자** 권한이 필요해요!',
    zh: '⛔ 这需要**管理员**权限！',
    it: '⛔ Servono i permessi di **amministratore** per farlo!',
  },
  errBotPerms: {
    de: '⛔ Der Bot hat in {channel} nicht genug Rechte (Nachrichten lesen/senden). Bitte Berechtigungen prüfen!',
    en: '⛔ The bot doesn’t have enough permissions in {channel} (read/send messages). Please check permissions!',
    fr: '⛔ Le bot n’a pas assez de droits dans {channel} (lire/envoyer des messages). Vérifie les permissions !',
    es: '⛔ El bot no tiene suficientes permisos en {channel} (leer/enviar mensajes). ¡Revisa los permisos!',
    pt: '⛔ O bot não tem permissões suficientes em {channel} (ler/enviar mensagens). Verifique as permissões!',
    ru: '⛔ У бота недостаточно прав в {channel} (читать/отправлять сообщения). Проверьте права!',
    ja: '⛔ {channel} でボットに十分な権限がありません（メッセージの読み取り/送信）。権限を確認してください！',
    ko: '⛔ {channel}에서 봇에게 충분한 권한이 없어요 (메시지 읽기/보내기). 권한을 확인해 주세요!',
    zh: '⛔ 机器人在 {channel} 中没有足够的权限（读取/发送消息）。请检查权限！',
    it: '⛔ Il bot non ha abbastanza permessi in {channel} (leggere/inviare messaggi). Controlla i permessi!',
  },
  errChannelBad: {
    de: '⛔ Das ist kein gültiger Textkanal.',
    en: '⛔ That is not a valid text channel.',
    fr: '⛔ Ce n’est pas un salon textuel valide.',
    es: '⛔ Eso no es un canal de texto válido.',
    pt: '⛔ Isso não é um canal de texto válido.',
    ru: '⛔ Это не действующий текстовый канал.',
    ja: '⛔ 有効なテキストチャンネルではありません。',
    ko: '⛔ 유효한 텍스트 채널이 아니에요.',
    zh: '⛔ 这不是有效的文字频道。',
    it: '⛔ Non è un canale testuale valido.',
  },
  errDmOnly: {
    de: '⛔ Das Admin-Panel funktioniert nur im Privatchat!',
    en: '⛔ The admin panel only works in DMs!',
    fr: '⛔ Le panneau d’admin ne fonctionne qu’en MP !',
    es: '⛔ ¡El panel de administración solo funciona en privado!',
    pt: '⛔ O painel de administração só funciona no privado!',
    ru: '⛔ Панель администратора работает только в личке!',
    ja: '⛔ 管理パネルはDMでのみ動作します！',
    ko: '⛔ 관리 패널은 DM에서만 작동해요!',
    zh: '⛔ 管理面板仅可在私信中运行！',
    it: '⛔ Il pannello admin funziona solo in privato!',
  },
  errOwnerOnly: {
    de: '⛔ Das darf nur der Bot-Owner!',
    en: '⛔ Only the bot owner may do that!',
    fr: '⛔ Seul le propriétaire du bot peut faire ça !',
    es: '⛔ ¡Solo el propietario del bot puede hacer eso!',
    pt: '⛔ Só o dono do bot pode fazer isso!',
    ru: '⛔ Это может делать только владелец бота!',
    ja: '⛔ それはボット所有者だけができます！',
    ko: '⛔ 그건 봇 소유자만 할 수 있어요!',
    zh: '⛔ 只有机器人所有者才能这样做！',
    it: '⛔ Solo il proprietario del bot può farlo!',
  },

  // ------------------------------------------------------------
  // Owner-Admin-Panel (bewusst nur Deutsch, wie bei den anderen Bots)
  // ------------------------------------------------------------
  apTitle: { de: '🛠️ Admin Panel – Love Tester' },
  apServerListDesc: {
    de: 'Wähle einen Server aus, um Details zu sehen:\n\n{list}',
  },
  apNoServers: { de: '😢 Der Love Tester ist noch auf keinem Server. Zeit, Freunde einzuladen!' },
  apPage: { de: 'Seite {page} von {total}' },
  apSelectPlaceholder: { de: 'Server auswählen …' },
  apSelectLabel: { de: 'Server wählen' },
  apDetailTitle: { de: '🗂️ Server-Übersicht – Love Tester' },
  apDetailOwner: { de: '👑 **Owner:** {mention}' },
  apDetailName: { de: '🏷️ **Name:** {name}' },
  apDetailMembers: { de: '👥 **Mitglieder:** {count}' },
  apDetailSetup: { de: '💘 **Love-Setup:** {status}' },
  apDetailChannels: { de: '📂 **Kanäle:** {count}' },
  apSetupYes: { de: '✅ Eingerichtet' },
  apSetupNo: { de: '❌ Nicht eingerichtet' },
  apBtnBack: { de: '◀ Zurück' },
  apBtnInvite: { de: '🔗 Einladung' },
  apBtnLeave: { de: '🚪 Verlassen' },
  apBtnRefresh: { de: '🔄 Aktualisieren' },
  apBtnPrev: { de: '◀' },
  apBtnNext: { de: '▶' },
  apLeaveAsk: { de: 'Sicher, dass der Love Tester **{name}** verlassen soll? Klicke erneut auf **Wirklich verlassen**.' },
  apBtnLeaveConfirm: { de: '🚪 Wirklich verlassen' },
  apBtnLeaveCancel: { de: '↩️ Abbrechen' },
  apInviteSent: { de: '🔗 Einladung erstellt – gültig **1 Stunde**, **1× nutzbar**!' },
  apInviteLink: { de: '**Einladungslink:** {url}' },
  apInviteFailed: { de: '⛔ Konnte keine Einladung erstellen: {error}' },
  apLeft: { de: '✅ Der Love Tester hat **{name}** verlassen.' },
  apJoinNotice: {
    de: '👋 **Neuer Love-Tester-Server!**\n\n🏷️ **{name}**\n👥 **{members}** Mitglieder\n👑 **Owner:** {owner}\n\nSchau mal ins **/adminpanel** – da kannst du alles verwalten! 🛠️',
  },
  apInvalidGuild: { de: '⛔ Diesen Server konnte ich nicht finden.' },
  apNeedDm: { de: '⛔ Das Love-Tester-Admin-Panel funktioniert nur im Privatchat mit dem Bot-Owner!' },
};

function t(key, lang, vars = {}) {
  const entry = T[key];
  if (!entry) return `??${key}??`;
  let text = entry[lang] || entry.de || '';
  for (const [k, v] of Object.entries(vars)) {
    text = text.split(`{${k}}`).join(String(v));
  }
  return text;
}

function tzOf(code) {
  const override = process.env[`LOVE_BOT_TZ_${String(code).toUpperCase()}`];
  return override || (LANGS[code] && LANGS[code].tz) || 'Europe/Berlin';
}

const DISCORD_LOCALE = {
  de: 'de',
  en: 'en-US',
  fr: 'fr',
  es: 'es-ES',
  pt: 'pt-BR',
  ru: 'ru',
  ja: 'ja',
  ko: 'ko',
  zh: 'zh-CN',
  it: 'it',
};

const DISCORD_LOCALE_MAP = {
  de: 'de',
  'en-US': 'en',
  'en-GB': 'en',
  fr: 'fr',
  'es-ES': 'es',
  'pt-BR': 'pt',
  'pt-PT': 'pt',
  ru: 'ru',
  ja: 'ja',
  ko: 'ko',
  'zh-CN': 'zh',
  'zh-TW': 'zh',
  it: 'it',
};

function langFromDiscord(locale) {
  return DISCORD_LOCALE_MAP[locale] || 'en';
}

module.exports = { LANGS, T, t, tzOf, langFromDiscord, DISCORD_LOCALE };
