/**
 * ============================================================================
 *  🛡️ Security Bot – Sprachdatei (10 Sprachen)
 *
 *  Unterstützte Sprachen:
 *  - de (Deutsch)
 *  - en (English)
 *  - fr (Français)
 *  - es (Español)
 *  - pt (Português - BR)
 *  - ru (Русский)
 *  - ja (日本語)
 *  - ko (한국어)
 *  - zh (中文 - CN)
 *  - it (Italiano)
 * ============================================================================
 */

const LANGS = {
  de: {
    name: 'Deutsch',
    names: { de: 'Deutsch', en: 'German', fr: 'Allemand', es: 'Alemán', pt: 'Alemão', ru: 'Немецкий', ja: 'ドイツ語', ko: '독일어', zh: '德语', it: 'Tedesco' },
    flag: '🇩🇪',
    locale: 'de-DE',
    tz: 'Europe/Berlin',
  },
  en: {
    name: 'English',
    names: { de: 'Englisch', en: 'English', fr: 'Anglais', es: 'Inglés', pt: 'Inglês', ru: 'Английский', ja: '英語', ko: '영어', zh: '英语', it: 'Inglese' },
    flag: '🇬🇧',
    locale: 'en-US',
    tz: 'America/New_York',
  },
  fr: {
    name: 'Français',
    names: { de: 'Französisch', en: 'French', fr: 'Français', es: 'Francés', pt: 'Francês', ru: 'Французский', ja: 'フランス語', ko: '프랑스어', zh: '法语', it: 'Francese' },
    flag: '🇫🇷',
    locale: 'fr-FR',
    tz: 'Europe/Paris',
  },
  es: {
    name: 'Español',
    names: { de: 'Spanisch', en: 'Spanish', fr: 'Espagnol', es: 'Español', pt: 'Espanhol', ru: 'Испанский', ja: 'スペイン語', ko: '스페인어', zh: '西班牙语', it: 'Spagnolo' },
    flag: '🇪🇸',
    locale: 'es-ES',
    tz: 'Europe/Madrid',
  },
  pt: {
    name: 'Português',
    names: { de: 'Portugiesisch', en: 'Portuguese', fr: 'Portugais', es: 'Portugués', pt: 'Português', ru: 'Португальский', ja: 'ポルトガル語', ko: '포르투갈어', zh: '葡萄牙语', it: 'Portoghese' },
    flag: '🇧🇷',
    locale: 'pt-BR',
    tz: 'America/Sao_Paulo',
  },
  ru: {
    name: 'Русский',
    names: { de: 'Russisch', en: 'Russian', fr: 'Russe', es: 'Ruso', pt: 'Russo', ru: 'Русский', ja: 'ロシア語', ko: '러시아어', zh: '俄语', it: 'Russo' },
    flag: '🇷🇺',
    locale: 'ru-RU',
    tz: 'Europe/Moscow',
  },
  ja: {
    name: '日本語',
    names: { de: 'Japanisch', en: 'Japanese', fr: 'Japonais', es: 'Japonés', pt: 'Japonês', ru: 'Японский', ja: '日本語', ko: '일본어', zh: '日语', it: 'Giapponese' },
    flag: '🇯🇵',
    locale: 'ja-JP',
    tz: 'Asia/Tokyo',
  },
  ko: {
    name: '한국어',
    names: { de: 'Koreanisch', en: 'Korean', fr: 'Coréen', es: 'Coreano', pt: 'Coreano', ru: 'Корейский', ja: '韓国語', ko: '한국어', zh: '韩语', it: 'Coreano' },
    flag: '🇰🇷',
    locale: 'ko-KR',
    tz: 'Asia/Seoul',
  },
  zh: {
    name: '中文',
    names: { de: 'Chinesisch', en: 'Chinese', fr: 'Chinois', es: 'Chino', pt: 'Chinês', ru: 'Китайский', ja: '中国語', ko: '중국어', zh: '中文', it: 'Cinese' },
    flag: '🇨🇳',
    locale: 'zh-CN',
    tz: 'Asia/Shanghai',
  },
  it: {
    name: 'Italiano',
    names: { de: 'Italienisch', en: 'Italian', fr: 'Italien', es: 'Italiano', pt: 'Italiano', ru: 'Итальянский', ja: 'イタリア語', ko: '이탈리아어', zh: '意大利语', it: 'Italiano' },
    flag: '🇮🇹',
    locale: 'it-IT',
    tz: 'Europe/Rome',
  },
};

const DISCORD_LOCALE = {
  de: 'de',
  en: 'en-US',
  fr: 'fr',
  es: 'es-ES',
  pt: 'pt-BR',
  ru: 'ru',
  ja: 'ja',
  ko: 'ko',
  zh: 'zh-CN',
  it: 'it',
};

const DISCORD_LOCALE_MAP = {
  de: 'de',
  'en-US': 'en',
  'en-GB': 'en',
  fr: 'fr',
  'es-ES': 'es',
  'pt-BR': 'pt',
  'pt-PT': 'pt',
  ru: 'ru',
  ja: 'ja',
  ko: 'ko',
  'zh-CN': 'zh',
  'zh-TW': 'zh',
  it: 'it',
};

function langFromDiscord(locale) {
  return DISCORD_LOCALE_MAP[locale] || 'en';
}

function tzOf(lang) {
  return LANGS[lang]?.tz || 'Europe/Berlin';
}

const T = {
  // Help & Info
  helpTitle: {
    de: '🛡️ Sicherheits-Bot – Befehlsübersicht',
    en: '🛡️ Security Bot – Commands Overview',
    fr: '🛡️ Bot de Sécurité – Aperçu des commandes',
    es: '🛡️ Bot de Seguridad – Resumen de comandos',
    pt: '🛡️ Bot de Segurança – Visão geral de comandos',
    ru: '🛡️ Бот Безопасности – Обзор команд',
    ja: '🛡️ セキュリティボット – コマンド一覧',
    ko: '🛡️ 보안 봇 – 명령어 안내',
    zh: '🛡️ 安全机器人 – 命令概览',
    it: '🛡️ Bot di Sicurezza – Panoramica comandi',
  },
  helpDesc: {
    de: 'Automatischer Schutz mit KI-Moderation von OpenAI. Überwacht Text- und Bildnachrichten in Echtzeit.',
    en: 'Automated protection powered by OpenAI AI moderation. Monitors text and image messages in real-time.',
    fr: 'Protection automatique avec modération IA OpenAI. Surveille les messages texte et image en temps réel.',
    es: 'Protección automática con moderación IA de OpenAI. Monitorea mensajes de texto e imágenes en tiempo real.',
    pt: 'Proteção automática com moderação por IA da OpenAI. Monitora mensagens de texto e imagens em tempo real.',
    ru: 'Автоматическая защита на базе ИИ-модерации OpenAI. Мониторинг текста и изображений в реальном времени.',
    ja: 'OpenAI AIモデレーションによる自動保護。テキストおよび画像メッセージをリアルタイムで監視します。',
    ko: 'OpenAI AI 검열 기반 자동 보호. 텍스트 및 이미지 메시지를 실시간으로 모니터링합니다.',
    zh: '基于 OpenAI AI 审核的自动防护系统。实时监控文本与图片消息。',
    it: 'Protezione automatica basata sulla moderazione AI di OpenAI. Monitora testi e immagini in tempo reale.',
  },
  helpSetApiKey: {
    de: 'OpenAI Moderation API Key für diesen Server hinterlegen (nur Admins)',
    en: 'Set OpenAI Moderation API Key for this server (Admins only)',
    fr: 'Définir la clé API de modération OpenAI pour ce serveur (Admins uniquement)',
    es: 'Establecer la clave API de moderación de OpenAI para este servidor (Solo admins)',
    pt: 'Definir a chave de API de moderação da OpenAI para este servidor (Apenas admins)',
    ru: 'Установить ключ OpenAI Moderation API для этого сервера (только админы)',
    ja: 'このサーバー用のOpenAIモデレーションAPIキーを設定（管理者のみ）',
    ko: '이 서버의 OpenAI 검열 API 키 설정 (관리자 전용)',
    zh: '设置此服务器的 OpenAI 审核 API 密钥（仅限管理员）',
    it: 'Imposta la chiave API di moderazione OpenAI per questo server (Solo admin)',
  },
  helpSetLanguage: {
    de: 'Ändert die Sprache des Sicherheitsbots dauerhaft (nur Admins)',
    en: 'Permanently changes the security bot language (Admins only)',
    fr: 'Modifie définitivement la langue du bot de sécurité (Admins uniquement)',
    es: 'Cambia permanentemente el idioma del bot de seguridad (Solo admins)',
    pt: 'Altera permanentemente o idioma do bot de segurança (Apenas admins)',
    ru: 'Навсегда изменить язык бота безопасности на сервере (только админы)',
    ja: 'セキュリティボットの言語を恒久的に変更（管理者のみ）',
    ko: '보안 봇의 언어를 영구 변경 (관리자 전용)',
    zh: '永久更改安全机器人的语言（仅限管理员）',
    it: 'Modifica definitivamente la lingua del bot di sicurezza (Solo admin)',
  },
  helpSetSensitivity: {
    de: 'Schutzlevel & Strenge der Filter anpassen (nur Admins)',
    en: 'Adjust filter sensitivity & protection level (Admins only)',
    fr: 'Ajuster la sensibilité et le niveau de protection (Admins uniquement)',
    es: 'Ajustar la sensibilidad y el nivel de protección (Solo admins)',
    pt: 'Ajustar a sensibilidade e o nível de proteção (Apenas admins)',
    ru: 'Настроить строгость и уровень защиты фильтров (только админы)',
    ja: 'フィルターの感度と保護レベルを設定（管理者のみ）',
    ko: '필터 민감도 및 보호 수준 설정 (관리자 전용)',
    zh: '调整过滤灵敏度与防护级别（仅限管理员）',
    it: 'Regola la sensibilità e il livello di protezione dei filtri (Solo admin)',
  },
  helpConfigureRules: {
    de: 'Interaktive Konfiguration für Kategorien & Auto-Löschen (nur Admins)',
    en: 'Interactive configuration for categories & auto-delete (Admins only)',
    fr: 'Configuration interactive des catégories et suppression auto (Admins uniquement)',
    es: 'Configuración interactiva de categorías y borrado automático (Solo admins)',
    pt: 'Configuração interativa de categorias e auto-exclusão (Apenas admins)',
    ru: 'Интерактивная настройка категорий и авто-удаления (только админы)',
    ja: 'カテゴリと自動削除のインタラクティブ設定（管理者のみ）',
    ko: '카테고리 및 자동 삭제 대화형 설정 (관리자 전용)',
    zh: '分类与自动删除的交互式配置面板（仅限管理员）',
    it: 'Configurazione interattiva di categorie ed eliminazione automatica (Solo admin)',
  },
  helpSetWarnings: {
    de: 'Verwarnungsstufen, Timeouts & Verfallszeit konfigurieren (nur Admins)',
    en: 'Configure warning tiers, timeouts & expiration time (Admins only)',
    fr: 'Configurer les avertissements, timeouts et durées (Admins uniquement)',
    es: 'Configurar niveles de advertencia, timeouts y vencimiento (Solo admins)',
    pt: 'Configurar níveis de aviso, timeouts e expiração (Apenas admins)',
    ru: 'Настроить уровни предупреждений, таймауты и срок действия (только админы)',
    ja: '警告レベル、タイムアウト、有効期限を設定（管理者のみ）',
    ko: '경고 단계, 타임아웃 및 만료 기간 설정 (관리자 전용)',
    zh: '配置警告级别、禁言时长及过期时间（仅限管理员）',
    it: 'Configura livelli di avviso, timeout e scadenza (Solo admin)',
  },
  helpStatus: {
    de: 'Zeigt deine aktiven Verwarnungen und deinen Sicherheitsstatus',
    en: 'Shows your active warnings and security status',
    fr: 'Affiche vos avertissements actifs et votre statut de sécurité',
    es: 'Muestra tus advertencias activas y tu estado de seguridad',
    pt: 'Mostra seus avisos ativos e seu status de segurança',
    ru: 'Показывает ваши активные предупреждения и статус безопасности',
    ja: 'あなたのアクティブな警告とセキュリティステータスを表示',
    ko: '내 활성 경고 및 보안 상태 확인',
    zh: '查看您的当前活跃警告及安全状态',
    it: 'Mostra i tuoi avvisi attivi e lo stato di sicurezza',
  },
  helpManageUser: {
    de: 'Status eines Nutzers einsehen und Verwarnungen löschen (nur Admins)',
    en: 'Inspect a user\'s status and remove warnings (Admins only)',
    fr: 'Inspecter le statut d\'un membre et supprimer des avertissements (Admins uniquement)',
    es: 'Inspeccionar el estado de un usuario y borrar advertencias (Solo admins)',
    pt: 'Verificar status de um usuário e remover avisos (Apenas admins)',
    ru: 'Просмотр статуса пользователя и удаление предупреждений (только админы)',
    ja: 'ユーザーのステータス確認と警告の削除（管理者のみ）',
    ko: '특정 유저 상태 확인 및 경고 삭제 (관리자 전용)',
    zh: '查看指定用户状态并清除误判警告（仅限管理员）',
    it: 'Controlla lo stato di un utente e rimuovi gli avvisi (Solo admin)',
  },
  helpTestText: {
    de: 'Überprüft Text mit OpenAI Moderation auf Regelverstöße (nur Admins)',
    en: 'Tests text with OpenAI Moderation for rule violations (Admins only)',
    fr: 'Teste un texte avec la modération OpenAI (Admins uniquement)',
    es: 'Prueba texto con la moderación de OpenAI (Solo admins)',
    pt: 'Testa texto com a moderação da OpenAI (Apenas admins)',
    ru: 'Проверка текста через OpenAI Moderation на нарушения (только админы)',
    ja: 'テキストのOpenAIモデレーション判定をテスト（管理者のみ）',
    ko: 'OpenAI 검열로 텍스트 위반 여부 테스트 (관리자 전용)',
    zh: '使用 OpenAI 审核测试文本违规程度（仅限管理员）',
    it: 'Verifica un testo con la moderazione OpenAI (Solo admin)',
  },
  helpSetProfile: {
    de: 'Ändert das Server-Profilbild des Sicherheitsbots (nur Admins)',
    en: 'Changes the server avatar of the security bot (Admins only)',
    fr: 'Change l\'avatar du bot de sécurité sur ce serveur (Admins uniquement)',
    es: 'Cambia el avatar del bot de seguridad en el servidor (Solo admins)',
    pt: 'Altera o avatar do bot de segurança neste servidor (Apenas admins)',
    ru: 'Изменить серверный аватар бота безопасности (только админы)',
    ja: 'セキュリティボットのサーバープロフィール画像を変更（管理者のみ）',
    ko: '보안 봇의 서버 프로필 사진 변경 (관리자 전용)',
    zh: '更改安全机器人在本服务器的头像（仅限管理员）',
    it: 'Modifica l\'immagine profilo del bot sul server (Solo admin)',
  },
  helpHelp: {
    de: 'Zeigt alle Befehle und Funktionen des Sicherheitsbots',
    en: 'Shows all commands and features of the security bot',
    fr: 'Affiche toutes les commandes et fonctionnalités du bot',
    es: 'Muestra todos los comandos y funciones del bot de seguridad',
    pt: 'Mostra todos os comandos e recursos do bot de segurança',
    ru: 'Показывает все команды и функции бота безопасности',
    ja: 'セキュリティボットの全コマンドと機能を表示',
    ko: '보안 봇의 모든 명령어 및 기능 표시',
    zh: '显示安全机器人的所有命令及功能',
    it: 'Mostra tutti i comandi e le funzionalità del bot',
  },
  helpAdminPanel: {
    de: 'Owner-Admin-Panel im Bot-Privatchat',
    en: 'Owner Admin Panel in Bot DM',
    fr: 'Panneau d\'administration dans les messages privés du bot',
    es: 'Panel de administración del propietario en MD del bot',
    pt: 'Painel de administração do dono no privado do bot',
    ru: 'Панель владельца в личных сообщениях с ботом',
    ja: 'ボットのDMでのオーナー管理パネル',
    ko: '봇 DM의 소유자 전용 관리 패널',
    zh: '机器人私信中的所有者管理面板',
    it: 'Pannello di amministrazione proprietario nei DM del bot',
  },

  // Category Names
  cat_hate: {
    de: 'Hassrede & Diskriminierung',
    en: 'Hate Speech & Discrimination',
    fr: 'Discours de haine et discrimination',
    es: 'Discurso de odio y discriminación',
    pt: 'Discurso de ódio e discriminação',
    ru: 'Язык вражды и дискриминация',
    ja: 'ヘイトスピーチ・差別',
    ko: '증오 발언 및 차별',
    zh: '仇恨言论与歧视',
    it: 'Incitamento all\'odio e discriminazione',
  },
  cat_hate_threatening: {
    de: 'Bedrohliche Hassrede',
    en: 'Threatening Hate Speech',
    fr: 'Discours de haine menaçant',
    es: 'Discurso de odio amenazante',
    pt: 'Discurso de ódio com ameaças',
    ru: 'Угрожающий язык вражды',
    ja: '脅迫的ヘイトスピーチ',
    ko: '위협적 증오 발언',
    zh: '威胁性仇恨言论',
    it: 'Incitamento all\'odio minaccioso',
  },
  cat_harassment: {
    de: 'Belästigung, Beleidigung & Toxizität',
    en: 'Harassment, Insults & Toxicity',
    fr: 'Harcèlement, insultes et toxicité',
    es: 'Acoso, insultos y toxicidad',
    pt: 'Assédio, ofensas e toxicidade',
    ru: 'Домогательства, оскорбления и токсичность',
    ja: '嫌がらせ・侮辱・有害性',
    ko: '괴롭힘, 모욕 및 악성 행위',
    zh: '骚扰、辱骂与不良言论',
    it: 'Molestie, insulti e tossicità',
  },
  cat_harassment_threatening: {
    de: 'Bedrohung & schwere Belästigung',
    en: 'Threatening Harassment',
    fr: 'Harcèlement avec menaces',
    es: 'Acoso con amenazas',
    pt: 'Assédio com ameaças graves',
    ru: 'Угрозы и преследование',
    ja: '脅迫的嫌がらせ',
    ko: '위협적 괴롭힘',
    zh: '威胁性骚扰',
    it: 'Molestie con minacce',
  },
  cat_violence: {
    de: 'Gewalt & Gewaltverherrlichung',
    en: 'Violence & Glorification of Violence',
    fr: 'Violence et glorification de la violence',
    es: 'Violencia y apología de la violencia',
    pt: 'Violência e apologia à violência',
    ru: 'Насилие и пропаганда насилия',
    ja: '暴力・暴力の美化',
    ko: '폭력 및 폭력 미화',
    zh: '暴力与宣扬暴力',
    it: 'Violenza ed esaltazione della violenza',
  },
  cat_violence_graphic: {
    de: 'Grausame & explizite Gewalt',
    en: 'Graphic & Explicit Violence',
    fr: 'Violence explicite et gore',
    es: 'Violencia gráfica y explícita',
    pt: 'Violência gráfica e explícita',
    ru: 'Жестокое и графическое насилие',
    ja: '生々しい・過激な暴力',
    ko: '노골적이고 끔찍한 폭력',
    zh: '血腥与露骨暴力',
    it: 'Violenza grafica ed esplicita',
  },
  cat_self_harm: {
    de: 'Selbstverletzung & Suizid',
    en: 'Self-Harm & Suicide',
    fr: 'Automutilation et suicide',
    es: 'Autolesión y suicidio',
    pt: 'Automutilação e suicídio',
    ru: 'Самоповреждение и суицид',
    ja: '自傷行為・自殺',
    ko: '자해 및 극단적 선택',
    zh: '自残与自杀',
    it: 'Autolesionismo e suicidio',
  },
  cat_self_harm_intent: {
    de: 'Selbstverletzungsabsicht',
    en: 'Self-Harm Intent',
    fr: 'Intention d\'automutilation',
    es: 'Intención de autolesión',
    pt: 'Intenção de automutilação',
    ru: 'Намерения самоповреждения',
    ja: '自傷行為の意図',
    ko: '자해 의도',
    zh: '自残意图',
    it: 'Intento di autolesionismo',
  },
  cat_self_harm_instructions: {
    de: 'Anleitungen zur Selbstverletzung',
    en: 'Self-Harm Instructions',
    fr: 'Instructions d\'automutilation',
    es: 'Instrucciones de autolesión',
    pt: 'Instruções de automutilação',
    ru: 'Инструкции по самоповреждению',
    ja: '自傷行為の指示',
    ko: '자해 방법 안내',
    zh: '自残指导',
    it: 'Istruzioni per autolesionismo',
  },
  cat_sexual: {
    de: 'Sexuelle & NSFW Inhalte',
    en: 'Sexual & NSFW Content',
    fr: 'Contenu sexuel et NSFW',
    es: 'Contenido sexual y NSFW',
    pt: 'Conteúdo sexual e NSFW',
    ru: 'Сексуальный и NSFW контент',
    ja: '性的・NSFWコンテンツ',
    ko: '성적 및 NSFW 콘텐츠',
    zh: '色情与 NSFW 内容',
    it: 'Contenuti sessuali e NSFW',
  },
  cat_sexual_minors: {
    de: 'Sexuelle Inhalte mit Minderjährigen (CSAM)',
    en: 'Sexual Content Involving Minors (CSAM)',
    fr: 'Contenu sexuel impliquant des mineurs (CSAM)',
    es: 'Contenido sexual con menores (CSAM)',
    pt: 'Conteúdo sexual envolvendo menores (CSAM)',
    ru: 'Сексуальный контент с несовершеннолетними (CSAM)',
    ja: '未成年者に関する性的コンテンツ (CSAM)',
    ko: '미성년자 관련 성적 콘텐츠 (CSAM)',
    zh: '涉及未成年人的色情内容 (CSAM)',
    it: 'Contenuti sessuali su minori (CSAM)',
  },
  cat_illicit: {
    de: 'Illegale Aktivitäten & Drogen',
    en: 'Illicit Activities & Drugs',
    fr: 'Activités illicites et drogues',
    es: 'Actividades ilícitas y drogas',
    pt: 'Atividades ilícitas e drogas',
    ru: 'Незаконная деятельность и наркотики',
    ja: '違法行為・薬物',
    ko: '불법 활동 및 마약',
    zh: '违法活动与毒品',
    it: 'Attività illecite e droghe',
  },
  cat_illicit_violent: {
    de: 'Illegale Gewalt & Waffen',
    en: 'Illicit Violent Acts & Weapons',
    fr: 'Actes violents illicites et armes',
    es: 'Actos violentos ilícitos y armas',
    pt: 'Atos violentos ilícitos e armas',
    ru: 'Незаконное насилие и оружие',
    ja: '違法な暴力行為・武器',
    ko: '불법 폭력 행위 및 무기',
    zh: '违法暴力行为与武器',
    it: 'Atti violenti illeciti e armi',
  },

  // Actions
  action_warn: {
    de: '⚠️ Verwarnung erteilt',
    en: '⚠️ Warning issued',
    fr: '⚠️ Avertissement émis',
    es: '⚠️ Advertencia emitida',
    pt: '⚠️ Aviso emitido',
    ru: '⚠️ Вынесено предупреждение',
    ja: '⚠️ 警告を発行',
    ko: '⚠️ 경고 부여',
    zh: '⚠️ 已发出警告',
    it: '⚠️ Avviso emesso',
  },
  action_timeout_60s: {
    de: '⏱️ 1 Minute Timeout',
    en: '⏱️ 1 minute timeout',
    fr: '⏱️ Timeout de 1 minute',
    es: '⏱️ Timeout de 1 minuto',
    pt: '⏱️ Timeout de 1 minuto',
    ru: '⏱️ Таймаут на 1 минуту',
    ja: '⏱️ 1分間のタイムアウト',
    ko: '⏱️ 1분 타임아웃',
    zh: '⏱️ 禁言 1 分钟',
    it: '⏱️ Timeout di 1 minuto',
  },
  action_timeout_300s: {
    de: '⏱️ 5 Minuten Timeout',
    en: '⏱️ 5 minutes timeout',
    fr: '⏱️ Timeout de 5 minutes',
    es: '⏱️ Timeout de 5 minutos',
    pt: '⏱️ Timeout de 5 minutos',
    ru: '⏱️ Таймаут на 5 минут',
    ja: '⏱️ 5分間のタイムアウト',
    ko: '⏱️ 5분 타임아웃',
    zh: '⏱️ 禁言 5 分钟',
    it: '⏱️ Timeout di 5 minuti',
  },
  action_timeout_600s: {
    de: '⏱️ 10 Minuten Timeout',
    en: '⏱️ 10 minutes timeout',
    fr: '⏱️ Timeout de 10 minutes',
    es: '⏱️ Timeout de 10 minutos',
    pt: '⏱️ Timeout de 10 minutos',
    ru: '⏱️ Таймаут на 10 минут',
    ja: '⏱️ 10分間のタイムアウト',
    ko: '⏱️ 10분 타임아웃',
    zh: '⏱️ 禁言 10 分钟',
    it: '⏱️ Timeout di 10 minuti',
  },
  action_timeout_3600s: {
    de: '⏱️ 1 Stunde Timeout',
    en: '⏱️ 1 hour timeout',
    fr: '⏱️ Timeout de 1 heure',
    es: '⏱️ Timeout de 1 hora',
    pt: '⏱️ Timeout de 1 hora',
    ru: '⏱️ Таймаут на 1 час',
    ja: '⏱️ 1時間のタイムアウト',
    ko: '⏱️ 1시간 타임아웃',
    zh: '⏱️ 禁言 1 小时',
    it: '⏱️ Timeout di 1 ora',
  },
  action_timeout_86400s: {
    de: '🚫 24 Stunden (1 Tag) Timeout',
    en: '🚫 24 hours (1 day) timeout',
    fr: '🚫 Timeout de 24 heures (1 jour)',
    es: '🚫 Timeout de 24 horas (1 día)',
    pt: '🚫 Timeout de 24 horas (1 dia)',
    ru: '🚫 Таймаут на 24 часа (1 день)',
    ja: '🚫 24時間（1日）のタイムアウト',
    ko: '🚫 24시간 (1일) 타임아웃',
    zh: '🚫 禁言 24 小时（1 天）',
    it: '🚫 Timeout di 24 ore (1 giorno)',
  },
  action_timeout_604800s: {
    de: '🚫 7 Tage (1 Woche) Timeout',
    en: '🚫 7 days (1 week) timeout',
    fr: '🚫 Timeout de 7 jours (1 semaine)',
    es: '🚫 Timeout de 7 días (1 semana)',
    pt: '🚫 Timeout de 7 dias (1 semana)',
    ru: '🚫 Таймаут на 7 дней (1 неделя)',
    ja: '🚫 7日間（1週間）のタイムアウト',
    ko: '🚫 7일 (1주) 타임아웃',
    zh: '🚫 禁言 7 天（1 周）',
    it: '🚫 Timeout di 7 giorni (1 settimana)',
  },

  // Violation Alert Message
  warnTitle: {
    de: '🛡️ Sicherheitswarnung / Regelverstoß',
    en: '🛡️ Security Warning / Rule Violation',
    fr: '🛡️ Avertissement de sécurité / Infraction',
    es: '🛡️ Advertencia de seguridad / Infracción',
    pt: '🛡️ Aviso de segurança / Violação de regras',
    ru: '🛡️ Предупреждение безопасности / Нарушение',
    ja: '🛡️ セキュリティ警告 / ルール違反',
    ko: '🛡️ 보안 경고 / 규칙 위반 감지',
    zh: '🛡️ 安全警告 / 违规提醒',
    it: '🛡️ Avviso di sicurezza / Violazione regole',
  },
  warnBody: {
    de: '{user}, deine Nachricht verstößt gegen die Richtlinien dieses Servers!\n\n**Grund:** {category}\n**Verwarnung:** {current} von {max}\n**Maßnahme:** {action}\n\n*Diese Verwarnung verfällt am {date}.*',
    en: '{user}, your message violates this server\'s guidelines!\n\n**Reason:** {category}\n**Warning:** {current} of {max}\n**Action:** {action}\n\n*This warning expires on {date}.*',
    fr: '{user}, votre message enfreint les règles de ce serveur !\n\n**Raison :** {category}\n**Avertissement :** {current} sur {max}\n**Mesure :** {action}\n\n*Cet avertissement expire le {date}.*',
    es: '¡{user}, tu mensaje infringe las normas de este servidor!\n\n**Motivo:** {category}\n**Advertencia:** {current} de {max}\n**Medida:** {action}\n\n*Esta advertencia vence el {date}.*',
    pt: '{user}, sua mensagem viola as diretrizes deste servidor!\n\n**Motivo:** {category}\n**Aviso:** {current} de {max}\n**Ação:** {action}\n\n*Este aviso expira em {date}.*',
    ru: '{user}, ваше сообщение нарушает правила сервера!\n\n**Причина:** {category}\n**Предупреждение:** {current} из {max}\n**Действие:** {action}\n\n*Предупреждение истекает {date}.*',
    ja: '{user}、あなたのメッセージはサーバーのルールに違反しています！\n\n**理由:** {category}\n**警告:** {current} / {max}\n**措置:** {action}\n\n*この警告は {date} に失効します。*',
    ko: '{user}님, 메시지가 서버의 보안 규칙을 위반했습니다!\n\n**사유:** {category}\n**경고 수:** {current} / {max}\n**조치:** {action}\n\n*이 경고는 {date}에 만료됩니다.*',
    zh: '{user}，您的消息违反了本服务器的安全准则！\n\n**原因：** {category}\n**当前警告：** {current} / {max}\n**处理措施：** {action}\n\n*本警告将于 {date} 过期。*',
    it: '{user}, il tuo messaggio viola le linee guida del server!\n\n**Motivo:** {category}\n**Avviso:** {current} di {max}\n**Azione:** {action}\n\n*Questo avviso scade il {date}.*',
  },

  // API Key Commands & Modals
  apiKeyModalTitle: {
    de: 'OpenAI API Key eingeben',
    en: 'Enter OpenAI API Key',
    fr: 'Entrer la clé API OpenAI',
    es: 'Introducir clave API de OpenAI',
    pt: 'Inserir chave de API da OpenAI',
    ru: 'Ввести ключ API OpenAI',
    ja: 'OpenAI APIキーを入力',
    ko: 'OpenAI API 키 입력',
    zh: '输入 OpenAI API 密钥',
    it: 'Inserisci chiave API OpenAI',
  },
  apiKeyInputLabel: {
    de: 'OpenAI Moderation API Key',
    en: 'OpenAI Moderation API Key',
    fr: 'Clé API de modération OpenAI',
    es: 'Clave API de moderación de OpenAI',
    pt: 'Chave de API de moderação da OpenAI',
    ru: 'Ключ OpenAI Moderation API',
    ja: 'OpenAIモデレーションAPIキー',
    ko: 'OpenAI 검열 API 키',
    zh: 'OpenAI 审核 API 密钥',
    it: 'Chiave API Moderazione OpenAI',
  },
  apiKeyInputPlaceholder: {
    de: 'sk-proj-... oder "remove" zum Löschen',
    en: 'sk-proj-... or "remove" to delete',
    fr: 'sk-proj-... ou "remove" pour effacer',
    es: 'sk-proj-... o "remove" para eliminar',
    pt: 'sk-proj-... ou "remove" para excluir',
    ru: 'sk-proj-... или "remove" для удаления',
    ja: 'sk-proj-... または削除する場合は "remove"',
    ko: 'sk-proj-... 또는 삭제하려면 "remove"',
    zh: 'sk-proj-... 或输入 "remove" 删除',
    it: 'sk-proj-... oppure "remove" per rimuovere',
  },
  apiKeySavedSuccess: {
    de: '✅ **OpenAI API Key erfolgreich gespeichert!**\n\nKey: `{key}`\nDer KI-Sicherheitsfilter ist jetzt aktiv und überwacht alle neuen Nachrichten.',
    en: '✅ **OpenAI API Key successfully saved!**\n\nKey: `{key}`\nAI security filter is now active and monitoring all new messages.',
    fr: '✅ **Clé API OpenAI enregistrée avec succès !**\n\nClé : `{key}`\nLe filtre de sécurité IA est désormais actif et surveille tous les nouveaux messages.',
    es: '✅ **¡Clave API de OpenAI guardada con éxito!**\n\nClave: `{key}`\nEl filtro de seguridad IA ya está activo y monitorea todos los mensajes nuevos.',
    pt: '✅ **Chave de API da OpenAI salva com sucesso!**\n\nChave: `{key}`\nO filtro de segurança por IA agora está ativo e monitorando novas mensagens.',
    ru: '✅ **Ключ API OpenAI успешно сохранен!**\n\nКлюч: `{key}`\nИИ-фильтр безопасности активен и проверяет все новые сообщения.',
    ja: '✅ **OpenAI APIキーが正常に保存されました！**\n\nキー: `{key}`\nAIセキュリティフィルターが有効になり、新しいメッセージを監視します。',
    ko: '✅ **OpenAI API 키가 성공적으로 저장되었습니다!**\n\n키: `{key}`\nAI 보안 필터가 활성화되어 모든 새 메시지를 모니터링합니다.',
    zh: '✅ **OpenAI API 密钥保存成功！**\n\n密钥：`{key}`\nAI 安全防护已启动，正在实时监控新消息。',
    it: '✅ **Chiave API OpenAI salvata con successo!**\n\nChiave: `{key}`\nIl filtro di sicurezza AI è attivo e monitora tutti i nuovi messaggi.',
  },
  apiKeySavedWarning: {
    de: '⚠️ **API Key wurde gespeichert, aber OpenAI meldet einen Fehler:** `{error}`\nBitte prüfe, ob der Key gültig ist und Guthaben vorhanden ist.',
    en: '⚠️ **API Key was saved, but OpenAI returned an error:** `{error}`\nPlease check if your key is valid and has sufficient quota.',
    fr: '⚠️ **Clé enregistrée, mais OpenAI a renvoyé une erreur :** `{error}`\nVeuillez vérifier la validité de la clé et votre quota.',
    es: '⚠️ **Clave guardada, pero OpenAI devolvió un error:** `{error}`\nVerifica que la clave sea válida y tenga saldo suficiente.',
    pt: '⚠️ **Chave salva, mas a OpenAI retornou um erro:** `{error}`\nVerifique se a chave é válida e possui saldo disponível.',
    ru: '⚠️ **Ключ сохранен, но OpenAI вернул ошибку:** `{error}`\nПожалуйста, проверьте правильность ключа и баланс аккаунта.',
    ja: '⚠️ **APIキーは保存されましたが、OpenAIでエラーが発生しました:** `{error}`\nキーの有効性とクォータをご確認ください。',
    ko: '⚠️ **API 키가 저장되었으나 OpenAI에서 오류를 반환했습니다:** `{error}`\n키의 유효성 및 잔액을 확인해주세요.',
    zh: '⚠️ **API 密钥已保存，但 OpenAI 返回错误：** `{error}`\n请检查密钥有效性及账户额度。',
    it: '⚠️ **Chiave salvata, ma OpenAI ha restituito un errore:** `{error}`\nVerifica la validità della chiave e il credito disponibile.',
  },
  apiKeyRemoved: {
    de: '🗑️ **OpenAI API Key wurde entfernt.** Der Sicherheitsbot führt vorerst keine Moderationsüberprüfungen mehr durch.',
    en: '🗑️ **OpenAI API Key has been removed.** The security bot is no longer conducting moderation checks.',
    fr: '🗑️ **Clé API OpenAI supprimée.** Le bot de sécurité ne réalise plus de vérifications.',
    es: '🗑️ **Clave API de OpenAI eliminada.** El bot de seguridad ya no realizará comprobaciones de moderación.',
    pt: '🗑️ **Chave de API da OpenAI removida.** O bot de segurança não realizará mais verificações.',
    ru: '🗑️ **Ключ API OpenAI удален.** Бот безопасности временно отключил проверку модерации.',
    ja: '🗑️ **OpenAI APIキーが削除されました。** セキュリティボットによるモデレーション検査は停止しています。',
    ko: '🗑️ **OpenAI API 키가 제거되었습니다.** 보안 봇의 자동 검열이 비활성화되었습니다.',
    zh: '🗑️ **OpenAI API 密钥已移除。** 安全机器人已暂停内容审核检测。',
    it: '🗑️ **Chiave API OpenAI rimossa.** Il bot di sicurezza ha sospeso i controlli di moderazione.',
  },

  // Language Command
  langChanged: {
    de: '✅ Die Serversprache wurde auf **{name}** geändert.',
    en: '✅ The server language has been changed to **{name}**.',
    fr: '✅ La langue du serveur a été changée pour **{name}**.',
    es: '✅ El idioma del servidor se ha cambiado a **{name}**.',
    pt: '✅ O idioma do servidor foi alterado para **{name}**.',
    ru: '✅ Язык сервера успешно изменен на **{name}**.',
    ja: '✅ サーバーの言語が **{name}** に変更されました。',
    ko: '✅ 서버 언어가 **{name}**(으)로 변경되었습니다.',
    zh: '✅ 服务器语言已成功设置为 **{name}**。',
    it: '✅ La lingua del server è stata modificata in **{name}**.',
  },

  // Sensitivity Presets
  preset_strict: {
    de: 'Strikter Schutz (Schwelle: 30%)',
    en: 'Strict Protection (Threshold: 30%)',
    fr: 'Protection stricte (Seuil : 30%)',
    es: 'Protección estricta (Umbral: 30%)',
    pt: 'Proteção estrita (Limite: 30%)',
    ru: 'Строгая защита (Порог: 30%)',
    ja: '厳格な保護（しきい値: 30%）',
    ko: '엄격한 보호 (기준치: 30%)',
    zh: '严格防护（阈值：30%）',
    it: 'Protezione rigorosa (Soglia: 30%)',
  },
  preset_balanced: {
    de: 'Ausgewogen – Standard (Schwelle: 50%)',
    en: 'Balanced – Default (Threshold: 50%)',
    fr: 'Équilibré – Par défaut (Seuil : 50%)',
    es: 'Equilibrado – Predeterminado (Umbral: 50%)',
    pt: 'Equilibrado – Padrão (Limite: 50%)',
    ru: 'Сбалансированный – По умолчанию (Порог: 50%)',
    ja: 'バランス – デフォルト（しきい値: 50%）',
    ko: '균형 잡힘 – 기본값 (기준치: 50%)',
    zh: '均衡防护 – 推荐默认（阈值：50%）',
    it: 'Bilanciato – Predefinito (Soglia: 50%)',
  },
  preset_relaxed: {
    de: 'Tolerant (Schwelle: 75%)',
    en: 'Relaxed (Threshold: 75%)',
    fr: 'Tolérant (Seuil : 75%)',
    es: 'Tolerante (Umbral: 75%)',
    pt: 'Tolerante (Limite: 75%)',
    ru: 'Мягкий (Порог: 75%)',
    ja: '寛容（しきい値: 75%）',
    ko: '유연한 보호 (기준치: 75%)',
    zh: '宽松防护（阈值：75%）',
    it: 'Tollerante (Soglia: 75%)',
  },
  preset_custom: {
    de: 'Benutzerdefiniert (Eigene Schwellenwerte)',
    en: 'Custom (Custom Thresholds)',
    fr: 'Personnalisé (Seuils sur mesure)',
    es: 'Personalizado (Umbrales a medida)',
    pt: 'Personalizado (Limites próprios)',
    ru: 'Пользовательский (Индивидуальные пороги)',
    ja: 'カスタム（個別しきい値設定）',
    ko: '사용자 지정 (개별 설정)',
    zh: '自定义配置（单独指定阈值）',
    it: 'Personalizzato (Soglie personalizzate)',
  },
  sensitivityUpdated: {
    de: '✅ **Schutzlevel aktualisiert:** `{preset}`\nAlle Kategorien wurden auf diesen Sensibilitätswert eingestellt.',
    en: '✅ **Protection level updated:** `{preset}`\nAll categories have been updated to this sensitivity level.',
    fr: '✅ **Niveau de protection mis à jour :** `{preset}`\nToutes les catégories ont été ajustées à cette sensibilité.',
    es: '✅ **Nivel de protección actualizado:** `{preset}`\nTodas las categorías se han ajustado a esta sensibilidad.',
    pt: '✅ **Nível de proteção atualizado:** `{preset}`\nTodas as categorias foram ajustadas para este nível.',
    ru: '✅ **Уровень защиты обновлен:** `{preset}`\nВсе категории переведены на этот порог чувствительности.',
    ja: '✅ **保護レベルを更新しました:** `{preset}`\nすべてのカテゴリがこの感度設定に適用されました。',
    ko: '✅ **보안 수준이 업데이트되었습니다:** `{preset}`\n모든 카테고리에 해당 민감도 설정이 적용되었습니다.',
    zh: '✅ **防护级别已更新：** `{preset}`\n所有分类均已应用此灵敏度阈值。',
    it: '✅ **Livello di protezione aggiornato:** `{preset}`\nTutte le categorie sono state regolate su questa sensibilità.',
  },

  // Rules Configuration
  rulesTitle: {
    de: '🛡️ Filter & Moderations-Regeln',
    en: '🛡️ Filters & Moderation Rules',
    fr: '🛡️ Filtres et règles de modération',
    es: '🛡️ Filtros y reglas de moderación',
    pt: '🛡️ Filtros e regras de moderação',
    ru: '🛡️ Фильтры и правила модерации',
    ja: '🛡️ フィルターとモデレーションルール',
    ko: '🛡️ 필터 및 검열 규칙 설정',
    zh: '🛡️ 过滤规则与审核配置',
    it: '🛡️ Filtri e regole di moderazione',
  },
  rulesDesc: {
    de: 'Übersicht über die aktiven Sicherheitsfilter und automatischen Aktionen:',
    en: 'Overview of active security filters and automatic actions:',
    fr: 'Aperçu des filtres de sécurité actifs et des actions automatiques :',
    es: 'Resumen de filtros de seguridad activos y acciones automáticas:',
    pt: 'Visão geral dos filtros de segurança ativos e ações automáticas:',
    ru: 'Обзор активных фильтров безопасности и автоматических действий:',
    ja: '有効なセキュリティフィルターと自動アクションの概要:',
    ko: '현재 활성화된 보안 필터 및 자동 조치 안내:',
    zh: '当前生效的安全过滤规则与自动处理措施概览：',
    it: 'Panoramica dei filtri di sicurezza attivi e delle azioni automatiche:',
  },
  rulesCategorySelect: {
    de: 'Kategorie zum Bearbeiten auswählen…',
    en: 'Select category to configure…',
    fr: 'Sélectionner une catégorie à modifier…',
    es: 'Seleccionar categoría para configurar…',
    pt: 'Selecionar categoria para configurar…',
    ru: 'Выберите категорию для настройки…',
    ja: '設定するカテゴリを選択…',
    ko: '설정할 카테고리 선택…',
    zh: '选择要调整的过滤分类…',
    it: 'Seleziona categoria da configurare…',
  },
  rulesBtnReset: {
    de: '🔄 Auf Standard zurücksetzen',
    en: '🔄 Reset to Defaults',
    fr: '🔄 Réinitialiser par défaut',
    es: '🔄 Restablecer valores predeterminados',
    pt: '🔄 Redefinir para padrão',
    ru: '🔄 Сбросить настройки',
    ja: '🔄 デフォルトに戻す',
    ko: '🔄 기본값으로 초기화',
    zh: '🔄 恢复推荐默认设置',
    it: '🔄 Ripristina predefiniti',
  },

  // Warnings Configuration
  warningsTitle: {
    de: '⚙️ Verwarnungs- & Strafsystem',
    en: '⚙️ Warning & Punishment System',
    fr: '⚙️ Système d\'avertissements et sanctions',
    es: '⚙️ Sistema de advertencias y sanciones',
    pt: '⚙️ Sistema de avisos e punições',
    ru: '⚙️ Система предупреждений и наказаний',
    ja: '⚙️ 警告・ペナルティ設定',
    ko: '⚙️ 경고 및 제재 시스템 설정',
    zh: '⚙️ 警告阶梯与惩罚机制配置',
    it: '⚙️ Sistema di avvisi e sanzioni',
  },
  warningsSummary: {
    de: '### Aktuelle Einstellungen:\n- **Max. Verwarnungen:** `{max}`\n- **Verfallsdauer:** `{days} Tage`\n- **Automatisches Löschen:** `{autoDelete}`\n\n### Eskalationsstufen:\n{escalation}\n\n💡 *Hinweis: Der Bot führt niemals Kicks oder Bans aus. Es werden ausschließlich Verwarnungen und Timeouts verhängt.*',
    en: '### Current Settings:\n- **Max Warnings:** `{max}`\n- **Expiration Period:** `{days} days`\n- **Auto Delete Messages:** `{autoDelete}`\n\n### Escalation Tiers:\n{escalation}\n\n💡 *Note: The bot never kicks or bans members. Only warnings and timeouts are applied.*',
    fr: '### Paramètres actuels :\n- **Max avertissements :** `{max}`\n- **Durée de validité :** `{days} jours`\n- **Suppression automatique :** `{autoDelete}`\n\n### Échelons de sanctions :\n{escalation}\n\n💡 *Note : Le bot n\'expulse et ne bannit jamais. Seuls les avertissements et timeouts sont appliqués.*',
    es: '### Configuración actual:\n- **Máx. advertencias:** `{max}`\n- **Plazo de caducidad:** `{days} días`\n- **Borrado automático:** `{autoDelete}`\n\n### Niveles de escalada:\n{escalation}\n\n💡 *Nota: El bot nunca expulsa ni banea miembros. Solo se aplican advertencias y timeouts.*',
    pt: '### Configurações atuais:\n- **Máx. de avisos:** `{max}`\n- **Período de expiração:** `{days} dias`\n- **Exclusão automática:** `{autoDelete}`\n\n### Níveis de punição:\n{escalation}\n\n💡 *Nota: O bot nunca expulsa ou bane membros. Apenas avisos e timeouts são aplicados.*',
    ru: '### Текущие настройки:\n- **Макс. предупреждений:** `{max}`\n- **Срок действия:** `{days} дней`\n- **Авто-удаление сообщений:** `{autoDelete}`\n\n### Шкала наказаний:\n{escalation}\n\n💡 *Примечание: Бот никогда не банит и не кикает. Применяются только предупреждения и таймауты.*',
    ja: '### 現在の設定:\n- **最大警告数:** `{max}`\n- **有効期限:** `{days} 日間`\n- **自動削除:** `{autoDelete}`\n\n### 罰則エスカレーション:\n{escalation}\n\n💡 *注: ボットはキックやBANを実行しません。警告とタイムアウトのみ適用されます。*',
    ko: '### 현재 설정:\n- **최대 경고 수:** `{max}`\n- **경고 유효 기간:** `{days}일`\n- **메시지 자동 삭제:** `{autoDelete}`\n\n### 제재 단계:\n{escalation}\n\n💡 *안내: 봇은 추방(Kick)이나 차단(Ban)을 실행하지 않습니다. 경고 및 타임아웃만 적용됩니다.*',
    zh: '### 当前配置参数：\n- **最大警告次数：** `{max}`\n- **违规过期周期：** `{days} 天`\n- **违规消息自动删除：** `{autoDelete}`\n\n### 惩处阶梯列表：\n{escalation}\n\n💡 *说明：本机器人绝不执行踢出（Kick）或封禁（Ban），仅执行警告及禁言（Timeout）。*',
    it: '### Impostazioni attuali:\n- **Max avvisi:** `{max}`\n- **Periodo di scadenza:** `{days} giorni`\n- **Eliminazione automatica:** `{autoDelete}`\n\n### Livelli di sanzione:\n{escalation}\n\n💡 *Nota: Il bot non espelle né banna utenti. Vengono applicati solo avvisi e timeout.*',
  },
  warningsSaved: {
    de: '✅ **Verwarnungssystem erfolgreich konfiguriert!**',
    en: '✅ **Warning system successfully configured!**',
    fr: '✅ **Système d\'avertissements configuré avec succès !**',
    es: '✅ **¡Sistema de advertencias configurado con éxito!**',
    pt: '✅ **Sistema de avisos configurado com sucesso!**',
    ru: '✅ **Система предупреждений успешно настроена!**',
    ja: '✅ **警告システムが正常に設定されました！**',
    ko: '✅ **경고 시스템이 성공적으로 설정되었습니다!**',
    zh: '✅ **警告与制裁机制配置已成功更新！**',
    it: '✅ **Sistema di avvisi configurato con successo!**',
  },

  // Status Command
  statusTitle: {
    de: '🛡️ Sicherheitsstatus für {user}',
    en: '🛡️ Security Status for {user}',
    fr: '🛡️ Statut de sécurité pour {user}',
    es: '🛡️ Estado de seguridad de {user}',
    pt: '🛡️ Status de segurança de {user}',
    ru: '🛡️ Статус безопасности для {user}',
    ja: '🛡️ {user} のセキュリティステータス',
    ko: '🛡️ {user}님의 보안 상태',
    zh: '🛡️ {user} 的安全违规状态',
    it: '🛡️ Stato di sicurezza per {user}',
  },
  statusClean: {
    de: '✅ **Keine aktiven Verwarnungen!**\nDu hast eine weiße Weste auf diesem Server. Danke, dass du dich an die Regeln hältst!',
    en: '✅ **No active warnings!**\nYou have a clean record on this server. Thank you for following the rules!',
    fr: '✅ **Aucun avertissement actif !**\nVotre casier est vierge sur ce serveur. Merci de respecter les règles !',
    es: '✅ **¡Sin advertencias activas!**\nTienes un historial limpio en este servidor. ¡Gracias por respetar las normas!',
    pt: '✅ **Nenhum aviso ativo!**\nVocê possui um histórico limpo neste servidor. Obrigado por seguir as regras!',
    ru: '✅ **Нет активных предупреждений!**\nУ вас чистая история на этом сервере. Спасибо за соблюдение правил!',
    ja: '✅ **アクティブな警告はありません！**\nこのサーバーでの履歴はクリーンです。ルールを守っていただきありがとうございます！',
    ko: '✅ **활성화된 경고가 없습니다!**\n현재 깨끗한 기록을 유지하고 계십니다. 규칙을 준수해주셔서 감사합니다!',
    zh: '✅ **当前无活跃违规警告！**\n您在本服务器保持着良好的记录，感谢遵守社区准则！',
    it: '✅ **Nessun avviso attivo!**\nHai la fedina pulita su questo server. Grazie per il rispetto delle regole!',
  },
  statusSummary: {
    de: '**Aktive Verwarnungen:** `{current} von {max}`\n**Timeout-Status:** {timeout}\n\n### Verstoß-Historie:\n{list}',
    en: '**Active Warnings:** `{current} of {max}`\n**Timeout Status:** {timeout}\n\n### Violation History:\n{list}',
    fr: '**Avertissements actifs :** `{current} sur {max}`\n**Statut Timeout :** {timeout}\n\n### Historique des infractions :\n{list}',
    es: '**Advertencias activas:** `{current} de {max}`\n**Estado de Timeout:** {timeout}\n\n### Historial de infracciones:\n{list}',
    pt: '**Avisos ativos:** `{current} de {max}`\n**Status de Timeout:** {timeout}\n\n### Histórico de infrações:\n{list}',
    ru: '**Активные предупреждения:** `{current} из {max}`\n**Статус таймаута:** {timeout}\n\n### История нарушений:\n{list}',
    ja: '**アクティブな警告:** `{current} / {max}`\n**タイムアウト状況:** {timeout}\n\n### 違反履歴:\n{list}',
    ko: '**활성 경고 수:** `{current} / {max}`\n**타임아웃 상태:** {timeout}\n\n### 위반 상세 내역:\n{list}',
    zh: '**当前有效警告：** `{current} / {max}`\n**禁言状态：** {timeout}\n\n### 违规历史记录：\n{list}',
    it: '**Avvisi attivi:** `{current} di {max}`\n**Stato Timeout:** {timeout}\n\n### Cronologia violazioni:\n{list}',
  },

  // Manage User Command
  manageTitle: {
    de: '🛡️ Moderations-Verwaltung für {user}',
    en: '🛡️ Moderation Management for {user}',
    fr: '🛡️ Gestion de modération pour {user}',
    es: '🛡️ Gestión de moderación de {user}',
    pt: '🛡️ Gestão de moderação de {user}',
    ru: '🛡️ Управление модерацией для {user}',
    ja: '🛡️ {user} のモデレーション管理',
    ko: '🛡️ {user} 모더레이션 관리',
    zh: '🛡️ 用户违规管理：{user}',
    it: '🛡️ Gestione moderazione per {user}',
  },
  manageSummary: {
    de: '**Aktive Verwarnungen:** `{current} von {max}`\n**Gesamte Verstöße:** `{total}`\n**Timeout-Status:** {timeout}\n\n{list}',
    en: '**Active Warnings:** `{current} of {max}`\n**Total Violations:** `{total}`\n**Timeout Status:** {timeout}\n\n{list}',
    fr: '**Avertissements actifs :** `{current} sur {max}`\n**Total infractions :** `{total}`\n**Statut Timeout :** {timeout}\n\n{list}',
    es: '**Advertencias activas:** `{current} de {max}`\n**Total infracciones:** `{total}`\n**Estado de Timeout:** {timeout}\n\n{list}',
    pt: '**Avisos ativos:** `{current} de {max}`\n**Total de infrações:** `{total}`\n**Status de Timeout:** {timeout}\n\n{list}',
    ru: '**Активные предупреждения:** `{current} из {max}`\n**Всего нарушений:** `{total}`\n**Статус таймаута:** {timeout}\n\n{list}',
    ja: '**アクティブな警告:** `{current} / {max}`\n**累計違反数:** `{total}`\n**タイムアウト状況:** {timeout}\n\n{list}',
    ko: '**활성 경고 수:** `{current} / {max}`\n**총 위반 횟수:** `{total}`\n**타임아웃 상태:** {timeout}\n\n{list}',
    zh: '**有效警告次数：** `{current} / {max}`\n**历史累计违规：** `{total}`\n**禁言状态：** {timeout}\n\n{list}',
    it: '**Avvisi attivi:** `{current} di {max}`\n**Totale violazioni:** `{total}`\n**Stato Timeout:** {timeout}\n\n{list}',
  },
  manageSelectPlaceholder: {
    de: 'Verstoß zum Löschen auswählen (Fehlalarm)…',
    en: 'Select violation to delete (False positive)…',
    fr: 'Sélectionner une infraction à effacer (Faux positif)…',
    es: 'Seleccionar infracción a eliminar (Falso positivo)…',
    pt: 'Selecionar infração para remover (Falso positivo)…',
    ru: 'Выберите нарушение для удаления (ложное срабатывание)…',
    ja: '削除する違反を選択（誤判定など）…',
    ko: '삭제할 위반 항목 선택 (오탐 처리)…',
    zh: '选择要撤销的违规记录（误判处理）…',
    it: 'Seleziona violazione da rimuovere (Falso positivo)…',
  },
  manageBtnClearAll: {
    de: '🗑️ Alle Verwarnungen löschen',
    en: '🗑️ Clear All Warnings',
    fr: '🗑️ Effacer tous les avertissements',
    es: '🗑️ Borrar todas las advertencias',
    pt: '🗑️ Limpar todos os avisos',
    ru: '🗑️ Очистить все предупреждения',
    ja: '🗑️ すべての警告を消去',
    ko: '🗑️ 모든 경고 초기화',
    zh: '🗑️ 清除该用户所有警告',
    it: '🗑️ Cancella tutti gli avvisi',
  },
  manageBtnRemoveTimeout: {
    de: '🔓 Timeout aufheben',
    en: '🔓 Remove Timeout',
    fr: '🔓 Lever le timeout',
    es: '🔓 Quitar timeout',
    pt: '🔓 Remover timeout',
    ru: '🔓 Снять таймаут',
    ja: '🔓 タイムアウト解除',
    ko: '🔓 타임아웃 해제',
    zh: '🔓 立即解除禁言',
    it: '🔓 Rimuovi timeout',
  },
  manageViolationDeleted: {
    de: '✅ **Verstoß #{id} wurde gelöscht.**\nAktive Verwarnungen für {user}: `{count}`',
    en: '✅ **Violation #{id} has been deleted.**\nActive warnings for {user}: `{count}`',
    fr: '✅ **L\'infraction #{id} a été supprimée.**\nAvertissements actifs pour {user} : `{count}`',
    es: '✅ **Se ha eliminado la infracción #{id}.**\nAdvertencias activas para {user}: `{count}`',
    pt: '✅ **A infração #{id} foi removida.**\nAvisos ativos para {user}: `{count}`',
    ru: '✅ **Нарушение #{id} удалено.**\nАктивных предупреждений у {user}: `{count}`',
    ja: '✅ **違反 #{id} を削除しました。**\n{user} のアクティブな警告数: `{count}`',
    ko: '✅ **위반 항목 #{id}이(가) 삭제되었습니다.**\n{user}님의 활성 경고 수: `{count}`',
    zh: '✅ **违规记录 #{id} 已撤销。**\n{user} 当前活跃警告数：`{count}`',
    it: '✅ **Violazione #{id} rimossa.**\nAvvisi attivi per {user}: `{count}`',
  },
  manageAllCleared: {
    de: '✅ **Alle Verwarnungen für {user} wurden gelöscht.**',
    en: '✅ **All warnings for {user} have been cleared.**',
    fr: '✅ **Tous les avertissements de {user} ont été effacés.**',
    es: '✅ **Se han borrado todas las advertencias de {user}.**',
    pt: '✅ **Todos os avisos de {user} foram limpos.**',
    ru: '✅ **Все предупреждения для {user} очищены.**',
    ja: '✅ **{user} のすべての警告をリセットしました。**',
    ko: '✅ **{user}님의 모든 경고가 초기화되었습니다.**',
    zh: '✅ **已成功清除 {user} 的全部违规记录。**',
    it: '✅ **Tutti gli avvisi per {user} sono stati cancellati.**',
  },
  manageTimeoutRemoved: {
    de: '✅ **Der Timeout für {user} wurde aufgehoben.**',
    en: '✅ **Timeout for {user} has been removed.**',
    fr: '✅ **Le timeout de {user} a été levé.**',
    es: '✅ **Se ha quitado el timeout de {user}.**',
    pt: '✅ **O timeout de {user} foi removido.**',
    ru: '✅ **Таймаут для {user} успешно снят.**',
    ja: '✅ **{user} のタイムアウトを解除しました。**',
    ko: '✅ **{user}님의 타임아웃이 해제되었습니다.**',
    zh: '✅ **已解除 {user} 的禁言限制。**',
    it: '✅ **Il timeout per {user} è stato rimosso.**',
  },

  // Test Text Command
  testTitle: {
    de: '🧪 KI-Moderationstest – Analysebericht',
    en: '🧪 AI Moderation Test – Analysis Report',
    fr: '🧪 Test de modération IA – Rapport d\'analyse',
    es: '🧪 Prueba de moderación IA – Informe de análisis',
    pt: '🧪 Teste de moderação por IA – Relatório',
    ru: '🧪 Тест ИИ-модерации – Отчет об анализе',
    ja: '🧪 AIモデレーションテスト – 分析レポート',
    ko: '🧪 AI 검열 테스트 – 분석 보고서',
    zh: '🧪 AI 审核测试 – 评估报告',
    it: '🧪 Test moderazione AI – Report di analisi',
  },
  testInputLabel: {
    de: '**Getesteter Text:**',
    en: '**Tested Text:**',
    fr: '**Texte analysé :**',
    es: '**Texto analizado:**',
    pt: '**Texto analisado:**',
    ru: '**Проверенный текст:**',
    ja: '**テスト対象テキスト:**',
    ko: '**테스트한 텍스트:**',
    zh: '**测试文本内容：**',
    it: '**Testo analizzato:**',
  },
  testClean: {
    de: '✅ **Unbedenklich** – Dieser Text verstößt gegen keine konfigurierten Filter.',
    en: '✅ **Clean** – This text does not violate any configured filters.',
    fr: '✅ **Conforme** – Ce texte n\'enfreint aucun filtre configuré.',
    es: '✅ **Limpio** – Este texto no infringe ningún filtro configurado.',
    pt: '✅ **Limpo** – Este texto não viola nenhum filtro configurado.',
    ru: '✅ **Безопасно** – Этот текст не нарушает настроенные фильтры.',
    ja: '✅ **問題なし** – 設定されたフィルターの違反はありません。',
    ko: '✅ **정상 (위반 없음)** – 설정된 보안 필터를 통과했습니다.',
    zh: '✅ **安全合规** – 未触发任何启用的审核规则。',
    it: '✅ **Conforme** – Questo testo non viola alcun filtro configurato.',
  },
  testViolated: {
    de: '⚠️ **Regelverstoß erkannt!**\n**Höchste Kategorie:** {category} ({score}%)\n**Ausgelöste Maßnahme:** {action}\n**Nachricht automatisch gelöscht:** {autoDelete}',
    en: '⚠️ **Rule violation detected!**\n**Highest Category:** {category} ({score}%)\n**Triggered Action:** {action}\n**Message Auto-Deleted:** {autoDelete}',
    fr: '⚠️ **Infraction détectée !**\n**Catégorie principale :** {category} ({score}%)\n**Action déclenchée :** {action}\n**Message supprimé auto :** {autoDelete}',
    es: '⚠️ **¡Infracción detectada!**\n**Categoría principal:** {category} ({score}%)\n**Medida activada:** {action}\n**Mensaje borrado auto:** {autoDelete}',
    pt: '⚠️ **Violação detectada!**\n**Categoria principal:** {category} ({score}%)\n**Ação disparada:** {action}\n**Mensagem excluída auto:** {autoDelete}',
    ru: '⚠️ **Обнаружено нарушение!**\n**Основная категория:** {category} ({score}%)\n**Применяемое действие:** {action}\n**Авто-удаление:** {autoDelete}',
    ja: '⚠️ **ルール違反が検出されました！**\n**該当カテゴリ:** {category} ({score}%)\n**実行される措置:** {action}\n**メッセージ自動削除:** {autoDelete}',
    ko: '⚠️ **규칙 위반 감지!**\n**주요 위반 항목:** {category} ({score}%)\n**적용 조치:** {action}\n**메시지 자동 삭제 여부:** {autoDelete}',
    zh: '⚠️ **检测到违规内容！**\n**主要违规项：** {category} ({score}%)\n**触发处理措施：** {action}\n**是否自动删除消息：** {autoDelete}',
    it: '⚠️ **Rilevata violazione!**\n**Categoria principale:** {category} ({score}%)\n**Azione eseguita:** {action}\n**Eliminazione automatica:** {autoDelete}',
  },

  // Generic errors & permissions
  errGuildOnly: {
    de: 'Dieser Befehl kann nur auf einem Discord-Server ausgeführt werden.',
    en: 'This command can only be used on a Discord server.',
    fr: 'Cette commande ne peut être utilisée que sur un serveur Discord.',
    es: 'Este comando solo se puede usar en un servidor de Discord.',
    pt: 'Este comando só pode ser usado em um servidor do Discord.',
    ru: 'Эту команду можно использовать только на сервере Discord.',
    ja: 'このコマンドはDiscordサーバー内でのみ使用できます。',
    ko: '이 명령어는 Discord 서버 내에서만 실행할 수 있습니다.',
    zh: '此命令仅可在 Discord 服务器中使用。',
    it: 'Questo comando può essere utilizzato solo su un server Discord.',
  },
  errNoPermission: {
    de: '❌ Du benötigst **Administrator-Berechtigungen**, um diesen Befehl auszuführen.',
    en: '❌ You need **Administrator permissions** to use this command.',
    fr: '❌ Vous avez besoin des **permissions Administrateur** pour exécuter cette commande.',
    es: '❌ Necesitas **permisos de Administrador** para usar este comando.',
    pt: '❌ Você precisa de **permissões de Administrador** para usar este comando.',
    ru: '❌ Для выполнения этой команды требуются **права Администратора**.',
    ja: '❌ このコマンドを実行するには**管理者権限**が必要です。',
    ko: '❌ 이 명령어를 사용하려면 **관리자 권한**이 필요합니다.',
    zh: '❌ 您需要 **管理员权限** 才能执行此命令。',
    it: '❌ Sono necessari i **permessi di Amministratore** per eseguire questo comando.',
  },
  errNoApiKey: {
    de: '⚠️ Für diesen Server ist noch kein OpenAI API Key hinterlegt. Ein Administrator kann den Key mit </set_api_key:{id}> einrichten.',
    en: '⚠️ No OpenAI API Key configured for this server. An admin can configure it with </set_api_key:{id}>.',
    fr: '⚠️ Aucune clé API OpenAI configurée. Un admin peut la définir avec </set_api_key:{id}>.',
    es: '⚠️ No se ha configurado una clave API de OpenAI. Un admin puede configurarla con </set_api_key:{id}>.',
    pt: '⚠️ Nenhuma chave de API da OpenAI configurada. Um admin pode configurar com </set_api_key:{id}>.',
    ru: '⚠️ Для сервера не настроен ключ OpenAI API. Администратор может установить его через </set_api_key:{id}>.',
    ja: '⚠️ このサーバーにはOpenAI APIキーが設定されていません。管理者は </set_api_key:{id}> で設定できます。',
    ko: '⚠️ 서버에 OpenAI API 키가 설정되지 않았습니다. 관리자가 </set_api_key:{id}> 명령어로 설정할 수 있습니다.',
    zh: '⚠️ 本服务器尚未配置 OpenAI API 密钥。管理员可通过 </set_api_key:{id}> 进行配置。',
    it: '⚠️ Nessuna chiave API OpenAI configurata. Un admin può impostarla con </set_api_key:{id}>.',
  },
  errGeneric: {
    de: '❌ Ein unerwarteter Fehler ist aufgetreten. Bitte versuche es später erneut.',
    en: '❌ An unexpected error occurred. Please try again later.',
    fr: '❌ Une erreur inattendue est survenue. Veuillez réessayer plus tard.',
    es: '❌ Ha ocurrido un error inesperado. Inténtalo de nuevo más tarde.',
    pt: '❌ Ocorreu um erro inesperado. Tente novamente mais tarde.',
    ru: '❌ Произошла непредвиденная ошибка. Пожалуйста, повторите попытку позже.',
    ja: '❌ 予期しないエラーが発生しました。後でもう一度お試しください。',
    ko: '❌ 예기치 않은 오류가 발생했습니다. 잠시 후 다시 시도해주세요.',
    zh: '❌ 发生未知错误，请稍后重试。',
    it: '❌ Si è verificato un errore imprevisto. Riprova più tardi.',
  },

  // Profile commands
  profileChoiceStandard: {
    de: 'Standard-Avatar (Bot-Default)',
    en: 'Default Avatar (Bot default)',
    fr: 'Avatar par défaut du bot',
    es: 'Avatar predeterminado del bot',
    pt: 'Avatar padrão do bot',
    ru: 'Стандартный аватар бота',
    ja: 'デフォルトアバター（初期状態）',
    ko: '기본 아바타 (봇 기본값)',
    zh: '默认头像（机器人初始外观）',
    it: 'Avatar predefinito del bot',
  },
  profileChoiceServer: {
    de: 'Server-Icon',
    en: 'Server Icon',
    fr: 'Icône du serveur',
    es: 'Icono del servidor',
    pt: 'Ícone do servidor',
    ru: 'Иконка сервера',
    ja: 'サーバーアイコン',
    ko: '서버 아이콘',
    zh: '服务器图标',
    it: 'Icona del server',
  },
  profileChoiceOwner: {
    de: 'Server-Owner Avatar',
    en: 'Server Owner Avatar',
    fr: 'Avatar du propriétaire du serveur',
    es: 'Avatar del dueño del servidor',
    pt: 'Avatar do dono do servidor',
    ru: 'Аватар владельца сервера',
    ja: 'サーバーオーナーのアバター',
    ko: '서버 소유자 아바타',
    zh: '服务器所有者头像',
    it: 'Avatar del proprietario del server',
  },
  profileSet: {
    de: '✅ Profilbild des Sicherheitsbots wurde auf **{choice}** gesetzt.',
    en: '✅ Security bot avatar has been updated to **{choice}**.',
    fr: '✅ L\'avatar du bot de sécurité a été changé pour **{choice}**.',
    es: '✅ El avatar del bot de seguridad se ha cambiado a **{choice}**.',
    pt: '✅ O avatar do bot de segurança foi alterado para **{choice}**.',
    ru: '✅ Аватар бота безопасности успешно изменен на **{choice}**.',
    ja: '✅ セキュリティボットのアバターが **{choice}** に設定されました。',
    ko: '✅ 보안 봇 프로필 사진이 **{choice}**(으)로 설정되었습니다.',
    zh: '✅ 安全机器人的服务器头像已成功更新为 **{choice}**。',
    it: '✅ L\'avatar del bot di sicurezza è stato impostato su **{choice}**.',
  },
  errAvatarPerms: {
    de: '❌ Dem Bot fehlt die Berechtigung „Server-Profil anpassen“ (Change Nickname / Manage Nicknames / Bot Role).',
    en: '❌ The bot lacks permission to change its server avatar.',
    fr: '❌ Le bot n\'a pas la permission de modifier son profil sur le serveur.',
    es: '❌ El bot no tiene permisos para cambiar su perfil en el servidor.',
    pt: '❌ O bot não possui permissão para alterar o perfil no servidor.',
    ru: '❌ У бота нет прав для изменения своего профиля на сервере.',
    ja: '❌ ボットにサーバープロフィールを変更する権限がありません。',
    ko: '❌ 봇에 서버 프로필을 변경할 권한이 없습니다.',
    zh: '❌ 机器人缺少修改本服务器个人资料的权限。',
    it: '❌ Il bot non dispone dei permessi per modificare il proprio profilo sul server.',
  },
  errAvatar: {
    de: '❌ Profilbild konnte nicht geändert werden: {error}',
    en: '❌ Could not change avatar: {error}',
    fr: '❌ Impossible de modifier l\'avatar : {error}',
    es: '❌ No se pudo cambiar el avatar: {error}',
    pt: '❌ Não foi possível alterar o avatar: {error}',
    ru: '❌ Не удалось изменить аватар: {error}',
    ja: '❌ アバターを変更できませんでした: {error}',
    ko: '❌ 프로필 사진을 변경할 수 없습니다: {error}',
    zh: '❌ 更换头像失败：{error}',
    it: '❌ Impossibile modificare l\'avatar: {error}',
  },
  errServerNoIcon: {
    de: '❌ Dieser Server hat kein Server-Icon.',
    en: '❌ This server does not have an icon.',
    fr: '❌ Ce serveur n\'a pas d\'icône.',
    es: '❌ Este servidor no tiene un icono configurado.',
    pt: '❌ Este servidor não possui um ícone configurado.',
    ru: '❌ У этого сервера нет иконки.',
    ja: '❌ このサーバーにはアイコンが設定されていません。',
    ko: '❌ 이 서버에는 설정된 아이콘이 없습니다.',
    zh: '❌ 当前服务器尚未设置服务器图标。',
    it: '❌ Questo server non ha un\'icona.',
  },

  // Owner Admin Panel (German only as per pattern)
  apTitle: { de: '🛡️ Sicherheits-Bot – Owner Admin Panel' },
  apNoServers: { de: 'Der Sicherheits-Bot befindet sich aktuell auf keinem Server.' },
  apSelectPlaceholder: { de: 'Server für Details auswählen…' },
  apServerListDesc: { de: 'Der Bot ist auf **{count}** Server(n) aktiv:\n\n{list}' },
  apPage: { de: 'Seite {page} von {total}' },
  apBtnPrev: { de: '◀ Zurück' },
  apBtnRefresh: { de: '🔄 Aktualisieren' },
  apBtnNext: { de: 'Weiter ▶' },
  apDetailTitle: { de: '🛡️ Server-Details' },
  apDetailName: { de: '🏷️ **Name:** {name}' },
  apDetailOwner: { de: '👑 **Owner:** {mention}' },
  apDetailMembers: { de: '👥 **Mitglieder:** {count}' },
  apDetailSetup: { de: '⚙️ **API Key Status:** {status}' },
  apDetailViolations: { de: '🚨 **Erfasste Verstöße:** {count}' },
  apSetupYes: { de: '✅ API Key hinterlegt' },
  apSetupNo: { de: '❌ Kein API Key hinterlegt' },
  apLeaveAsk: { de: 'Möchtest du den Bot wirklich von „{name}“ entfernen?' },
  apInviteSent: { de: 'Einladung erstellt:' },
  apInviteLink: { de: '[Klicke hier, um dem Server beizutreten]({url})' },
  apInviteFailed: { de: 'Konnte keine Einladung erstellen: {error}' },
  apBtnBack: { de: '◀ Zurück zur Liste' },
  apBtnInvite: { de: '🔗 Einladung erstellen' },
  apBtnLeave: { de: '🚪 Server verlassen' },
  apBtnLeaveConfirm: { de: 'Ja, Server verlassen' },
  apBtnLeaveCancel: { de: 'Abbrechen' },
  apLeft: { de: 'Der Bot hat den Server „{name}“ verlassen.' },
  apJoinNotice: { de: 'Der Sicherheits-Bot wurde zum Server **{name}** hinzugefügt!\n- Mitglieder: **{members}**\n- Owner: {owner}' },
  apNeedDm: { de: 'Das Admin-Panel kann nur im Privatchat (DM) mit dem Bot geöffnet werden.' },
};

function t(key, lang = 'de', params = {}) {
  const entry = T[key];
  if (!entry) return `[Missing:${key}]`;
  let str = entry[lang] ?? entry.en ?? entry.de ?? Object.values(entry)[0] ?? '';
  if (typeof str !== 'string') return '';
  for (const [k, v] of Object.entries(params)) {
    str = str.replaceAll(`{${k}}`, String(v ?? ''));
  }
  return str;
}

module.exports = {
  LANGS,
  DISCORD_LOCALE,
  DISCORD_LOCALE_MAP,
  T,
  t,
  tzOf,
  langFromDiscord,
};
