/**
 * ============================================================================
 *  🎭 Self-Roles-Bot – DIE Sprachdatei (alle 10 Sprachen in EINER Datei).
 *
 *  Aufbau exakt wie beim Geburtstags-Bot:
 *  - Jeder Text-Key enthält direkt untereinander alle 10 Sprachen.
 *  - Die 10 meistgenutzten Discord-Sprachen: Deutsch, Englisch, Französisch,
 *    Spanisch, Portugiesisch (BR), Russisch, Japanisch, Koreanisch,
 *    Chinesisch (CN), Italienisch.
 *  - T-Keys, die nur `de` enthalten, sind bewusst nur auf Deutsch
 *    (z. B. das Owner-Admin-Panel).
 *
 *  Platzhalter in Texten: {title}, {count}, {role} … werden zur Laufzeit
 *  ersetzt (siehe t() am Ende der Datei).
 * ============================================================================
 */

const LANGS = {
  de: {
    name: 'Deutsch',
    names: { de: 'Deutsch', en: 'German', fr: 'Allemand', es: 'Alemán', pt: 'Alemão', ru: 'Немецкий', ja: 'ドイツ語', ko: '독일어', zh: '德语', it: 'Tedesco' },
    flag: '🇩🇪',
    locale: 'de-DE',
  },
  en: {
    name: 'English',
    names: { de: 'Englisch', en: 'English', fr: 'Anglais', es: 'Inglés', pt: 'Inglês', ru: 'Английский', ja: '英語', ko: '영어', zh: '英语', it: 'Inglese' },
    flag: '🇬🇧',
    locale: 'en-US',
  },
  fr: {
    name: 'Français',
    names: { de: 'Französisch', en: 'French', fr: 'Français', es: 'Francés', pt: 'Francês', ru: 'Французский', ja: 'フランス語', ko: '프랑스어', zh: '法语', it: 'Francese' },
    flag: '🇫🇷',
    locale: 'fr-FR',
  },
  es: {
    name: 'Español',
    names: { de: 'Spanisch', en: 'Spanish', fr: 'Espagnol', es: 'Español', pt: 'Espanhol', ru: 'Испанский', ja: 'スペイン語', ko: '스페인어', zh: '西班牙语', it: 'Spagnolo' },
    flag: '🇪🇸',
    locale: 'es-ES',
  },
  pt: {
    name: 'Português',
    names: { de: 'Portugiesisch', en: 'Portuguese', fr: 'Portugais', es: 'Portugués', pt: 'Português', ru: 'Португальский', ja: 'ポルトガル語', ko: '포르투갈어', zh: '葡萄牙语', it: 'Portoghese' },
    flag: '🇧🇷',
    locale: 'pt-BR',
  },
  ru: {
    name: 'Русский',
    names: { de: 'Russisch', en: 'Russian', fr: 'Russe', es: 'Ruso', pt: 'Russo', ru: 'Русский', ja: 'ロシア語', ko: '러시아어', zh: '俄语', it: 'Russo' },
    flag: '🇷🇺',
    locale: 'ru-RU',
  },
  ja: {
    name: '日本語',
    names: { de: 'Japanisch', en: 'Japanese', fr: 'Japonais', es: 'Japonés', pt: 'Japonês', ru: 'Японский', ja: '日本語', ko: '일본어', zh: '日语', it: 'Giapponese' },
    flag: '🇯🇵',
    locale: 'ja-JP',
  },
  ko: {
    name: '한국어',
    names: { de: 'Koreanisch', en: 'Korean', fr: 'Coréen', es: 'Coreano', pt: 'Coreano', ru: 'Корейский', ja: '韓国語', ko: '한국어', zh: '韩语', it: 'Coreano' },
    flag: '🇰🇷',
    locale: 'ko-KR',
  },
  zh: {
    name: '中文',
    names: { de: 'Chinesisch', en: 'Chinese', fr: 'Chinois', es: 'Chino', pt: 'Chinês', ru: 'Китайский', ja: '中国語', ko: '중국어', zh: '中文', it: 'Cinese' },
    flag: '🇨🇳',
    locale: 'zh-CN',
  },
  it: {
    name: 'Italiano',
    names: { de: 'Italienisch', en: 'Italian', fr: 'Italien', es: 'Italiano', pt: 'Italiano', ru: 'Итальянский', ja: 'イタリア語', ko: '이탈리아어', zh: '意大利语', it: 'Italiano' },
    flag: '🇮🇹',
    locale: 'it-IT',
  },
};

const T = {
  // ----------------------------------------------------------
  // Allgemeine Fehler
  // ----------------------------------------------------------
  errGuildOnly: {
    de: '🚫 Das geht nur auf einem Server – im Privatchat gibt es keine Rollen zu verteilen.',
    en: '🚫 Server-only command – there are no roles to hand out in a DM.',
    fr: '🚫 Uniquement sur un serveur – aucun rôle à distribuer en MP.',
    es: '🚫 Solo en un servidor – en los MD no hay roles que repartir.',
    pt: '🚫 Só funciona num servidor – no privado não há cargos para distribuir.',
    ru: '🚫 Только на сервере – в личке раздавать нечего.',
    ja: '🚫 サーバー専用コマンドです。DM に配れるロールはありません。',
    ko: '🚫 서버 전용 명령어예요. DM에는 나눠줄 역할이 없어요.',
    zh: '🚫 该命令仅限服务器使用——私聊里没有身份组可发。',
    it: '🚫 Solo nei server – nei DM non ci sono ruoli da distribuire.',
  },
  errNoPermission: {
    de: '🛑 Nur Admins dürfen an den Self-Roles schrauben. Nice try! 😏',
    en: '🛑 Only admins may tinker with the self-roles. Nice try! 😏',
    fr: '🛑 Seuls les admins peuvent toucher aux self-roles. Bien tenté ! 😏',
    es: '🛑 Solo los admins pueden tocar los self-roles. ¡Buen intento! 😏',
    pt: '🛑 Só admins mexem nos self-roles. Boa tentativa! 😏',
    ru: '🛑 Крутить self-roles могут только админы. Хорошая попытка! 😏',
    ja: '🛑 セルフロールをいじれるのは管理者だけです。惜しい！😏',
    ko: '🛑 셀프 역할은 관리자만 만질 수 있어요. 시도는 좋았어요! 😏',
    zh: '🛑 只有管理员能改自助身份组。想得美！😏',
    it: '🛑 Solo gli admin possono toccare i self-role. Bel tentativo! 😏',
  },
  errGeneric: {
    de: '💥 Da ist was explodiert. Versuch es nochmal – der Bot sammelt gerade seine Einzelteile ein.',
    en: '💥 Something blew up. Try again – the bot is picking up its pieces.',
    fr: '💥 Quelque chose a explosé. Réessaie – le bot ramasse ses morceaux.',
    es: '💥 Algo ha explotado. Inténtalo de nuevo – el bot está recogiendo sus piezas.',
    pt: '💥 Algo explodiu. Tenta de novo – o bot está juntando os pedaços.',
    ru: '💥 Что-то рвануло. Попробуй снова – бот собирает себя по кусочкам.',
    ja: '💥 何かが爆発しました。もう一度どうぞ – ボットが破片を拾っています。',
    ko: '💥 뭔가 터졌어요. 다시 시도해 주세요 – 봇이 조각을 줍는 중입니다.',
    zh: '💥 出了点小爆炸。再试一次——机器人正在捡碎片。',
    it: '💥 Qualcosa è esploso. Riprova – il bot sta raccogliendo i pezzi.',
  },
  errBotPerms: {
    de: '🔐 Mir fehlt **„Rollen verwalten“** (oder meine Rolle hängt zu weit unten). Schieb mich hoch und ich mach den Rest! 💪',
    en: '🔐 I need **“Manage Roles”** (or my role sits too low). Move me up and I’ll handle the rest! 💪',
    fr: '🔐 Il me faut **« Gérer les rôles »** (ou mon rôle est trop bas). Remonte-moi et je gère ! 💪',
    es: '🔐 Necesito **«Gestionar roles»** (o mi rol está demasiado abajo). ¡Súbeme y yo me encargo! 💪',
    pt: '🔐 Preciso de **“Gerenciar cargos”** (ou meu cargo está baixo demais). Me sobe que eu resolvo! 💪',
    ru: '🔐 Мне нужно право **«Управлять ролями»** (или моя роль слишком низко). Подними меня – дальше сам! 💪',
    ja: '🔐 **「ロールの管理」**が必要です（または私のロールが下すぎます）。上げてくれれば後は任せて！💪',
    ko: '🔐 **“역할 관리”** 권한이 필요해요 (또는 제 역할이 너무 아래예요). 올려주시면 나머지는 제가! 💪',
    zh: '🔐 我需要**“管理身份组”**权限（或者我的身份组太靠下）。把我往上挪，剩下的交给我！💪',
    it: '🔐 Mi serve **“Gestire i ruoli”** (o il mio ruolo è troppo in basso). Spostami su e faccio il resto! 💪',
  },
  errSessionExpired: {
    de: '⌛ Diese Bearbeitungs-Session ist abgelaufen oder der Bot wurde neu gestartet. Öffne den Editor einfach neu – deine bereits gesendete Nachricht ist safe! 🛟',
    en: '⌛ This editing session expired or the bot restarted. Just open the editor again – your published message is safe! 🛟',
    fr: '⌛ Session d’édition expirée ou bot redémarré. Rouvre l’éditeur – ton message publié est intact ! 🛟',
    es: '⌛ Esta sesión de edición ha caducado o el bot se reinició. Abre el editor de nuevo – ¡tu mensaje publicado está a salvo! 🛟',
    pt: '⌛ Esta sessão de edição expirou ou o bot reiniciou. Abra o editor de novo – sua mensagem publicada está segura! 🛟',
    ru: '⌛ Сессия редактирования истекла или бот перезапустился. Просто открой редактор снова – опубликованное сообщение цело! 🛟',
    ja: '⌛ 編集セッションが期限切れ、またはボットが再起動しました。エディタを開き直してください – 投稿済みメッセージは無事です！🛟',
    ko: '⌛ 편집 세션이 만료됐거나 봇이 재시작됐어요. 편집기를 다시 열어주세요 – 게시된 메시지는 안전합니다! 🛟',
    zh: '⌛ 编辑会话已过期或机器人重启了。重新打开编辑器即可——已发布的消息安然无恙！🛟',
    it: '⌛ Sessione di modifica scaduta o bot riavviato. Riapri l’editor – il messaggio pubblicato è al sicuro! 🛟',
  },
  errMaxMessages: {
    de: '📦 Maximum erreicht: **10 Self-Roles-Nachrichten** pro Server. Lösch eine alte, dann gibt’s wieder Platz im Regal.',
    en: '📦 Limit reached: **10 self-role messages** per server. Delete an old one to free a shelf.',
    fr: '📦 Limite atteinte : **10 messages self-role** par serveur. Supprime-en un pour faire de la place.',
    es: '📦 Límite alcanzado: **10 mensajes de self-roles** por servidor. Borra uno viejo para hacer sitio.',
    pt: '📦 Limite atingido: **10 mensagens de self-roles** por servidor. Apague uma antiga para abrir espaço.',
    ru: '📦 Достигнут лимит: **10 сообщений self-roles** на сервер. Удали старое – освободится место.',
    ja: '📦 上限に達しました：サーバーごとに**セルフロールメッセージ 10 件**まで。古いものを削除してね。',
    ko: '📦 한도 도달: 서버당 **셀프 역할 메시지 10개**. 오래된 걸 지우면 자리가 생겨요.',
    zh: '📦 已达上限：每个服务器 **10 条自助身份组消息**。删掉一条旧的就有位置了。',
    it: '📦 Limite raggiunto: **10 messaggi self-role** per server. Cancellane uno vecchio per fare spazio.',
  },
  errChannelBad: {
    de: '📭 In diesem Kanal kann ich nicht schreiben (oder es ist kein Textkanal). Wähl einen anderen!',
    en: '📭 I can’t post in that channel (or it isn’t a text channel). Pick another one!',
    fr: '📭 Je ne peux pas écrire dans ce salon (ou ce n’est pas un salon textuel). Choisis-en un autre !',
    es: '📭 No puedo escribir en ese canal (o no es un canal de texto). ¡Elige otro!',
    pt: '📭 Não consigo postar nesse canal (ou não é um canal de texto). Escolha outro!',
    ru: '📭 Я не могу писать в этот канал (или это не текстовый канал). Выбери другой!',
    ja: '📭 そのチャンネルには投稿できません（またはテキストチャンネルではありません）。別のを選んでね！',
    ko: '📭 그 채널에는 글을 쓸 수 없어요 (또는 텍스트 채널이 아니에요). 다른 채널을 골라주세요!',
    zh: '📭 我无法在该频道发言（或它不是文字频道）。换一个吧！',
    it: '📭 Non posso scrivere in quel canale (o non è un canale testuale). Scegline un altro!',
  },

  // ----------------------------------------------------------
  // /create_self_role – Formular
  // ----------------------------------------------------------
  createModalTitle: {
    de: '🎭 Neue Self-Roles-Nachricht',
    en: '🎭 New self-roles message',
    fr: '🎭 Nouveau message self-roles',
    es: '🎭 Nuevo mensaje de self-roles',
    pt: '🎭 Nova mensagem de self-roles',
    ru: '🎭 Новое сообщение self-roles',
    ja: '🎭 新しいセルフロール',
    ko: '🎭 새 셀프 역할 메시지',
    zh: '🎭 新的自助身份组消息',
    it: '🎭 Nuovo messaggio self-role',
  },
  createTitleLabel: {
    de: 'Titel der Nachricht',
    en: 'Message title',
    fr: 'Titre du message',
    es: 'Título del mensaje',
    pt: 'Título da mensagem',
    ru: 'Заголовок сообщения',
    ja: 'メッセージのタイトル',
    ko: '메시지 제목',
    zh: '消息标题',
    it: 'Titolo del messaggio',
  },
  createTitlePlaceholder: {
    de: 'z. B. Wähle deine Rollen 🎉',
    en: 'e.g. Pick your roles 🎉',
    fr: 'ex. Choisis tes rôles 🎉',
    es: 'p. ej. Elige tus roles 🎉',
    pt: 'ex.: Escolha seus cargos 🎉',
    ru: 'напр. Выбери свои роли 🎉',
    ja: '例：ロールを選ぼう 🎉',
    ko: '예: 역할을 골라보세요 🎉',
    zh: '例如：来选你的身份组 🎉',
    it: 'es. Scegli i tuoi ruoli 🎉',
  },
  createDescLabel: {
    de: 'Beschreibung (1 Zeile, wird geglättet)',
    en: 'Description (1 line, gets flattened)',
    fr: 'Description (1 ligne, aplatie)',
    es: 'Descripción (1 línea, se aplana)',
    pt: 'Descrição (1 linha, é achatada)',
    ru: 'Описание (1 строка, склеится)',
    ja: '説明（1行に整形されます）',
    ko: '설명 (1줄로 정리됩니다)',
    zh: '描述（会合并为 1 行）',
    it: 'Descrizione (1 riga, viene appiattita)',
  },
  createDescPlaceholder: {
    de: 'Klick dich reich – Zeilenumbrüche werden zu Leerzeichen.',
    en: 'Click away – line breaks become spaces.',
    fr: 'Clique à volonté – les retours à la ligne deviennent des espaces.',
    es: 'Haz clic sin miedo – los saltos de línea pasan a ser espacios.',
    pt: 'Clique à vontade – quebras de linha viram espaços.',
    ru: 'Кликай смело – переносы строк станут пробелами.',
    ja: 'ポチポチどうぞ – 改行はスペースになります。',
    ko: '마음껏 눌러요 – 줄바꿈은 공백이 됩니다.',
    zh: '尽情点击——换行会变成空格。',
    it: 'Clicca pure – gli a capo diventano spazi.',
  },

  // ----------------------------------------------------------
  // Editor (Bestätigungs-/Bearbeitungs-Nachricht)
  // ----------------------------------------------------------
  editorTitle: {
    de: '🛠️ Self-Roles-Werkstatt',
    en: '🛠️ Self-roles workshop',
    fr: '🛠️ Atelier self-roles',
    es: '🛠️ Taller de self-roles',
    pt: '🛠️ Oficina de self-roles',
    ru: '🛠️ Мастерская self-roles',
    ja: '🛠️ セルフロール工房',
    ko: '🛠️ 셀프 역할 공방',
    zh: '🛠️ 自助身份组工坊',
    it: '🛠️ Officina self-role',
  },
  editorIntroNew: {
    de: 'Letzter Check, bevor das Ding live geht. Alles korrekt? Dann Feuer frei! 🚀',
    en: 'Final check before this thing goes live. All good? Then let it rip! 🚀',
    fr: 'Dernier contrôle avant le grand saut. Tout est bon ? Alors go ! 🚀',
    es: 'Última revisión antes de que salga en vivo. ¿Todo bien? ¡Entonces fuego! 🚀',
    pt: 'Última conferida antes de ir ao ar. Tudo certo? Então manda ver! 🚀',
    ru: 'Последняя проверка перед запуском. Всё ок? Тогда поехали! 🚀',
    ja: '公開前の最終チェック。問題なし？ならば発射！🚀',
    ko: '공개 전 마지막 점검. 괜찮나요? 그럼 발사! 🚀',
    zh: '上线前最后检查。没问题？那就发射！🚀',
    it: 'Ultimo controllo prima del lancio. Tutto ok? Allora via! 🚀',
  },
  editorIntroEdit: {
    de: 'Du bearbeitest eine **bestehende** Nachricht. Änderungen gehen erst mit „Speichern“ live. ✍️',
    en: 'You’re editing an **existing** message. Changes go live only on “Save”. ✍️',
    fr: 'Tu modifies un message **existant**. Les changements ne s’appliquent qu’en « Enregistrer ». ✍️',
    es: 'Estás editando un mensaje **existente**. Los cambios se aplican al pulsar «Guardar». ✍️',
    pt: 'Você está editando uma mensagem **existente**. As mudanças só valem ao “Salvar”. ✍️',
    ru: 'Ты редактируешь **существующее** сообщение. Изменения применятся по кнопке «Сохранить». ✍️',
    ja: '**既存の**メッセージを編集中です。変更は「保存」で反映されます。✍️',
    ko: '**기존** 메시지를 편집 중이에요. 변경은 “저장”을 눌러야 반영됩니다. ✍️',
    zh: '你正在编辑**已有**消息。改动需点“保存”才生效。✍️',
    it: 'Stai modificando un messaggio **esistente**. Le modifiche vanno live solo con “Salva”. ✍️',
  },
  editorChannel: {
    de: '📍 **Kanal:** {channel}',
    en: '📍 **Channel:** {channel}',
    fr: '📍 **Salon :** {channel}',
    es: '📍 **Canal:** {channel}',
    pt: '📍 **Canal:** {channel}',
    ru: '📍 **Канал:** {channel}',
    ja: '📍 **チャンネル:** {channel}',
    ko: '📍 **채널:** {channel}',
    zh: '📍 **频道：** {channel}',
    it: '📍 **Canale:** {channel}',
  },
  editorMsgTitle: {
    de: '🏷️ **Titel:** {title}',
    en: '🏷️ **Title:** {title}',
    fr: '🏷️ **Titre :** {title}',
    es: '🏷️ **Título:** {title}',
    pt: '🏷️ **Título:** {title}',
    ru: '🏷️ **Заголовок:** {title}',
    ja: '🏷️ **タイトル:** {title}',
    ko: '🏷️ **제목:** {title}',
    zh: '🏷️ **标题：** {title}',
    it: '🏷️ **Titolo:** {title}',
  },
  editorDesc: {
    de: '📝 **Beschreibung:** {desc}',
    en: '📝 **Description:** {desc}',
    fr: '📝 **Description :** {desc}',
    es: '📝 **Descripción:** {desc}',
    pt: '📝 **Descrição:** {desc}',
    ru: '📝 **Описание:** {desc}',
    ja: '📝 **説明:** {desc}',
    ko: '📝 **설명:** {desc}',
    zh: '📝 **描述：** {desc}',
    it: '📝 **Descrizione:** {desc}',
  },
  editorDescEmpty: {
    de: '*(leer – mutig!)*',
    en: '*(empty – bold move!)*',
    fr: '*(vide – audacieux !)*',
    es: '*(vacía – ¡qué valiente!)*',
    pt: '*(vazia – corajoso!)*',
    ru: '*(пусто – смело!)*',
    ja: '*(空欄 – 攻めるね！)*',
    ko: '*(비어 있음 – 대담하네요!)*',
    zh: '*（空的——很勇！）*',
    it: '*(vuota – che coraggio!)*',
  },
  editorMode: {
    de: '🎚️ **Auswahl:** {mode}',
    en: '🎚️ **Selection:** {mode}',
    fr: '🎚️ **Sélection :** {mode}',
    es: '🎚️ **Selección:** {mode}',
    pt: '🎚️ **Seleção:** {mode}',
    ru: '🎚️ **Выбор:** {mode}',
    ja: '🎚️ **選択方式:** {mode}',
    ko: '🎚️ **선택 방식:** {mode}',
    zh: '🎚️ **选择方式：** {mode}',
    it: '🎚️ **Selezione:** {mode}',
  },
  modeSingle: {
    de: 'nur EINE Rolle (neue Rolle wirft die alte raus)',
    en: 'only ONE role (a new pick kicks the old one)',
    fr: 'un SEUL rôle (le nouveau éjecte l’ancien)',
    es: 'solo UN rol (el nuevo echa al anterior)',
    pt: 'só UM cargo (o novo expulsa o antigo)',
    ru: 'только ОДНА роль (новая выкидывает старую)',
    ja: '1つだけ（新しいロールが古いロールを追い出す）',
    ko: '오직 하나 (새로 고르면 이전 역할은 사라짐)',
    zh: '只能选一个（新的会顶掉旧的）',
    it: 'solo UN ruolo (il nuovo scalza il vecchio)',
  },
  modeMulti: {
    de: 'so viele wie du willst (Sammelwut erlaubt) 🧺',
    en: 'as many as you like (hoarding allowed) 🧺',
    fr: 'autant que tu veux (collectionne !) 🧺',
    es: 'todos los que quieras (acumular permitido) 🧺',
    pt: 'quantos quiser (pode colecionar) 🧺',
    ru: 'сколько угодно (собирай коллекцию) 🧺',
    ja: '好きなだけ（コレクション歓迎）🧺',
    ko: '원하는 만큼 (수집 환영) 🧺',
    zh: '想要多少都行（欢迎收集）🧺',
    it: 'quanti vuoi (collezionismo consentito) 🧺',
  },
  editorRolesTitle: {
    de: '### 🎭 Rollen ({count}/{max})',
    en: '### 🎭 Roles ({count}/{max})',
    fr: '### 🎭 Rôles ({count}/{max})',
    es: '### 🎭 Roles ({count}/{max})',
    pt: '### 🎭 Cargos ({count}/{max})',
    ru: '### 🎭 Роли ({count}/{max})',
    ja: '### 🎭 ロール ({count}/{max})',
    ko: '### 🎭 역할 ({count}/{max})',
    zh: '### 🎭 身份组 ({count}/{max})',
    it: '### 🎭 Ruoli ({count}/{max})',
  },
  editorNoRoles: {
    de: '🫥 **Noch keine Rollen konfiguriert.** Minimum sind **{min}**, Maximum **{max}** – ran an die Buttons!',
    en: '🫥 **No roles configured yet.** Minimum **{min}**, maximum **{max}** – hit those buttons!',
    fr: '🫥 **Aucun rôle configuré.** Minimum **{min}**, maximum **{max}** – clique sur les boutons !',
    es: '🫥 **Aún no hay roles configurados.** Mínimo **{min}**, máximo **{max}** – ¡a los botones!',
    pt: '🫥 **Nenhum cargo configurado ainda.** Mínimo **{min}**, máximo **{max}** – bora nos botões!',
    ru: '🫥 **Ролей пока нет.** Минимум **{min}**, максимум **{max}** – жми кнопки!',
    ja: '🫥 **まだロールがありません。** 最低 **{min}**、最大 **{max}** – ボタンを押そう！',
    ko: '🫥 **아직 역할이 없어요.** 최소 **{min}**, 최대 **{max}** – 버튼을 눌러요!',
    zh: '🫥 **还没有配置身份组。** 最少 **{min}**，最多 **{max}** —— 快按按钮！',
    it: '🫥 **Nessun ruolo configurato.** Minimo **{min}**, massimo **{max}** – premi i pulsanti!',
  },
  editorRoleLineNew: {
    de: '`{index}.` **{label}** → Rolle „{name}“ *(wird beim Absenden erstellt)*',
    en: '`{index}.` **{label}** → role “{name}” *(created on publish)*',
    fr: '`{index}.` **{label}** → rôle « {name} » *(créé à la publication)*',
    es: '`{index}.` **{label}** → rol «{name}» *(se crea al publicar)*',
    pt: '`{index}.` **{label}** → cargo “{name}” *(criado ao publicar)*',
    ru: '`{index}.` **{label}** → роль «{name}» *(создастся при публикации)*',
    ja: '`{index}.` **{label}** → ロール「{name}」*(送信時に作成)*',
    ko: '`{index}.` **{label}** → 역할 “{name}” *(게시할 때 생성)*',
    zh: '`{index}.` **{label}** → 身份组“{name}”*(发布时创建)*',
    it: '`{index}.` **{label}** → ruolo “{name}” *(creato alla pubblicazione)*',
  },
  editorRoleLineExisting: {
    de: '`{index}.` **{label}** → {mention} *(bereits vorhanden)*',
    en: '`{index}.` **{label}** → {mention} *(already exists)*',
    fr: '`{index}.` **{label}** → {mention} *(déjà existant)*',
    es: '`{index}.` **{label}** → {mention} *(ya existe)*',
    pt: '`{index}.` **{label}** → {mention} *(já existe)*',
    ru: '`{index}.` **{label}** → {mention} *(уже есть)*',
    ja: '`{index}.` **{label}** → {mention} *(既存)*',
    ko: '`{index}.` **{label}** → {mention} *(이미 있음)*',
    zh: '`{index}.` **{label}** → {mention} *(已存在)*',
    it: '`{index}.` **{label}** → {mention} *(già esistente)*',
  },
  editorNeedMore: {
    de: '⚠️ Es fehlen noch **{missing}** Rolle(n) bis zum Minimum von {min}.',
    en: '⚠️ Still **{missing}** role(s) short of the minimum of {min}.',
    fr: '⚠️ Il manque encore **{missing}** rôle(s) pour atteindre le minimum de {min}.',
    es: '⚠️ Faltan **{missing}** rol(es) para el mínimo de {min}.',
    pt: '⚠️ Faltam **{missing}** cargo(s) para o mínimo de {min}.',
    ru: '⚠️ Не хватает **{missing}** роли(ей) до минимума в {min}.',
    ja: '⚠️ 最低 {min} まであと **{missing}** 個のロールが必要です。',
    ko: '⚠️ 최소 {min}개까지 **{missing}**개 더 필요해요.',
    zh: '⚠️ 距离最少 {min} 个还差 **{missing}** 个身份组。',
    it: '⚠️ Mancano ancora **{missing}** ruoli per il minimo di {min}.',
  },
  editorReady: {
    de: '✅ Startklar! Drück den Knopf und lass es krachen.',
    en: '✅ Ready to fly! Hit the button and make it rain.',
    fr: '✅ Prêt à décoller ! Appuie et fais péter.',
    es: '✅ ¡Listo para despegar! Pulsa el botón y que arda.',
    pt: '✅ Pronto pra decolar! Aperta o botão e detona.',
    ru: '✅ Готово к запуску! Жми кнопку и жги.',
    ja: '✅ 準備完了！ボタンを押してぶちかませ。',
    ko: '✅ 준비 완료! 버튼을 눌러 터뜨려요.',
    zh: '✅ 万事俱备！按下按钮，开整。',
    it: '✅ Pronto al decollo! Premi il pulsante e spacca.',
  },
  editorRemoveHint: {
    de: 'ℹ️ Entfernte Rollen bleiben auf dem Server bestehen – ich lösche nichts hinter deinem Rücken.',
    en: 'ℹ️ Removed entries keep their server role – I don’t delete anything behind your back.',
    fr: 'ℹ️ Les entrées retirées conservent leur rôle sur le serveur – je ne supprime rien dans ton dos.',
    es: 'ℹ️ Las entradas quitadas conservan su rol en el servidor – no borro nada a tus espaldas.',
    pt: 'ℹ️ Entradas removidas mantêm o cargo no servidor – não apago nada pelas suas costas.',
    ru: 'ℹ️ Удалённые пункты сохраняют роль на сервере – я ничего не удаляю тайком.',
    ja: 'ℹ️ 削除した項目のサーバーロールは残ります – 勝手に消したりしません。',
    ko: 'ℹ️ 제거한 항목의 서버 역할은 남습니다 – 몰래 지우지 않아요.',
    zh: 'ℹ️ 被移除的条目仍保留服务器身份组——我不会背着你删东西。',
    it: 'ℹ️ Le voci rimosse mantengono il ruolo sul server – non cancello nulla alle tue spalle.',
  },

  // ----------------------------------------------------------
  // Editor-Buttons
  // ----------------------------------------------------------
  btnAddRole: {
    de: '➕ Rolle hinzufügen',
    en: '➕ Add role',
    fr: '➕ Ajouter un rôle',
    es: '➕ Añadir rol',
    pt: '➕ Adicionar cargo',
    ru: '➕ Добавить роль',
    ja: '➕ ロールを追加',
    ko: '➕ 역할 추가',
    zh: '➕ 添加身份组',
    it: '➕ Aggiungi ruolo',
  },
  btnRemoveRole: {
    de: '➖ Rolle entfernen',
    en: '➖ Remove role',
    fr: '➖ Retirer un rôle',
    es: '➖ Quitar rol',
    pt: '➖ Remover cargo',
    ru: '➖ Убрать роль',
    ja: '➖ ロールを削除',
    ko: '➖ 역할 제거',
    zh: '➖ 移除身份组',
    it: '➖ Rimuovi ruolo',
  },
  btnEditText: {
    de: '✏️ Titel & Text',
    en: '✏️ Title & text',
    fr: '✏️ Titre & texte',
    es: '✏️ Título y texto',
    pt: '✏️ Título e texto',
    ru: '✏️ Заголовок и текст',
    ja: '✏️ タイトルと本文',
    ko: '✏️ 제목 & 본문',
    zh: '✏️ 标题和文字',
    it: '✏️ Titolo e testo',
  },
  btnToggleMode: {
    de: '🎚️ Auswahl umschalten',
    en: '🎚️ Toggle selection',
    fr: '🎚️ Basculer la sélection',
    es: '🎚️ Cambiar selección',
    pt: '🎚️ Alternar seleção',
    ru: '🎚️ Переключить выбор',
    ja: '🎚️ 選択方式を切替',
    ko: '🎚️ 선택 방식 전환',
    zh: '🎚️ 切换选择方式',
    it: '🎚️ Cambia selezione',
  },
  btnPublish: {
    de: '🚀 Absenden',
    en: '🚀 Publish',
    fr: '🚀 Publier',
    es: '🚀 Publicar',
    pt: '🚀 Publicar',
    ru: '🚀 Опубликовать',
    ja: '🚀 送信',
    ko: '🚀 게시',
    zh: '🚀 发送',
    it: '🚀 Pubblica',
  },
  btnSave: {
    de: '💾 Speichern',
    en: '💾 Save',
    fr: '💾 Enregistrer',
    es: '💾 Guardar',
    pt: '💾 Salvar',
    ru: '💾 Сохранить',
    ja: '💾 保存',
    ko: '💾 저장',
    zh: '💾 保存',
    it: '💾 Salva',
  },
  btnCancel: {
    de: '❌ Abbrechen',
    en: '❌ Cancel',
    fr: '❌ Annuler',
    es: '❌ Cancelar',
    pt: '❌ Cancelar',
    ru: '❌ Отмена',
    ja: '❌ キャンセル',
    ko: '❌ 취소',
    zh: '❌ 取消',
    it: '❌ Annulla',
  },
  btnBack: {
    de: '↩️ Zurück',
    en: '↩️ Back',
    fr: '↩️ Retour',
    es: '↩️ Atrás',
    pt: '↩️ Voltar',
    ru: '↩️ Назад',
    ja: '↩️ 戻る',
    ko: '↩️ 뒤로',
    zh: '↩️ 返回',
    it: '↩️ Indietro',
  },
  btnRemoveMyRole: {
    de: '🗑️ Rolle wieder abgeben',
    en: '🗑️ Give the role back',
    fr: '🗑️ Rendre le rôle',
    es: '🗑️ Devolver el rol',
    pt: '🗑️ Devolver o cargo',
    ru: '🗑️ Вернуть роль',
    ja: '🗑️ ロールを返す',
    ko: '🗑️ 역할 반납',
    zh: '🗑️ 交还身份组',
    it: '🗑️ Restituisci il ruolo',
  },

  // ----------------------------------------------------------
  // Rollen-Formular
  // ----------------------------------------------------------
  roleModalTitle: {
    de: '🎭 Rolle hinzufügen',
    en: '🎭 Add a role',
    fr: '🎭 Ajouter un rôle',
    es: '🎭 Añadir un rol',
    pt: '🎭 Adicionar um cargo',
    ru: '🎭 Добавить роль',
    ja: '🎭 ロールを追加',
    ko: '🎭 역할 추가',
    zh: '🎭 添加身份组',
    it: '🎭 Aggiungi un ruolo',
  },
  roleNameLabel: {
    de: 'Name der Rolle (wird erstellt)',
    en: 'Role name (will be created)',
    fr: 'Nom du rôle (sera créé)',
    es: 'Nombre del rol (se creará)',
    pt: 'Nome do cargo (será criado)',
    ru: 'Название роли (будет создана)',
    ja: 'ロール名（作成されます）',
    ko: '역할 이름 (생성됩니다)',
    zh: '身份组名称（将被创建）',
    it: 'Nome del ruolo (verrà creato)',
  },
  roleNamePlaceholder: {
    de: 'z. B. Gamer',
    en: 'e.g. Gamer',
    fr: 'ex. Gamer',
    es: 'p. ej. Gamer',
    pt: 'ex.: Gamer',
    ru: 'напр. Геймер',
    ja: '例：ゲーマー',
    ko: '예: 게이머',
    zh: '例如：玩家',
    it: 'es. Gamer',
  },
  roleLabelLabel: {
    de: 'Text-Platzhalter (Anzeige)',
    en: 'Text placeholder (display)',
    fr: 'Texte affiché (placeholder)',
    es: 'Texto mostrado (placeholder)',
    pt: 'Texto exibido (placeholder)',
    ru: 'Отображаемый текст',
    ja: '表示テキスト',
    ko: '표시 텍스트',
    zh: '显示文本',
    it: 'Testo mostrato',
  },
  roleLabelPlaceholder: {
    de: 'z. B. 🎮 Zocker-Squad',
    en: 'e.g. 🎮 Gamer squad',
    fr: 'ex. 🎮 Escouade gamer',
    es: 'p. ej. 🎮 Escuadrón gamer',
    pt: 'ex.: 🎮 Esquadrão gamer',
    ru: 'напр. 🎮 Отряд геймеров',
    ja: '例：🎮 ゲーマー部隊',
    ko: '예: 🎮 게이머 부대',
    zh: '例如：🎮 游戏小队',
    it: 'es. 🎮 Squadra gamer',
  },
  roleAddedToDraft: {
    de: '➕ **{label}** liegt jetzt im Warenkorb.',
    en: '➕ **{label}** is in the basket now.',
    fr: '➕ **{label}** est dans le panier.',
    es: '➕ **{label}** ya está en la cesta.',
    pt: '➕ **{label}** está no carrinho.',
    ru: '➕ **{label}** уже в корзине.',
    ja: '➕ **{label}** をカートに入れました。',
    ko: '➕ **{label}** 담았어요.',
    zh: '➕ 已把 **{label}** 放进购物车。',
    it: '➕ **{label}** è nel carrello.',
  },
  errDuplicateLabel: {
    de: '🙅 Diesen Platzhalter gibt es schon. Zwillinge verwirren nur die Leute!',
    en: '🙅 That placeholder already exists. Twins just confuse people!',
    fr: '🙅 Ce texte existe déjà. Les jumeaux, ça sème la confusion !',
    es: '🙅 Ese texto ya existe. ¡Los gemelos solo confunden!',
    pt: '🙅 Esse texto já existe. Gêmeos só confundem!',
    ru: '🙅 Такой текст уже есть. Близнецы только путают!',
    ja: '🙅 その表示テキストは既にあります。双子は混乱のもと！',
    ko: '🙅 그 표시 텍스트는 이미 있어요. 쌍둥이는 혼란만 줘요!',
    zh: '🙅 该显示文本已存在。双胞胎只会让人迷惑！',
    it: '🙅 Quel testo esiste già. I gemelli confondono!',
  },
  errTooManyRoles: {
    de: '🧯 Schluss bei **{max}** Rollen – mehr passt nicht unter die Nachricht.',
    en: '🧯 Hard stop at **{max}** roles – no more fit under the message.',
    fr: '🧯 Stop à **{max}** rôles – pas plus sous le message.',
    es: '🧯 Tope de **{max}** roles – no caben más bajo el mensaje.',
    pt: '🧯 Limite de **{max}** cargos – não cabe mais na mensagem.',
    ru: '🧯 Стоп на **{max}** ролях – больше не влезет.',
    ja: '🧯 **{max}** ロールで打ち止め – これ以上は入りません。',
    ko: '🧯 **{max}**개에서 멈춰요 – 더는 안 들어가요.',
    zh: '🧯 最多 **{max}** 个身份组——消息下面塞不下了。',
    it: '🧯 Stop a **{max}** ruoli – sotto al messaggio non ci stanno.',
  },
  errNeedTwoRoles: {
    de: '🤏 Mindestens **{min}** Rollen – mit einer einzigen ist das keine Wahl, das ist eine Ansage.',
    en: '🤏 At least **{min}** roles – with only one it isn’t a choice, it’s a decree.',
    fr: '🤏 Au moins **{min}** rôles – avec un seul ce n’est pas un choix, c’est un décret.',
    es: '🤏 Mínimo **{min}** roles – con uno solo no es elección, es un decreto.',
    pt: '🤏 No mínimo **{min}** cargos – com um só não é escolha, é decreto.',
    ru: '🤏 Минимум **{min}** роли – с одной это не выбор, а указ.',
    ja: '🤏 最低 **{min}** ロール – 1つだけでは選択ではなく命令です。',
    ko: '🤏 최소 **{min}**개 – 하나뿐이면 선택이 아니라 통보예요.',
    zh: '🤏 至少 **{min}** 个身份组——只有一个那不叫选择，叫通知。',
    it: '🤏 Minimo **{min}** ruoli – con uno solo non è una scelta, è un decreto.',
  },
  removeSelectPlaceholder: {
    de: 'Welche Rolle fliegt raus?',
    en: 'Which role gets kicked?',
    fr: 'Quel rôle dégage ?',
    es: '¿Qué rol se va?',
    pt: 'Qual cargo sai?',
    ru: 'Какую роль выкинуть?',
    ja: 'どのロールを外す？',
    ko: '어떤 역할을 뺄까요?',
    zh: '踢掉哪个身份组？',
    it: 'Quale ruolo salta?',
  },
  roleRemovedFromDraft: {
    de: '➖ **{label}** ist raus aus der Liste.',
    en: '➖ **{label}** is off the list.',
    fr: '➖ **{label}** est hors de la liste.',
    es: '➖ **{label}** fuera de la lista.',
    pt: '➖ **{label}** fora da lista.',
    ru: '➖ **{label}** больше нет в списке.',
    ja: '➖ **{label}** をリストから外しました。',
    ko: '➖ **{label}** 목록에서 뺐어요.',
    zh: '➖ 已把 **{label}** 移出列表。',
    it: '➖ **{label}** fuori dalla lista.',
  },
  cancelled: {
    de: '🚮 Abgebrochen. Nichts gesendet, nichts erstellt, alles gut.',
    en: '🚮 Cancelled. Nothing sent, nothing created, all good.',
    fr: '🚮 Annulé. Rien envoyé, rien créé, tout va bien.',
    es: '🚮 Cancelado. Nada enviado, nada creado, todo bien.',
    pt: '🚮 Cancelado. Nada enviado, nada criado, tudo certo.',
    ru: '🚮 Отменено. Ничего не отправлено, ничего не создано.',
    ja: '🚮 キャンセルしました。送信も作成もしていません。',
    ko: '🚮 취소했어요. 보낸 것도 만든 것도 없어요.',
    zh: '🚮 已取消。什么都没发，也没创建。',
    it: '🚮 Annullato. Niente inviato, niente creato, tutto ok.',
  },

  // ----------------------------------------------------------
  // Veröffentlichen / Speichern
  // ----------------------------------------------------------
  publishing: {
    de: '⚙️ Baue Rollen & Nachricht … einen Moment, ich schwitze schon. 😤',
    en: '⚙️ Building roles & message … one moment, I’m already sweating. 😤',
    fr: '⚙️ Création des rôles & du message … un instant, je transpire déjà. 😤',
    es: '⚙️ Creando roles y mensaje … un momento, ya estoy sudando. 😤',
    pt: '⚙️ Criando cargos e mensagem … um momento, já estou suando. 😤',
    ru: '⚙️ Создаю роли и сообщение … секунду, я уже потею. 😤',
    ja: '⚙️ ロールとメッセージを作成中 … 少々お待ちを、汗だくです。😤',
    ko: '⚙️ 역할과 메시지 만드는 중 … 잠깐만요, 벌써 땀나요. 😤',
    zh: '⚙️ 正在创建身份组和消息……稍等，我已经在冒汗了。😤',
    it: '⚙️ Creo ruoli e messaggio … un attimo, sto già sudando. 😤',
  },
  publishedTitle: {
    de: '🎉 Ab geht die Post!',
    en: '🎉 And it’s live!',
    fr: '🎉 C’est parti !',
    es: '🎉 ¡Al aire!',
    pt: '🎉 No ar!',
    ru: '🎉 Полетело!',
    ja: '🎉 公開しました！',
    ko: '🎉 나갔습니다!',
    zh: '🎉 发出去啦！',
    it: '🎉 È online!',
  },
  publishedBody: {
    de: '**{count}** Rollen erstellt und in {channel} scharf geschaltet. [Zur Nachricht springen]({url}) 🏃',
    en: '**{count}** roles created and armed in {channel}. [Jump to message]({url}) 🏃',
    fr: '**{count}** rôles créés et actifs dans {channel}. [Aller au message]({url}) 🏃',
    es: '**{count}** roles creados y activos en {channel}. [Ir al mensaje]({url}) 🏃',
    pt: '**{count}** cargos criados e ativos em {channel}. [Ir para a mensagem]({url}) 🏃',
    ru: '**{count}** ролей создано и включено в {channel}. [К сообщению]({url}) 🏃',
    ja: '**{count}** 個のロールを作成し、{channel} で稼働中。[メッセージへ]({url}) 🏃',
    ko: '**{count}**개 역할을 만들고 {channel}에 배치했어요. [메시지로 이동]({url}) 🏃',
    zh: '已创建 **{count}** 个身份组并在 {channel} 上线。[跳转到消息]({url}) 🏃',
    it: '**{count}** ruoli creati e attivi in {channel}. [Vai al messaggio]({url}) 🏃',
  },
  savedTitle: {
    de: '💾 Gespeichert!',
    en: '💾 Saved!',
    fr: '💾 Enregistré !',
    es: '💾 ¡Guardado!',
    pt: '💾 Salvo!',
    ru: '💾 Сохранено!',
    ja: '💾 保存しました！',
    ko: '💾 저장했어요!',
    zh: '💾 已保存！',
    it: '💾 Salvato!',
  },
  savedBody: {
    de: 'Die Nachricht in {channel} ist frisch poliert. [Ansehen]({url}) ✨',
    en: 'The message in {channel} is freshly polished. [Take a look]({url}) ✨',
    fr: 'Le message dans {channel} est tout neuf. [Regarde]({url}) ✨',
    es: 'El mensaje en {channel} está recién pulido. [Míralo]({url}) ✨',
    pt: 'A mensagem em {channel} está polida. [Dá uma olhada]({url}) ✨',
    ru: 'Сообщение в {channel} отполировано. [Посмотреть]({url}) ✨',
    ja: '{channel} のメッセージを磨き上げました。[見る]({url}) ✨',
    ko: '{channel}의 메시지를 새로 다듬었어요. [보러가기]({url}) ✨',
    zh: '{channel} 里的消息已焕然一新。[去看看]({url}) ✨',
    it: 'Il messaggio in {channel} è lucidato a nuovo. [Guarda]({url}) ✨',
  },
  publishFailed: {
    de: '💀 Absenden fehlgeschlagen: {error}\nBereits erstellte Rollen habe ich wieder aufgeräumt.',
    en: '💀 Publishing failed: {error}\nI cleaned up the roles I had already created.',
    fr: '💀 Échec de la publication : {error}\nJ’ai nettoyé les rôles déjà créés.',
    es: '💀 Fallo al publicar: {error}\nHe limpiado los roles ya creados.',
    pt: '💀 Falha ao publicar: {error}\nLimpei os cargos já criados.',
    ru: '💀 Публикация не удалась: {error}\nУже созданные роли я убрал.',
    ja: '💀 送信に失敗：{error}\n作成済みのロールは片付けました。',
    ko: '💀 게시 실패: {error}\n이미 만든 역할은 정리했어요.',
    zh: '💀 发布失败：{error}\n我已清理掉刚创建的身份组。',
    it: '💀 Pubblicazione fallita: {error}\nHo ripulito i ruoli già creati.',
  },

  // ----------------------------------------------------------
  // /edit_self_role
  // ----------------------------------------------------------
  editPickTitle: {
    de: '🗂️ Welche Nachricht darf ich aufhübschen?',
    en: '🗂️ Which message shall I glam up?',
    fr: '🗂️ Quel message dois-je relooker ?',
    es: '🗂️ ¿Qué mensaje retoco?',
    pt: '🗂️ Qual mensagem eu dou um trato?',
    ru: '🗂️ Какое сообщение подкрутить?',
    ja: '🗂️ どのメッセージを magic しましょう？',
    ko: '🗂️ 어떤 메시지를 손볼까요?',
    zh: '🗂️ 要美化哪条消息？',
    it: '🗂️ Quale messaggio sistemo?',
  },
  editPickPlaceholder: {
    de: 'Nachricht auswählen …',
    en: 'Select a message …',
    fr: 'Choisir un message …',
    es: 'Selecciona un mensaje …',
    pt: 'Selecione uma mensagem …',
    ru: 'Выбери сообщение …',
    ja: 'メッセージを選択 …',
    ko: '메시지 선택 …',
    zh: '选择一条消息 …',
    it: 'Seleziona un messaggio …',
  },
  editNoMessages: {
    de: '🕳️ Hier gibt es noch keine Self-Roles-Nachricht. Bau erst eine mit `/create_self_role`!',
    en: '🕳️ No self-roles message here yet. Build one with `/create_self_role` first!',
    fr: '🕳️ Aucun message self-roles ici. Crée-en un avec `/create_self_role` !',
    es: '🕳️ Aquí no hay ningún mensaje de self-roles. ¡Crea uno con `/create_self_role`!',
    pt: '🕳️ Nenhuma mensagem de self-roles aqui. Crie uma com `/create_self_role`!',
    ru: '🕳️ Здесь ещё нет сообщений self-roles. Сначала создай через `/create_self_role`!',
    ja: '🕳️ セルフロールのメッセージがまだありません。`/create_self_role` で作ってね！',
    ko: '🕳️ 아직 셀프 역할 메시지가 없어요. `/create_self_role`로 먼저 만들어요!',
    zh: '🕳️ 这里还没有自助身份组消息。先用 `/create_self_role` 建一个！',
    it: '🕳️ Nessun messaggio self-role qui. Creane uno con `/create_self_role`!',
  },
  editEntryDesc: {
    de: '{count} Rollen · #{channel}',
    en: '{count} roles · #{channel}',
    fr: '{count} rôles · #{channel}',
    es: '{count} roles · #{channel}',
    pt: '{count} cargos · #{channel}',
    ru: '{count} ролей · #{channel}',
    ja: '{count} ロール · #{channel}',
    ko: '{count}개 역할 · #{channel}',
    zh: '{count} 个身份组 · #{channel}',
    it: '{count} ruoli · #{channel}',
  },
  editMessageGone: {
    de: '👻 Diese Nachricht existiert nicht mehr – wahrscheinlich gelöscht. Ich habe sie aus meiner Liste geworfen.',
    en: '👻 That message is gone – probably deleted. I dropped it from my list.',
    fr: '👻 Ce message n’existe plus – sans doute supprimé. Je l’ai retiré de ma liste.',
    es: '👻 Ese mensaje ya no existe – borrado, seguramente. Lo he quitado de mi lista.',
    pt: '👻 Essa mensagem sumiu – provavelmente apagada. Tirei da minha lista.',
    ru: '👻 Этого сообщения больше нет – видимо, удалено. Убрал из списка.',
    ja: '👻 そのメッセージはもうありません（削除済み？）。リストから外しました。',
    ko: '👻 그 메시지는 사라졌어요 – 아마 삭제됐네요. 목록에서 뺐어요.',
    zh: '👻 那条消息不见了——大概被删了。我已从列表移除。',
    it: '👻 Quel messaggio non c’è più – forse cancellato. L’ho tolto dalla lista.',
  },

  // ----------------------------------------------------------
  // Rollen-Buttons in der finalen Nachricht
  // ----------------------------------------------------------
  roleGiven: {
    de: '✅ Zack! {role} gehört jetzt dir. Trag sie mit Stolz. 😎',
    en: '✅ Boom! {role} is yours now. Wear it with pride. 😎',
    fr: '✅ Boum ! {role} est à toi. Porte-le fièrement. 😎',
    es: '✅ ¡Zas! {role} ya es tuyo. Llévalo con orgullo. 😎',
    pt: '✅ Pronto! {role} agora é seu. Use com orgulho. 😎',
    ru: '✅ Бам! {role} теперь твоя. Носи с гордостью. 😎',
    ja: '✅ どん！{role} はあなたのものです。誇り高く。😎',
    ko: '✅ 짠! 이제 {role}은(는) 당신 거예요. 자랑스럽게! 😎',
    zh: '✅ 搞定！{role} 归你了，戴着有面子。😎',
    it: '✅ Boom! {role} è tuo. Portalo con orgoglio. 😎',
  },
  roleSwapped: {
    de: '🔄 Rollentausch! {old} raus, {role} rein – Einzelauswahl eben.',
    en: '🔄 Swap! {old} out, {role} in – single choice, remember?',
    fr: '🔄 Échange ! {old} dehors, {role} dedans – choix unique.',
    es: '🔄 ¡Cambio! {old} fuera, {role} dentro – selección única.',
    pt: '🔄 Troca! {old} sai, {role} entra – escolha única.',
    ru: '🔄 Обмен! {old} долой, {role} на место – одиночный выбор.',
    ja: '🔄 交代！{old} を外して {role} を装備 – 単一選択です。',
    ko: '🔄 교체! {old} 빼고 {role} 장착 – 단일 선택이니까요.',
    zh: '🔄 换装！{old} 下场，{role} 上场——单选模式。',
    it: '🔄 Scambio! {old} fuori, {role} dentro – scelta singola.',
  },
  roleAlready: {
    de: '🤨 Du hast {role} längst. Soll ich sie dir wieder abnehmen?',
    en: '🤨 You already have {role}. Want me to take it back?',
    fr: '🤨 Tu as déjà {role}. Je te le reprends ?',
    es: '🤨 Ya tienes {role}. ¿Te lo quito?',
    pt: '🤨 Você já tem {role}. Quer que eu tire?',
    ru: '🤨 У тебя уже есть {role}. Забрать обратно?',
    ja: '🤨 すでに {role} を持っています。外しますか？',
    ko: '🤨 이미 {role}을(를) 갖고 있어요. 뺄까요?',
    zh: '🤨 你已经有 {role} 了。要我收回吗？',
    it: '🤨 Hai già {role}. Te lo tolgo?',
  },
  roleRemoved: {
    de: '🗑️ {role} ist weg. Falls du sie vermisst: Button ist noch da. 👋',
    en: '🗑️ {role} is gone. If you miss it, the button is still there. 👋',
    fr: '🗑️ {role} est parti. S’il te manque, le bouton est toujours là. 👋',
    es: '🗑️ {role} fuera. Si lo echas de menos, el botón sigue ahí. 👋',
    pt: '🗑️ {role} removido. Se sentir falta, o botão continua ali. 👋',
    ru: '🗑️ {role} снята. Соскучишься – кнопка на месте. 👋',
    ja: '🗑️ {role} を外しました。恋しくなったらボタンはそこに。👋',
    ko: '🗑️ {role} 뺐어요. 그리우면 버튼은 그대로 있어요. 👋',
    zh: '🗑️ 已移除 {role}。想它了？按钮还在。👋',
    it: '🗑️ {role} rimosso. Se ti manca, il pulsante è ancora lì. 👋',
  },
  roleNotHad: {
    de: '🫥 Diese Rolle hast du gerade gar nicht. Nichts zu tun!',
    en: '🫥 You don’t even have that role right now. Nothing to do!',
    fr: '🫥 Tu n’as pas ce rôle actuellement. Rien à faire !',
    es: '🫥 Ahora mismo no tienes ese rol. ¡Nada que hacer!',
    pt: '🫥 Você nem tem esse cargo agora. Nada a fazer!',
    ru: '🫥 У тебя сейчас нет этой роли. Делать нечего!',
    ja: '🫥 今そのロールを持っていません。何もしません！',
    ko: '🫥 지금 그 역할이 없어요. 할 일이 없네요!',
    zh: '🫥 你现在根本没有这个身份组。无事可做！',
    it: '🫥 Non hai quel ruolo al momento. Niente da fare!',
  },
  roleGone: {
    de: '🪦 Diese Rolle wurde auf dem Server gelöscht. Ich putze das gleich aus der Nachricht.',
    en: '🪦 That role was deleted on the server. I’ll scrub it from the message.',
    fr: '🪦 Ce rôle a été supprimé du serveur. Je le retire du message.',
    es: '🪦 Ese rol se borró del servidor. Lo limpio del mensaje.',
    pt: '🪦 Esse cargo foi apagado no servidor. Vou limpar da mensagem.',
    ru: '🪦 Эта роль удалена на сервере. Уберу её из сообщения.',
    ja: '🪦 そのロールはサーバーで削除されました。メッセージから消しておきます。',
    ko: '🪦 그 역할은 서버에서 삭제됐어요. 메시지에서 지울게요.',
    zh: '🪦 该身份组已在服务器被删除。我会把它从消息里清掉。',
    it: '🪦 Quel ruolo è stato eliminato dal server. Lo tolgo dal messaggio.',
  },
  roleActionFailed: {
    de: '😵 Das hat nicht geklappt: {error}\nMeistens fehlt mir „Rollen verwalten“ oder meine Rolle steht zu weit unten.',
    en: '😵 That didn’t work: {error}\nUsually I lack “Manage Roles” or my role sits too low.',
    fr: '😵 Ça n’a pas marché : {error}\nSouvent il me manque « Gérer les rôles » ou mon rôle est trop bas.',
    es: '😵 No funcionó: {error}\nNormalmente me falta «Gestionar roles» o mi rol está muy abajo.',
    pt: '😵 Não rolou: {error}\nGeralmente falta “Gerenciar cargos” ou meu cargo está baixo.',
    ru: '😵 Не вышло: {error}\nОбычно не хватает «Управлять ролями» или моя роль слишком низко.',
    ja: '😵 うまくいきませんでした：{error}\nたいてい「ロールの管理」不足か、私のロールが下すぎます。',
    ko: '😵 실패했어요: {error}\n보통 “역할 관리” 권한이 없거나 제 역할이 너무 아래예요.',
    zh: '😵 没成功：{error}\n通常是我缺“管理身份组”或我的身份组太靠下。',
    it: '😵 Non ha funzionato: {error}\nDi solito mi manca “Gestire i ruoli” o il mio ruolo è troppo in basso.',
  },
  messageBroken: {
    de: '🧟 Diese Nachricht ist kaputt oder veraltet. Ein Admin kann sie mit `/edit_self_role` neu aufsetzen.',
    en: '🧟 This message is broken or outdated. An admin can rebuild it with `/edit_self_role`.',
    fr: '🧟 Ce message est cassé ou obsolète. Un admin peut le refaire avec `/edit_self_role`.',
    es: '🧟 Este mensaje está roto o desfasado. Un admin puede rehacerlo con `/edit_self_role`.',
    pt: '🧟 Esta mensagem está quebrada ou desatualizada. Um admin pode refazer com `/edit_self_role`.',
    ru: '🧟 Это сообщение сломано или устарело. Админ может пересобрать его через `/edit_self_role`.',
    ja: '🧟 このメッセージは壊れているか古いです。管理者が `/edit_self_role` で作り直せます。',
    ko: '🧟 이 메시지는 손상됐거나 오래됐어요. 관리자가 `/edit_self_role`로 다시 만들 수 있어요.',
    zh: '🧟 这条消息已损坏或过时。管理员可用 `/edit_self_role` 重建。',
    it: '🧟 Questo messaggio è rotto o obsoleto. Un admin può rifarlo con `/edit_self_role`.',
  },

  // ----------------------------------------------------------
  // /admin_set_bot_profile
  // ----------------------------------------------------------
  profileChoiceStandard: {
    de: 'Standard', en: 'Default', fr: 'Par défaut', es: 'Predeterminado', pt: 'Padrão',
    ru: 'Стандарт', ja: '標準', ko: '기본', zh: '默认', it: 'Predefinito',
  },
  profileChoiceServer: {
    de: 'Server-Icon', en: 'Server icon', fr: 'Icône du serveur', es: 'Icono del servidor', pt: 'Ícone do servidor',
    ru: 'Иконка сервера', ja: 'サーバーアイコン', ko: '서버 아이콘', zh: '服务器图标', it: 'Icona del server',
  },
  profileChoiceOwner: {
    de: 'Server-Owner-Bild', en: 'Server owner avatar', fr: 'Avatar du propriétaire', es: 'Avatar del dueño', pt: 'Avatar do dono',
    ru: 'Аватар владельца', ja: 'オーナーのアイコン', ko: '서버 소유자 아바타', zh: '服主头像', it: 'Avatar del proprietario',
  },
  profileImageDesc: {
    de: 'Welches Bild soll verwendet werden?',
    en: 'Which image should be used?',
    fr: 'Quelle image utiliser ?',
    es: '¿Qué imagen se debe usar?',
    pt: 'Qual imagem usar?',
    ru: 'Какое изображение использовать?',
    ja: 'どの画像を使いますか？',
    ko: '어떤 이미지를 사용할까요?',
    zh: '使用哪张图片？',
    it: 'Quale immagine usare?',
  },
  profileSet: {
    de: '🖼️ Neues Outfit sitzt: **{choice}**. Sexy!',
    en: '🖼️ New outfit locked in: **{choice}**. Looking sharp!',
    fr: '🖼️ Nouveau look validé : **{choice}**. Classe !',
    es: '🖼️ Nuevo look listo: **{choice}**. ¡Elegante!',
    pt: '🖼️ Novo visual no ar: **{choice}**. Estiloso!',
    ru: '🖼️ Новый образ готов: **{choice}**. Красота!',
    ja: '🖼️ 新しい見た目に変更：**{choice}**。イケてる！',
    ko: '🖼️ 새 스타일 적용: **{choice}**. 멋져요!',
    zh: '🖼️ 换装完成：**{choice}**。帅！',
    it: '🖼️ Nuovo look: **{choice}**. Che stile!',
  },
  errServerNoIcon: {
    de: '🖼️ Dieser Server hat gar kein Icon. Kann ich schlecht klauen.',
    en: '🖼️ This server has no icon at all. Hard to steal that.',
    fr: '🖼️ Ce serveur n’a pas d’icône. Difficile de la voler.',
    es: '🖼️ Este servidor no tiene icono. Difícil de robar.',
    pt: '🖼️ Este servidor não tem ícone. Difícil roubar.',
    ru: '🖼️ У сервера нет иконки. Красть нечего.',
    ja: '🖼️ このサーバーにはアイコンがありません。盗めません。',
    ko: '🖼️ 이 서버에는 아이콘이 없어요. 훔칠 게 없네요.',
    zh: '🖼️ 这个服务器没有图标，没得偷。',
    it: '🖼️ Questo server non ha icona. Difficile rubarla.',
  },
  errAvatar: {
    de: '🖼️ Profilbild fehlgeschlagen: {error}',
    en: '🖼️ Avatar update failed: {error}',
    fr: '🖼️ Échec de l’avatar : {error}',
    es: '🖼️ Fallo del avatar: {error}',
    pt: '🖼️ Falha no avatar: {error}',
    ru: '🖼️ Не удалось сменить аватар: {error}',
    ja: '🖼️ アイコンの変更に失敗：{error}',
    ko: '🖼️ 아바타 변경 실패: {error}',
    zh: '🖼️ 头像更新失败：{error}',
    it: '🖼️ Avatar non aggiornato: {error}',
  },
  errAvatarPerms: {
    de: '🔐 Mir fehlen die Rechte für das Server-Profilbild (z. B. „Nickname ändern“).',
    en: '🔐 I lack permissions for the server avatar (e.g. “Change Nickname”).',
    fr: '🔐 Permissions manquantes pour l’avatar serveur (ex. « Changer de pseudo »).',
    es: '🔐 Me faltan permisos para el avatar del servidor (p. ej. «Cambiar apodo»).',
    pt: '🔐 Faltam permissões para o avatar do servidor (ex.: “Mudar apelido”).',
    ru: '🔐 Не хватает прав на серверный аватар (напр. «Изменять ник»).',
    ja: '🔐 サーバーアイコン変更の権限がありません（例：「ニックネームの変更」）。',
    ko: '🔐 서버 아바타 권한이 없어요 (예: “별명 변경”).',
    zh: '🔐 我缺少设置服务器头像的权限（例如“更改昵称”）。',
    it: '🔐 Mi mancano i permessi per l’avatar del server (es. “Cambia nickname”).',
  },

  // ----------------------------------------------------------
  // /set_role_logging
  // ----------------------------------------------------------
  helpSetRoleLogging: {
    de: 'Aktiviert oder deaktiviert private Benachrichtigungen bei Rollenänderungen (nur Admins)',
    en: 'Enables or disables private notifications for role changes (admins only)',
    fr: 'Active ou désactive les notifications privées lors des changements de rôle (admins uniquement)',
    es: 'Activa o desactiva las notificaciones privadas en cambios de rol (solo admins)',
    pt: 'Ativa ou desativa notificações privadas em alterações de cargo (só admins)',
    ru: 'Включает или выключает личные уведомления при изменении ролей (только для админов)',
    ja: 'ロール変更時のDM通知を有効または無効にします（管理者のみ）',
    ko: '역할 변경 시 개인 DM 알림을 켜거나 끕니다 (관리자 전용)',
    zh: '启用或禁用身份组变更时的私信通知（仅管理员）',
    it: 'Attiva o disattiva le notifiche private per i cambi di ruolo (solo admin)',
  },
  setRoleLoggingStatusDesc: {
    de: 'Logging an- oder ausschalten (True/False)',
    en: 'Turn logging on or off (True/False)',
    fr: 'Activer ou désactiver les logs (True/False)',
    es: 'Activar o desactivar el registro (True/False)',
    pt: 'Ligar ou desligar o registro (True/False)',
    ru: 'Включить или выключить логирование (True/False)',
    ja: 'ログ記録のオン/オフ (True/False)',
    ko: '로깅 켜기 또는 끄기 (True/False)',
    zh: '开启或关闭日志记录 (True/False)',
    it: 'Attiva o disattiva il logging (True/False)',
  },
  setRoleLoggingLangDesc: {
    de: 'Sprache für die Direktnachrichten (optional)',
    en: 'Language for direct messages (optional)',
    fr: 'Langue des messages privés (optionnel)',
    es: 'Idioma para los mensajes directos (opcional)',
    pt: 'Idioma das mensagens diretas (opcional)',
    ru: 'Язык для личных сообщений (необязательно)',
    ja: 'ダイレクトメッセージの言語（任意）',
    ko: '다이렉트 메시지 언어 (선택)',
    zh: '私信通知的语言（可选）',
    it: 'Lingua per i messaggi diretti (opzionale)',
  },
  setRoleLoggingEnabled: {
    de: '📬 **Rollen-Logging aktiviert!**\nNutzer erhalten ab sofort eine humorvolle DM, wenn sie auf **{server}** Rollen wählen oder ablegen. (Sprache: **{lang}**)',
    en: '📬 **Role logging enabled!**\nUsers will now receive a humorous DM whenever they pick or drop roles on **{server}**. (Language: **{lang}**)',
    fr: '📬 **Journalisation des rôles activée !**\nLes utilisateurs recevront désormais un MP plein d’humour lorsqu’ils prennent ou retirent des rôles sur **{server}**. (Langue : **{lang}**)',
    es: '📬 **¡Registro de roles activado!**\nLos usuarios recibirán un MD con humor cada vez que elijan o quiten roles en **{server}**. (Idioma: **{lang}**)',
    pt: '📬 **Registro de cargos ativado!**\nOs membros receberão uma DM bem-humorada sempre que escolherem ou removerem cargos em **{server}**. (Idioma: **{lang}**)',
    ru: '📬 **Логирование ролей включено!**\nТеперь пользователи будут получать забавные ЛС при получении или снятии ролей на **{server}**. (Язык: **{lang}**)',
    ja: '📬 **ロールログを有効化しました！**\n**{server}** でロールを取得・解除した際、ユーモアあふれるDMが届きます。（言語: **{lang}**）',
    ko: '📬 **역할 로깅이 활성화되었습니다!**\n이제 **{server}**에서 역할을 얻거나 해제할 때 유쾌한 DM 알림을 받게 됩니다. (언어: **{lang}**)',
    zh: '📬 **身份组日志已启用！**\n成员在 **{server}** 领取或退还身份组时将收到幽默风趣的私信通知。（语言：**{lang}**）',
    it: '📬 **Logging dei ruoli attivato!**\nGli utenti riceveranno un messaggio privato simpatico ogni volta che scelgono o rimuovono ruoli su **{server}**. (Lingua: **{lang}**)',
  },
  setRoleLoggingDisabled: {
    de: '📴 **Rollen-Logging deaktiviert.**\nEs werden keine Direktnachrichten bei Rollenänderungen auf **{server}** mehr verschickt.',
    en: '📴 **Role logging disabled.**\nNo direct messages will be sent for role changes on **{server}**.',
    fr: '📴 **Journalisation des rôles désactivée.**\nAucun message privé ne sera envoyé pour les changements de rôle sur **{server}**.',
    es: '📴 **Registro de roles desactivado.**\nYa no se enviarán mensajes directos por cambios de rol en **{server}**.',
    pt: '📴 **Registro de cargos desativado.**\nNenhuma DM será enviada para mudanças de cargo em **{server}**.',
    ru: '📴 **Логирование ролей выключено.**\nЛичные сообщения при изменении ролей на **{server}** больше не отправляются.',
    ja: '📴 **ロールログを無効化しました。**\n**{server}** でのロール変更時にDMは送信されません。' ,
    ko: '📴 **역할 로깅이 비활성화되었습니다.**\n**{server}**에서 역할이 바뀌어도 DM 알림을 보내지 않습니다.',
    zh: '📴 **身份组日志已禁用。**\n在 **{server}** 变更身份组时将不再发送私信。',
    it: '📴 **Logging dei ruoli disattivato.**\nNon verranno più inviati messaggi privati per i cambi di ruolo su **{server}**.',
  },

  // ----------------------------------------------------------
  // Humorvolle Privat-DMs bei Rollenänderungen
  // ----------------------------------------------------------
  dmRoleGiven: {
    de: '🎉 Schick, schick! Du hast auf **{server}** soeben die Rolle **{role}** abgestaubt. Steht dir fabelhaft! 😎✨',
    en: '🎉 Looking sharp! You just scored the **{role}** role on **{server}**. Suits you brilliantly! 😎✨',
    fr: '🎉 Quelle classe ! Tu viens d’obtenir le rôle **{role}** sur **{server}**. Ça te va comme un gant ! 😎✨',
    es: '🎉 ¡Qué estilazo! Acabas de conseguir el rol **{role}** en **{server}**. ¡Te queda de maravilla! 😎✨',
    pt: '🎉 Que elegância! Você acabou de conquistar o cargo **{role}** no servidor **{server}**. Ficou um charme! 😎✨',
    ru: '🎉 Стильно выглядишь! Ты только что урвал роль **{role}** на сервере **{server}**. Тебе безумно идёт! 😎✨',
    ja: '🎉 キマってるね！サーバー **{server}** で **{role}** ロールをゲットしました。バッチリ似合ってます！😎✨',
    ko: '🎉 멋진데요! **{server}** 서버에서 **{role}** 역할을 획득했어요. 완전 찰떡이에요! 😎✨',
    zh: '🎉 帅气拉满！你刚刚在 **{server}** 服务器领取了 **{role}** 身份组。气质拿捏得死死的！😎✨',
    it: '🎉 Che stile! Hai appena sbloccato il ruolo **{role}** su **{server}**. Ti dona tantissimo! 😎✨',
  },
  dmRoleRemoved: {
    de: '👋 Alles hat ein Ende: Du hast die Rolle **{role}** auf **{server}** abgelegt. Wir vergießen eine kleine Träne... oder feiern kurz! 😜🎭',
    en: '👋 Every journey ends: You dropped the **{role}** role on **{server}**. Shedding a tiny tear... or maybe celebrating! 😜🎭',
    fr: '👋 Toute bonne chose a une fin : Tu as rendu le rôle **{role}** sur **{server}**. On verse une petite larme... ou on fête ça ! 😜🎭',
    es: '👋 Todo lo bueno se acaba: Has dejado el rol **{role}** en **{server}**. Derramamos una lagrimita... ¡o lo celebramos! 😜🎭',
    pt: '👋 Tudo que é bom dura pouco: Você largou o cargo **{role}** no servidor **{server}**. Uma lágrima caiu... ou abrimos o champanhe! 😜🎭',
    ru: '👋 Всё когда-нибудь заканчивается: Ты скинул роль **{role}** на сервере **{server}**. Смахнули скупую слезу... или устроили праздник! 😜🎭',
    ja: '👋 別れの時です：サーバー **{server}** で **{role}** ロールを手放しました。少し涙が…いやパーティーだ！😜🎭',
    ko: '👋 이별의 순간: **{server}** 서버에서 **{role}** 역할을 내려놓았어요. 눈물이 찔끔... 아니 파티 시작! 😜🎭',
    zh: '👋 挥手告别：你退还了 **{server}** 服务器的 **{role}** 身份组。我们流下了感动的泪水……或者开了瓶香槟！😜🎭',
    it: '👋 Tutto ha una fine: Hai rimosso il ruolo **{role}** su **{server}**. Versiamo una lacrimuccia... o festeggiamo! 😜🎭',
  },
  dmRoleSwapped: {
    de: '🔄 Aus alt mach neu! Auf **{server}** hast du **{oldRole}** gegen **{role}** getauscht. Ein echtes Upgrade! 🚀',
    en: '🔄 Out with the old, in with the new! On **{server}**, you traded **{oldRole}** for **{role}**. Solid upgrade! 🚀',
    fr: '🔄 Du changement dans l’air ! Sur **{server}**, tu as troqué **{oldRole}** contre **{role}**. Jolie amélioration ! 🚀',
    es: '🔄 ¡Renovarse o morir! En **{server}** has cambiado **{oldRole}** por **{role}**. ¡Menuda mejora! 🚀',
    pt: '🔄 Troca de visual! No servidor **{server}**, você trocou **{oldRole}** por **{role}**. Belo upgrade! 🚀',
    ru: '🔄 Апгрейд подъехал! На сервере **{server}** ты сменил **{oldRole}** на **{role}**. Отличный обмен! 🚀',
    ja: '🔄 気分一新！サーバー **{server}** で **{oldRole}** を **{role}** に切り替えました。ナイスアップグレード！🚀',
    ko: '🔄 새로운 변신! **{server}** 서버에서 **{oldRole}**을(를) **{role}**(으)로 교체했어요. 확실한 업그레이드! 🚀',
    zh: '🔄 辞旧迎新！在 **{server}** 服务器，你把 **{oldRole}** 换成了 **{role}**。超值大升级！🚀',
    it: '🔄 Cambio di look! Su **{server}** hai scambiato **{oldRole}** con **{role}**. Che bel salto di qualità! 🚀',
  },

  // ----------------------------------------------------------
  // /help
  // ----------------------------------------------------------
  helpTitle: {
    de: '🎭 Self-Roles-Bot – Bedienungsanleitung',
    en: '🎭 Self-Roles Bot – manual',
    fr: '🎭 Bot Self-Roles – mode d’emploi',
    es: '🎭 Bot de Self-Roles – manual',
    pt: '🎭 Bot de Self-Roles – manual',
    ru: '🎭 Self-Roles-бот – инструкция',
    ja: '🎭 セルフロールBot – 取扱説明書',
    ko: '🎭 셀프 역할 봇 – 사용 설명서',
    zh: '🎭 自助身份组机器人 – 使用手册',
    it: '🎭 Self-Roles Bot – manuale',
  },
  helpDesc: {
    de: 'Rollen zum Selbstbedienen – ohne Datenbank, ohne Drama. Alles steckt in der Nachricht selbst. 🤯',
    en: 'Self-service roles – no database, no drama. Everything lives inside the message. 🤯',
    fr: 'Rôles en libre-service – sans base de données, sans drame. Tout vit dans le message. 🤯',
    es: 'Roles en autoservicio – sin base de datos, sin dramas. Todo vive en el mensaje. 🤯',
    pt: 'Cargos self-service – sem banco de dados, sem drama. Tudo vive na mensagem. 🤯',
    ru: 'Роли самообслуживания – без базы данных и драм. Всё живёт в самом сообщении. 🤯',
    ja: 'セルフサービスのロール – DBなし、ドラマなし。すべてはメッセージの中に。🤯',
    ko: '셀프서비스 역할 – DB 없이, 드라마 없이. 모든 게 메시지 안에 있어요. 🤯',
    zh: '自助身份组——不用数据库，不闹剧。一切都藏在消息里。🤯',
    it: 'Ruoli self-service – niente database, niente drammi. Tutto vive nel messaggio. 🤯',
  },
  helpCreate: {
    de: 'Startet den Editor für eine neue Self-Roles-Nachricht im gewählten Kanal (nur Admins).',
    en: 'Opens the editor for a new self-roles message in the chosen channel (admins only).',
    fr: 'Ouvre l’éditeur d’un nouveau message self-roles dans le salon choisi (admins).',
    es: 'Abre el editor de un nuevo mensaje de self-roles en el canal elegido (solo admins).',
    pt: 'Abre o editor de uma nova mensagem de self-roles no canal escolhido (só admins).',
    ru: 'Открывает редактор нового сообщения self-roles в выбранном канале (только админы).',
    ja: '選んだチャンネルに新しいセルフロールを作るエディタを開きます（管理者のみ）。',
    ko: '선택한 채널에 새 셀프 역할 메시지를 만드는 편집기를 엽니다 (관리자 전용).',
    zh: '在所选频道打开新建自助身份组消息的编辑器（仅管理员）。',
    it: 'Apre l’editor per un nuovo messaggio self-role nel canale scelto (solo admin).',
  },
  helpEdit: {
    de: 'Öffnet eine Auswahl aller bestehenden Self-Roles-Nachrichten zum Bearbeiten (nur Admins).',
    en: 'Opens a picker with all existing self-roles messages for editing (admins only).',
    fr: 'Ouvre la liste des messages self-roles existants à modifier (admins).',
    es: 'Abre una lista de los mensajes de self-roles existentes para editar (solo admins).',
    pt: 'Abre a lista das mensagens de self-roles existentes para editar (só admins).',
    ru: 'Открывает список существующих сообщений self-roles для редактирования (только админы).',
    ja: '既存のセルフロールメッセージを選んで編集します（管理者のみ）。',
    ko: '기존 셀프 역할 메시지를 골라 편집합니다 (관리자 전용).',
    zh: '打开现有自助身份组消息列表进行编辑（仅管理员）。',
    it: 'Apre l’elenco dei messaggi self-role esistenti da modificare (solo admin).',
  },
  helpSetProfile: {
    de: 'Ändert das serverspezifische Profilbild des Bots (nur Admins).',
    en: 'Changes the bot’s server-specific avatar (admins only).',
    fr: 'Change l’avatar du bot pour ce serveur (admins).',
    es: 'Cambia el avatar del bot en este servidor (solo admins).',
    pt: 'Muda o avatar do bot neste servidor (só admins).',
    ru: 'Меняет аватар бота на этом сервере (только админы).',
    ja: 'このサーバーでのBotのアイコンを変更します（管理者のみ）。',
    ko: '이 서버에서 봇의 아바타를 바꿉니다 (관리자 전용).',
    zh: '更改机器人在本服务器的头像（仅管理员）。',
    it: 'Cambia l’avatar del bot in questo server (solo admin).',
  },
  helpHelp: {
    de: 'Zeigt genau diese Übersicht.',
    en: 'Shows exactly this overview.',
    fr: 'Affiche exactement cet aperçu.',
    es: 'Muestra exactamente este resumen.',
    pt: 'Mostra exatamente este resumo.',
    ru: 'Показывает именно этот обзор.',
    ja: 'まさにこの一覧を表示します。',
    ko: '바로 이 목록을 보여줍니다.',
    zh: '显示的就是这个概览。',
    it: 'Mostra esattamente questa panoramica.',
  },
  helpAdminPanel: {
    de: 'Owner-Admin-Panel (nur im DM)',
    en: 'Owner admin panel (DM only)',
    fr: 'Panneau owner (MP uniquement)',
    es: 'Panel del owner (solo MD)',
    pt: 'Painel do owner (só no DM)',
    ru: 'Панель владельца (только в ЛС)',
    ja: 'オーナー管理パネル（DM限定）',
    ko: '소유자 관리 패널 (DM 전용)',
    zh: '所有者管理面板（仅私聊）',
    it: 'Pannello owner (solo DM)',
  },
  helpFooter: {
    de: '💡 Klick auf einen Button unter einer Self-Roles-Nachricht = Rolle an/aus. Die Zähler aktualisieren sich von selbst – auch wenn ein Admin Rollen manuell verteilt. 🧠',
    en: '💡 Click a button under a self-roles message = role on/off. Counters update themselves – even when an admin hands out roles manually. 🧠',
    fr: '💡 Un clic sur un bouton = rôle activé/désactivé. Les compteurs se mettent à jour seuls – même si un admin distribue les rôles à la main. 🧠',
    es: '💡 Pulsa un botón = rol activado/desactivado. Los contadores se actualizan solos – incluso si un admin reparte roles a mano. 🧠',
    pt: '💡 Clique num botão = cargo liga/desliga. Os contadores se atualizam sozinhos – mesmo com admin distribuindo manualmente. 🧠',
    ru: '💡 Клик по кнопке = роль вкл/выкл. Счётчики обновляются сами – даже если админ выдаёт роли вручную. 🧠',
    ja: '💡 ボタンを押すとロールのオン/オフ。カウンターは自動更新 – 管理者が手動で配っても追随します。🧠',
    ko: '💡 버튼을 누르면 역할 on/off. 카운터는 알아서 갱신돼요 – 관리자가 수동으로 줘도요. 🧠',
    zh: '💡 点按钮 = 身份组开/关。计数会自动更新——即使管理员手动发放也一样。🧠',
    it: '💡 Clicca un pulsante = ruolo on/off. I contatori si aggiornano da soli – anche se un admin assegna a mano. 🧠',
  },
  helpLanguageHint: {
    de: '🌍 Die Sprache richtet sich nach deinem Discord-Client – 10 Sprachen an Bord.',
    en: '🌍 The language follows your Discord client – 10 languages on board.',
    fr: '🌍 La langue suit ton client Discord – 10 langues à bord.',
    es: '🌍 El idioma sigue a tu cliente de Discord – 10 idiomas a bordo.',
    pt: '🌍 O idioma segue seu cliente Discord – 10 idiomas a bordo.',
    ru: '🌍 Язык берётся из твоего клиента Discord – 10 языков на борту.',
    ja: '🌍 言語は Discord クライアントに追従 – 10言語対応。',
    ko: '🌍 언어는 Discord 클라이언트를 따라가요 – 10개 언어 지원.',
    zh: '🌍 语言跟随你的 Discord 客户端——支持 10 种语言。',
    it: '🌍 La lingua segue il tuo client Discord – 10 lingue a bordo.',
  },
  createChannelDesc: {
    de: 'Kanal, in dem die Self-Roles-Nachricht landet',
    en: 'Channel where the self-roles message lands',
    fr: 'Salon où atterrit le message self-roles',
    es: 'Canal donde aparecerá el mensaje de self-roles',
    pt: 'Canal onde a mensagem de self-roles vai aparecer',
    ru: 'Канал, куда попадёт сообщение self-roles',
    ja: 'セルフロールを投稿するチャンネル',
    ko: '셀프 역할 메시지를 보낼 채널',
    zh: '自助身份组消息发送到的频道',
    it: 'Canale dove finirà il messaggio self-role',
  },

  // ----------------------------------------------------------
  // Owner-Admin-Panel (bewusst nur Deutsch)
  // ----------------------------------------------------------
  apNeedDm: { de: '🔒 Dieses Panel gibt es nur im Privatchat mit dem Bot-Owner.' },
  apTitle: { de: '🛰️ Self-Roles Owner-Panel' },
  apNoServers: { de: 'Der Bot ist aktuell auf **keinem** Server. Einsam hier. 🥲' },
  apServerListDesc: { de: '**{count}** Server insgesamt:\n\n{list}' },
  apPage: { de: 'Seite {page}/{total}' },
  apSelectPlaceholder: { de: 'Server auswählen …' },
  apBtnPrev: { de: '◀' },
  apBtnNext: { de: '▶' },
  apBtnRefresh: { de: '🔄 Aktualisieren' },
  apDetailTitle: { de: '🔍 Server-Details' },
  apDetailName: { de: '**Name:** {name}' },
  apDetailOwner: { de: '**Owner:** {mention}' },
  apDetailMembers: { de: '**Mitglieder:** {count}' },
  apDetailSetup: { de: '**Self-Roles:** {status}' },
  apDetailMessages: { de: '**Nachrichten:** {count} · **Rollen:** {roles}' },
  apSetupYes: { de: '✅ eingerichtet' },
  apSetupNo: { de: '❌ noch nichts da' },
  apBtnBack: { de: '↩️ Zurück' },
  apBtnInvite: { de: '✉️ Einladung' },
  apBtnLeave: { de: '🚪 Verlassen' },
  apBtnLeaveConfirm: { de: '⚠️ Wirklich verlassen' },
  apBtnLeaveCancel: { de: '↩️ Doch nicht' },
  apLeaveAsk: { de: 'Server **{name}** wirklich verlassen? Danach ist der Bot dort raus.' },
  apLeft: { de: '👋 Server **{name}** verlassen.' },
  apInviteSent: { de: '✉️ Einladung erstellt (1 Stunde gültig, 1× nutzbar):' },
  apInviteLink: { de: '{url}' },
  apInviteFailed: { de: '⚠️ Einladung fehlgeschlagen: {error}' },
  apJoinNotice: { de: '🎉 Neuer Server: **{name}**\n👥 Mitglieder: **{members}**\n👑 Owner: {owner}' },
};

/** Übersetzt einen Key in die gewünschte Sprache und ersetzt {platzhalter}. */
function t(key, lang, vars = {}) {
  const entry = T[key];
  if (!entry) return `??${key}??`;
  let text = entry[lang] || entry.de || entry.en || '';
  for (const [k, v] of Object.entries(vars)) {
    text = text.split(`{${k}}`).join(String(v));
  }
  return text;
}

/**
 * Unsere Sprach-Codes → Discord-Locale-Codes (für Command-Lokalisierung).
 * Discord akzeptiert z. B. „en-US“ aber kein nacktes „en“.
 */
const DISCORD_LOCALE = {
  de: 'de',
  en: 'en-US',
  fr: 'fr',
  es: 'es-ES',
  pt: 'pt-BR',
  ru: 'ru',
  ja: 'ja',
  ko: 'ko',
  zh: 'zh-CN',
  it: 'it',
};

/** Mappt die Discord-Client-Locale eines Nutzers auf unsere Sprach-Codes. */
const DISCORD_LOCALE_MAP = {
  de: 'de',
  'en-US': 'en',
  'en-GB': 'en',
  fr: 'fr',
  'es-ES': 'es',
  'es-419': 'es',
  'pt-BR': 'pt',
  'pt-PT': 'pt',
  ru: 'ru',
  ja: 'ja',
  ko: 'ko',
  'zh-CN': 'zh',
  'zh-TW': 'zh',
  it: 'it',
};

function langFromDiscord(locale) {
  return DISCORD_LOCALE_MAP[locale] || 'en';
}

/** Gültiger Sprachcode? Sonst Fallback auf 'en'. */
function normalizeLang(code) {
  return LANGS[code] ? code : 'en';
}

module.exports = {
  LANGS,
  T,
  t,
  langFromDiscord,
  normalizeLang,
  DISCORD_LOCALE,
  DISCORD_LOCALE_MAP,
};
