/**
 * ============================================================================
 *  ✅ Verify-Bot – DIE Sprachdatei (alle 10 Sprachen in EINER Datei).
 *
 *  Aufbau exakt wie bei den anderen Bots:
 *  - Jeder Text-Key enthält direkt untereinander alle 10 Sprachen.
 *  - Die 10 meistgenutzten Discord-Sprachen: Deutsch, Englisch, Französisch,
 *    Spanisch, Portugiesisch (BR), Russisch, Japanisch, Koreanisch,
 *    Chinesisch (CN), Italienisch.
 *  - T-Keys, die nur `de` enthalten, sind bewusst nur auf Deutsch
 *    (z. B. das Owner-Admin-Panel).
 *
 *  Platzhalter in Texten: {channel}, {role}, {user}, {xp}, {reason} …
 *  werden zur Laufzeit ersetzt (siehe t() am Ende der Datei).
 * ============================================================================
 */

const LANGS = {
  de: {
    name: 'Deutsch',
    names: { de: 'Deutsch', en: 'German', fr: 'Allemand', es: 'Alemán', pt: 'Alemão', ru: 'Немецкий', ja: 'ドイツ語', ko: '독일어', zh: '德语', it: 'Tedesco' },
    flag: '🇩🇪',
    locale: 'de-DE',
  },
  en: {
    name: 'English',
    names: { de: 'Englisch', en: 'English', fr: 'Anglais', es: 'Inglés', pt: 'Inglês', ru: 'Английский', ja: '英語', ko: '영어', zh: '英语', it: 'Inglese' },
    flag: '🇬🇧',
    locale: 'en-US',
  },
  fr: {
    name: 'Français',
    names: { de: 'Französisch', en: 'French', fr: 'Français', es: 'Francés', pt: 'Francês', ru: 'Французский', ja: 'フランス語', ko: '프랑스어', zh: '法语', it: 'Francese' },
    flag: '🇫🇷',
    locale: 'fr-FR',
  },
  es: {
    name: 'Español',
    names: { de: 'Spanisch', en: 'Spanish', fr: 'Espagnol', es: 'Español', pt: 'Espanhol', ru: 'Испанский', ja: 'スペイン語', ko: '스페인어', zh: '西班牙语', it: 'Spagnolo' },
    flag: '🇪🇸',
    locale: 'es-ES',
  },
  pt: {
    name: 'Português',
    names: { de: 'Portugiesisch', en: 'Portuguese', fr: 'Portugais', es: 'Portugués', pt: 'Português', ru: 'Португальский', ja: 'ポルトガル語', ko: '포르투갈어', zh: '葡萄牙语', it: 'Portoghese' },
    flag: '🇧🇷',
    locale: 'pt-BR',
  },
  ru: {
    name: 'Русский',
    names: { de: 'Russisch', en: 'Russian', fr: 'Russe', es: 'Ruso', pt: 'Russo', ru: 'Русский', ja: 'ロシア語', ko: '러시아어', zh: '俄语', it: 'Russo' },
    flag: '🇷🇺',
    locale: 'ru-RU',
  },
  ja: {
    name: '日本語',
    names: { de: 'Japanisch', en: 'Japanese', fr: 'Japonais', es: 'Japonés', pt: 'Japonês', ru: 'Японский', ja: '日本語', ko: '일본어', zh: '日语', it: 'Giapponese' },
    flag: '🇯🇵',
    locale: 'ja-JP',
  },
  ko: {
    name: '한국어',
    names: { de: 'Koreanisch', en: 'Korean', fr: 'Coréen', es: 'Coreano', pt: 'Coreano', ru: 'Корейский', ja: '韓国語', ko: '한국어', zh: '韩语', it: 'Coreano' },
    flag: '🇰🇷',
    locale: 'ko-KR',
  },
  zh: {
    name: '中文',
    names: { de: 'Chinesisch', en: 'Chinese', fr: 'Chinois', es: 'Chino', pt: 'Chinês', ru: 'Китайский', ja: '中国語', ko: '중국어', zh: '中文', it: 'Cinese' },
    flag: '🇨🇳',
    locale: 'zh-CN',
  },
  it: {
    name: 'Italiano',
    names: { de: 'Italienisch', en: 'Italian', fr: 'Italien', es: 'Italiano', pt: 'Italiano', ru: 'Итальянский', ja: 'イタリア語', ko: '이탈리아어', zh: '意大利语', it: 'Italiano' },
    flag: '🇮🇹',
    locale: 'it-IT',
  },
};

const T = {
  // ----------------------------------------------------------
  // Allgemeine Fehler
  // ----------------------------------------------------------
  errGuildOnly: {
    de: '🚫 Das geht nur auf einem Server – im Privatchat gibt es nichts zu verifizieren.',
    en: '🚫 Server-only command – there’s nothing to verify in a DM.',
    fr: '🚫 Uniquement sur un serveur – rien à vérifier en MP.',
    es: '🚫 Solo en un servidor – no hay nada que verificar en los MD.',
    pt: '🚫 Só funciona num servidor – não há nada para verificar no privado.',
    ru: '🚫 Только на сервере – в личке верифицировать нечего.',
    ja: '🚫 サーバー専用コマンドです。DM には検証するものがありません。',
    ko: '🚫 서버 전용 명령어예요. DM에는 인증할 게 없어요.',
    zh: '🚫 该命令仅限服务器使用——私聊里没有可验证的内容。',
    it: '🚫 Solo nei server – nei DM non c’è nulla da verificare.',
  },
  errNoPermission: {
    de: '🛑 Nur Admins dürfen an den Verify-Regeln schrauben. Nice try! 😏',
    en: '🛑 Only admins may tinker with the verify rules. Nice try! 😏',
    fr: '🛑 Seuls les admins peuvent toucher aux règles de vérification. Bien tenté ! 😏',
    es: '🛑 Solo los admins pueden tocar las reglas de verificación. ¡Buen intento! 😏',
    pt: '🛑 Só admins mexem nas regras de verificação. Boa tentativa! 😏',
    ru: '🛑 Крутить правила верификации могут только админы. Хорошая попытка! 😏',
    ja: '🛑 検証ルールをいじれるのは管理者だけです。惜しい！😏',
    ko: '🛑 인증 규칙은 관리자만 만질 수 있어요. 시도는 좋았어요! 😏',
    zh: '🛑 只有管理员能改验证规则。想得美！😏',
    it: '🛑 Solo gli admin possono toccare le regole di verifica. Bel tentativo! 😏',
  },
  errGeneric: {
    de: '💥 Da ist was explodiert. Versuch es nochmal – der Bot sammelt gerade seine Einzelteile ein.',
    en: '💥 Something blew up. Try again – the bot is picking up its pieces.',
    fr: '💥 Quelque chose a explosé. Réessaie – le bot ramasse ses morceaux.',
    es: '💥 Algo ha explotado. Inténtalo de nuevo – el bot está recogiendo sus piezas.',
    pt: '💥 Algo explodiu. Tenta de novo – o bot está juntando os pedaços.',
    ru: '💥 Что-то рвануло. Попробуй снова – бот собирает себя по кусочкам.',
    ja: '💥 何かが爆発しました。もう一度どうぞ – ボットが破片を拾っています。',
    ko: '💥 뭔가 터졌어요. 다시 시도해 주세요 – 봇이 조각을 줍는 중입니다.',
    zh: '💥 出了点小爆炸。再试一次——机器人正在捡碎片。',
    it: '💥 Qualcosa è esploso. Riprova – il bot sta raccogliendo i pezzi.',
  },
  errBotPerms: {
    de: '🔐 Mir fehlt **„Rollen verwalten“** (oder meine Rolle hängt zu weit unten). Schieb mich hoch und ich mach den Rest! 💪',
    en: '🔐 I need **“Manage Roles”** (or my role sits too low). Move me up and I’ll handle the rest! 💪',
    fr: '🔐 Il me faut **« Gérer les rôles »** (ou mon rôle est trop bas). Remonte-moi et je gère ! 💪',
    es: '🔐 Necesito **«Gestionar roles»** (o mi rol está demasiado abajo). ¡Súbeme y yo me encargo! 💪',
    pt: '🔐 Preciso de **“Gerenciar cargos”** (ou meu cargo está baixo demais). Me sobe que eu resolvo! 💪',
    ru: '🔐 Мне нужно право **«Управлять ролями»** (или моя роль слишком низко). Подними меня – дальше сам! 💪',
    ja: '🔐 **「ロールの管理」**が必要です（または私のロールが下すぎます）。上げてくれれば後は任せて！💪',
    ko: '🔐 **“역할 관리”** 권한이 필요해요 (또는 제 역할이 너무 아래예요). 올려주시면 나머지는 제가! 💪',
    zh: '🔐 我需要**“管理身份组”**权限（或者我的身份组太靠下）。把我往上挪，剩下的交给我！💪',
    it: '🔐 Mi serve **“Gestire i ruoli”** (o il mio ruolo è troppo in basso). Spostami su e faccio il resto! 💪',
  },
  errSessionExpired: {
    de: '⌛ Diese Bearbeitungs-Session ist abgelaufen oder der Bot wurde neu gestartet. Öffne den Editor einfach neu – deine bereits gesendete Nachricht ist safe! 🛟',
    en: '⌛ This editing session expired or the bot restarted. Just open the editor again – your published message is safe! 🛟',
    fr: '⌛ Session d’édition expirée ou bot redémarré. Rouvre l’éditeur – ton message publié est intact ! 🛟',
    es: '⌛ Esta sesión de edición ha caducado o el bot se reinició. Abre el editor de nuevo – ¡tu mensaje publicado está a salvo! 🛟',
    pt: '⌛ Esta sessão de edição expirou ou o bot reiniciou. Abra o editor de novo – sua mensagem publicada está segura! 🛟',
    ru: '⌛ Сессия редактирования истекла или бот перезапустился. Просто открой редактор снова – опубликованное сообщение цело! 🛟',
    ja: '⌛ 編集セッションが期限切れ、またはボットが再起動しました。エディタを開き直してください – 投稿済みメッセージは無事です！🛟',
    ko: '⌛ 편집 세션이 만료됐거나 봇이 재시작됐어요. 편집기를 다시 열어주세요 – 게시된 메시지는 안전합니다! 🛟',
    zh: '⌛ 编辑会话已过期或机器人重启了。重新打开编辑器即可——已发布的消息安然无恙！🛟',
    it: '⌛ Sessione di modifica scaduta o bot riavviato. Riapri l’editor – il messaggio pubblicato è al sicuro! 🛟',
  },
  errChannelBad: {
    de: '📭 In diesem Kanal kann ich nicht schreiben (oder es ist kein Textkanal). Wähl einen anderen!',
    en: '📭 I can’t post in that channel (or it isn’t a text channel). Pick another one!',
    fr: '📭 Je ne peux pas écrire dans ce salon (ou ce n’est pas un salon textuel). Choisis-en un autre !',
    es: '📭 No puedo escribir en ese canal (o no es un canal de texto). ¡Elige otro!',
    pt: '📭 Não consigo postar nesse canal (ou não é um canal de texto). Escolha outro!',
    ru: '📭 Я не могу писать в этот канал (или это не текстовый канал). Выбери другой!',
    ja: '📭 そのチャンネルには投稿できません（またはテキストチャンネルではありません）。別のを選んでね！',
    ko: '📭 그 채널에는 글을 쓸 수 없어요 (또는 텍스트 채널이 아니에요). 다른 채널을 골라주세요!',
    zh: '📭 我无法在该频道发言（或它不是文字频道）。换一个吧！',
    it: '📭 Non posso scrivere in quel canale (o non è un canale testuale). Scegline un altro!',
  },
  errRolesMissing: {
    de: '🔍 Eine der angegebenen Rollen existiert nicht (mehr) auf diesem Server. Prüf das nochmal!',
    en: '🔍 One of the given roles doesn’t exist (anymore) on this server. Double-check it!',
    fr: '🔍 Un des rôles indiqués n’existe (plus) sur ce serveur. Vérifie !',
    es: '🔍 Uno de los roles indicados ya no existe en este servidor. ¡Revíselo!',
    pt: '🔍 Um dos cargos indicados não existe (mais) neste servidor. Confira!',
    ru: '🔍 Одна из указанных ролей (больше) не существует на этом сервере. Проверь!',
    ja: '🔍 指定したロールのどれかがこのサーバーに（もう）存在しません。確認して！',
    ko: '🔍 지정한 역할 중 하나가 이 서버에 (더 이상) 존재하지 않아요. 확인해 주세요!',
    zh: '🔍 指定的身份组中有个（已）不在本服务器。请再确认！',
    it: '🔍 Uno dei ruoli indicati non esiste (più) su questo server. Controlla!',
  },

  // ----------------------------------------------------------
  // /create_verify_rules & /create_classic_rules – Formular
  // ----------------------------------------------------------
  createModalTitle: {
    de: '📜 Neue Regeln erstellen',
    en: '📜 Create new rules',
    fr: '📜 Créer de nouvelles règles',
    es: '📜 Crear nuevas reglas',
    pt: '📜 Criar novas regras',
    ru: '📜 Создать новые правила',
    ja: '📜 新しいルールを作成',
    ko: '📜 새 규칙 만들기',
    zh: '📜 创建新规则',
    it: '📜 Crea nuove regole',
  },
  createRulesLabel: {
    de: 'Regeln (großes Textfeld)',
    en: 'Rules (big text box)',
    fr: 'Règles (grand champ de texte)',
    es: 'Reglas (campo de texto grande)',
    pt: 'Regras (campo de texto grande)',
    ru: 'Правила (большое поле)',
    ja: 'ルール（大きなテキスト欄）',
    ko: '규칙 (큰 텍스트 상자)',
    zh: '规则（大文本框）',
    it: 'Regole (campo di testo grande)',
  },
  createRulesPlaceholder: {
    de: 'Schreib hier deine Regeln rein. Markdown erlaubt – mach sie hübsch! ✨',
    en: 'Type your rules here. Markdown allowed – make them pretty! ✨',
    fr: 'Écris tes règles ici. Markdown autorisé – fais-les belles ! ✨',
    es: 'Escribe tus reglas aquí. Markdown permitido – ¡hazlas bonitas! ✨',
    pt: 'Escreva suas regras aqui. Markdown permitido – deixe bonito! ✨',
    ru: 'Пиши правила сюда. Markdown разрешён – сделай красиво! ✨',
    ja: 'ここにルールを書いてね。Markdown対応 – かっこよくして！✨',
    ko: '여기에 규칙을 적어주세요. Markdown 지원 – 예쁘게 꾸며요! ✨',
    zh: '在这里写下规则。支持 Markdown——弄漂亮点！✨',
    it: 'Scrivi qui le regole. Markdown consentito – falle belle! ✨',
  },
  createButtonLabel: {
    de: 'Name des Verifizier-Buttons',
    en: 'Verify button name',
    fr: 'Nom du bouton de vérification',
    es: 'Nombre del botón de verificación',
    pt: 'Nome do botão de verificação',
    ru: 'Название кнопки верификации',
    ja: '認証ボタンの名前',
    ko: '인증 버튼 이름',
    zh: '验证按钮名称',
    it: 'Nome del pulsante di verifica',
  },
  createButtonPlaceholder: {
    de: 'z. B. ✅ Verifizieren',
    en: 'e.g. ✅ Verify',
    fr: 'ex. ✅ Vérifier',
    es: 'p. ej. ✅ Verificar',
    pt: 'ex.: ✅ Verificar',
    ru: 'напр. ✅ Верифицироваться',
    ja: '例：✅ 認証する',
    ko: '예: ✅ 인증하기',
    zh: '例如：✅ 验证',
    it: 'es. ✅ Verifica',
  },

  // ----------------------------------------------------------
  // Editor (Bestätigungs-/Bearbeitungs-Nachricht)
  // ----------------------------------------------------------
  editorTitle: {
    de: '🛠️ Regeln-Werkstatt',
    en: '🛠️ Rules workshop',
    fr: '🛠️ Atelier des règles',
    es: '🛠️ Taller de reglas',
    pt: '🛠️ Oficina de regras',
    ru: '🛠️ Мастерская правил',
    ja: '🛠️ ルール工房',
    ko: '🛠️ 규칙 공방',
    zh: '🛠️ 规则工坊',
    it: '🛠️ Officina regole',
  },
  editorIntroNew: {
    de: 'Letzter Check, bevor das Ding live geht. Alles korrekt? Dann Feuer frei! 🚀',
    en: 'Final check before this thing goes live. All good? Then let it rip! 🚀',
    fr: 'Dernier contrôle avant le grand saut. Tout est bon ? Alors go ! 🚀',
    es: 'Última revisión antes de que salga en vivo. ¿Todo bien? ¡Entonces fuego! 🚀',
    pt: 'Última conferida antes de ir ao ar. Tudo certo? Então manda ver! 🚀',
    ru: 'Последняя проверка перед запуском. Всё ок? Тогда поехали! 🚀',
    ja: '公開前の最終チェック。問題なし？ならば発射！🚀',
    ko: '공개 전 마지막 점검. 괜찮나요? 그럼 발사! 🚀',
    zh: '上线前最后检查。没问题？那就发射！🚀',
    it: 'Ultimo controllo prima del lancio. Tutto ok? Allora via! 🚀',
  },
  editorChannel: {
    de: '📍 **Kanal:** {channel}',
    en: '📍 **Channel:** {channel}',
    fr: '📍 **Salon :** {channel}',
    es: '📍 **Canal:** {channel}',
    pt: '📍 **Canal:** {channel}',
    ru: '📍 **Канал:** {channel}',
    ja: '📍 **チャンネル:** {channel}',
    ko: '📍 **채널:** {channel}',
    zh: '📍 **频道：** {channel}',
    it: '📍 **Canale:** {channel}',
  },
  editorMode: {
    de: '🎛️ **Modus:** {mode}',
    en: '🎛️ **Mode:** {mode}',
    fr: '🎛️ **Mode :** {mode}',
    es: '🎛️ **Modo:** {mode}',
    pt: '🎛️ **Modo:** {mode}',
    ru: '🎛️ **Режим:** {mode}',
    ja: '🎛️ **モード:** {mode}',
    ko: '🎛️ **모드:** {mode}',
    zh: '🎛️ **模式：** {mode}',
    it: '🎛️ **Modalità:** {mode}',
  },
  modeVerify: {
    de: 'Verifizierung (mit Button & Rollen)', en: 'Verification (button & roles)', fr: 'Vérification (bouton & rôles)',
    es: 'Verificación (botón y roles)', pt: 'Verificação (botão e cargos)', ru: 'Верификация (кнопка и роли)',
    ja: '認証（ボタン＆ロール）', ko: '인증 (버튼 & 역할)', zh: '验证（按钮和身份组）', it: 'Verifica (pulsante e ruoli)',
  },
  modeClassic: {
    de: 'Klassisch (nur Regeln)', en: 'Classic (rules only)', fr: 'Classique (règles seules)',
    es: 'Clásico (solo reglas)', pt: 'Clássico (só regras)', ru: 'Классика (только правила)',
    ja: 'クラシック（ルールのみ）', ko: '클래식 (규칙만)', zh: '经典（仅规则）', it: 'Classico (solo regole)',
  },
  editorButtonName: {
    de: '🔘 **Button-Name:** {name}',
    en: '🔘 **Button name:** {name}',
    fr: '🔘 **Nom du bouton :** {name}',
    es: '🔘 **Nombre del botón:** {name}',
    pt: '🔘 **Nome do botão:** {name}',
    ru: '🔘 **Название кнопки:** {name}',
    ja: '🔘 **ボタン名:** {name}',
    ko: '🔘 **버튼 이름:** {name}',
    zh: '🔘 **按钮名称：** {name}',
    it: '🔘 **Nome pulsante:** {name}',
  },
  editorRoles: {
    de: '🎭 **Rollen:** {unverified} → {verified}',
    en: '🎭 **Roles:** {unverified} → {verified}',
    fr: '🎭 **Rôles :** {unverified} → {verified}',
    es: '🎭 **Roles:** {unverified} → {verified}',
    pt: '🎭 **Cargos:** {unverified} → {verified}',
    ru: '🎭 **Роли:** {unverified} → {verified}',
    ja: '🎭 **ロール:** {unverified} → {verified}',
    ko: '🎭 **역할:** {unverified} → {verified}',
    zh: '🎭 **身份组：** {unverified} → {verified}',
    it: '🎭 **Ruoli:** {unverified} → {verified}',
  },
  editorLogging: {
    de: '📋 **Log-Kanal:** {channel}',
    en: '📋 **Logging channel:** {channel}',
    fr: '📋 **Salon de logs :** {channel}',
    es: '📋 **Canal de registro:** {channel}',
    pt: '📋 **Canal de log:** {channel}',
    ru: '📋 **Канал логов:** {channel}',
    ja: '📋 **ログチャンネル:** {channel}',
    ko: '📋 **로그 채널:** {channel}',
    zh: '📋 **日志频道：** {channel}',
    it: '📋 **Canale log:** {channel}',
  },
  editorRules: {
    de: '📜 **Regeln:** {rules}',
    en: '📜 **Rules:** {rules}',
    fr: '📜 **Règles :** {rules}',
    es: '📜 **Reglas:** {rules}',
    pt: '📜 **Regras:** {rules}',
    ru: '📜 **Правила:** {rules}',
    ja: '📜 **ルール:** {rules}',
    ko: '📜 **규칙:** {rules}',
    zh: '📜 **规则：** {rules}',
    it: '📜 **Regole:** {rules}',
  },
  editorNoRules: {
    de: '*(noch keine Regeln eingetragen)*',
    en: '*(no rules entered yet)*',
    fr: '*(aucune règle saisie)*',
    es: '*(aún no hay reglas)*',
    pt: '*(nenhuma regra ainda)*',
    ru: '*(правил пока нет)*',
    ja: '*(まだルール未入力)*',
    ko: '*(아직 규칙 없음)*',
    zh: '*(尚未填写规则)*',
    it: '*(nessuna regola inserita)*',
  },
  editorImage: {
    de: '🖼️ **Bild (oben rechts):** {status}',
    en: '🖼️ **Image (top right):** {status}',
    fr: '🖼️ **Image (en haut à droite) :** {status}',
    es: '🖼️ **Imagen (arriba a la derecha):** {status}',
    pt: '🖼️ **Imagem (canto sup. direito):** {status}',
    ru: '🖼️ **Картинка (справа сверху):** {status}',
    ja: '🖼️ **画像（右上）:** {status}',
    ko: '🖼️ **이미지 (오른쪽 위):** {status}',
    zh: '🖼️ **图片（右上角）：** {status}',
    it: '🖼️ **Immagine (in alto a destra):** {status}',
  },
  editorBanner: {
    de: '🎨 **Banner (oben):** {status}',
    en: '🎨 **Banner (top):** {status}',
    fr: '🎨 **Bannière (en haut) :** {status}',
    es: '🎨 **Banner (arriba):** {status}',
    pt: '🎨 **Banner (topo):** {status}',
    ru: '🎨 **Баннер (сверху):** {status}',
    ja: '🎨 **バナー（上部）:** {status}',
    ko: '🎨 **배너 (위):** {status}',
    zh: '🎨 **横幅（顶部）：** {status}',
    it: '🎨 **Banner (in alto):** {status}',
  },
  statusSet: {
    de: '✅ gesetzt', en: '✅ set', fr: '✅ défini', es: '✅ puesto', pt: '✅ definido',
    ru: '✅ задано', ja: '✅ 設定済み', ko: '✅ 설정됨', zh: '✅ 已设置', it: '✅ impostato',
  },
  statusEmpty: {
    de: '— (optional)', en: '— (optional)', fr: '— (optionnel)', es: '— (opcional)', pt: '— (opcional)',
    ru: '— (необязательно)', ja: '—（任意）', ko: '— (선택)', zh: '—（可选）', it: '— (opzionale)',
  },
  btnEditRules: { de: '✏️ Regeln', en: '✏️ Rules', fr: '✏️ Règles', es: '✏️ Reglas', pt: '✏️ Regras', ru: '✏️ Правила', ja: '✏️ ルール', ko: '✏️ 규칙', zh: '✏️ 规则', it: '✏️ Regole' },
  btnEditButton: { de: '🔘 Button-Name', en: '🔘 Button name', fr: '🔘 Nom du bouton', es: '🔘 Nombre del botón', pt: '🔘 Nome do botão', ru: '🔘 Название кнопки', ja: '🔘 ボタン名', ko: '🔘 버튼 이름', zh: '🔘 按钮名称', it: '🔘 Nome pulsante' },
  btnUploadImage: { de: '🖼️ Bild hochladen', en: '🖼️ Upload image', fr: '🖼️ Importer une image', es: '🖼️ Subir imagen', pt: '🖼️ Enviar imagem', ru: '🖼️ Загрузить картинку', ja: '🖼️ 画像をアップロード', ko: '🖼️ 이미지 업로드', zh: '🖼️ 上传图片', it: '🖼️ Carica immagine' },
  btnUploadBanner: { de: '🎨 Banner hochladen', en: '🎨 Upload banner', fr: '🎨 Importer une bannière', es: '🎨 Subir banner', pt: '🎨 Enviar banner', ru: '🎨 Загрузить баннер', ja: '🎨 バナーをアップロード', ko: '🎨 배너 업로드', zh: '🎨 上传横幅', it: '🎨 Carica banner' },
  btnRemoveImage: { de: '🗑️ Bild weg', en: '🗑️ Remove image', fr: '🗑️ Retirer l’image', es: '🗑️ Quitar imagen', pt: '🗑️ Remover imagem', ru: '🗑️ Убрать картинку', ja: '🗑️ 画像を外す', ko: '🗑️ 이미지 제거', zh: '🗑️ 移除图片', it: '🗑️ Rimuovi immagine' },
  btnRemoveBanner: { de: '🗑️ Banner weg', en: '🗑️ Remove banner', fr: '🗑️ Retirer la bannière', es: '🗑️ Quitar banner', pt: '🗑️ Remover banner', ru: '🗑️ Убрать баннер', ja: '🗑️ バナーを外す', ko: '🗑️ 배너 제거', zh: '🗑️ 移除横幅', it: '🗑️ Rimuovi banner' },
  btnPublish: {
    de: '🚀 Absenden', en: '🚀 Publish', fr: '🚀 Publier', es: '🚀 Publicar', pt: '🚀 Publicar',
    ru: '🚀 Опубликовать', ja: '🚀 送信', ko: '🚀 게시', zh: '🚀 发送', it: '🚀 Pubblica',
  },
  btnCancel: {
    de: '❌ Abbrechen', en: '❌ Cancel', fr: '❌ Annuler', es: '❌ Cancelar', pt: '❌ Cancelar',
    ru: '❌ Отмена', ja: '❌ キャンセル', ko: '❌ 취소', zh: '❌ 取消', it: '❌ Annulla',
  },
  btnBack: {
    de: '↩️ Zurück', en: '↩️ Back', fr: '↩️ Retour', es: '↩️ Atrás', pt: '↩️ Voltar',
    ru: '↩️ Назад', ja: '↩️ 戻る', ko: '↩️ 뒤로', zh: '↩️ 返回', it: '↩️ Indietro',
  },

  // ----------------------------------------------------------
  // Veröffentlichen
  // ----------------------------------------------------------
  publishing: {
    de: '⚙️ Baue die Regeln-Nachricht … einen Moment, ich schwitze schon. 😤',
    en: '⚙️ Building the rules message … one moment, I’m already sweating. 😤',
    fr: '⚙️ Création du message … un instant, je transpire déjà. 😤',
    es: '⚙️ Creando el mensaje … un momento, ya estoy sudando. 😤',
    pt: '⚙️ Criando a mensagem … um momento, já estou suando. 😤',
    ru: '⚙️ Создаю сообщение … секунду, я уже потею. 😤',
    ja: '⚙️ ルールメッセージを作成中 … 少々お待ちを、汗だくです。😤',
    ko: '⚙️ 규칙 메시지 만드는 중 … 잠깐만요, 벌써 땀나요. 😤',
    zh: '⚙️ 正在创建规则消息……稍等，我已经在冒汗了。😤',
    it: '⚙️ Creo il messaggio … un attimo, sto già sudando. 😤',
  },
  publishedTitle: { de: '🎉 Ab geht die Post!', en: '🎉 And it’s live!', fr: '🎉 C’est parti !', es: '🎉 ¡Al aire!', pt: '🎉 No ar!', ru: '🎉 Полетело!', ja: '🎉 公開しました！', ko: '🎉 나갔습니다!', zh: '🎉 发出去啦！', it: '🎉 È online!' },
  publishedBody: {
    de: 'Regeln in {channel} scharf geschaltet. Alte Regeln habe ich aufgeräumt. [Zur Nachricht springen]({url}) 🏃',
    en: 'Rules armed in {channel}. I cleaned up the old ones. [Jump to message]({url}) 🏃',
    fr: 'Règles actives dans {channel}. Anciennes règles nettoyées. [Aller au message]({url}) 🏃',
    es: 'Reglas activas en {channel}. Limpié las antiguas. [Ir al mensaje]({url}) 🏃',
    pt: 'Regras ativas em {channel}. Limpei as antigas. [Ir para a mensagem]({url}) 🏃',
    ru: 'Правила включены в {channel}. Старые убрал. [К сообщению]({url}) 🏃',
    ja: '{channel} でルールを公開しました。古いのは片付けました。[メッセージへ]({url}) 🏃',
    ko: '{channel}에 규칙을 배치했어요. 이전 규칙은 정리했어요. [메시지로 이동]({url}) 🏃',
    zh: '规则已在 {channel} 上线，旧的已清理。[跳转到消息]({url}) 🏃',
    it: 'Regole attive in {channel}. Ho ripulito le vecchie. [Vai al messaggio]({url}) 🏃',
  },
  publishFailed: {
    de: '💀 Absenden fehlgeschlagen: {error}',
    en: '💀 Publishing failed: {error}',
    fr: '💀 Échec de la publication : {error}',
    es: '💀 Fallo al publicar: {error}',
    pt: '💀 Falha ao publicar: {error}',
    ru: '💀 Публикация не удалась: {error}',
    ja: '💀 送信に失敗：{error}',
    ko: '💀 게시 실패: {error}',
    zh: '💀 发布失败：{error}',
    it: '💀 Pubblicazione fallita: {error}',
  },
  cancelled: {
    de: '🚮 Abgebrochen. Nichts gesendet, alles gut.',
    en: '🚮 Cancelled. Nothing sent, all good.',
    fr: '🚮 Annulé. Rien envoyé, tout va bien.',
    es: '🚮 Cancelado. Nada enviado, todo bien.',
    pt: '🚮 Cancelado. Nada enviado, tudo certo.',
    ru: '🚮 Отменено. Ничего не отправлено.',
    ja: '🚮 キャンセルしました。何も送信していません。',
    ko: '🚮 취소했어요. 보낸 것 없어요.',
    zh: '🚮 已取消。什么都没发。',
    it: '🚮 Annullato. Niente inviato, tutto ok.',
  },

  // ----------------------------------------------------------
  // Verify-Button & Verifizierungsablauf
  // ----------------------------------------------------------
  verifyNeedRole: {
    de: '🤔 Dafür brauchst du die {role}-Rolle. Die fehlt dir gerade – wende dich an das Team, falls das falsch ist.',
    en: '🤔 You need the {role} role for that. You don’t have it right now – ask the team if that’s wrong.',
    fr: '🤔 Il te faut le rôle {role}. Tu ne l’as pas – contacte l’équipe si c’est une erreur.',
    es: '🤔 Para eso necesitas el rol {role}. Ahora no lo tienes – avisa al equipo si es un error.',
    pt: '🤔 Para isso você precisa do cargo {role}. Você não o tem agora – fale com a equipe se estiver errado.',
    ru: '🤔 Для этого нужна роль {role}. Сейчас её нет – напиши команде, если это ошибка.',
    ja: '🤔 それには {role} ロールが必要です。今は持っていません – 間違いならチームへ。',
    ko: '🤔 그러려면 {role} 역할이 필요해요. 지금은 없어요 – 잘못됐다면 팀에 문의하세요.',
    zh: '🤔 你需要 {role} 身份组。现在还没有——如有误请联系管理团队。',
    it: '🤔 Ti serve il ruolo {role}. Ora non ce l’hai – chiedi al team se è un errore.',
  },
  verifyAlready: {
    de: '✅ Du bist schon verifiziert! Da gibt’s nichts mehr zu holen. 😎',
    en: '✅ You’re already verified! Nothing left to claim. 😎',
    fr: '✅ Tu es déjà vérifié ! Plus rien à récupérer. 😎',
    es: '✅ ¡Ya estás verificado! No queda nada por reclamar. 😎',
    pt: '✅ Você já está verificado! Não há mais nada para pegar. 😎',
    ru: '✅ Ты уже верифицирован! Больше брать нечего. 😎',
    ja: '✅ もう認証済みだよ！これ以上は何もない。😎',
    ko: '✅ 이미 인증됐어요! 더 받을 게 없어요. 😎',
    zh: '✅ 你已经验证过了！没什么好再领的了。😎',
    it: '✅ Sei già verificato! Non c’è più nulla da prendere. 😎',
  },
  verifySuccess: {
    de: '🎉 Willkommen im Club! Du bist jetzt verifiziert – die {role}-Rolle ist dein.',
    en: '🎉 Welcome to the club! You’re verified now – the {role} role is yours.',
    fr: '🎉 Bienvenue au club ! Tu es vérifié – le rôle {role} est à toi.',
    es: '🎉 ¡Bienvenido al club! Ya estás verificado – el rol {role} es tuyo.',
    pt: '🎉 Bem-vindo ao clube! Você está verificado – o cargo {role} é seu.',
    ru: '🎉 Добро пожаловать в клуб! Ты верифицирован – роль {role} твоя.',
    ja: '🎉 クラブへようこそ！認証完了 – {role} ロールは君のもの。',
    ko: '🎉 클럽에 오신 걸 환영해요! 인증 완료 – {role} 역할은 이제 당신 거예요.',
    zh: '🎉 欢迎加入！你已验证——{role} 身份组归你了。',
    it: '🎉 Benvenuto nel club! Sei verificato – il ruolo {role} è tuo.',
  },
  verifyRequestSent: {
    de: '📨 Deine Verifizierungs-Anfrage ist raus! Das Team prüft sie jetzt – du bekommst Bescheid. 🕵️',
    en: '📨 Your verification request is out! The team is reviewing it now – you’ll hear back. 🕵️',
    fr: '📨 Demande envoyée ! L’équipe vérifie – tu seras tenu au courant. 🕵️',
    es: '📨 ¡Solicitud enviada! El equipo la revisa – te avisaremos. 🕵️',
    pt: '📨 Pedido enviado! A equipe está revisando – você será avisado. 🕵️',
    ru: '📨 Заявка отправлена! Команда проверяет – ты получишь ответ. 🕵️',
    ja: '📨 認証リクエストを送ったよ！チームが確認中 – 結果はお知らせするね。🕵️',
    ko: '📨 인증 요청을 보냈어요! 팀이 확인 중 – 결과를 알려드릴게요. 🕵️',
    zh: '📨 验证请求已发送！团队正在审核——会通知你。🕵️',
    it: '📨 Richiesta inviata! Il team sta verificando – ti faremo sapere. 🕵️',
  },
  verifyPending: {
    de: '⏳ Du hast bereits eine offene Anfrage! Warte, bis das Team sie bearbeitet hat. 🫡',
    en: '⏳ You already have an open request! Wait until the team has handled it. 🫡',
    fr: '⏳ Tu as déjà une demande en cours ! Attends que l’équipe la traite. 🫡',
    es: '⏳ ¡Ya tienes una solicitud abierta! Espera a que el equipo la gestione. 🫡',
    pt: '⏳ Você já tem um pedido em aberto! Espere a equipe resolver. 🫡',
    ru: '⏳ У тебя уже есть открытая заявка! Подожди, пока команда её обработает. 🫡',
    ja: '⏳ すでにリクエスト中だよ！チームの対応を待ってね。🫡',
    ko: '⏳ 이미 열린 요청이 있어요! 팀이 처리할 때까지 기다려 주세요. 🫡',
    zh: '⏳ 你已经有一个待处理请求！请等待团队处理。🫡',
    it: '⏳ Hai già una richiesta aperta! Aspetta che il team la gestisca. 🫡',
  },
  logVerified: {
    de: '✅ **{user}** hat sich verifiziert! ({unverified} → {verified})',
    en: '✅ **{user}** verified! ({unverified} → {verified})',
    fr: '✅ **{user}** s’est vérifié ! ({unverified} → {verified})',
    es: '✅ **{user}** se ha verificado. ({unverified} → {verified})',
    pt: '✅ **{user}** se verificou! ({unverified} → {verified})',
    ru: '✅ **{user}** верифицировался! ({unverified} → {verified})',
    ja: '✅ **{user}** が認証しました！({unverified} → {verified})',
    ko: '✅ **{user}**님이 인증했어요! ({unverified} → {verified})',
    zh: '✅ **{user}** 已通过验证！({unverified} → {verified})',
    it: '✅ **{user}** si è verificato! ({unverified} → {verified})',
  },
  requestTitle: {
    de: '🙋 Verifizierungs-Anfrage',
    en: '🙋 Verification request',
    fr: '🙋 Demande de vérification',
    es: '🙋 Solicitud de verificación',
    pt: '🙋 Pedido de verificação',
    ru: '🙋 Заявка на верификацию',
    ja: '🙋 認証リクエスト',
    ko: '🙋 인증 요청',
    zh: '🙋 验证请求',
    it: '🙋 Richiesta di verifica',
  },
  requestBody: {
    de: '**{user}** möchte sich verifizieren.',
    en: '**{user}** wants to verify.',
    fr: '**{user}** veut se vérifier.',
    es: '**{user}** quiere verificarse.',
    pt: '**{user}** quer se verificar.',
    ru: '**{user}** хочет верифицироваться.',
    ja: '**{user}** が認証を希望しています。',
    ko: '**{user}**님이 인증을 원해요.',
    zh: '**{user}** 想要验证。',
    it: '**{user}** vuole verificarsi.',
  },
  requestAnswerLine: {
    de: '**{question}**\n{answer}',
    en: '**{question}**\n{answer}',
    fr: '**{question}**\n{answer}',
    es: '**{question}**\n{answer}',
    pt: '**{question}**\n{answer}',
    ru: '**{question}**\n{answer}',
    ja: '**{question}**\n{answer}',
    ko: '**{question}**\n{answer}',
    zh: '**{question}**\n{answer}',
    it: '**{question}**\n{answer}',
  },
  btnApprove: { de: '✅ Annehmen', en: '✅ Approve', fr: '✅ Accepter', es: '✅ Aceptar', pt: '✅ Aprovar', ru: '✅ Принять', ja: '✅ 承認', ko: '✅ 승인', zh: '✅ 通过', it: '✅ Accetta' },
  btnReject: { de: '❌ Ablehnen', en: '❌ Reject', fr: '❌ Refuser', es: '❌ Rechazar', pt: '❌ Rejeitar', ru: '❌ Отклонить', ja: '❌ 拒否', ko: '❌ 거절', zh: '❌ 拒绝', it: '❌ Rifiuta' },
  errNotAdmin: {
    de: '🛑 Nur Administratoren dürfen Anfragen annehmen oder ablehnen.',
    en: '🛑 Only administrators may approve or reject requests.',
    fr: '🛑 Seuls les administrateurs peuvent accepter ou refuser.',
    es: '🛑 Solo los administradores pueden aceptar o rechazar.',
    pt: '🛑 Só administradores podem aprovar ou rejeitar.',
    ru: '🛑 Принимать или отклонять могут только администраторы.',
    ja: '🛑 承認・拒否は管理者のみ可能です。',
    ko: '🛑 승인/거절은 관리자만 할 수 있어요.',
    zh: '🛑 只有管理员能通过或拒绝请求。',
    it: '🛑 Solo gli amministratori possono accettare o rifiutare.',
  },
  rejectModalTitle: {
    de: '❌ Anfrage ablehnen',
    en: '❌ Reject request',
    fr: '❌ Refuser la demande',
    es: '❌ Rechazar solicitud',
    pt: '❌ Rejeitar pedido',
    ru: '❌ Отклонить заявку',
    ja: '❌ リクエストを拒否',
    ko: '❌ 요청 거절',
    zh: '❌ 拒绝请求',
    it: '❌ Rifiuta richiesta',
  },
  rejectReasonLabel: {
    de: 'Ablehnungsgrund',
    en: 'Rejection reason',
    fr: 'Motif du refus',
    es: 'Motivo del rechazo',
    pt: 'Motivo da rejeição',
    ru: 'Причина отказа',
    ja: '拒否の理由',
    ko: '거절 사유',
    zh: '拒绝原因',
    it: 'Motivo del rifiuto',
  },
  rejectReasonPlaceholder: {
    de: 'Warum lehnst du ab? (Der Nutzer sieht das anonym.)',
    en: 'Why reject? (The user sees this anonymously.)',
    fr: 'Pourquoi refuser ? (L’utilisateur le voit anonymement.)',
    es: '¿Por qué rechazas? (El usuario lo verá de forma anónima.)',
    pt: 'Por que rejeitar? (O usuário verá anonimamente.)',
    ru: 'Почему отказываешь? (Пользователь увидит анонимно.)',
    ja: '拒否理由は？（ユーザーには匿名で表示されます）',
    ko: '거절 사유는? (사용자에게 익명으로 보여집니다.)',
    zh: '拒绝原因？（用户将以匿名方式看到。）',
    it: 'Perché rifiuti? (L’utente lo vedrà in forma anonima.)',
  },
  requestApproved: {
    de: '✅ **{user}** wurde angenommen (von {admin}). Willkommen! 🎉',
    en: '✅ **{user}** was approved (by {admin}). Welcome! 🎉',
    fr: '✅ **{user}** a été accepté (par {admin}). Bienvenue ! 🎉',
    es: '✅ **{user}** fue aceptado (por {admin}). ¡Bienvenido! 🎉',
    pt: '✅ **{user}** foi aprovado (por {admin}). Bem-vindo! 🎉',
    ru: '✅ **{user}** принят (кем: {admin}). Добро пожаловать! 🎉',
    ja: '✅ **{user}** は承認されました（by {admin}）。ようこそ！🎉',
    ko: '✅ **{user}**님이 승인됐어요 ({admin} 승인). 환영해요! 🎉',
    zh: '✅ **{user}** 已通过（由 {admin}）。欢迎！🎉',
    it: '✅ **{user}** è stato accettato (da {admin}). Benvenuto! 🎉',
  },
  requestRejected: {
    de: '❌ **{user}** wurde abgelehnt (von {admin}).',
    en: '❌ **{user}** was rejected (by {admin}).',
    fr: '❌ **{user}** a été refusé (par {admin}).',
    es: '❌ **{user}** fue rechazado (por {admin}).',
    pt: '❌ **{user}** foi rejeitado (por {admin}).',
    ru: '❌ **{user}** отклонён (кем: {admin}).',
    ja: '❌ **{user}** は拒否されました（by {admin}）。',
    ko: '❌ **{user}**님이 거절됐어요 ({admin} 거절).',
    zh: '❌ **{user}** 已被拒绝（由 {admin}）。',
    it: '❌ **{user}** è stato rifiutato (da {admin}).',
  },
  acceptNotice: {
    de: '🎉 Gute Nachrichten! Deine Verifizierung wurde **angenommen** – du hast jetzt die {verified}-Rolle. Willkommen an Bord!',
    en: '🎉 Great news! Your verification was **approved** – you now have the {verified} role. Welcome aboard!',
    fr: '🎉 Bonne nouvelle ! Ta vérification a été **acceptée** – tu as maintenant le rôle {verified}. Bienvenue !',
    es: '🎉 ¡Buenas noticias! Tu verificación fue **aceptada** – ya tienes el rol {verified}. ¡Bienvenido!',
    pt: '🎉 Boa notícia! Sua verificação foi **aprovada** – você agora tem o cargo {verified}. Bem-vindo!',
    ru: '🎉 Отличные новости! Верификация **принята** – у тебя теперь роль {verified}. Добро пожаловать!',
    ja: '🎉 朗報！認証が**承認**されました – これで {verified} ロールを取得。ようこそ！',
    ko: '🎉 좋은 소식! 인증이 **승인**됐어요 – 이제 {verified} 역할을 갖게 됐어요. 환영해요!',
    zh: '🎉 好消息！你的验证已**通过**——现在你拥有 {verified} 身份组。欢迎！',
    it: '🎉 Ottime notizie! La verifica è stata **accettata** – ora hai il ruolo {verified}. Benvenuto!',
  },
  rejectNotice: {
    de: '😔 Deine Verifizierung wurde **abgelehnt**. Grund: {reason}\n\nDu kannst es jederzeit nochmal versuchen! 💪',
    en: '😔 Your verification was **rejected**. Reason: {reason}\n\nYou can try again anytime! 💪',
    fr: '😔 Ta vérification a été **refusée**. Motif : {reason}\n\nTu peux réessayer quand tu veux ! 💪',
    es: '😔 Tu verificación fue **rechazada**. Motivo: {reason}\n\n¡Puedes intentarlo de nuevo cuando quieras! 💪',
    pt: '😔 Sua verificação foi **rejeitada**. Motivo: {reason}\n\nPode tentar de novo quando quiser! 💪',
    ru: '😔 Верификация **отклонена**. Причина: {reason}\n\nМожешь попробовать ещё раз в любой момент! 💪',
    ja: '😔 認証が**拒否**されました。理由：{reason}\n\nいつでも再挑戦できるよ！💪',
    ko: '😔 인증이 **거절**됐어요. 사유: {reason}\n\n언제든 다시 시도할 수 있어요! 💪',
    zh: '😔 你的验证被**拒绝**。原因：{reason}\n\n你随时可以再试！💪',
    it: '😔 La verifica è stata **rifiutata**. Motivo: {reason}\n\nPuoi riprovare quando vuoi! 💪',
  },
  rejectNoReason: {
    de: '(kein Grund angegeben)',
    en: '(no reason given)',
    fr: '(aucun motif)',
    es: '(sin motivo)',
    pt: '(sem motivo)',
    ru: '(причина не указана)',
    ja: '（理由なし）',
    ko: '(사유 없음)',
    zh: '（未注明原因）',
    it: '(nessun motivo)',
  },
  formModalTitle: {
    de: '📝 Verifizierung',
    en: '📝 Verification',
    fr: '📝 Vérification',
    es: '📝 Verificación',
    pt: '📝 Verificação',
    ru: '📝 Верификация',
    ja: '📝 認証',
    ko: '📝 인증',
    zh: '📝 验证',
    it: '📝 Verifica',
  },

  // ----------------------------------------------------------
  // /set_verify_form
  // ----------------------------------------------------------
  vfChoiceNone: { de: 'Keine Überprüfung', en: 'No review', fr: 'Aucune vérification', es: 'Sin revisión', pt: 'Sem revisão', ru: 'Без проверки', ja: '確認なし', ko: '검토 없음', zh: '无需审核', it: 'Nessuna revisione' },
  vfChoiceSimple: { de: 'Überprüfung ohne Formular', en: 'Review without form', fr: 'Vérification sans formulaire', es: 'Revisión sin formulario', pt: 'Revisão sem formulário', ru: 'Проверка без формы', ja: 'フォームなしで確認', ko: '양식 없이 검토', zh: '审核（无表单）', it: 'Revisione senza modulo' },
  vfChoiceForm: { de: 'Überprüfung mit Formular', en: 'Review with form', fr: 'Vérification avec formulaire', es: 'Revisión con formulario', pt: 'Revisão com formulário', ru: 'Проверка с формой', ja: 'フォームありで確認', ko: '양식과 함께 검토', zh: '审核（带表单）', it: 'Revisione con modulo' },
  vfDesc: {
    de: 'Wie soll die Verifizierung ablaufen?',
    en: 'How should verification work?',
    fr: 'Comment doit se dérouler la vérification ?',
    es: '¿Cómo debe funcionar la verificación?',
    pt: 'Como a verificação deve funcionar?',
    ru: 'Как должна проходить верификация?',
    ja: '認証の流れを選んでね。',
    ko: '인증을 어떻게 진행할까요?',
    zh: '验证应该如何进行？',
    it: 'Come deve funzionare la verifica?',
  },
  vfNeedVerify: {
    de: '🕵️ Dafür brauche ich erst eine Verify-Regel-Nachricht (mit Button). Erstell sie mit `/create_verify_rules`.',
    en: '🕵️ I need a verify rules message (with button) first. Create one with `/create_verify_rules`.',
    fr: '🕵️ Il me faut d’abord un message de règles avec bouton. Crée-le avec `/create_verify_rules`.',
    es: '🕵️ Primero necesito un mensaje de reglas con botón. Créalo con `/create_verify_rules`.',
    pt: '🕵️ Primeiro preciso de uma mensagem de regras com botão. Crie com `/create_verify_rules`.',
    ru: '🕵️ Сначала нужно сообщение правил с кнопкой. Создай через `/create_verify_rules`.',
    ja: '🕵️ 先にボタン付きのルールメッセージが必要です。`/create_verify_rules` で作って。',
    ko: '🕵️ 먼저 버튼이 있는 인증 규칙 메시지가 필요해요. `/create_verify_rules`로 만드세요.',
    zh: '🕵️ 我需要先有一条带按钮的验证规则消息。用 `/create_verify_rules` 创建。',
    it: '🕵️ Prima mi serve un messaggio di regole con pulsante. Crealo con `/create_verify_rules`.',
  },
  vfUpdated: {
    de: '🎛️ Verifizierungs-Modus auf **{mode}** gestellt.',
    en: '🎛️ Verification mode set to **{mode}**.',
    fr: '🎛️ Mode de vérification réglé sur **{mode}**.',
    es: '🎛️ Modo de verificación en **{mode}**.',
    pt: '🎛️ Modo de verificação definido como **{mode}**.',
    ru: '🎛️ Режим верификации: **{mode}**.',
    ja: '🎛️ 認証モードを **{mode}** に設定しました。',
    ko: '🎛️ 인증 모드를 **{mode}**(으)로 설정했어요.',
    zh: '🎛️ 验证模式已设为 **{mode}**。',
    it: '🎛️ Modalità di verifica impostata su **{mode}**.',
  },

  // ----------------------------------------------------------
  // Formular-Editor (Überprüfung mit Formular)
  // ----------------------------------------------------------
  feTitle: {
    de: '🧾 Formular-Baukasten',
    en: '🧾 Form builder',
    fr: '🧾 Constructeur de formulaire',
    es: '🧾 Constructor de formulario',
    pt: '🧾 Construtor de formulário',
    ru: '🧾 Конструктор формы',
    ja: '🧾 フォームビルダー',
    ko: '🧾 양식 만들기',
    zh: '🧾 表单生成器',
    it: '🧾 Costruttore di moduli',
  },
  feIntro: {
    de: 'Welche Felder soll der Nutzer beim Verifizieren ausfüllen?',
    en: 'Which fields should the user fill in when verifying?',
    fr: 'Quels champs l’utilisateur doit-il remplir ?',
    es: '¿Qué campos debe rellenar el usuario al verificar?',
    pt: 'Quais campos o usuário deve preencher ao verificar?',
    ru: 'Какие поля должен заполнять пользователь?',
    ja: '認証時にユーザーが入力する項目は？',
    ko: '인증할 때 사용자가 채울 항목은 무엇인가요?',
    zh: '验证时用户需要填写哪些字段？',
    it: 'Quali campi deve compilare l’utente?',
  },
  feEmpty: {
    de: 'Noch keine Felder. Klick auf „➕ Feld hinzufügen“ – oder speichere ein leeres Formular, dann gibt’s keine Extra-Fragen. 😌',
    en: 'No fields yet. Click “➕ Add field” – or save an empty form for no extra questions. 😌',
    fr: 'Aucun champ. Clique sur « ➕ Ajouter » – ou enregistre un formulaire vide sans questions. 😌',
    es: 'Aún no hay campos. Pulsa «➕ Añadir campo» – o guarda un formulario vacío sin preguntas extra. 😌',
    pt: 'Nenhum campo ainda. Clique em “➕ Adicionar” – ou salve um formulário vazio sem perguntas. 😌',
    ru: 'Полей пока нет. Нажми «➕ Добавить» – или сохрани пустую форму без вопросов. 😌',
    ja: 'まだ項目なし。「➕ 追加」を押すか、空のフォームを保存して質問なしに。😌',
    ko: '아직 항목이 없어요. “➕ 추가”를 누르거나 빈 양식을 저장하세요. 😌',
    zh: '还没有字段。点“➕ 添加字段”——或者保存空表单，就没有额外问题。😌',
    it: 'Nessun campo. Clicca “➕ Aggiungi” – o salva un modulo vuoto senza domande. 😌',
  },
  feFieldShort: { de: 'kurz', en: 'short', fr: 'court', es: 'corto', pt: 'curto', ru: 'короткое', ja: '短い', ko: '짧게', zh: '短', it: 'breve' },
  feFieldLong: { de: 'lang (mehrzeilig)', en: 'long (multi-line)', fr: 'long (multiligne)', es: 'largo (multilínea)', pt: 'longo (multilinha)', ru: 'длинное (многострочное)', ja: '長い（複数行）', ko: '길게 (여러 줄)', zh: '长（多行）', it: 'lungo (multiriga)' },
  feFieldRequired: { de: 'Pflichtfeld', en: 'Required', fr: 'Obligatoire', es: 'Obligatorio', pt: 'Obrigatório', ru: 'Обязательное', ja: '必須', ko: '필수', zh: '必填', it: 'Obbligatorio' },
  feFieldOptional: { de: 'optional', en: 'optional', fr: 'optionnel', es: 'opcional', pt: 'opcional', ru: 'необязательное', ja: '任意', ko: '선택', zh: '选填', it: 'facoltativo' },
  feFieldLine: {
    de: '{index}. **{question}** ({style}, {required})',
    en: '{index}. **{question}** ({style}, {required})',
    fr: '{index}. **{question}** ({style}, {required})',
    es: '{index}. **{question}** ({style}, {required})',
    pt: '{index}. **{question}** ({style}, {required})',
    ru: '{index}. **{question}** ({style}, {required})',
    ja: '{index}. **{question}**（{style}, {required}）',
    ko: '{index}. **{question}** ({style}, {required})',
    zh: '{index}. **{question}**（{style}, {required}）',
    it: '{index}. **{question}** ({style}, {required})',
  },
  btnAddField: { de: '➕ Feld hinzufügen', en: '➕ Add field', fr: '➕ Ajouter', es: '➕ Añadir campo', pt: '➕ Adicionar', ru: '➕ Добавить', ja: '➕ 追加', ko: '➕ 추가', zh: '➕ 添加字段', it: '➕ Aggiungi' },
  btnRemoveField: { de: '➖ Feld entfernen', en: '➖ Remove field', fr: '➖ Retirer', es: '➖ Quitar campo', pt: '➖ Remover', ru: '➖ Удалить', ja: '➖ 削除', ko: '➖ 제거', zh: '➖ 删除字段', it: '➖ Rimuovi' },
  btnSaveFields: { de: '💾 Speichern', en: '💾 Save', fr: '💾 Enregistrer', es: '💾 Guardar', pt: '💾 Salvar', ru: '💾 Сохранить', ja: '💾 保存', ko: '💾 저장', zh: '💾 保存', it: '💾 Salva' },
  feRemoveTitle: { de: '🗑️ Welches Feld fliegt raus?', en: '🗑️ Which field goes?', fr: '🗑️ Quel champ retirer ?', es: '🗑️ ¿Qué campo quito?', pt: '🗑️ Qual campo sai?', ru: '🗑️ Какое поле удалить?', ja: '🗑️ どの項目を外す？', ko: '🗑️ 어떤 항목을 뺄까요?', zh: '🗑️ 删除哪个字段？', it: '🗑️ Quale campo rimuovo?' },
  fieldModalTitle: { de: '🧾 Feld bearbeiten', en: '🧾 Edit field', fr: '🧾 Modifier le champ', es: '🧾 Editar campo', pt: '🧾 Editar campo', ru: '🧾 Поле', ja: '🧾 項目を編集', ko: '🧾 항목 편집', zh: '🧾 编辑字段', it: '🧾 Modifica campo' },
  fieldQuestionLabel: { de: 'Frage / Label', en: 'Question / label', fr: 'Question / libellé', es: 'Pregunta / etiqueta', pt: 'Pergunta / rótulo', ru: 'Вопрос / подпись', ja: '質問 / ラベル', ko: '질문 / 라벨', zh: '问题 / 标签', it: 'Domanda / etichetta' },
  fieldQuestionPlaceholder: { de: 'z. B. Wie alt bist du?', en: 'e.g. How old are you?', fr: 'ex. Quel âge as-tu ?', es: 'p. ej. ¿Cuántos años tienes?', pt: 'ex.: Quantos anos você tem?', ru: 'напр. Сколько тебе лет?', ja: '例：何歳ですか？', ko: '예: 몇 살인가요?', zh: '例如：你几岁？', it: 'es. Quanti anni hai?' },
  fieldPlaceholderLabel: { de: 'Platzhalter (was grau drinsteht)', en: 'Placeholder (grey hint text)', fr: 'Placeholder (texte gris)', es: 'Placeholder (texto gris)', pt: 'Placeholder (texto cinza)', ru: 'Плейсхолдер (серый текст)', ja: 'プレースホルダー（グレーのヒント）', ko: '플레이스홀더 (회색 안내)', zh: '占位符（灰色提示文字）', it: 'Placeholder (testo grigio)' },
  fieldValueLabel: { de: 'Vorausgefüllter Wert (optional)', en: 'Pre-filled value (optional)', fr: 'Valeur préremplie (optionnel)', es: 'Valor precargado (opcional)', pt: 'Valor pré-preenchido (opcional)', ru: 'Предзаполненное значение (опц.)', ja: '初期値（任意）', ko: '미리 채울 값 (선택)', zh: '预填值（可选）', it: 'Valore precompilato (opzionale)' },
  fieldStyleLabel: { de: 'Feld-Typ: kurz | lang', en: 'Field type: short | long', fr: 'Type : court | long', es: 'Tipo: corto | largo', pt: 'Tipo: curto | longo', ru: 'Тип: короткое | длинное', ja: '種類：短い | 長い', ko: '종류: 짧게 | 길게', zh: '类型：短 | 长', it: 'Tipo: breve | lungo' },
  fieldStylePlaceholder: { de: '"short" oder "long"', en: '"short" or "long"', fr: '« short » ou « long »', es: '"short" o "long"', pt: '"short" ou "long"', ru: '"short" или "long"', ja: '"short" か "long"', ko: '"short" 또는 "long"', zh: '“short” 或 “long”', it: '"short" o "long"' },
  fieldRequiredLabel: { de: 'Pflicht? ja | nein', en: 'Required? yes | no', fr: 'Obligatoire ? oui | non', es: '¿Obligatorio? sí | no', pt: 'Obrigatório? sim | não', ru: 'Обязательно? да | нет', ja: '必須？ はい | いいえ', ko: '필수? 예 | 아니요', zh: '必填？是 | 否', it: 'Obbligatorio? sì | no' },
  feSaved: { de: '💾 Formular gespeichert.', en: '💾 Form saved.', fr: '💾 Formulaire enregistré.', es: '💾 Formulario guardado.', pt: '💾 Formulário salvo.', ru: '💾 Форма сохранена.', ja: '💾 フォームを保存しました。', ko: '💾 양식을 저장했어요.', zh: '💾 表单已保存。', it: '💾 Modulo salvato.' },

  // ----------------------------------------------------------
  // /set_language
  // ----------------------------------------------------------
  setLangTitle: {
    de: '🌍 Welche Sprache soll der Verify-Bot hier sprechen?',
    en: '🌍 Which language should the Verify Bot speak here?',
    fr: '🌍 Quelle langue le bot doit-il parler ici ?',
    es: '🌍 ¿Qué idioma debe hablar el bot aquí?',
    pt: '🌍 Qual idioma o bot deve falar aqui?',
    ru: '🌍 На каком языке говорить боту?',
    ja: '🌍 ボットはここでどの言語を使う？',
    ko: '🌍 봇이 여기서 어떤 언어를 쓸까요?',
    zh: '🌍 验证机器人在这里用哪种语言？',
    it: '🌍 Che lingua deve parlare il bot qui?',
  },
  setLangUpdated: {
    de: '🌍 Sprache auf **{lang}** gestellt. Ab jetzt quatsche ich so! 🗣️',
    en: '🌍 Language set to **{lang}**. That’s how I’ll talk now! 🗣️',
    fr: '🌍 Langue réglée sur **{lang}**. Je parle comme ça maintenant ! 🗣️',
    es: '🌍 Idioma en **{lang}**. ¡Así hablaré ahora! 🗣️',
    pt: '🌍 Idioma definido como **{lang}**. É assim que falo agora! 🗣️',
    ru: '🌍 Язык: **{lang}**. Теперь говорю так! 🗣️',
    ja: '🌍 言語を **{lang}** に設定。これからこの言葉で話すよ！🗣️',
    ko: '🌍 언어를 **{lang}**(으)로 설정했어요. 이제 이렇게 말할게요! 🗣️',
    zh: '🌍 语言已设为 **{lang}**。以后我就这么说！🗣️',
    it: '🌍 Lingua impostata su **{lang}**. Ora parlo così! 🗣️',
  },

  // ----------------------------------------------------------
  // /admin_set_bot_profile
  // ----------------------------------------------------------
  profileChoiceStandard: { de: 'Standard', en: 'Default', fr: 'Par défaut', es: 'Predeterminado', pt: 'Padrão', ru: 'Стандарт', ja: '標準', ko: '기본', zh: '默认', it: 'Predefinito' },
  profileChoiceServer: { de: 'Server-Icon', en: 'Server icon', fr: 'Icône du serveur', es: 'Icono del servidor', pt: 'Ícone do servidor', ru: 'Иконка сервера', ja: 'サーバーアイコン', ko: '서버 아이콘', zh: '服务器图标', it: 'Icona del server' },
  profileChoiceOwner: { de: 'Server-Owner-Bild', en: 'Server owner avatar', fr: 'Avatar du propriétaire', es: 'Avatar del dueño', pt: 'Avatar do dono', ru: 'Аватар владельца', ja: 'オーナーのアイコン', ko: '서버 소유자 아바타', zh: '服主头像', it: 'Avatar del proprietario' },
  profileImageDesc: {
    de: 'Welches Bild soll verwendet werden?', en: 'Which image should be used?', fr: 'Quelle image utiliser ?',
    es: '¿Qué imagen se debe usar?', pt: 'Qual imagem usar?', ru: 'Какое изображение использовать?',
    ja: 'どの画像を使いますか？', ko: '어떤 이미지를 사용할까요?', zh: '使用哪张图片？', it: 'Quale immagine usare?',
  },
  profileSet: {
    de: '🖼️ Neues Outfit sitzt: **{choice}**. Sexy!', en: '🖼️ New outfit locked in: **{choice}**. Looking sharp!',
    fr: '🖼️ Nouveau look validé : **{choice}**. Classe !', es: '🖼️ Nuevo look listo: **{choice}**. ¡Elegante!',
    pt: '🖼️ Novo visual no ar: **{choice}**. Estiloso!', ru: '🖼️ Новый образ готов: **{choice}**. Красота!',
    ja: '🖼️ 新しい見た目に変更：**{choice}**。イケてる！', ko: '🖼️ 새 스타일 적용: **{choice}**. 멋져요!',
    zh: '🖼️ 换装完成：**{choice}**。帅！', it: '🖼️ Nuovo look: **{choice}**. Che stile!',
  },
  errServerNoIcon: {
    de: '🖼️ Dieser Server hat gar kein Icon. Kann ich schlecht klauen.', en: '🖼️ This server has no icon at all. Hard to steal that.',
    fr: '🖼️ Ce serveur n’a pas d’icône. Difficile de la voler.', es: '🖼️ Este servidor no tiene icono. Difícil de robar.',
    pt: '🖼️ Este servidor não tem ícone. Difícil roubar.', ru: '🖼️ У сервера нет иконки. Красть нечего.',
    ja: '🖼️ このサーバーにはアイコンがありません。盗めません。', ko: '🖼️ 이 서버에는 아이콘이 없어요. 훔칠 게 없네요.',
    zh: '🖼️ 这个服务器没有图标，没得偷。', it: '🖼️ Questo server non ha icona. Difficile rubarla.',
  },
  errAvatar: {
    de: '🖼️ Profilbild fehlgeschlagen: {error}', en: '🖼️ Avatar update failed: {error}', fr: '🖼️ Échec de l’avatar : {error}',
    es: '🖼️ Fallo del avatar: {error}', pt: '🖼️ Falha no avatar: {error}', ru: '🖼️ Не удалось сменить аватар: {error}',
    ja: '🖼️ アイコンの変更に失敗：{error}', ko: '🖼️ 아바타 변경 실패: {error}', zh: '🖼️ 头像更新失败：{error}', it: '🖼️ Avatar non aggiornato: {error}',
  },
  errAvatarPerms: {
    de: '🔐 Mir fehlen die Rechte für das Server-Profilbild (z. B. „Nickname ändern“).',
    en: '🔐 I lack permissions for the server avatar (e.g. “Change Nickname”).',
    fr: '🔐 Permissions manquantes pour l’avatar serveur (ex. « Changer de pseudo »).',
    es: '🔐 Me faltan permisos para el avatar del servidor (p. ej. «Cambiar apodo»).',
    pt: '🔐 Faltam permissões para o avatar do servidor (ex.: “Mudar apelido”).',
    ru: '🔐 Не хватает прав на серверный аватар (напр. «Изменять ник»).',
    ja: '🔐 サーバーアイコン変更の権限がありません（例：「ニックネームの変更」）。',
    ko: '🔐 서버 아바타 권한이 없어요 (예: “별명 변경”).',
    zh: '🔐 我缺少设置服务器头像的权限（例如“更改昵称”）。',
    it: '🔐 Mi mancano i permessi per l’avatar del server (es. “Cambia nickname”).',
  },

  // ----------------------------------------------------------
  // /help
  // ----------------------------------------------------------
  helpTitle: { de: '✅ Verify-Bot – Bedienungsanleitung', en: '✅ Verify Bot – manual', fr: '✅ Bot de vérification – mode d’emploi', es: '✅ Bot de verificación – manual', pt: '✅ Bot de verificação – manual', ru: '✅ Verify-бот – инструкция', ja: '✅ 認証Bot – 取扱説明書', ko: '✅ 인증 봇 – 사용 설명서', zh: '✅ 验证机器人 – 使用手册', it: '✅ Verify Bot – manuale' },
  helpDesc: {
    de: 'Regeln & Verifizierung zum Selbstbedienen – ohne Datenbank, alles steckt in der Nachricht. 🤯',
    en: 'Rules & self-service verification – no database, everything lives in the message. 🤯',
    fr: 'Règles & vérification libre-service – sans base de données, tout vit dans le message. 🤯',
    es: 'Reglas y verificación autoservicio – sin base de datos, todo vive en el mensaje. 🤯',
    pt: 'Regras e verificação self-service – sem banco de dados, tudo vive na mensagem. 🤯',
    ru: 'Правила и верификация – без базы данных, всё живёт в сообщении. 🤯',
    ja: 'ルール＆セルフサービス認証 – DBなし、すべてはメッセージの中に。🤯',
    ko: '규칙 & 셀프 인증 – DB 없이 모든 게 메시지 안에 있어요. 🤯',
    zh: '规则与自助验证——不用数据库，一切都藏在消息里。🤯',
    it: 'Regole e verifica self-service – niente database, tutto vive nel messaggio. 🤯',
  },
  helpCreateVerify: {
    de: 'Erstellt eine neue Verify-Regel-Nachricht mit Button & Rollen (nur Admins).',
    en: 'Creates a new verify rules message with button & roles (admins only).',
    fr: 'Crée un nouveau message de règles avec bouton & rôles (admins).',
    es: 'Crea un nuevo mensaje de reglas con botón y roles (solo admins).',
    pt: 'Cria uma nova mensagem de regras com botão e cargos (só admins).',
    ru: 'Создаёт новое сообщение правил с кнопкой и ролями (только админы).',
    ja: 'ボタン＆ロール付きの新しい認証ルールを作成します（管理者のみ）。',
    ko: '버튼 & 역할이 있는 새 인증 규칙 메시지를 만듭니다 (관리자 전용).',
    zh: '创建一条带按钮和身份组的新验证规则消息（仅管理员）。',
    it: 'Crea un nuovo messaggio di regole con pulsante e ruoli (solo admin).',
  },
  helpCreateClassic: {
    de: 'Erstellt eine klassische Regel-Nachricht ohne Button (nur Admins).',
    en: 'Creates a classic rules message without a button (admins only).',
    fr: 'Crée un message de règles classique sans bouton (admins).',
    es: 'Crea un mensaje de reglas clásico sin botón (solo admins).',
    pt: 'Cria uma mensagem de regras clássica sem botão (só admins).',
    ru: 'Создаёт классическое сообщение правил без кнопки (только админы).',
    ja: 'ボタンなしのクラシックなルールを作成します（管理者のみ）。',
    ko: '버튼 없는 클래식 규칙 메시지를 만듭니다 (관리자 전용).',
    zh: '创建一条不带按钮的经典规则消息（仅管理员）。',
    it: 'Crea un messaggio di regole classico senza pulsante (solo admin).',
  },
  helpSetVerifyForm: {
    de: 'Legt fest, wie verifiziert wird: ohne Prüfung, mit Prüfung oder mit Formular (nur Admins).',
    en: 'Sets how verification works: no review, with review, or with a form (admins only).',
    fr: 'Règle la vérification : sans contrôle, avec contrôle ou avec formulaire (admins).',
    es: 'Define la verificación: sin revisión, con revisión o con formulario (solo admins).',
    pt: 'Define a verificação: sem revisão, com revisão ou com formulário (só admins).',
    ru: 'Задаёт тип верификации: без проверки, с проверкой или с формой (только админы).',
    ja: '認証方法を設定：確認なし、確認あり、フォームあり（管理者のみ）。',
    ko: '인증 방식을 정합니다: 검토 없음, 검토, 양식 (관리자 전용).',
    zh: '设置验证方式：无需审核、需审核或带表单（仅管理员）。',
    it: 'Imposta la verifica: senza revisione, con revisione o con modulo (solo admin).',
  },
  helpSetLanguage: {
    de: 'Stellt die Sprache des Bots auf diesem Server ein (nur Admins).',
    en: 'Sets the bot’s language on this server (admins only).',
    fr: 'Règle la langue du bot sur ce serveur (admins).',
    es: 'Establece el idioma del bot en este servidor (solo admins).',
    pt: 'Define o idioma do bot neste servidor (só admins).',
    ru: 'Задаёт язык бота на этом сервере (только админы).',
    ja: 'このサーバーでのボットの言語を設定します（管理者のみ）。',
    ko: '이 서버에서 봇의 언어를 설정합니다 (관리자 전용).',
    zh: '设置机器人在本服务器的语言（仅管理员）。',
    it: 'Imposta la lingua del bot su questo server (solo admin).',
  },
  helpSetProfile: {
    de: 'Ändert das serverspezifische Profilbild des Bots (nur Admins).',
    en: 'Changes the bot’s server-specific avatar (admins only).',
    fr: 'Change l’avatar du bot pour ce serveur (admins).',
    es: 'Cambia el avatar del bot en este servidor (solo admins).',
    pt: 'Muda o avatar do bot neste servidor (só admins).',
    ru: 'Меняет аватар бота на этом сервере (только админы).',
    ja: 'このサーバーでのBotのアイコンを変更します（管理者のみ）。',
    ko: '이 서버에서 봇의 아바타를 바꿉니다 (관리자 전용).',
    zh: '更改机器人在本服务器的头像（仅管理员）。',
    it: 'Cambia l’avatar del bot in questo server (solo admin).',
  },
  helpHelp: { de: 'Zeigt genau diese Übersicht.', en: 'Shows exactly this overview.', fr: 'Affiche exactement cet aperçu.', es: 'Muestra exactamente este resumen.', pt: 'Mostra exatamente este resumo.', ru: 'Показывает именно этот обзор.', ja: 'まさにこの一覧を表示します。', ko: '바로 이 목록을 보여줍니다.', zh: '显示的就是这个概览。', it: 'Mostra esattamente questa panoramica.' },
  helpAdminPanel: { de: 'Owner-Admin-Panel (nur im DM)', en: 'Owner admin panel (DM only)', fr: 'Panneau owner (MP uniquement)', es: 'Panel del owner (solo MD)', pt: 'Painel do owner (só no DM)', ru: 'Панель владельца (только в ЛС)', ja: 'オーナー管理パネル（DM限定）', ko: '소유자 관리 패널 (DM 전용)', zh: '所有者管理面板（仅私聊）', it: 'Pannello owner (solo DM)' },
  helpFooter: {
    de: '💡 Klick auf den grünen Button unter den Regeln = verifizieren. Admins können mit `/set_verify_form` wählen, ob geprüft wird. 🧠',
    en: '💡 Click the green button under the rules to verify. Admins can choose whether requests get reviewed via `/set_verify_form`. 🧠',
    fr: '💡 Clique sur le bouton vert sous les règles pour te vérifier. Les admins choisissent la vérification via `/set_verify_form`. 🧠',
    es: '💡 Pulsa el botón verde bajo las reglas para verificarte. Los admins eligen la revisión con `/set_verify_form`. 🧠',
    pt: '💡 Clique no botão verde sob as regras para verificar. Admins escolhem a revisão com `/set_verify_form`. 🧠',
    ru: '💡 Жми зелёную кнопку под правилами для верификации. Админы выбирают проверку через `/set_verify_form`. 🧠',
    ja: '💡 ルール下の緑ボタンで認証。管理者は `/set_verify_form` で審査を選べます。🧠',
    ko: '💡 규칙 아래 초록 버튼을 눌러 인증하세요. 관리자는 `/set_verify_form`으로 검토 여부를 정해요. 🧠',
    zh: '💡 点击规则下方的绿色按钮进行验证。管理员可用 `/set_verify_form` 选择是否审核。🧠',
    it: '💡 Clicca il pulsante verde sotto le regole per verificarti. Gli admin scelgono la revisione con `/set_verify_form`. 🧠',
  },
  helpLanguageHint: {
    de: '🌍 Die Sprache richtet sich nach deinem Discord-Client – oder stell sie mit `/set_language` um.',
    en: '🌍 The language follows your Discord client – or change it with `/set_language`.',
    fr: '🌍 La langue suit ton client Discord – ou change-la avec `/set_language`.',
    es: '🌍 El idioma sigue a tu cliente – o cámbialo con `/set_language`.',
    pt: '🌍 O idioma segue seu cliente – ou mude com `/set_language`.',
    ru: '🌍 Язык берётся из клиента Discord – или смени через `/set_language`.',
    ja: '🌍 言語は Discord クライアントに追従 – または `/set_language` で変更。',
    ko: '🌍 언어는 Discord 클라이언트를 따라가요 – `/set_language`로 바꿀 수도 있어요.',
    zh: '🌍 语言跟随你的 Discord 客户端——或用 `/set_language` 更改。',
    it: '🌍 La lingua segue il tuo client Discord – o cambiala con `/set_language`.',
  },
  createChannelDesc: {
    de: 'Kanal, in dem die Regeln landen', en: 'Channel where the rules land', fr: 'Salon où atterrissent les règles',
    es: 'Canal donde aparecen las reglas', pt: 'Canal onde as regras vão aparecer', ru: 'Канал, куда попадут правила',
    ja: 'ルールを投稿するチャンネル', ko: '규칙을 보낼 채널', zh: '规则发送到的频道', it: 'Canale dove finiranno le regole',
  },
  createLoggingDesc: {
    de: 'Kanal, in dem Verifizierungen geloggt werden', en: 'Channel where verifications are logged', fr: 'Salon où les vérifications sont journalisées',
    es: 'Canal donde se registran las verificaciones', pt: 'Canal onde as verificações são registradas', ru: 'Канал для логов верификации',
    ja: '認証をログするチャンネル', ko: '인증을 기록할 채널', zh: '记录验证的频道', it: 'Canale dove vengono registrate le verifiche',
  },
  createUnverifiedDesc: {
    de: 'Rolle für noch nicht verifizierte Nutzer', en: 'Role for not-yet-verified users', fr: 'Rôle des utilisateurs non vérifiés',
    es: 'Rol de usuarios sin verificar', pt: 'Cargo de usuários não verificados', ru: 'Роль непроверенных пользователей',
    ja: '未認証ユーザーのロール', ko: '미인증 사용자 역할', zh: '未验证用户的身份组', it: 'Ruolo degli utenti non verificati',
  },
  createVerifiedDesc: {
    de: 'Rolle für verifizierte Nutzer', en: 'Role for verified users', fr: 'Rôle des utilisateurs vérifiés',
    es: 'Rol de usuarios verificados', pt: 'Cargo de usuários verificados', ru: 'Роль проверенных пользователей',
    ja: '認証済みユーザーのロール', ko: '인증된 사용자 역할', zh: '已验证用户的身份组', it: 'Ruolo degli utenti verificati',
  },
  setVerifyFormDesc: {
    de: 'Wie soll verifiziert werden?', en: 'How should verification work?', fr: 'Comment vérifier ?',
    es: '¿Cómo verificar?', pt: 'Como verificar?', ru: 'Как верифицировать?', ja: '認証の方法は？',
    ko: '어떻게 인증할까요?', zh: '如何验证？', it: 'Come verificare?',
  },
  setLanguageDesc: {
    de: 'Welche Sprache soll der Bot sprechen?', en: 'Which language should the bot speak?', fr: 'Quelle langue parler ?',
    es: '¿Qué idioma hablar?', pt: 'Qual idioma falar?', ru: 'На каком языке говорить?', ja: 'どの言語を使う？',
    ko: '어떤 언어를 쓸까요?', zh: '用哪种语言？', it: 'Che lingua parlare?',
  },

  // ----------------------------------------------------------
  // Owner-Admin-Panel (bewusst nur Deutsch)
  // ----------------------------------------------------------
  apNeedDm: { de: '🔒 Dieses Panel gibt es nur im Privatchat mit dem Bot-Owner.' },
  apTitle: { de: '🛰️ Verify Owner-Panel' },
  apNoServers: { de: 'Der Bot ist aktuell auf **keinem** Server. Einsam hier. 🥲' },
  apServerListDesc: { de: '**{count}** Server insgesamt:\n\n{list}' },
  apPage: { de: 'Seite {page}/{total}' },
  apSelectPlaceholder: { de: 'Server auswählen …' },
  apBtnPrev: { de: '◀' },
  apBtnNext: { de: '▶' },
  apBtnRefresh: { de: '🔄 Aktualisieren' },
  apDetailTitle: { de: '🔍 Server-Details' },
  apDetailName: { de: '**Name:** {name}' },
  apDetailOwner: { de: '**Owner:** {mention}' },
  apDetailMembers: { de: '**Mitglieder:** {count}' },
  apDetailSetup: { de: '**Verify:** {status}' },
  apDetailMessages: { de: '**Nachrichten:** {count}' },
  apSetupYes: { de: '✅ eingerichtet' },
  apSetupNo: { de: '❌ noch nichts da' },
  apBtnBack: { de: '↩️ Zurück' },
  apBtnInvite: { de: '✉️ Einladung' },
  apBtnLeave: { de: '🚪 Verlassen' },
  apBtnLeaveConfirm: { de: '⚠️ Wirklich verlassen' },
  apBtnLeaveCancel: { de: '↩️ Doch nicht' },
  apLeaveAsk: { de: 'Server **{name}** wirklich verlassen? Danach ist der Bot dort raus.' },
  apLeft: { de: '👋 Server **{name}** verlassen.' },
  apInviteSent: { de: '✉️ Einladung erstellt (1 Stunde gültig, 1× nutzbar):' },
  apInviteLink: { de: '{url}' },
  apInviteFailed: { de: '⚠️ Einladung fehlgeschlagen: {error}' },
  apJoinNotice: { de: '🎉 Neuer Server: **{name}**\n👥 Mitglieder: **{members}**\n👑 Owner: {owner}' },
};

/** Übersetzt einen Key in die gewünschte Sprache und ersetzt {platzhalter}. */
function t(key, lang, vars = {}) {
  const entry = T[key];
  if (!entry) return `??${key}??`;
  let text = entry[lang] || entry.de || entry.en || '';
  for (const [k, v] of Object.entries(vars)) {
    text = text.split(`{${k}}`).join(String(v));
  }
  return text;
}

/**
 * Unsere Sprach-Codes → Discord-Locale-Codes (für Command-Lokalisierung).
 * Discord akzeptiert z. B. „en-US“ aber kein nacktes „en“.
 */
const DISCORD_LOCALE = {
  de: 'de',
  en: 'en-US',
  fr: 'fr',
  es: 'es-ES',
  pt: 'pt-BR',
  ru: 'ru',
  ja: 'ja',
  ko: 'ko',
  zh: 'zh-CN',
  it: 'it',
};

/** Mappt die Discord-Client-Locale eines Nutzers auf unsere Sprach-Codes. */
const DISCORD_LOCALE_MAP = {
  de: 'de',
  'en-US': 'en',
  'en-GB': 'en',
  fr: 'fr',
  'es-ES': 'es',
  'es-419': 'es',
  'pt-BR': 'pt',
  'pt-PT': 'pt',
  ru: 'ru',
  ja: 'ja',
  ko: 'ko',
  'zh-CN': 'zh',
  'zh-TW': 'zh',
  it: 'it',
};

function langFromDiscord(locale) {
  return DISCORD_LOCALE_MAP[locale] || 'en';
}

/** Gültiger Sprachcode? Sonst Fallback auf 'en'. */
function normalizeLang(code) {
  return LANGS[code] ? code : 'en';
}

module.exports = {
  LANGS,
  T,
  t,
  langFromDiscord,
  normalizeLang,
  DISCORD_LOCALE,
  DISCORD_LOCALE_MAP,
};
